# quay.io/flightctl/flightctl-device:v4
#
# Image built on top of base image which includes an embedded
# compose application with 3 sleep containers

ARG BASE_IMAGE=quay.io/flightctl/flightctl-device:base

FROM ${BASE_IMAGE}

COPY --from=variant-context test-podman-compose-sleep.yaml /usr/local/etc/compose/manifests/embedded-demo-app/podman-compose.yaml

