// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3LctrLgr2B5bpXtk3lIjuN1VHUrV5Ef0caytHokda9He40he2YQkQANgJInKVXt",
	"P+wf7pfcwosESZDDGSs+p258TlU8Il6NRqPR3ehu/BHFLMsZBSpFdPBHJOIVZFj/PJwLlhYSzrBcqb8T",
	"EDEnuSSMRgfROeQchGqGMEXY1kULkgLKsVxNolGUc5YDlwR0f3mwn8sVVK1VFSQZwqYfRpFcARJrISGb",
	"oHdMApIrLBGmawSfiJCELk3VO5KmaA6I3QK/40RKoAoC+ISzPIXoIJreYj5N2XKK83ySsmU0iuQ6VyVC",
	"ckKX0f19+YXNf4NYRvej6DDPL/W3ENiqNmILDSPO85TEWJXqcWmRRQfvDXIFRKPoY4GTFGQ0imJGJSYU",
	"eHTdhGEUfRqrpuNbzCnOFN7eOxiOyq7sh/9d9ljWKDs2oDuIVAFQqWaB0/R0ER28/yP6Fw6L6CD627Qi",
	"gKld/elrkoJrdD/qr3sOKZbk1pCJqszhY0E4JAp2vebXLcQ24HtFb3/B3BBJjWSgKsBJQlRdnJ7VqjQW",
	"cdRYp1f0lnBGM6AS3WJO8DwFdAPr8S1OC0VwhIsRIlTBBQlKCtUN4gWVJIMJUst8A2uEaYJMC8DxCmWF",
	"kIra5iDvACja1xWefvctileY41gCF5OoNe0OCnNoOGNctilNfUUZznMFGKFowXiGJZpFKyakKjwoCUr9",
	"NYvQY5gsJyM0i17svdg7eLE3i57U94L9rnYolhK4Gub/zGbJNwfqP//S3hp1MDm7JQnwixzi4SQVWG5F",
	"LPX1xtV229CXrnY/itQu6WAq1YBI1SoXbf///9//V18qlDK6HCEhMZfojsgVwigFhRnEOKJFNgc+0kts",
	"UY0oQ3crIkHkOIZJkJf428DNq70TRn9EjMIA/B1neAldq7Bpjx7TlNDu1tf31/2UeQ6CFTyGtyQj5pxo",
	"HgamHKW6gqLREFesL3acF+2ejs6uTCeK1GPGQUzQa0PxHBR29TadYwGJOh78RVYTqNP53uR/fhci5gwy",
	"xtftwU/0dzu+pgOWG56DCkrkZ0Dy9Lvn2eATp4n1PoTHjArJMaFDsZ6WSzhwtzbWfhPQFxLLQoQPTVOm",
	"jkyMBKHLtL5L7XGfwC0xm8qdomcccmwPyAu1Sc3P84JS8+sV54xHo+iK3lB2R6NRpE7LFCQkww/Z+gz8",
	"MVuFHhCtsgqqVpEDs1VQwd0q8iZSR/QvLC0M76sYcB3dL2FBKAiENf9L0K1ugQpFsfO1Ftv6KCXMWq8o",
	"+ViA4ahW9vH7VbuG0BAZ9nNIPdjnskeDkq044wkrqNyhnR6vs/H1fXCxmidnHd8GjYHN/pYIqTeNt1ds",
	"ZYVYIiHbZkNbwqn2MeYcrzdubNPMEGX/1n4QOnvXIrBJiJVzWAAHGkOIR9oipVEYxpKnbA0JOj06Hisc",
	"pQRTiYhaSnXQqz29wLFEcxzfKGmrd+wQAfvwbDhSxUWRZZivB/LLNPWRKLp55U+AU7laR6PoJSw5TiAJ",
	"8sd3zIdleyZZB78atLOKB01nnQB/rFcI8sl6lebE7kfRkaK1hfoEF2SpmPM5fCxABITtzqqIe/ou4vaj",
	"OnHVUbakkKC4aosWnGV6gY4O2wSPc/ILcKFHbAJweHZsy1Bi2bemQvMNEmQ2tNkZRFRg2SN0obabIbgJ",
	"ugCuGiKxYkWqhddb4GoqMVtS8nvZm3A7JMVSTYtQpRTg1Kg8RvLN8BpxUP2igno96Cpigk4YB0Togh2g",
	"lZS5OJhOl0RObl6ICWGKI2VKhFpPlQTNybyQjItpAreQTgVZjjGPlTwdy4LDFOdkrIGlehEnWfI37mSh",
	"IBe4ITRp4/JnQhNE1HqZmlaDK1Hmtvj5q4tL5AYwaDUY9Ba9QqZCBKEL4KZmudJAk5wRKvUfcUqUximK",
	"uZaHLb0oPE/QEaaUaU2kyBMsIZmgY4qOcAbpERbwp6NSYU+MFcrCyMxA4gRLvOlIOdU4OgGJVSthz7S+",
	"Fp27yx65kShPl926Mc3b2le53yypeJO0kIe4dT+4LXL7leM8B3WMsIImCKsDkI9jDmqN0dHF+QhlLIHU",
	"6As3xRw4BQkCEabXFudk4vEQMbndn/SC0OYs8Ckn3AiPEDOaBDUH3d7YOkqmcYtTkhC5LnUIDxA1jDE6",
	"RAcRofLbpxXVKE6xBK6wBZ8kx32WmlJOaVFcXQ5pmXBUxwhLQ+sgnFSg0GvMgQ7HmuEqPOcsL1L9ab7W",
	"Xw/PjpHQG1jhXtdXM1eMjWRZIfE8hYDBxtBR8KS4XIFW/p4/GwONWQIJOnt1Uv3++ejib/t7CpwJOsEy",
	"XllOrqhtUp4fBNJEabrYp4e+Q8gwqdqSzNcSQvtYH0v8XVC6OqaJITINEy9pwrQxHF9zzo8FTsmCQKIl",
	"/iC/KEiA914dv/wC6+QBIfAyJDtf6e8a62oa+jAALU3fwBqZVt78repChCjqJ3pN0N5IwGrKm8XaL4CY",
	"Bid01Fwjju1YX4f8XxEUznPObnE6TYASnE4XmKQFByRKYbacpWdREx14R2RRWftFwIhUVQ3vUdtlW0Yb",
	"VYhDTGkJJc4H7S7FXomRMdtSZFlmhHa1sszfaRP0s5JjUexV5IAONeogGaGXQIn6V2HoNSapAWqQplcO",
	"HtTwfGrwphCkgbKj7glWy5eAxCQ1RihGAWG15aRb7rjgXAtEUq2pE14VUZ97LK1hqcJCXnJMhR7pknQZ",
	"elU9JEkGZqQSNFm2hcSIaQouS4aSIUyZXAGvrbaSx8aqr7BgJBS/aEPxU5FhijjgRFOTrYeI2RNKzHTY",
	"wXNWSAtxCV6QobG53u7JG6Bgzunw7CdOkpksy5qGqdSxcYeF5nzGYFnkZlj/XH/+LHiuc8AiqKmgx3NO",
	"YPEEmRqV6ODGfCQGzXSg0Od6dUKe62lgM3Nh0NgBuocSglGI5EoEVOvfu1k2G0hqOBppomQLdMmVpvUa",
	"pwJGyOq5vl6vyqNRpCt4mvwwxb0Bne2r8dV13fhcjuTPsuNS1F6IVlRHfMXGm43jdNEoujw7+QW4ljGM",
	"Xu8KDA/Uc1YMsF01jkEIMk+h+YfjKWeYC131Yk1j/eMXJeeqGixNWSGP6RlnSw5CLf6V0saskTmH2FU9",
	"KVJJ8hRO7yhwoeG6JTG8BKWIEaHUCtVo2EK8opylaQZU2vPUm2+rrD7dziPZ66KzTonLzholkjtr1ME5",
	"h5wJIhlfB1GvMN5Z0Fofv7Bcq9cpgHSroP8IrZpZDW/tzAd/Bc2XoetoyHxBlk1r7TBD9BsiA803mZN/",
	"LqX/C4g5yB1u93YY9Scp81AzjYO8cKtywqha6PZ9b/28zky1zf4SlamFIdtos+jq9x68J+j3UWjPxMyS",
	"M/rqU65oKSzocEYRlBXc5bs66lTfSZFqIxLJQExmVE3S1iACffg7sv//cIDG6IRQpb0eoA9//4AyqxHu",
	"jb/7foLG6CdW8FbR029V0Uu8Vkg7YVSu6jX2x9/uqxrBov2nXuNfAW6avT+fzOhFkeeMKzVDLSSWTAEx",
	"VhUPSqVVSd/GcGb9ClQ3hKKVArnsD26Br/W3J2rcD+MPB+gc02XVam/84oNG3P5TdHii1v4FOjwxtUcf",
	"DpC+5XCV90f7T21tIbUUvP9UrlCmcWjaTD8coAsJeQXW1LUxwDRbXJgbx/pcXlQoUefyC6/JjL4y97cK",
	"c2hv/GK0/3z89Fu7pEFR5qgQkmWGsRzTBeszhzSlKW0tMjbfBMW6I2Q3mF2A4JBNddfrhFBDjFpR1IJn",
	"/cqgJcQYwNvAme91E3i+WgsS49Tr76uV+6uV+6uVe1oJIMO1G9tmB/v1dec+brkStK+ct/e3gmwOSQIB",
	"Ovx1BUqdbl79K9J0jZx5bc6YjM29q7c2c8ZSwLTbq6uhZvsuCP2+BlqHS9ZhqcS4d1m1xfjRCXS3IvFK",
	"22R0SzTIpUENo33IAvz9XTmKq4Ocht/lt9NWxYfRUtgZ537U7WBQ6aa2Snl3rzd/A67d/A2aanuHTaq8",
	"Rlfr5SHUU9JLEhz1+dW1N0H9njh0BAtTwRHVSt9qNzwvAlfv9T1F7LnfS7v+0WxsQ45Na4tJzZnsIawn",
	"/Y4HzUWwfXZj1SgNXYg88ox9lcnD4EttsgVZttHGgSbAIemUGc5tBScldPa7yQReH6d3koKlneKQLfal",
	"ImvZ0Z9jRinE1ghSLnZ73sJoFscvw9zJFqPjl759rTFCmDBMyxPvnGvQeymYlqO4U8XxOwW3vSv515rD",
	"dIypPtqFMW0TSiTBKfnd2GBLx3jgGaE4HZUwS+aajRDIuGu5cHJK03V0IHkBDdJszGrkIbB7KX0lP+T2",
	"aWdthGTsSCqpmwZK431rDSXmS5DDzngflEvdLmyZNF0Om5LXT5u3lzdfZrMINUJrahnIFUvqW8q3111R",
	"0NYpbY2LJePrcxA1+PqsXn0Qez33VauPWmLhWB2OnMj10Qrimy6G1F23uXvrLIu4FihWTVAOXO0Ic4G/",
	"4xkwDp4BlXrWHNNA9Bmsv3vyu/H+zp42mLy3QGZFdc7d64oKZ6rwDcKlPXIbOgxNoBqpr44PQ3e9Erru",
	"KhXcbbR2XiBY4aSLRFt7N2+YG/QoiVKR5Hp3olGEsLWIU5G3Fm8qoDcIN6p2iav2+UgyJR5muZt7o/Nb",
	"3bISXIfd8u20q6xbuFkiJ2/LPPscPO+8MdvADN6anQeAZ/kv6Tu8PXfaio1t0TGlrp21YQ+3t2+17d6S",
	"BcTrOIWdhNnUtX4ANaBpoas6f6gzoDHX3dh/qJMu8vIDJEMYa/N5cwdm17h+MVP/siWhNaBukkqjuAZF",
	"oDwE2oZqNaI7FWEPQr8UmaK5FdyMPIhOL0o1oFP2yII+Cpe1TozPu7GgcHR1/naz4mT67SaMU7HTFjq9",
	"GDyFX+qKn5tGcF/okpdk2em7l+iyZl/mXgCJFX763fMDvDeZTJ4MRU190G5ElZedW6GrNA1vOuhtWN1m",
	"dlCHwx1aCRE3n9O+iq3brYemj1JeRGWnFrqhqO2/iRS1q0iDbGN4b4dS/Iq53ehHnEgS4zQQVLENP6oD",
	"6sdstEurwUOlHkChYgdkqMz37PCM1h1sqcGUcM/Fjxd/MSiYKbe3zzuFMzVuvFu+mMYw1A2IKd8BhuCF",
	"e2h4wdKQ1VX7rjlsxJLcVqYda9MYDkvdYhV0qa4fWVvbKrRP2kA47PlmDOJdIayHCrTaHrRX/HZFrHf6",
	"cBw0LvlDWDCZJJIOU5sp1G62RDHauntCw9kBy3h1ZqLng7Zkt7K6IrJx9vXJtMzP5oLawVFQIvURPbKx",
	"yFz/q6REUSwW5NMImfCjFaTpWMh1CmiZsrkbTMOvR8dLTKiQzgszXaOU4QTMEBqmDH96C3QpV9HB0++e",
	"1/ICvN8bf4/Hvx+O/+NgNhv/52Sm//d+Nrv+H7PZeDb7+2z2w/U3j/9tWL0nPzyezSbvTcVQcTD7wOZA",
	"RXPJeMZSEg88fK68FoZc7zvPlX7DUtuUFJbrhRcjaZknsm0zrHVhkpqLoFgWOK2cZT+X11pRy2e5/nm3",
	"BYdp3ykGdhluXzZs3Xvjsma4w3W5ChqT5o7NXdwoTAa9kX0Ef66TtX/iDGLZ1U2KNq1YpXUnA4SzmVwA",
	"0CHO0pYwjG8wUBdsYDkgevzu9PLVgbkELF1RiECUScRBFpzWAhSeDDSyKLloyca/CUbHZEkZB2PpV8A7",
	"DWonjXbLM6psUzulthVb9bmyDZW3KNswfOcvNKCDqn7fmeZ2f+082Xrfm8GSK0pk9463Lh7bMN6kw8zl",
	"bfMaZupsJQpzGX8p/b1U7klNHxW81cr5pNetX+x+g+ztthXmyR3moB2OjN8doUu7TKjmAvTwN8sWBhcF",
	"8RB3ywHU7GZa2ioiPmymPNWusOHg93OYM2adhM/YHXBITheLmh3z8A4TqT2e7eWqcYdfpCSWZ7gQW1qd",
	"ahPyQGuVedAGSus6XK3In1OguDbNQHnTDlYrDCEjUK2Jn2o5a2xtmBvkqcu3Y3eDF/UJn3ImqvMGL4HK",
	"yYy+wvFKx/LFjHMQOaOJie6p1AizLayzX4xzPCcpkevJjG52qDSTqO2qmKWpyRZWesV1imcKyE6PBnUe",
	"Hy51ZjJTJbgJfUe3jj68Gkr+MR69Fk8td8+qZ0U6Ib+DHxmT6PjlNl0Zf9UhR1jLRVad2Y4JGmyHZ3la",
	"csoLxykHgtd0p/MRWmKhDcWovnzdfKulSWy4hM91TW3IzTDFSxMgpvmyOZh0Rro4LRJVcrcC6r47H9c5",
	"oITdUavFqXPExhkG7v1svQvjrr5RsDKTKWuXh/uu7e83oC3ZyWpsYHrQWxf/eDTdP+TxWJvsbsdju4st",
	"7l0qhJWXLvkle4l1cOtpIU8X9rcXSbOLYbMGpDdEoNQfNdi4EdJTL/Vtl0TcbIxV2To8ZPRPFt8S5ChW",
	"m9esxHSgmQkRNya2fZssrAnhoJ1syjSsziCnuq/32T+XnqyfL4u+YNYMfyJZkVWpKXCasjvfRdZ41EmG",
	"YpsXzeToLBtUDNKF/CcI63gFpnbyrb3sBjUp2/d8jbBRiU2Svyoopvyow7MP0Adh4kuESa4xQh8y88GE",
	"jKgPK/NBB8dM6gk2H/9w8H5//P31bJb8/ckPs1nyXmSr66C96xWNmWL+Q1y6wNY15Kc98vR6YYkbcRP+",
	"7s9TTJT4Y1JYDI5eNEOd2cbu7x9tJ/eBIMY2+K0qPbmVbC4BteDGTazXFvY14ORrwMlfMOCktaG2iz1p",
	"N3/YNEodMc84HcAaXNUqz0RYeCsZhWfMtRxDp37udN3FLni6J6PJnRfZ4rjTCgs0B6DIdRAOZEnxHNLP",
	"yV996NLVmJ60Zpvn6brKadgRzdfOQGzmudUKVbL5MEGqe6nbEsyGQTetuHeZ8rlrf9jhIqKPfyxtMJC/",
	"+ndY1BZ+mGeha/FjVyRSPaBJ1eWDcku7Xkf+lALy12jLJdjhRiuA+HKBJkFaC2vMwWrm1PEqmpFbdR8J",
	"5+qkb3gCPjKCh5cglMLLz0YkTEYEn6YCG7h+ZTg87m8UaaXmfFMozKUmxd5wGH1+Wm//yW+CUfTY5bJ+",
	"0uFq+9CcyuWgcbdJ+okGj3kRUd4/rYAidaB7xENEiLV2cDe1noMYW5exoaPidjug1UkXyzFH306M1LsP",
	"3ZT5yqfldvqrydZJrdopnCA85S+bpsp/qyKIh9gUmjVakJCzbtzXXqtKSMIniR5fXb4ev3iCGG/m/vMG",
	"0YFTJO3EsKrnNKfNdOApgkFbmpp+d4yXKi2jutrzXnJW5OFZqxk8EkjXGHnKNBAtC2GXVty+kACcxOj4",
	"5QS9hAUuUi2To1nEGZOzKCwPswR6h86BW98jnTdzgv6dFVpNMMAYo2+mhPoFzkhKMEcsljitXnDAWi/+",
	"HThz+R72nj97ppcPm5MkJpltYCK/Qm2ePd17ovQUWZBkKkAu1T+SxDdrNLemAVS6lk/Q8ULfj5cYGxmb",
	"b30yWrtV81Q8sEKYAi8c+lsI4L3YYnc6ceODL1QXzW1nYdvmQZkaRW+qXHukKPj6TLnnOixS4YQ9rVD5",
	"JZHnCozwWexlGsfoDZF1HzabuXEbY5wzwdmAzwVZupjMKvFSRwi6K94sZFZd1TKLtt2vtDB1DrekTx4x",
	"pQroQngZsHvhbQXnlsC3Rh11mRX7HoHxZ9tw9Byc0t2ufGjgjgRKLeJZSZkPpB6Kfrq8PBtIP2rvh5/n",
	"Ul8dxRgp65EwL2XZm1XJPL3GnV5Npx4NioBb4J5h1Xte67Ooj7epzxEPttGYaxqjHro0bpChyfPyJL46",
	"f2tzrLIMBMILaTV5dYDryAd0LHU8s7lyA/SxAG0D5zgD/TqQKOIVwuIAzaKposGpZFNnlvpB1/5XXbuL",
	"f3ZSeLl8X56oHUWGRu59amiXB5863tcYFPTResXh9Og48GRDIIcGynF80xUfok5r0f/Y1m7e6IzLkIfU",
	"YBez4Ps/Q2NxOlez66WSdoyNebtDc+8K05lqDgnCnlzT8cpfuYwDX2u50FM0AmFBNwbRm0Z6Op1hOKaj",
	"TlycFWlaOQpb8Ss6iI4X75g8M+peNOpwTKnLTY/8No8m6FelyCo1WJUdpnd4LR4Z+c/gkQiUF2mqpDOd",
	"osw8Mldr9U6V1Brpd8twahLR6DzI3RHTZsxo1JyM7nXgLY/CT9mP+qPRl/pk+3MoDVMWZdJk9vBvOfXS",
	"3D8U1QyOUWu3DThz+wF39kAyNz8bHowJCHY1Gts4KY8kt3jTZjNgJrU8hyURkq8n6HJFzE3LHIyDlMl3",
	"5DU0OZHLq2zFAlxnI3Usp4wu1b9WxGU8E23GLPzL6SFnYt+bOf1v1/15x5Fx1+uJ7PCPGitA7XJiVGpR",
	"vxnEAjSQ6XelBD3Yfp5GTZXMZqlvM59BMy51xsDh+OeKOp2IG0W9aVdbqHooMEeR0KMN1ScrKJFpGAhH",
	"Unx1R02gdsNhBvCkfXv0B6cxDCEVzMEO9BOa3b3o4o1dhVe+6n7kYeh6kzXZtq4WKUQ65q3Iv0CK3MGi",
	"4zv/kUGN7roWqyYQEAnsmX0fJOnPEQe7xUDvir3tgVyWKWmtTIhlnp1OU5QDF0S/FVJFZGsJbYVvYWR3",
	"klUlhW5hxtU59bitazhp4HqAUiaraK4db2Kqyibjfy2oJ5j41b0nUmZU6bkQNWFV2o/jDgv3dMnwW9AE",
	"UthlLPvAt26+zXjLngcUDpGAj4XmtDYNZM2LBZeSDPIeVygv2kwqLXPFiM6aL7a4V8vPASdjRtP1wPcW",
	"Pvsi7gTrhDjWOecG1qJ6vtpeyzXStzG+xJT8biJSYixhybj687GIWW6+Ckghlk8cMQepaNhxYL2ogm9e",
	"3NGQlfvQ9yLCErE7/VyMdtMy30fqgJtpp5SpGmsW2TzcXVk6datubzGKWI4/FuCQqIclOndS6XdnbHKP",
	"hOfWVd3EVt5iwyzqZ1jGK89jrhSpwjSw0M9ENJgH69hJ1q/dmGZt1i1fZ8RJogOn8tSclBwydqu3Uj2P",
	"hWc8CQoah+h/XZy+Q2dMI6Q0D7Raa0IMg2o8yZTQkyRKHbFATVq8neV99uCmfFl7oj6gU9W8D01VIyGF",
	"TRxd02+3dbKy4wXvmLQ0XL5ppMhL13cMjt0C90ys1RvSgsdTQhP4NPlNDKMqd6YfpsDluXXez7vDb9pT",
	"WtVT1jVcL7TBTfUd9oPodPV1TsDqhJWO16t5e4IovgWudMlCWMNJmS53DgvG7cCELt2r3Af9Lr6PxKO6",
	"7+6j7FHdd/fR6lGn7+5slnzT7a6bA4+Bys68O1W5wpqZkXGP4GS5VFJBCJPmRDLqwi0MiQmurfeFbRQO",
	"NnA9estUm0f9ULneRFy1wdoOy7a0RTOOBQXzq+jooGEmq05Yqo47q3gjdtYxoHiTdjkm1FSJmmpGKLYf",
	"rPlY/Tw6u+r0fwi/r2GiGTrdhToiHZw60vnKdaeyUonda/NSYE2LUGfyoFdPOmaz8fXtHrg2OE51YOL+",
	"ukcnai9gb7hWOLgC1+5KG/K7Y7R9+U50JcRVrQk6penavJemv+bAkdub2gXKMLCtc6BUHD+UBUWdKIQu",
	"j9U5HfTDLRn0HOQdAC0jQXRTBfcX4LllsEQX4+1Rf0f+UgRmHGJoG17uIkY8kAWnVk5RgMc4db5uCaOP",
	"3BUqMmZUT1r+Gqvw58YqxEF3ootiuTQve+qrbLs4sfPA0fgzLnwjtIeIdd0xJqYBb95+DZB40ACJjucV",
	"h4ihfpSowqPTebpeg+h40jDD8YpQ6BzqbrVuDKAW2lpXZzo1asGV+mlTdqJjC5AhAf0WRi61gYCDSaVS",
	"dyy9xSTVb7miQ3Ru3lWMU8zt27XWOUQ4D/kE0LxQnAdMUhYlQ3OSACJyQ8RqX1qFCnnoVD9OeIBm0UWh",
	"X3ObRUov82b6p5ONyCEeY5qMO7OgDohTKR+P0Gxi4JuONvXJoc7NplAE3YbbFVmuxqmalMmzohO6VamW",
	"ape0JtmbhiJl2t9Q31KUnxcuza3rRFdIoPZnhhUfophanX3BQaxMUbFV3G57locOkHbRuQdxu/S4mkO7",
	"sEze2zFg+fZiq/hlfebtCic1XISg9rDTLvZjiW3pK6o24YY1B12p7hCtF995/7oFNxUT/UX/GvOCWntl",
	"SuiNLjI/vBKcEiz0SgtTw/zwaqiRSWzSYroRCDVxvFFp+dSfTSi7ucCf48SjklG0HaF4qHlVzquz7LwE",
	"tl3lrZt6V1Ff40OLnXbJicNXV1FftxcOpe2ilxWS24XHFdrbhW+8hQgQmLc07dIfcbhVlbolgHt1xvjk",
	"/JbhZAMxq309gJSFLOaKWJlNV0OZHC9YoZnsHCdjAdJuU7BZazLgS498d+VP5RQuDATNz28dRM2Cd0y+",
	"tgA2i37EyUUJb7PQZd1pfj9x82kVNOiuLAjwFy+dVvtRroozDUzO1TyhmlcCwQOrW6RyvnQ6HL5mgjzN",
	"gV5c/OReok8wZOYU9dJH7j17EZA8oKLOgZNqsuB7Q3XbdFEne+0wOi/bh7bAnTnCR3rqYzWJcXkDVB3j",
	"JTp4Qak7jUsEPH9W12Lx+Pe98ffj62+CpkM1UBiaMv2ni0OYRUKskom9x5tFTxrmYa9wo4ykh61TSX2N",
	"fGSPaiTpYTEkNF2SDP6DOY8S51v3lhkLW/sBB/Q7o1DdrXBhLQiaAo8P3x26F1UPz18dTt+eHh1eHp++",
	"G6E7LUGrj/X0AUrKJFSH4nDEYsDUKK+uZenAqJNCYC5JXKSYI0Ek6EAQYp9PxxzwyDwnanCMDnXwBJ6+",
	"g7v//HfGb0boVaF27vQMc+JsOQXF2ZwsC1YI9O04XmGOY+1y7ObaCBhBj2fRm5PLWaQW+OryyK5ri1Cu",
	"Wll4mt5rlanAPk1rdFxcSKa0i7hMGaStWDQJJRuSJHOlLlxQQ86KUDDbxuv5xvO6RgPh8g3HMfiZQHot",
	"fa7e/SiSHnH1tSmJsKUbyCgIQ4iSfd+C9ptRbf8Gg23rADH01sj0k3s+OpVXno5jsoSiOzdLIur7fgoy",
	"ntIloZ+UhrWYJAec7Zqh5d573EXDEeupQ4ZJGh1EEnD2b4uULFcylumEsMhd+mqO9VqXoCOl57EUXQLO",
	"1GnPVVOnGdZat66u39e7uH4cavbE2lZsWKlOdgJKSTaXbzqlFmQ2GG+RAkit2UKydA5Q5kJcroBwdMf4",
	"jdoUwqSDS0kMVEDl7hUd5jheAXo62WtN5u7uboJ18YTx5dS2FdO3x0ev3l28Gj+d7E1WMksN6Uq9XA0k",
	"HZ4dR6Po1tkCo9v9OUi8b7OiUZyT6CD6drI32bcXnpqWlJ48vd2fevGcNjLZWXw0xbFQ+pUj48WHUedD",
	"7zUDd2kMOE7Kxp0tI0NlIOSPzLy36UVWev6S09+s/cVs2I1spHO8+zph2yyyJg+gMPvu6d7+lwIkhOhE",
	"LeWzvb0Hg6HMztEa8EecoBIeNej+Fxj0iuJCrrS/iJ3qt19g1NeMz0mSADVDfv8Fhqxnu9TjPv0S414y",
	"hk4wXbul1cHf330RLF8YFntFS7Ok8TPAS62ZdXKf6FpV28ykpn8oHnuvwytBhjwzcGIEmjLopHMHtnnV",
	"G5B9jKoK8NK3m/1OS5t5JZIMLc3FAVE92NhTe4iUz9r6nGrkLVBTES4o+VjAsbnz02zN3GzWGNveP4ax",
	"nf78F2Mvz77AkKWZ4itjGcpYrDBnucjUZUTpZCdvQNrAU5s6xaYf6RZ33oB0yVhMppZt+YZpZXlDfXDR",
	"dDJ4GNZx3860VOb912Yo1HgBuRxWR7JW4wZT0fSN+2fyJ4v9Tmb01OzR5pZCXnDNP4pffSHmgSru8UXE",
	"oX8KQcjjGWYv9zKI6vYzxzIOh8q4MBgvrc/LTVxCN6tlctqNS/iihIbwoTjC9TZq2VgP/c12q1bzXx6k",
	"lH053vBV+fpvIR2hv5x4hLrko5LXjaK8CAg6VzZ9+baM7Ny42z8wK6tSj39xXrYbE/nKuv4igtI/qdhS",
	"ZUEcbs2lKJRWu9+M287V/efsrfY4X9hs2wHAV3Ptf2Nz7V/RUNspMLQ4yiaGs8ky+wbktjznDcgQw9lK",
	"uuge70HNr3+uLWMQN/pqY/2qRfwjmIKONtQBB3o7mvvuqUkyY9q1n2yzu1wgRpvyv/ZVsJvQijpt+2S9",
	"h+497nfWBv7++v6/AgAA//+sQzFUzbwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
