{{ if and (eq (include "flightctl.enableMulticlusterExtensions" .) "false") (eq (include "flightctl.getServiceExposeMethod" .) "route") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flightctl-telemetry-gateway-from-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-telemetry-gateway
spec:
  ingress:
  - from:
    - podSelector: {}
  - from:
    - namespaceSelector:
        matchLabels:
          policy-group.network.openshift.io/ingress: ""
  podSelector:
    matchLabels:
      flightctl.service: flightctl-telemetry-gateway
  policyTypes:
  - Ingress
{{ end }}
