apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-telemetry-gateway
  name: flightctl-telemetry-gateway
  namespace: {{ .Release.Namespace }}
