// Code generated by api-metadata-extractor. DO NOT EDIT.

package server

import (
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
)

// EndpointMetadataVersion contains version-specific information for an endpoint
type EndpointMetadataVersion struct {
	Version      string     // e.g., "v1", "v1beta1"
	DeprecatedAt *time.Time // nil if not deprecated; interpreted as 00:00:00 UTC
}

// EndpointMetadata contains metadata for an API endpoint
type EndpointMetadata struct {
	OperationID string
	Resource    string                    // empty = fixed-contract
	Action      string                    // x-rbac.action, else inferred from method/pattern
	Versions    []EndpointMetadataVersion // Ordered by preference (stable > beta > alpha)
}

// timePtr is a helper to create time.Time pointers
func timePtr(year, month, day int) *time.Time {
	t := time.Date(year, time.Month(month), day, 0, 0, 0, 0, time.UTC)
	return &t
}

// APIMetadataMap provides O(1) lookup for endpoint metadata using pattern+method as key
var APIMetadataMap = map[string]EndpointMetadata{
	"GET:/auth/config": {
		OperationID: "authConfig",
		Resource:    "",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/auth/permissions": {
		OperationID: "authGetPermissions",
		Resource:    "",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/auth/userinfo": {
		OperationID: "authUserInfo",
		Resource:    "",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/auth/validate": {
		OperationID: "authValidate",
		Resource:    "",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/auth/{providername}/token": {
		OperationID: "authToken",
		Resource:    "",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/authproviders": {
		OperationID: "listAuthProviders",
		Resource:    "authproviders",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/authproviders": {
		OperationID: "createAuthProvider",
		Resource:    "authproviders",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/authproviders/{name}": {
		OperationID: "deleteAuthProvider",
		Resource:    "authproviders",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/authproviders/{name}": {
		OperationID: "getAuthProvider",
		Resource:    "authproviders",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/authproviders/{name}": {
		OperationID: "patchAuthProvider",
		Resource:    "authproviders",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/authproviders/{name}": {
		OperationID: "replaceAuthProvider",
		Resource:    "authproviders",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/certificatesigningrequests": {
		OperationID: "listCertificateSigningRequests",
		Resource:    "certificatesigningrequests",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/certificatesigningrequests": {
		OperationID: "createCertificateSigningRequest",
		Resource:    "certificatesigningrequests",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/certificatesigningrequests/{name}": {
		OperationID: "deleteCertificateSigningRequest",
		Resource:    "certificatesigningrequests",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/certificatesigningrequests/{name}": {
		OperationID: "getCertificateSigningRequest",
		Resource:    "certificatesigningrequests",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/certificatesigningrequests/{name}": {
		OperationID: "patchCertificateSigningRequest",
		Resource:    "certificatesigningrequests",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/certificatesigningrequests/{name}": {
		OperationID: "replaceCertificateSigningRequest",
		Resource:    "certificatesigningrequests",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/certificatesigningrequests/{name}/approval": {
		OperationID: "updateCertificateSigningRequestApproval",
		Resource:    "certificatesigningrequests/approval",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/deviceactions/resume": {
		OperationID: "resumeDevices",
		Resource:    "devices/resume",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/devices": {
		OperationID: "listDevices",
		Resource:    "devices",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/devices": {
		OperationID: "createDevice",
		Resource:    "devices",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/devices/{name}": {
		OperationID: "deleteDevice",
		Resource:    "devices",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/devices/{name}": {
		OperationID: "getDevice",
		Resource:    "devices",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/devices/{name}": {
		OperationID: "patchDevice",
		Resource:    "devices",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/devices/{name}": {
		OperationID: "replaceDevice",
		Resource:    "devices",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/devices/{name}/decommission": {
		OperationID: "decommissionDevice",
		Resource:    "devices/decommission",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/devices/{name}/lastseen": {
		OperationID: "getDeviceLastSeen",
		Resource:    "devices/lastseen",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/devices/{name}/rendered": {
		OperationID: "getRenderedDevice",
		Resource:    "devices/rendered",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/devices/{name}/status": {
		OperationID: "getDeviceStatus",
		Resource:    "devices/status",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/devices/{name}/status": {
		OperationID: "patchDeviceStatus",
		Resource:    "devices/status",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/devices/{name}/status": {
		OperationID: "replaceDeviceStatus",
		Resource:    "devices/status",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/enrollmentconfig": {
		OperationID: "getEnrollmentConfig",
		Resource:    "",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/enrollmentrequests": {
		OperationID: "listEnrollmentRequests",
		Resource:    "enrollmentrequests",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/enrollmentrequests": {
		OperationID: "createEnrollmentRequest",
		Resource:    "enrollmentrequests",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/enrollmentrequests/{name}": {
		OperationID: "deleteEnrollmentRequest",
		Resource:    "enrollmentrequests",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/enrollmentrequests/{name}": {
		OperationID: "getEnrollmentRequest",
		Resource:    "enrollmentrequests",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/enrollmentrequests/{name}": {
		OperationID: "patchEnrollmentRequest",
		Resource:    "enrollmentrequests",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/enrollmentrequests/{name}": {
		OperationID: "replaceEnrollmentRequest",
		Resource:    "enrollmentrequests",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/enrollmentrequests/{name}/approval": {
		OperationID: "approveEnrollmentRequest",
		Resource:    "enrollmentrequests/approval",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/enrollmentrequests/{name}/status": {
		OperationID: "getEnrollmentRequestStatus",
		Resource:    "enrollmentrequests/status",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/enrollmentrequests/{name}/status": {
		OperationID: "patchEnrollmentRequestStatus",
		Resource:    "enrollmentrequests/status",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/enrollmentrequests/{name}/status": {
		OperationID: "replaceEnrollmentRequestStatus",
		Resource:    "enrollmentrequests/status",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/events": {
		OperationID: "listEvents",
		Resource:    "events",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/fleets": {
		OperationID: "listFleets",
		Resource:    "fleets",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/fleets": {
		OperationID: "createFleet",
		Resource:    "fleets",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/fleets/{fleet}/templateversions": {
		OperationID: "listTemplateVersions",
		Resource:    "fleets/templateversions",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/fleets/{fleet}/templateversions/{name}": {
		OperationID: "deleteTemplateVersion",
		Resource:    "fleets/templateversions",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/fleets/{fleet}/templateversions/{name}": {
		OperationID: "getTemplateVersion",
		Resource:    "fleets/templateversions",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/fleets/{name}": {
		OperationID: "deleteFleet",
		Resource:    "fleets",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/fleets/{name}": {
		OperationID: "getFleet",
		Resource:    "fleets",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/fleets/{name}": {
		OperationID: "patchFleet",
		Resource:    "fleets",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/fleets/{name}": {
		OperationID: "replaceFleet",
		Resource:    "fleets",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/fleets/{name}/status": {
		OperationID: "getFleetStatus",
		Resource:    "fleets/status",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/fleets/{name}/status": {
		OperationID: "patchFleetStatus",
		Resource:    "fleets/status",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/fleets/{name}/status": {
		OperationID: "replaceFleetStatus",
		Resource:    "fleets/status",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/labels": {
		OperationID: "listLabels",
		Resource:    "labels",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/organizations": {
		OperationID: "listOrganizations",
		Resource:    "organizations",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/repositories": {
		OperationID: "listRepositories",
		Resource:    "repositories",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/repositories": {
		OperationID: "createRepository",
		Resource:    "repositories",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/repositories/{name}": {
		OperationID: "deleteRepository",
		Resource:    "repositories",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/repositories/{name}": {
		OperationID: "getRepository",
		Resource:    "repositories",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/repositories/{name}": {
		OperationID: "patchRepository",
		Resource:    "repositories",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/repositories/{name}": {
		OperationID: "replaceRepository",
		Resource:    "repositories",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/resourcesyncs": {
		OperationID: "listResourceSyncs",
		Resource:    "resourcesyncs",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"POST:/resourcesyncs": {
		OperationID: "createResourceSync",
		Resource:    "resourcesyncs",
		Action:      "create",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"DELETE:/resourcesyncs/{name}": {
		OperationID: "deleteResourceSync",
		Resource:    "resourcesyncs",
		Action:      "delete",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/resourcesyncs/{name}": {
		OperationID: "getResourceSync",
		Resource:    "resourcesyncs",
		Action:      "get",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PATCH:/resourcesyncs/{name}": {
		OperationID: "patchResourceSync",
		Resource:    "resourcesyncs",
		Action:      "patch",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"PUT:/resourcesyncs/{name}": {
		OperationID: "replaceResourceSync",
		Resource:    "resourcesyncs",
		Action:      "update",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
	"GET:/version": {
		OperationID: "getVersion",
		Resource:    "",
		Action:      "list",
		Versions: []EndpointMetadataVersion{
			{Version: "v1beta1", DeprecatedAt: nil},
		},
	},
}

// GetEndpointMetadata returns metadata for a given request using the existing Chi router context
func GetEndpointMetadata(r *http.Request) (*EndpointMetadata, bool) {
	// Get the route context from the existing Chi router that already processed this request
	rctx := chi.RouteContext(r.Context())
	if rctx == nil {
		return nil, false
	}

	// Get the route pattern that matched in the main Chi router
	routePattern := rctx.RoutePattern()
	if routePattern == "" {
		return nil, false
	}

	// O(1) lookup using method:pattern as key
	key := r.Method + ":" + routePattern
	if metadata, exists := APIMetadataMap[key]; exists {
		return &metadata, true
	}

	return nil, false
}

