apiVersion: flightctl.io/v1alpha1
items:
- apiVersion: flightctl.io/v1alpha1
  kind: Device
  metadata:
    annotations:
      device-controller/renderedVersion: "1"
    creationTimestamp: "2025-07-14T12:02:36.205843Z"
    generation: 1
    labels: {}
    name: aqb2l2s77kfa143fu7o3iccliukm832gdgb5gtm8eg314g8pp4pg
    resourceVersion: "82"
  spec: {}
  status:
    applications: []
    applicationsSummary:
      info: No application workloads are defined.
      status: Healthy
    conditions:
    - lastTransitionTime: "2025-07-14T12:02:44.175224309Z"
      message: 'Updated to desired renderedVersion: 1'
      reason: Updated
      status: "False"
      type: Updating
    - lastTransitionTime: "2025-07-14T12:02:36.238105721Z"
      message: ""
      reason: Valid
      status: "True"
      type: SpecValid
    config:
      renderedVersion: "1"
    integrity:
      status: Unknown
    lastSeen: "2025-07-14T12:05:41.957590931Z"
    lifecycle:
      status: Enrolled
    os:
      image: 10.100.102.70:5000/flightctl-device:base
      imageDigest: sha256:99f26a0cb7d9c8e9071c55ebd54f6989b3a7648ea732d38657070cb85d8ddbf3
    resources:
      cpu: Healthy
      disk: Healthy
      memory: Healthy
    summary:
      info: All system resources are healthy.
      status: Online
    systemInfo:
      agentVersion: 0.7.0-rc1-160-g91318412
      architecture: amd64
      bootID: 7cc514be-dac4-46d8-9323-a6129413b354
      distroName: CentOS Stream
      distroVersion: "9"
      hostname: localhost.localdomain
      kernel: 5.14.0-595.el9.x86_64
      netInterfaceDefault: enp1s0
      netIpDefault: 192.168.122.187/24
      netMacDefault: 52:54:00:07:c9:3e
      operatingSystem: linux
      productName: Standard PC (Q35 + ICH9, 2009)
      productSerial: ""
      productUuid: eef3d292-6cc0-4761-a85c-1db066d621c1
    updated:
      info: The device has been updated to the latest device spec.
      status: UpToDate
kind: DeviceList
metadata: {}
summary:
  applicationStatus:
    Healthy: 1
  summaryStatus:
    Online: 1
  total: 1
  updateStatus:
    UpToDate: 1

