apiVersion: flightctl.io/v1alpha1
kind: Device
metadata:
  name: aqb2l2s77kfa143fu7o3iccliukm832gdgb5gtm8eg314g8pp4pg
  labels:
    region: us
  annotations:
    device-controller/renderedVersion: "1"
  resourceVersion: "82"
spec: {}
