apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  name: us-fleet
spec:
  selector:
    matchLabels:
      region: us
  template:
    metadata:
      labels:
        region: us
    spec:
      os:
        image: quay.io/redhat/rhde:9.2 