apiVersion: v1
kind: Pod
metadata:
  name: certs-debug
  namespace: flightctl-external
spec:
  containers:
  - name: shell
    image: registry.access.redhat.com/ubi9/ubi
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
    - mountPath: /mnt/certs
      name: certs-vol
  volumes:
  - name: certs-vol
    persistentVolumeClaim:
      claimName: flightctl-api-certs
  restartPolicy: Never
