// Code generated by scripts/air-gap/generate-embed. DO NOT EDIT.
// Run "make generate-mirror-embed" to regenerate.
//
// embeddedBuildManifest contains the fully-resolved image and RPM lists for
// all supported variants.  It is produced at build time from source files in
// the flightctl repository so the binary is self-contained when installed via RPM.
//
// Known limitations:
//   - The embedded image set is version-pinned to build time.  --tag-override
//     changes which tag is mirrored but cannot change which images are included.
//   - To pre-stage images for an upcoming upgrade before it is installed,
//     either install the target version's flightctl-cli RPM, or set
//     MIRROR_MANIFEST to a manifest produced from that version's source tree.
//   - Custom image configurations require a custom manifest (MIRROR_MANIFEST).
package main

var embeddedBuildManifest = []byte(`
{
  "schema_version": "1",
  "app_version": "latest",
  "variants": {
    "community-el10": {
      "images": [
        {
          "ref": "quay.io/flightctl/flightctl-alert-exporter-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-alertmanager-proxy-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-api-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-cli-artifacts-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-db-setup-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-imagebuilder-api-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-imagebuilder-worker-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-ocp-ui-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-pam-issuer-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-periodic-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-remote-access-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-telemetry-gateway-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-ui-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-userinfo-proxy-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-worker-el10",
          "tag": ""
        },
        {
          "ref": "quay.io/openshift/origin-cli",
          "tag": "4.20.0"
        },
        {
          "ref": "quay.io/prometheus/alertmanager",
          "tag": "v0.28.1"
        },
        {
          "ref": "quay.io/sclorg/nginx-126-c10s",
          "tag": "20260421"
        },
        {
          "ref": "quay.io/sclorg/postgresql-16-c10s",
          "tag": "20250214"
        },
        {
          "ref": "quay.io/sclorg/valkey-8-c10s",
          "tag": "20260121"
        },
        {
          "ref": "registry.access.redhat.com/ubi10/ubi-minimal",
          "tag": "10.1-1769677092"
        }
      ],
      "rpms": [
        "bash",
        "container-selinux",
        "flightctl-agent",
        "flightctl-selinux",
        "flightctl-services",
        "greenboot",
        "jq",
        "openssl",
        "podman",
        "policycoreutils",
        "policycoreutils-python-utils",
        "python3-pyyaml",
        "selinux-policy",
        "selinux-policy-targeted",
        "sudo",
        "systemd"
      ]
    },
    "community-el9": {
      "images": [
        {
          "ref": "quay.io/flightctl/flightctl-alert-exporter-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-alertmanager-proxy-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-api-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-cli-artifacts-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-db-setup-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-imagebuilder-api-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-imagebuilder-worker-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-ocp-ui-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-pam-issuer-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-periodic-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-remote-access-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-telemetry-gateway-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-ui-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-userinfo-proxy-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/flightctl/flightctl-worker-el9",
          "tag": ""
        },
        {
          "ref": "quay.io/openshift/origin-cli",
          "tag": "4.20.0"
        },
        {
          "ref": "quay.io/prometheus/alertmanager",
          "tag": "v0.28.1"
        },
        {
          "ref": "quay.io/sclorg/nginx-124-c9s",
          "tag": "20260422"
        },
        {
          "ref": "quay.io/sclorg/postgresql-16-c9s",
          "tag": "20250214"
        },
        {
          "ref": "quay.io/sclorg/redis-7-c9s",
          "tag": "20250108"
        },
        {
          "ref": "registry.access.redhat.com/ubi9/ubi-minimal",
          "tag": "9.7-1763362218"
        }
      ],
      "rpms": [
        "bash",
        "container-selinux",
        "flightctl-agent",
        "flightctl-selinux",
        "flightctl-services",
        "greenboot",
        "jq",
        "openssl",
        "podman",
        "policycoreutils",
        "policycoreutils-python-utils",
        "python3-pyyaml",
        "selinux-policy",
        "selinux-policy-targeted",
        "sudo",
        "systemd"
      ]
    },
    "rhem-el10": {
      "images": [
        {
          "ref": "registry.redhat.io/openshift4/ose-cli-rhel9",
          "tag": "v4.20.0"
        },
        {
          "ref": "registry.redhat.io/rhacm2/prometheus-alertmanager-rhel9",
          "tag": "v2.15.0-1"
        },
        {
          "ref": "registry.redhat.io/rhel10/postgresql-16",
          "tag": "10.1-1776906601"
        },
        {
          "ref": "registry.redhat.io/rhel10/valkey-8",
          "tag": "10.1-1776907598"
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-alert-exporter-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-alertmanager-proxy-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-api-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-cli-artifacts-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-db-setup-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-imagebuilder-api-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-imagebuilder-worker-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-pam-issuer-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-periodic-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-remote-access-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-telemetry-gateway-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-ui-ocp-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-ui-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-userinfo-proxy-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-worker-rhel10",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/ubi10/ubi-minimal",
          "tag": "10.1-1769677092"
        }
      ],
      "rpms": [
        "bash",
        "container-selinux",
        "flightctl-agent",
        "flightctl-selinux",
        "flightctl-services",
        "greenboot",
        "jq",
        "openssl",
        "podman",
        "policycoreutils",
        "policycoreutils-python-utils",
        "python3-pyyaml",
        "selinux-policy",
        "selinux-policy-targeted",
        "sudo",
        "systemd"
      ]
    },
    "rhem-el9": {
      "images": [
        {
          "ref": "registry.redhat.io/openshift4/ose-cli-rhel9",
          "tag": "v4.20.0"
        },
        {
          "ref": "registry.redhat.io/rhacm2/prometheus-alertmanager-rhel9",
          "tag": "v2.15.0-1"
        },
        {
          "ref": "registry.redhat.io/rhel9/postgresql-16",
          "tag": "9.7-1766414426"
        },
        {
          "ref": "registry.redhat.io/rhel9/redis-7",
          "tag": "9.7-1766414358"
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-alert-exporter-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-alertmanager-proxy-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-api-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-cli-artifacts-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-db-setup-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-imagebuilder-api-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-imagebuilder-worker-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-pam-issuer-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-periodic-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-remote-access-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-telemetry-gateway-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-ui-ocp-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-ui-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-userinfo-proxy-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/rhem/flightctl-worker-rhel9",
          "tag": ""
        },
        {
          "ref": "registry.redhat.io/ubi9/ubi-minimal",
          "tag": "9.7-1763362218"
        }
      ],
      "rpms": [
        "bash",
        "container-selinux",
        "flightctl-agent",
        "flightctl-selinux",
        "flightctl-services",
        "greenboot",
        "jq",
        "openssl",
        "podman",
        "policycoreutils",
        "policycoreutils-python-utils",
        "python3-pyyaml",
        "selinux-policy",
        "selinux-policy-targeted",
        "sudo",
        "systemd"
      ]
    }
  }
}
`)
