package main

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"
)

// toolVersion is embedded in every manifest so operators can correlate a manifest
// with the tool version that produced it.  Increment when parsing or output logic changes.
const toolVersion = "2.0.0"

// -----------------------------------------------------------------------------
// Manifest output types
//
// The manifest is a valid YAML file written to artifact-manifest-<variant>.yaml
// in the current working directory.  It is both human-readable and parseable by
// tooling (yq, Python, etc.).
// -----------------------------------------------------------------------------

// Manifest is the top-level structure of the artifact manifest YAML file.
type Manifest struct {
	// Metadata describes when and how the manifest was generated.
	Metadata ManifestMeta `yaml:"metadata"`

	// Images lists every container image to be mirrored, with source and destination.
	Images []ManifestImg `yaml:"images"`

	// RPMs lists the runtime package names required for RHEL-based installation.
	// Mirror these to a local dnf repository before attempting offline installation.
	RPMs []string `yaml:"rpms"`

	// Catalogs is reserved for future catalog content import support.
	Catalogs []string `yaml:"catalogs"`
}

// ManifestMeta holds generation metadata for the manifest file.
type ManifestMeta struct {
	// Variant is the chart variant this manifest was generated for.
	Variant string `yaml:"variant"`

	// GeneratedAt is the UTC timestamp of manifest generation in RFC 3339 format.
	GeneratedAt string `yaml:"generated_at"`

	// ToolVersion is the version of mirror-images that produced this manifest.
	ToolVersion string `yaml:"tool_version"`
}

// ManifestImg is one entry in the images[] list.
type ManifestImg struct {
	Source      string `yaml:"source"`
	Destination string `yaml:"destination"`
}

// -----------------------------------------------------------------------------
// WriteManifest  (EDM-3960)
// -----------------------------------------------------------------------------

// WriteManifest builds and writes artifact-manifest-<variant>.yaml to the
// current working directory.
//
// The file begins with a human-readable comment block explaining its purpose
// and how to regenerate it, followed by the YAML body.
func WriteManifest(variant string, pairs []ImagePair, rpms []string) error {
	filename := fmt.Sprintf("artifact-manifest-%s.yaml", variant)
	logInfo("Writing artifact manifest to %s...", filename)

	// Build the images list from the deduplicated ImagePairs
	imgs := make([]ManifestImg, len(pairs))
	for i, p := range pairs {
		imgs[i] = ManifestImg{Source: p.Source, Destination: p.Dest}
	}

	// Build the top-level manifest struct
	m := Manifest{
		Metadata: ManifestMeta{
			Variant:     variant,
			GeneratedAt: time.Now().UTC().Format(time.RFC3339),
			ToolVersion: toolVersion,
		},
		Images:   imgs,
		RPMs:     buildRPMList(rpms),
		Catalogs: []string{}, // reserved — empty list, not null
	}

	// Marshal to YAML
	body, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("marshal manifest: %w", err)
	}

	// Prepend a comment header before the YAML body
	header := fmt.Sprintf(`# RHEM Air-gapped Installation Artifact Manifest
# Generated by scripts/air-gap/mirror-images (Go tool)
# Re-run the tool to regenerate this file with updated image references.
#
# To mirror all listed images, pipe the tool's stdout to bash:
#   ./bin/mirror-images --variant %s \
#       --dest-registry <registry> | bash

`, variant)

	f, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("create manifest file: %w", err)
	}
	defer f.Close()

	if _, err := f.WriteString(header); err != nil {
		return fmt.Errorf("write manifest header: %w", err)
	}
	if _, err := f.Write(body); err != nil {
		return fmt.Errorf("write manifest body: %w", err)
	}

	logInfo("Manifest written: %s", filename)
	logInfo("  Images: %d", len(imgs))

	return nil
}

// buildRPMList prepends the well-known top-level flightctl packages (they are
// not listed as Requires of themselves in the spec) then appends the transitive
// runtime dependencies parsed from flightctl.spec, skipping any that are already
// in the prefix list.
func buildRPMList(specRPMs []string) []string {
	// Top-level packages the operator must always mirror regardless of what the
	// spec Requires lines say.
	topLevel := []string{
		"flightctl-cli",
		"flightctl-agent",
		"flightctl-selinux",
		"flightctl-services",
		"flightctl-observability",
	}

	// Build a set of the top-level packages for fast lookup
	topLevelSet := make(map[string]struct{}, len(topLevel))
	for _, p := range topLevel {
		topLevelSet[p] = struct{}{}
	}

	result := make([]string, 0, len(topLevel)+len(specRPMs))
	result = append(result, topLevel...)

	// Append transitive deps, skipping duplicates with the top-level list
	for _, pkg := range specRPMs {
		if _, skip := topLevelSet[pkg]; skip {
			continue
		}
		result = append(result, pkg)
	}

	return result
}
