global:
  auth:
    type: "none"
  internalNamespace: flightctl-internal
  imagePullPolicy: IfNotPresent

api:
  rateLimit: null
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
cliArtifacts:
  enabled: true
worker:
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
periodic:
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
  tasks:
    resourceSync:
      schedule:
        interval: 5s
alertExporter:
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
ui:
  enabled: false

dev:
  exposeServicesMethod: "nodePort"
  nodePorts:
    api: 3443
    agent: 7443
    ui: 9001
    db: 5432
    kv: 6379
    alertmanager: 9093
    alertmanagerProxy: 8443
    cliArtifacts: 8090
    telemetryGatewayOtlp: 4317
    telemetryGatewayProm: 9464
    gitserver: 3222
    registry: 5000
    imagebuilderApi: 8445
  tracing:
    endpoint: jaeger-collector.flightctl-e2e.svc.cluster.local:4318
    insecure: true
