FROM quay.io/centos-bootc/centos-bootc:stream9

# Copy locally built services rpm
COPY /bin/rpm/flightctl-services-*.rpm /tmp/

# Install the locally built rpm
RUN dnf -y localinstall /tmp/flightctl-services-*.rpm && \
    dnf clean all && \
    rm -rf /tmp/*

# Enable the flightctl service to start at boot
RUN systemctl enable flightctl.target


RUN dnf -y install cloud-init && sudo systemctl enable cloud-init

# TODO add bootc clean thing
