FROM quay.io/centos-bootc/centos-bootc:stream9

# Copy  and install the locally built services rpm
COPY /bin/rpm/flightctl-services-*.rpm /tmp/flightctl-services.rpm
RUN dnf -y install /tmp/flightctl-services.rpm && \
    dnf clean all && \
    rm -rf /tmp/* /var/cache/dnf

RUN systemctl enable flightctl.target

RUN bootc container lint
