package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"time"
)

// GitHubClient interacts with the GitHub REST API for pull request management.
type GitHubClient struct {
	HTTPClient *http.Client
	Token      string
	BaseURL    string // e.g. "https://api.github.com"
}

// NewGitHubClient creates a GitHubClient with the given token.
func NewGitHubClient(token string) *GitHubClient {
	return &GitHubClient{
		HTTPClient: &http.Client{Timeout: 30 * time.Second},
		Token:      token,
		BaseURL:    "https://api.github.com",
	}
}

// PullRequest represents a GitHub pull request (subset of fields).
type PullRequest struct {
	Number  int    `json:"number"`
	HTMLURL string `json:"html_url"`
	State   string `json:"state"`
}

// ListOpenPRs returns open PRs with the given head branch.
func (g *GitHubClient) ListOpenPRs(ctx context.Context, owner, repo, head string) ([]PullRequest, error) {
	url := fmt.Sprintf("%s/repos/%s/%s/pulls?state=open&head=%s:%s", g.BaseURL, owner, repo, owner, head)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	g.setHeaders(req)

	resp, err := g.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("listing PRs: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		return nil, fmt.Errorf("list PRs: status %d: %s", resp.StatusCode, body)
	}

	var prs []PullRequest
	if err := json.NewDecoder(resp.Body).Decode(&prs); err != nil {
		return nil, fmt.Errorf("decoding PRs: %w", err)
	}
	return prs, nil
}

// CreatePR creates a new pull request.
func (g *GitHubClient) CreatePR(ctx context.Context, owner, repo, title, body, head, base string) (*PullRequest, error) {
	url := fmt.Sprintf("%s/repos/%s/%s/pulls", g.BaseURL, owner, repo)
	payload := map[string]string{
		"title": title,
		"body":  body,
		"head":  head,
		"base":  base,
	}
	data, _ := json.Marshal(payload)

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(data))
	if err != nil {
		return nil, err
	}
	g.setHeaders(req)

	resp, err := g.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("creating PR: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		respBody, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		return nil, fmt.Errorf("create PR: status %d: %s", resp.StatusCode, respBody)
	}

	var pr PullRequest
	if err := json.NewDecoder(resp.Body).Decode(&pr); err != nil {
		return nil, fmt.Errorf("decoding PR: %w", err)
	}
	return &pr, nil
}

// UpdatePR updates an existing pull request's body.
func (g *GitHubClient) UpdatePR(ctx context.Context, owner, repo string, number int, body string) error {
	url := fmt.Sprintf("%s/repos/%s/%s/pulls/%d", g.BaseURL, owner, repo, number)
	payload := map[string]string{"body": body}
	data, _ := json.Marshal(payload)

	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, url, bytes.NewReader(data))
	if err != nil {
		return err
	}
	g.setHeaders(req)

	resp, err := g.HTTPClient.Do(req)
	if err != nil {
		return fmt.Errorf("updating PR: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		return fmt.Errorf("update PR: status %d: %s", resp.StatusCode, respBody)
	}
	return nil
}

func (g *GitHubClient) setHeaders(req *http.Request) {
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")
	if g.Token != "" {
		req.Header.Set("Authorization", "Bearer "+g.Token)
	}
}

// BuildPRBody generates a pull request body from the updates map.
func BuildPRBody(updates map[string]VersionUpdate, repoFullName string) string {
	var sb strings.Builder
	sb.WriteString("## Updated base image references\n\n")

	// Sort keys for deterministic output.
	versions := make([]string, 0, len(updates))
	for ver := range updates {
		versions = append(versions, ver)
	}
	sort.Slice(versions, func(i, j int) bool {
		a, _ := strconv.Atoi(versions[i])
		b, _ := strconv.Atoi(versions[j])
		return a < b
	})

	for _, ver := range versions {
		vu := updates[ver]
		if !vu.Any {
			continue
		}
		sb.WriteString(fmt.Sprintf("### EL%s\n", ver))
		if vu.Micro.Updated {
			sb.WriteString(fmt.Sprintf("- ubi-micro (flightctl-base): %s\n", vu.Micro.Tag))
		}
		if vu.Minimal.Updated {
			sb.WriteString(fmt.Sprintf("- ubi-minimal: %s\n", vu.Minimal.Tag))
		}
		if vu.GoToolset.Updated {
			sb.WriteString(fmt.Sprintf("- go-toolset: %s\n", vu.GoToolset.Tag))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("Generated by the [refresh-base-images workflow](https://github.com/%s/actions/workflows/refresh-base-images.yaml).\n", repoFullName))
	return sb.String()
}
