{
 "title": "Flight Control API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Flight Control API" } },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"2..\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "OK (p99)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"4..|5..\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Error (p99)"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"4..\"}[$__rate_interval])))",
     "legendFormat": "code 4xx"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[$__rate_interval])))",
     "legendFormat": "code 5xx"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "flightctl_cpu_utilization", "legendFormat": "CPU" },
    { "expr": "flightctl_memory_utilization", "legendFormat": "Memory" },
    { "expr": "flightctl_disk_utilization", "legendFormat": "Disk" }
   ]
  }
 ]
}