// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package imagebuilder

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rc9w2EuBfQXG3KvbezEiyk33oaqtOlu2sNn5oJTn5EPtSGLJnBisSoAFQ8iSlqvsR9wvvl1yhAYIg",
	"Cc5DkfyI54utIUE8Gv3uRuO3JBVFKThwrZLD3xKVLqCg+OdRyX4EqZjg5lcGKpWs1PgzOTo9ce9IBjPG",
	"QRG9AHJln0FGbD9EzIheMEUklBIUcE1NB+Yx5URM/wupnpBzkOZDohaiyjOSCn4FUhMJqZhz9qvvTREt",
	"cJicalCaMK5BcpqTK5pXMCKUZ6SgSyLB9EsqHvSATdSEvBQSCOMzcUgWWpfqcG9vzvTk8u9qwsReKoqi",
	"4kwv91LBtWTTSgup9jK4gnxPsfmYynTBNKS6krBHSzbGyXKzKDUpsj9JUKKSKahJMkqAV0Vy+HNydUDz",
	"ckEPklEyy9l8oVOdm9H883ejRC9LSA4TpSXj82SUfBibr8dXVHJagDLdNPvxY9Nh8/B53fWJ+DHo+MN4",
	"Lsbt3m9GyZHUbEZTfSpFIczszzXVFW47zTJmntD8VIoSpGZm+BnNFYySMnj0WzITsqA6gh2ud2IbTMjb",
	"xMCTMg7ybWKe4jaeFHQOTyqWZ4S6L/4nERws1gCBD6WQ+jn2odwO4sfNFP2HCPDeMstqmjO1gKw/xwtZ",
	"AbleALcIamf6jfIdEgkzkMBTIAuqyBSAE1WlKSg1q/J8Sa4l09p8bnHymGqai/mJhsJtyIQ8dwtlnGlG",
	"c+KmMyI0z92IZkAgfp6EalGwlOb50n5OC+BZYahz1HyRZQajGSWnRxfH/9o7fXNBlKZSE6qarv6JW4ZE",
	"oSXlCiFmZtu00AEMgMlwDaSkOl3YFUMWQncqRA6UG/BKoNlyFWipJjlQpXFXG+g1QK75g10aYYrQK8py",
	"Os1haEgl8ivIniFu9Md+RQuPP4hftiGpCZPoBdXkmuU5mQJ5ICS5puohqRRkDi/9bCbkaGpYlsdXj8PN",
	"/A10zet6a7jQZAlmOJotIyiJK3hfMWlQ8ueagGpIhgjb8ATLJs3inzCeMT6/wOc9qC+AmC/M6qe2oZ85",
	"M5AgU0NqIWMCKnMzquGnGzKhYArP3NfBoxfY0c0owXfuRX+q+NZPMhV8xuaVtKJhTKCYQqZIavjMjKVU",
	"GwJqlmEW0GZDelN49Nf+bt0O4dvYXjz7wJRmfB7QzAWVc0CcpHn+epYc/vxb8mcJs+Qw+dNeI2b3nDTb",
	"Q/z0HNh+/YQqSG5GW7HhtJmCQf/VRBHSuBakKjOqIco8XbfruyypNGTievakFu3UIHqsv9elY+hOhRjn",
	"RuYS27yhTPeWANdyOSEvqbzMxDU3jENVpaF0yAbGLXOaWnj18UQxPs+9+mKHMiyr/mpktRyDrbhgyQoq",
	"l6Qq55JmQCCbx1erLll5Rvk8suBzKK5AEmneGkC6sZVlUCnlvveMSUh1vrSSxs3sAUzmRq6+rfb3H8M/",
	"Dyb7k32CP9KDyePJ/tvk4eCMIkA4aiTqdhMxgzANRUCIwWjuAZWSLpvf3cGfMvOrYJxqy0oRyBrpAUk4",
	"pNsI3UWoeJRcDamuDvD1Xtsv/Kgcrlsk0ka4KEPvsIZ3o86Ap5an+wUZsNKyBJ4pQhucE0YlBre6cA4T",
	"coYKLWSEFQVkjGrIl4T16TkTYEUQdjOxbKrRodbLDSeGtXC6VyA8tGiptEV2mYyS96m4fmQwQIn61zhj",
	"6nLsReWGYqU7zR9fPv0h6c/+P8evf3oUeX5y/nqo9VOmLo+b2dyMkkbtXKvutiEV6KvenjFbOHWP3lfG",
	"KkEFNdAVvNCCD7Qoc9wBGphWAzbBKLlkPGuNmoySAjTNqKamE46MOUmBa6HGUyF0OlZaAi3+McYpIb2X",
	"kJrG00YWu+1AoX+Da9SG9Byx4HQtz0+K5bhSIPdaQ6SV0qIwm25aXtB5cphcIf9BPaYUimkhl/ZzCXOm",
	"tETit1KhO0bYd2ug9ghuYd0h3ld0OWYiuTGE2JaKtGW+rpLDgaF74wa16B9jlIaVGVKJKZeOZzaWA3LJ",
	"ZgMn5DXPl6QUZWWgn1kl+Zrphe1IkfcVyKURqLQAbZBHEaOkt7jsWpXC6cYR/mtRqrumHxjPUPWumSGa",
	"Wg2O12Lv7Nn5RahIGwmATC8gh8aaN5Y44zOodWopCmvV8awUjFvekubMqA6qmhZMq5qGjKE/IceUG142",
	"BaekZBNywskxLSA/pgru3ZY3wFNjA7K4cRnS4qo9SYWEX64OpqDpwS+iBE5L9strBNxL0DSk0rVbi2h0",
	"blqbr7zNvuF3tn1XxQ0IxWFIsDY3t5gG3HQ8qOj3mhDTG5sxUAPqfy2Hva2ShcqBGaGgZekGszr8wLpb",
	"JoizcQaaGrOlbtnwkaXjULjwm1EiOGyg1LeGNYr8qsatgduy6VhwK5g2tyeiiOb78ZZF3HjaDIV8b6hL",
	"bGgs9TQi3wtud0usevdZHBhnQFVMqbPPY56lM2NZGySzHYRKzCnUyIFN7Z+nlVrYv74HDgYr+fz8yeuX",
	"ySg5FkZ+azAE8pyyHP84pjyF3H5h/24Z76uUnsH1NRMbbBLMeLgbv5TBJr01DrYMFz/YyENluJsAXGsa",
	"GTjGsWBAkXVKbLD50W1HjLj9FplhXBet2T1t61FDjDBoFjBDg7SBItZig3rI7xGoUTGlngcmuqh0WQUd",
	"FfTDC+BzvUgOH3333SgpGK9/H0REXaOIRa0HOt9gnINHf++OU1KtQZpu/vfPb99evzP/TMbvftsfHTz6",
	"282fB+x4r/2tW/SZb9toLeaVwZPXxyfWF2oMszagnamzEiQdxhfMahRsSwC41QL0BVN6FdKY91ZDy81f",
	"bSRvxRzuSAeudc32hF6sGXxzFfVJbZ/sNNTPVUM1m2310+30RYsEq/H9FVy7Ls4sPLe0xN1XZCqyZei6",
	"8U6dauqxoN7NPnUEDPdkkMG9vgIpWWZ9kIZhT4LPJjV9T8jJjIiCaQ3ZKHCKfqOQOzKFEYZ74Yh82D8b",
	"OrUiNNsTBI/XCgL74TbQckN9ckB1kBihthpJz2B27l0WQ5zZNwqEOSUO9aw4Qb5C+dAORGR63fN6ERfp",
	"E736CghVJNjm1du6PoLSdFWrUc1MN4yijDqLWw399aDvwd0ApA35rjF5a/0p7PY+9acV43x++pPzcdbC",
	"tzf3j6hAnTsHyq28ueZjYl9OazSySJU22jjl3ShqG5kCB+tm2k/gcOi4YDf7PrQ30DsxFVTG3TA/YYhf",
	"VjAijCtN89yu0nuex83X5Oz0JYa1gdNpDiraaKxAV+VEgbxiqaWzGZNKo+eWZIBP246dK0YJJccivSyZ",
	"Hk+pgowEo16zX6nMJsSYmVSzaQ7oFyVToRcE/Tw4qZxq8NFc8hRmtMpRGSO4x/GcgcbxvKGfzLa/GSWV",
	"AnkcLmPzTt70Pu3ivJtWe/tHHpHWILz3/Q1iNbYIIxWozlYSg7XWd+gSsQIPdd+ECHTQOMsIW9Sso2O3",
	"9mPLtTUdWcKxm2LTpi/tbmFtNA61iNmBMz2r/fbxdc6qPHc8oPHw99drQ7Mj8r6iS6PlCznfwxeGtR5q",
	"Oo8HZnOq9DkAj49t3hLNCmjkGbk2Eh6AkwcLoFJPgWrsus7KSoxJMjYfRW0DytkMlH7K5hAzPs2oGb6L",
	"rbH+eqOIaIi3b2IUNYTCvcaBsDekuc533MZkzK1JL2FA8tnX5BIai6I/RnTrTDM+qEbUb7frtcMr/BCj",
	"YBmDHKJJjtpWHvqAVhPe5HUsuA5wauFTNA1LRhcKYgXy4YzNkDbq5D/1e0OfbjHR2GexHEM2h7Gd4dho",
	"2v3Qp6eHOlrdCUQ22vaqWKqHdaD33mHUcef3+MIjcxZNbxGacx/eQ2zO9vzZBZI607rrSFI3Jj8Zgsc2",
	"sSTX6UbBpGPLHLvhpHuJHkWX1AkfRdu0Jrmiq3YIaaCrTmQo2qodGop31I0NrWgVBodiCLU6OuS2827C",
	"Q5HhO/GhMDHpdGHIJ66BmFeoktcJiS4fy4pb1Zno+woqhGga7mXpdyx1+2JUQgv8rRcVTPk/9Wjx10P4",
	"FDSJ4lKrCz/feAOHQh2wroidNA0iwZM+n/iY0ZPY6LsMn138ZG38xKkLq7yjYZNN3KNWe16XbBPovWtt",
	"7cZ1/nvTaaJ9vosB42JDH3bnUESz+E0c2+sYZjOVIMzZne4tfZXN15s7K5vVDZ3cWpnL1E0e3s6Z1kLV",
	"Qe+Xm8o6hF/l7wqbbO7wejYAm9/hm2q63JaXr/RObeMbcsb6x3YO2WExRT30D/XOVG3hL/InY25DLP5j",
	"oiVNL1WjU7kjVoRqDUWpY+E5LQhtZeAnX5CZ/7kYxM3R0u1t4u6x1Ds1i33nn51l3J/ZXRvHDVlE7OP+",
	"8NuYyE3XK6zknygz2PxcyPqMsEIjGUlyhZ2MdNn+5e3AUXJUH5J9vrWdM7Tm+ERXftJaxcqWPYt5qGHb",
	"aB5q1QbO+qYB5FY27oF1GFE2sLkb/Lgbszs+iY7l7RutsBJbbSKGYpRmPqatODCBzVWMRpJ+GovxS7Gt",
	"GrHjldxt9I7MwMWbWvUZ8QfqYXDqvo85rSoHKw7G1jgZKX7gj59rQRhP8yrzR6aHzzISdDl51Lqmxjxn",
	"nEQ4H6m4Zvngaf7QoYEnD22VBrgCzBxBg98er3ca4EaYGzM+omHb4WypV+sypQy6NiBgiuSMX0KGzomL",
	"8MT/HoaEGoCXUmRVChmZLm0vNiRrCCa/pktVb0O2fh+2zJTZMIeqrX1th8hPQZnR0GSC0GLqM6I+Om9h",
	"H3bJzWywP0K/7cH5YQPT9bkBqAZszNdTBfLqtgCpccb2HjuBfgpyHJQdoRnjoBRRVVFQQ6ivOVhciZ1v",
	"edCvSvEQ47LCf1WCDMgw5DcT8sY63ghtKp8oMoVUFNCU4iBCmgYcrltVSyJ1SDam7qECNBEiX2mPN3a4",
	"84nUgim0+5tKBX6/cjaDdJnmcEtJutZeR+UJsqOY9cwKUJoWZT2tQigsd2QdpU2VlFr/Ig/YBCYjX6rF",
	"mvyBIHBGvwsXGNt/bXWah768CevCZoF7fQXSVr2hdiWbew98EZONFl8XxwkW7qcyIedgxE3alKkJ5okp",
	"Z4Zg0gUo4pVqu+UT8kro2q9s2LSqpsoQAddBUZ1NF7XeSdEU/+iUG/D+1+sFSFuPZyGuA5Wgqy1Y0YNO",
	"yxkDK1XwfFDonF3nrY2VSRgUtEOVTEbJK7jeoId2q5of/07P70Cn65SGobXcvBvYsifReNyxKApEMcgz",
	"RdSCSotFNM9JrBdyRSWjDqPurjxLKgHZlwwKtazJNb6Lsi23ShffqIzHJ6zTEUlID2E16m1UM7l3G5L/",
	"xRaAafjYQKWTDu2NNit9soHB3My1N8RQw+jQN6MkPMDcN2KDZN1elSeXJGxeK2NZWGZu1Ow7KvAUL2q1",
	"cX2nKPv5oko7Wd7x8Uo7ZUyVOV3GO/Vm7KIqKB8bLRc1S/cR4d3zSh33+/aFpIxSF6si1e9+izJSd1DA",
	"qENzX17tIotXitA+IIcKFbWiKTax30x4zq6Akw6OE5pjNTznSkD39JnDux+ivqozb88vS1CoDCtnmLSN",
	"JZDk6PQk3IxWcZ12umnHcxbbpyGD0UUi0X0mQVeSO/eZ2anUHb+gmmSCf6PrFkIvQDrn2R06GFORxaqP",
	"VfO5NQf/dXFxWk/BtG0idjZeMyL7Zge50ESBbunLjOvHj4LEWK5hDnKXhXLnWShK0VgJuaMeM21e+wNl",
	"Puxt4VjCikR2ORDuOSIFTReMw+BQ14tlZwCz0c739RbjOJWEt4mbD54CtQX9EAWYIlCU2vRhbCSmCBcI",
	"cYNpprOmKig5Ii76lOZUugOX3KKxWyyi8bTSTT00UR9LZTpeFW81IdfFDTzw0CUjZofkbXJuzda3iVHS",
	"g5XeO9qoEtIx5dnYgXStzhvzjbuFOzbhMaBBuphqtEEQtAdJ87QJ/BgGUNkDQzOR5+LakP4P1RQkByNa",
	"jk5PSLhc8ka582CofmGAPssMI3GpL1YRNFy9zzlzqvSFr4B7wYYOarTzKJq5NtVzIbPsBf3fFjWwbB+y",
	"7i2yKzYmaNey59uq5zZyfmbzIgNNWa4MGpZSzCUoNSHHgquqCIprG2ooqVSOr6J9GyUJ4ZyedYUYMZB9",
	"MqnDK5O5b2mlWxuKNiFFE3vyryotCwplyV+/jcqSYaY0lQxmoz5vku3otJ/DN8rtsd9Qi1hGHuGHnucT",
	"VsdypDvjovu81oKb8XqX1nCW26cVDCRBeNqNIPidUPL5RlwxQEZXu/sCT5o+R3uGvOGXXFy3Qr3mPQb3",
	"c2X+dy02NGU7s3N9dZ7WXXce+5GGlu7jitGArHkTpN7ViG+xXS25XoBmaVANsKiUJgt6BSGd5hggM1h1",
	"RSUTlfIy2ql+5KhRfoxyYzoggufLGr6/NRk5I1JP7CaayKYZryKM5iVdGn3H0KPz/uKhNPObkpwVTBNh",
	"ZTeviqlRS2doTymnKUJmq+0bqztFY8BTPHINiT7kwghAhFAgvg3P8EJflPR9Bb5w/xRsIW4tCFMKX1it",
	"ODh61lHtDORtcAb5GQZJtTDTlAyuwNlFH1B5xchNE9OowX1swWT2But2Kqa0URaxLzMtpx2WQik8mOxA",
	"5lbadmyYdacLyueQGU6MINALygklM7gmBeOVARfuaUmVMtqmAUm94/WtCtbzW0Pber8rZQUAU6TeWgfK",
	"up65ZVspzWtIOUjbvaz95aoU3JBmxXNQiixFZecjIQXmQanFJXCfHQdSmuWs4HQSClsMwBhyx6LiA3mD",
	"DUYFHnmLXG6eCPjrBUsXGGYy4G+HU+uNrpfi1Emon1pkqQNjGcnpFHKCh9QNVBXkkBptCwuQdPHcr6Oe",
	"lCKV5Ru2lv6idsvXQM9hpknFkXh4Vhc3IVmFNo4CyWjOfnWKYzhR3EcbtCAPgCGmTyGllRFA2mrBmqSL",
	"il+ankTzFkHgwgIo0rDRw2Y9EhzoLAZ212QXUsv/262ktr8E2tWI41cHk4PvSCZqazHUMRDLjVjnZhsr",
	"5V1MfbwxK/sLKM0KrEz3F0tt7Fd3NiYVudk/nMQx2nUt7UYCcsqhvrWoOZ9RD/AHfKCp3kgbudlUhgY5",
	"k5Fwcv3OLLQtRWiek9KwALTNo5LEEoYjCIVfOFaGTNy1bZx/HTeCsXWpj6bGXZGRSt4dt5BvbHW6pWeI",
	"rOUcDKBk5uO0Ewz/Dfhza/XbGfxGa7RL2SL+mEEOtxnLUQF+vs148xUq8hGxLC71LKbl7ggsmEB9dpSR",
	"hXkYE3LqywbX8F4q53Wj2dgoCBtq1MgOV25/UHbmr49H67DhJcVgrnPqXMKyVm/wwhZfRj6Q7kLOKTcE",
	"bdoZBWIupPn5QKWitE8tk34YOsR6SMU3q31orxmKFLvqGz3XHGRsE9vXh4hrLI+P9xrZ50bBI2/Rqt4z",
	"Y9tbbuIJ7/YSk0DYRwbktWrkgIrDsnaCmdU/vlHBPUhOeWhdr7RZMDvKxU6pThdBhTafJ7FFBEMMUF/j",
	"KNLCsDwDrtBIoFmW+Gsb8K9CXCH5mcnEvLElNRvb37t/n79+RU4FQomYRvE4pMHW+FStEuV8DkLWt0JM",
	"ehaZKBM3jZix1c4SMbYhpJVkenlurEBXRQioBHlU2ZVETcb2R3HTMehmaG/bI9lfz2ve8e+fLpKRvQsM",
	"a+ng2wZqC63LwY6FnJ9kcUC+eXPy1FOlZQGBv8BRVaMLTwh5SUvnY2l90IjNiaE2zOHhWA4esIKUKw8h",
	"5PwXFpRuoCX7ATBDx0/y1iC2PWAFCMZnora3aIqUYvSOPDlMNNDif4VVLprJGYDYO7vQApEiJxdAi2SU",
	"VDJ3QFaHe3utr2+ih11IHd0ICzK1+5685Rfo1HctCsqxYkdQ0ypQN8z3U1dh2Bf5cFHc8FoDNXnLk1GS",
	"sxS49fq5xR2VNF0AeYSXArTXc319PaH4eiLkfM99q/ZenBw/e3X+bPxosj9Z6CJHkmE6N9114NRe9NHp",
	"SRCqP2yuWzP7bHcrOUweT/YnB448kdT2aMn2rg5sbR5cLD6OJvFgOvZQ1VPPyQxGYdOmpcIRXTV/hWHj",
	"vn5grRFrthqGlOrGRkCDxBmBtZpnxT+T1q5RQ9iPb89d7zU504h2dzO601nZnJmhWeHb283KUExBP7Ci",
	"Klr2msIaYH5CoRXpLcQhGLGC6dYsetEtN2JyeLC/v4+pMfbnfsw8iApyF5BubnXQwl304IwzuwAfubKC",
	"fWjK3quzFeyM3ekKwDnDQYJVJuMXWTBOgKaLEOlZbVOtBmlwnUVripkt1ubVhG6dtpt3qBhh30iJj/b3",
	"a64K1plAyzJ3x1z3/uucws0Amx0jxoMgyLY7VtkPhl98e4djerdtb6wnNCO1WoWDHnyEQd9wWukF6tmZ",
	"HfXxRxj1uZBTlmWAsehvH/3jIwx5IQR5SfmyBjEmFX/3UVZ77qTrG+79jFbdpnPlk/en/lB4KWKHko5t",
	"zt9wxdi2wLHNW4kMzgP2RNjbGe+YguzCG73X8JWbHu0e3NvIMWhlqIXwSxzcnm9rX/PUhlnabdGW0l6N",
	"+bNndlORLf+0V2udaOPhzgbQb6qudQbrNent0J0WRVsz6VsVRlvd50BttJtR8hR9Kau2Iuu2uPVWfA96",
	"1UDz1uu7GeWFmK8ZyLS45Vg3O3l03/Jo/2PIo2PBZzmzPoCdBGxLwA/jWrDV3MNZYjejmIG295uhjRsr",
	"M7FWVD8XE59vLD2frmY/P9+iALtXjNET5PVixynbcnOVDn+f+vDwBn4iPXjylTGebz/CkK+EJs9FxbMd",
	"5+lznqif53uMfG7GOb5foU98SrZxF6b/H8DO3/G2HW/baVXbaFV71irGUulxxwS+J5TIimMySe9mW9uf",
	"4SCuBu2I1BcVjoiQxJUAdYeyXVA4deVoIq6N1Wb6z7e8HccO+CWoaZ8lO9txs3vmZh/VKiVjS6Iuzc4R",
	"B2ZIIpXu+Ovm/LXmoKvZbG6dRoMKaC7mqq7iGdMTyXPzLtXsygVu1YjYuwqU/TZnV65V6msi1A1tlMwl",
	"wn+3v09yxmNhzO9XO7E+TwXXQsECwYXJRKXyJXmQs0sgl9UUUp3b9+PZwygkLwFK/JrbHEMiSuDroElz",
	"1yvmM+VCwXD8E8+73LXGrOGD3oMr4NpdW9Gmik40W8zri1qpcnmc43Pgmjy7stmUFo4PMOvYTvifBsIW",
	"K0N4PYxnF5nZlDllfPNpYHNivmyPizAh7lhtdwdiw++0/p3Wv5NKodwxAme1SGquTl2h/buwZPc20Qwk",
	"HhrwJwVcqQgiOIxIKsqlzTtXmOpqT/H5nAi8+tAdzsQzvTq4cG7ChJnZ2E1t7EaoE5htakoqZIZCzJ1L",
	"WB0cbS6e3VaguUoI9+3vvc/Abf/W3c8ykruzaf5YvJqMI8Tjj2Yju/gkZk8wG2RKthoF75eg2AmbLYRN",
	"IEq6Mgect3h9lmXsdpSBNMvGBb3Ls9zlWX7sPMt7d/4FdxztPIC7pMVPxvkt7948a7HDwVdq5kNZcXdN",
	"RZ9E3Q2H3iZzcTCbsNfk1qlsQe7L0GhZr8ntRxPXPBc0Wz1epNHvTtUbGmzefn9H46zMCWya7JICd0mB",
	"u6TAuITpGxe16TBgUmyfF7hWPj1dw/k2i4BEhtmlBu4c6TtH+mfNf9bmBq7lHt+vUi3+sKxjjcK74x87",
	"/rHTX1boL7fMwHO3jtoUPNdjKwevuZz7d2bh3R07+wLz8D47xrbja3+wRDxHI7tMvDtgtUO5eB2OWzuc",
	"BoNStduqq/s1d+/V4QQJc6Zcpf2OLbnWq/UFqYQi1RDPMvMhnSnjFEMpG+RmkTGp7wIj01xMST3szSh5",
	"vP+ovyF1TPkMMiYhdeU+LehtD2/OXiSjZAE0c761FyL15dmGwXCDI/4tUroIilJIKpfNmPc0/E6E7FTj",
	"u+PXHwOXTuraczaNlDyTUsgvUVx4QbBGYGydvd1l2mHSset7g/xt33LbBO6hiMMnlTj3k8LtYbRRDncP",
	"ol9hEreDwSfL4l4x/s57tBORO5OmLaNiidz+GsFN8uoGbpIfSK07bbreZdftsuv+gNl1HsN3CXa7BLtP",
	"KwDK5qbBTXPs+tw8vFWaBnpWWOXX3QyixExfUwn19YsrM/SaaxDvMUmvGeRT5Ol1Rt8dTfkKkq/IOEJL",
	"ndtJ+cCVpDuu1edafc010E6HFdfts7f6nG9lAlfIvrb3gcQH26Vx7QzprzlcueOBcR64NndsE95VO2+/",
	"Rsa1XhvbMbCdJ/CrMQSpTiO3GuHNTKsMQXtX5NnzY/LXf+w/cncgmY9cmpjnN8rd7W+a76kS0j3bw551",
	"OtorgRR5ICTWcEgXLM8k8IcYJWmOp1gnHl46SNMUSrxG3UWPZq6Pgi7tPaZTIDTLICMPaFkCt5eXPbRX",
	"BPrl23vs3N2bjJPnlOX2Us1Ta+H6FDZ7CU2bg+JaP38euqkpPUY8+B/bIeL6O702MrS/Ata+4+w71fQr",
	"kCVVRDU9s5fZrVJPrcQwsmHinnRkQ8DFyf/7P//X+herqbs+1t6jbJj5FO9ar0qQ7jZmvD+8krK+btlK",
	"FX+3mxMq7mpod63yhBzlObH3QmNFIRup8SP07kBWWkjw11EKSSj5dn+fsCbYcqeSxwH0jyN77teN+/Gl",
	"y851vBNrX2iCeCp4zS6rMsPTG+7lzid9K5803sKK95gjU7Y3Ve4lhkG6Pnu3dzeGk+CDd0I6xhwUTepH",
	"1SM9xeoehV25LJGN+hrI9Qi7ayB18+7m/wcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
