// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package imagebuilder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9a3PbNrZ/BcO9M0129EjS9j48c2eu6yRd3yRN1na6HzaZDkQeSViTAAOAdtSO/vvO",
	"OQBJUAIlOrHdpNWnWAR4cF44T4D5LUlVUSoJ0prk6LfEpEsoOP15XIqfQRuhJP7KwKRalJZ+JsdvTv0Y",
	"y2AuJBhml8Cu3DPImIPD1JzZpTBMQ6nBgLQcAeBjLpma/QtSO2HnoPFFZpaqyjOWKnkF2jINqVpI8WsD",
	"zTCraJmcWzCWCWlBS56zK55XMGJcZqzgK6YB4bJKBhBoipmwV0oDE3KujtjS2tIcTacLYSeX/20mQk1T",
	"VRSVFHY1TZW0Wswqq7SZZnAF+dSIxZjrdCkspLbSMOWlGBOyEokykyL7iwajKp2CmSSjBGRVJEf/TK4e",
	"87xc8sfJKJnnYrG0qc1xteb5+1FiVyUkR4mxWshFMko+jvHt8RXXkhdgEEwrj59bgO3D5zXoU/VzAPjj",
	"eKHGXejrUfKDkJmQiwt6vinciyUwfAPFNHMT2VxpYr0o+ALYrBJ5FpIIXOerZJSgZAaSE6DwzL8dPHpJ",
	"gNajhMb8wDaqNNogmSo5F4tKOyUbMyhmkBmWgrZiLlJuUfQtGUhAqVWJw0Aqb4fyY5v2LaLX61Gi4UMl",
	"NGQ4jUbbWU75URbPPpZK2+dKF9zuF8ic5uFOAHovkIpVHa0rsstklHxI1fWTZJQIo+pf40yYS9Rcy4UE",
	"PVBem2j+/Orpi2Qb+7+fvP7Hk8jz0/PXfbOfCnN50mKzHiWnSM8PqGTbzGjHWqtiGHc6yZDjaBtQXzlr",
	"aOwTOO/YuP/QME+Okr9MW5s49aZnGljD9SghcE4AJmIdteYrFBbh6mhmjWlgdsnx5xw0yBScgWypmrDX",
	"Ml+xUpUV7qaMXS9Bsmthlw6QYR8q0CtWcs0LsEibYVZXRJ2wUJh9pARYIS1e9hyRxt+XQkbY/kLIDFfi",
	"zCmJs6itCPARquLZs/OLhlZHm1P1QFqtyUdzLeQctJs516ogKCCzUgnptDvNBUjLTDUrhDW1iNEbTNgJ",
	"l1JZNgNWlRmya8JOJTvhBeQn3MCdG3xknhkjy8jkbxnaAizPuOX7ZJIqDb9cPZ6B5Y9/USVIXopfXhPj",
	"XoHlCMqUkA4SLanROc7Gtyy3lbnBe27+pvUKNorXkIA2j1vMuLWAe2341hSG0MRcgOmx7LUzatxQJhBg",
	"ISS3SuMKBS9Lv5gzzz10d7yLd189U9Ej1TPXjR1Z/cQLfIUIX48SJeH1PDn65252d5Zdj3ZP7izctY4n",
	"SmbCeuvF83zA0lFFa+D8wA0QQnG/OEyFGmjkzQb6wfejDbVooJC4O1a/ibHizDgDbmJBq3veaE8A8gx4",
	"tkIlcwBCN/oGauWgqe7PN5VZur9OVFHmYAH3w3MucvrjhMsUcj+B/oZsoJftJafFo3dKgGA/mAbz3ikh",
	"Sb2TGlr7wQRM2DMJuRMXZU885GOhQIJR2ZFYP53xuIwH0cHuKRiLpiaaGUWnBRYNNS8LRkJbZvvCFHrs",
	"LE0sNkQiXKoFTFW2rAJAWx6JRi74oifM5IvBkDSUygir9Go/WmfN3DY4wCGU5OuTU4xny8osN1nhY9rd",
	"kXWAxyhgVUDqbs/0Uhi7S5A47kKfHP/qKl4n47ul4LIO4roIvdyz+PDYz0XWh9DvCw79UNgu8LtZIOaU",
	"YLe+n8H8nGS0S+mbSYHt4szL1u1NEhmXMYXsMWE15P32IgITbURlgHHD2kW2uL4/hW9frv1Ei9vANH60",
	"Qc5ufu9n9hankQVdXm+GvJ/sIEKwn+cg9kK6TQfhU/na1uxZ+5Y9xLlPvXrlV0LK3OCslp6TZdp6eS43",
	"q2ddGc7aBGmYBQ+ykawbkgx7P4xjMFNs1HRgpujmr0dJZUCfhBnacCBvt17dlJ1Hq0vjqOHWHsE12W+v",
	"6GhGWEoiv1NpTY7Hjbp6dVCj2fb1gbOIK3s4o1b6jaBvawM1UW2EhBOPYjtn23Z+QljQppSR+IAwPasr",
	"V3E651Wee0Vva1zb9LIHMFlMRuxDxVfojpVeTGkAjcKR5YuHUY7k3NhzABlfG0eZFQW0tpJdo78AkOzB",
	"Eri2M+CWQLtCanKUYOwwxpeiTpxLMQdjn4oFxKJEXDWjsRiN9dtxC7VDb9/GdlSfCm9NDhwJbs191ZOu",
	"JpfVLBfpJfTYbDfMLmHVANpeIyo6nCZ7XVQ9ejOoG7aiWWIUkNFrIXwJNM7ZpmrblphlXXKvi8xWNc0q",
	"LjOXwJDgqVOViTmpv/U1+1vMEA5x+ldeonXa9Qk1Wv/iHRRpHeQvrqK4gdZtlxQ3mzOTPn7cpKjogQ6q",
	"Kp44A3IvdcUoSRuFxeicDpI7QHWLiz2gNqqL0Vnd8mIc0GZ9ccessMAYU6jdFUYvztspMUaW36gxhj3S",
	"N0vcPnFHjEMUmTIj5CKHujXsXJLZQPRDBRVxNA1lWTYSS71cMDJyzL8xUQHKf69Xiw/36VMwJapLHRAN",
	"vvEJXoU22Lqj1tdOiBT7tu3EfVb7YqsfWr2Het/eep8PF3YVoMIpQypQLgbe13UNSmp7U862Hvm5fdUo",
	"zPcxZlwMLBNuHHxqiR9SO9xnMFtUgrL8Jrr9pad2wvDaU0tA13rV2fCevvXmUaWblY062thb5/Go7NPp",
	"XZWdcMrw0s6zHt58RhWmBXlTc72zDnOTKojPWe+7DOKWhWyjEuL3EzoAWnhgZSQ8A7HtKrmF3jOAGVyJ",
	"1A0bxi2bC20smyllb+n4X/zI4+DTf2fef76IuuKzxrui8yGmGsjYleAblT7Q7PjNaYhXYFK69Y73Efn2",
	"7Sa/hSgY0GArLX0wgGJMeZ7702yZkt/YeoayS9A+FLjFQClVWUQ659UC1Q4y9reLizc1Cji3VTW31Ufs",
	"ERNzhjGEAdvRfSHtt09aTRTSwgL0IUK69QjJGL6ICPGYLauCy7EGnvFZDiwYbrpNjb12fCxhR61R92Tr",
	"x6zg6VJI6F3qernaWAAF7Y8Nv6NcvNLwLvH4TNipR8ipgDAMitIiDND0UyriOGoaAuNXXOS48IQdM188",
	"SHOufYdVOjX2xJIazyrcX2BIc9UVaC0yYMJGCTe7N3J9tKNhHnst0bAdsXfJeZWmYMy7hCkdUnrnaoPh",
	"ypjLbOxZurfMG4uJPeHeTDQa0CpdzPgOKF1tcRKftu4eDUDlejpzlefqGrf+i2oGWoIFg0aZheSytwbo",
	"MC+j4hqzivEsQ0PiYzbnatCIb1tOdOwXmkvjSgeir5beDQBaXG3zLmTOvCjZbCzERJLpvkFY0Leh/4bb",
	"mTV7zM9j6D0xKpULloHlIjeMz1RlPcYNelHVVjODhjL7EST0NUWQ+kmdHk0WzUznpbrccBGRZTOOLrUq",
	"3bKhT/jP76I+od+4PJhpAfOHTHeLgs2a35hBlA6rB+9W3p4ScbNNIrp0K5vmfJABajgyIhVUc3ahKxix",
	"5zw3MGJv5aVU1536FY5TLTQ3+K+fMTDn2sDOw9p4WoPeeNys1Ed6k7pHazg4EqRntW46hTQraZdgRRrc",
	"DigqY9mSX8GICZnmFUW1uTDUgcrYFddCVaZxhz7KYsdtnIFxBAJgSuarmr+/tZ2KEasRW0eTHStkFdnT",
	"r/gKQwvcMmLetujwN2e5KIRlyrlJWRUzjADnjLIeH5RB5q5oeSNQX4Qg304REFtywwr0NcShwFPitm78",
	"qyr5hwqa214zwiND+yWMoQEXgAZduo0oCjlPpsR5bir0WYVoagFXzmpK+EhxIiWINSYtu08cm1A2dM3E",
	"CGMxLiNYiJYPxEpljMA3Pcs8pd0sBelOl1wuIEPfSyywSy4ZZ3O4ZoWQFbKLZFpyYzCwQ5bUEq+v4s0F",
	"0Hkpx213caQyLhgVhtWi9ay8FnmOKIoMnVPK85pTntNOli5f0mBKJXFrVjIHY9hKVQ4fDSmIhpVWXYJs",
	"DoaB1kiOsyU9cVrhDvWcWihOVCV7cstWo0w1MyhYab1yeTyJ8ddLkS4Z10Dsd9sHU1AZCLomxUduUD91",
	"ylLfGMpYzmeQozgcVw3kkGJgM8KXNvW8oaNGyrDK2Q3SU8dIBFMzPYe5ZZWkzSMzpgphMYfJKkonDGjB",
	"c/Grj9FCREmOrvTNHoAgTZ9ByiuDMaELOC1Ll5W8REiqHSUWCONvUBo/6WFLjwbPOqeBmzQ5QjAx+XRK",
	"6lRHUcZKOn71ePL4e5apOjEL1nBajp5Xohgr0xwk2dYbpOyvYKwoKL74q9tt4lffIklVjvIjJE4ohWru",
	"m+K6GshS9sG2qrZ86NHpB3zkqR0UMKyH+tCgl7y1CdoxJLTrRXiesxJNAKXBUU/iNobfEIbe8KaMjLif",
	"m2rgNnZLDtNK3lTAeOb8I8/fRMonwe7uktBOdmHXqjGIonOWM+AS4uOjE2N5UfYUZ+pI1+fWGNg5UrLh",
	"oWwGOXzKWn4X0Os3WW+xI4o9Zs7EpY2J6VQWgmQhiHD9zsjAYKxH8QFM2JvmGmHN75WxUEyoOT3GAGFg",
	"0Evm8HPE/4qXZL9dweQSVnU8k1d1KJByGbpzpRdc4g7GeRgxLJTGnw9Mqkr31Fnlh2GxaUuL5LB7E+4y",
	"ejTxuJagY1IKKjvcMnUtTX3b3T3HCI69owx1imu9S/qrnugLO948sqCsYx/PRFrWue+2Z0MW9hsT3I73",
	"0UHn0v2QsitmIpBWWtjVOeYc/pgqcA36uLLL3gSl+1I8UQnA9NnD7kru1/NaU///HxeY9dMSyZEfbala",
	"Wlv2AlZ6cZrFVeLt29OnjUo4/QsSSC/iNvKaMPaKlz557rzQGukJip5aALgIXd5Naq1MlF78IrIWb16K",
	"F0A1/gbJT2axg7BGOQo5V3V0z1MKstDL5clRYoEX/xd+l6BFDhniPitA8a5WObsAXiSjpNK5Z7I5mk47",
	"b29tfKo9s7pK7e095cZd2JN38oKqtX5GwSUdpQsOTQfODd+f+Qtvzek73wAI73ybyTtMaHORgnTlHE/c",
	"ccnTJbAnk0db9FxfX084DU+UXkz9u2b68vTk2U/nz8ZPJo8mS1vk1JoRNkdwG3zqEn385jQZJVf1xm6/",
	"CIFydtJKjpJvJ48mj9H5crukrTblpZhePXbnYolYerwA23NeoO9qUFPvQ42iqe1MQyv6u+SGWqzb3sjF",
	"vi5JQoOR2jYipfDXpxx1UOGcjdAuijZ92k+j5x56vZ15xJmsR7eKFUWXvVjR6KdhhTum4B9FURWd7MBU",
	"uW3z4E7O0uQjfTzCzLqDxd62RYRb6Dqc0w4+HGCV/5aAj/cdlk3fwbmSPryaQsGNGISpDFV6mlhUg4tP",
	"4t9KEJIBT5ehZos6TN/Nt+CLCR0UM5jzKrfJ0ZxqTTXKM6Vy4DJZr9+TKybYtN2ePHpUm05w+Skvy9x3",
	"16f/8qXAdoFhBxToIBLZ5o1A/wUahe9ucc2mEri11g88Y2cu8XWLPr6HRd9KXtklRXKZW/Xbe1j1udIz",
	"kWVAncTvnvzPPSx5oRR7xeWqZrHBpb+/F2rPvQt9K5vSlQvw+MI0h1ZmzXGTUsV6+ieUQu244Nf1Km56",
	"p+vsiyo/qGx1BzvIEd4Wt9GurLf27uM7WznGreywee988z66j817ouQ8Fy6BPJiLrrn4OK6tAAYdQWy6",
	"HsVC1ulv6JHXzsDQkd0tU/OUng82NW56x9TsjGAHXC5uoggMvtsgwl8m6hqZXQHP/QQPuwKHP40Z+O4e",
	"lvxJWfZcVTI72IFtOxDNQ3+kPsCwffwj2C9yE99G1vIHSFEOVuZgZb7WaGOa0sUvutAcz25onHGmK0lN",
	"zq0vMDp4uJf9FbkRq7+wNWJKM39DyXVa6t5F6u+bRfIjGrlVe0cXkAnsHyd8OaROfyxrdq/ZGhu7LeqP",
	"f/jNQSd3aJce7Otw+1pb0N1mNleL3pYEhoK5Wpj6BlIsYmPPcSy14sq3eMyIGauBF8a9m4srP6s+9pI1",
	"E1093Z+p/P7RI5YLGWt4dOLMl2rxVYSajguOCb7WriqTr9iDXFwCu6xmkNrcjY/nD6OcvAQo6W3pzr4w",
	"VYLcx02ee6jUds+Vgf5OCR15vu3Y1cJHO4UrkHbsmNDdFRt9L7Wov1TIjT9fND4HadmzK3fKx/HxAZ2G",
	"cwj/L3LYaWXIr4fxpjhiU+ZcyOFo0HSGb3bXJZ7QmbKIBGLLH+LvQ/z9pfoHNP2bziH4JPqeLnXsSntP",
	"m7pNkQ996kOf+k761Hee9wRfnzgkP4em7+9m18HfAR7a9d0w0zvbvv5+8R32fesvmfwOjd9w6UPn99D5",
	"/XPajO1gsI74eiLBmzd/91qcoPvbWJybp/ORZb6KAmq/HTqkhofU8J7Nwd4O8N7NXJfmDjv5sJMPO/nr",
	"c+yf2Gf138VyjVYPsdNpbb8Q+Zm91tszLF9ht3W/iTnkK4d26+e0W/0eOfRbb8HU9nVcNyxupq5lrnjW",
	"W2R/6idsRmFcWzHnqW0rpxoWwli9iiRZHsYfIjhTqYV4L7EpUc+E5FQ1HtCBY2N2XLNylqsZq5ddj5Jv",
	"Hz3ZFghtTzZmZ5AJDan/2IhjvYPw9uxlMkqWwDPi7W/JS5U2l8P72bCmFf8rcpUVilJprlftmne0/MGF",
	"HELj27PX96FLp/XFeHdYgD3TWumv0V00jmCPw7jxGZ1Nox0eLfGwB5zSaWbe9JiO75V94jmdO/I4d3NQ",
	"p+HRoJM6Wxz9Ex7V8Tz43c7q7Fj/UMc51HG+XG9Bx3Xoky70CS4yp+6zF1P6r3I8xK0PT9Um2jAlez8w",
	"4Y1McHRo22BGIMUOAYWgPGHr9+t/BwAA//8XWl7uqIYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
