#!/usr/bin/env bash
set -eo pipefail

# create a bare git repo in /home/user/repos/$1.git
# $1 is the name of the repo

if [ -z "$1" ]; then
    echo "Usage: $0 <repo_name>"
    exit 1
fi

mkdir -p /home/user/repos
cd /home/user/repos
git init --bare "${1}.git"
