// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rc9w2suhfwc6eKkvJzOhhJzfRVmqvIj+iE79WkrVVN/JuMCRmBkckwADgyBMf7W+/1Q2ABIfkvCzL",
	"dsIvtoYkXo1Gv9H9vhfJNJOCCaN7R+97OpqylOKfx+MxiwyLnyaMGXhA45gbLgVNXiuZMWU4072jMU00",
	"6/dipiPFM3jfO+q9EoyMoR2Ripip+5EwrQmdTBSbUMPIDTdTErMZjxihIiY8pRNGIpkLo8lYKkLJyeWT",
	"Ya/fy4Lx3veom9hjbIqPqqO7F4QLYqZclzMpZzFRMs+I74mM5jhLN9xYqpSa3lGPC/Pto16/Z+YZsz/Z",
	"hKnebb835iLmYtIw+GumBjGfMG2I/whXumoyMDA3LMUu/0uxce+o99e9cnf23NbsXeaJYIqOeMLN/Bk0",
	"PTUshUm5aVKl6BwnCSO8pCmrzxI3laTM0JgaOhQ0ZX3C0szMEfItWzYsYaGN4mJSjALf1Ue5UDkjN1Pm",
	"lq7kDVEsU0zDgtzWayKkIfJG2G2gdtxgpJGUCaOid3vb7yn2W84Vi3tHvwSrC+fQr6FHsFlvi07l6H9Y",
	"ZGD6xxm/ZErjhBfnf/z61L0jMRtzwTRCZmafsZjYPSFy7BboF0ehA3hMBbFDDck5U9CQ6KnMk5hEUsyY",
	"MkSxSE4E/73oTRMjcZiEGsAiwDolaEJmNMlZH49KSudEMeiX5CLoAT/RQ/JCKka4GMsjMjUm00d7exNu",
	"htff6SGXgFRpLriZ70VSGMVHuZFK78VsxpI9zScDqqIpNywyuWJ7NOMDnKyARelhGv9VMS1zFTEN28RE",
	"nsJ+zA5okk3pAW4Hn0xNZBIYrXj+dhF5+r13A2g9mFEFGKihm3I/LssOy4dPfden8jLo+N1gIgc11Dyh",
	"hiZyspJ4sXc0zRI8JjRAh5Z19HvXXMS9o6L7fs8fJOhB4IHrsXjCBjTLNExEZyxC9OI6S+jcnsnek3jC",
	"yHGWJTxChNGI4wvEroKey+hCgMi3foqLCP0zBzqrCSUWSBZhSryFR4B6Z0/OL4jfZYvbFo2D81tiNGAj",
	"F2OmHIVTMsVemIgzyYXBH1HCmTBE56OUGzgqv+VMG0D2ITmhAojAiJE8i6lh8ZCcCnJCU5acUM0+Oj4D",
	"4ugBgEw3krhwe5dtwexgxAw9+LfMmKAZ//crhNkLZmiIBMt6cCh1Dp9CE0NNrtdtZD9epJMBBjm0CBbk",
	"ZtVEGF2vyFw24/5By5DeU0FoiezEsDQDEmfxhZLIthqSU0MyJWc8ZsAjxjRPDFDLMZ/kyja1ZI6YKTUk",
	"ogIQJ8q1kSkSQWQ4MF2HzJVBZchhvpij9iFIGezGFpgIzSw23j1aHSvDxzTaVLg8FoS6lkSxMVNMRGxI",
	"LqaMwGhkzFmCoAfwxhyaplxQAxIl8M5cW1Ij+G85K2UzVvSqScJ1A4KIRlHqVWbnTaZ5SsVAMRrTUYIj",
	"A60n0MoJVYAObgzknJ7t9P5x8uqfh+Qx19fkFKTgpv22D9beNA/cC2h22+/lijcIOB6Ob85OERIyN168",
	"Ib/lNOFjzpSFrX9cgJzsGDoBSdaKu7uI7XDWWEyoQZxOcnvqeMqqC/4tp3Mg3YrFU2r21JQlg5GUJhr8",
	"FsmbQ8AlLp4zMTHT3tFBDRoLuIhv7RLXRLkLB8wWcFgNoIo8Q/JiXcwhpyJKcqBfdk2o2QxGOU9ipojM",
	"TZb7MSoiFLAvygVTvX7Pw4GmHDQDLeFvQSMpYjqwP2dpfA3/TeHsKXrT6/cmEfNtBzHX14Oyy7ch/MOR",
	"1hDKWiB4EvTS8sk/3DJaXh/j6lpenuIq21o6WCz96NJCqO0tAq7l5RnCs+XlMwTzsiXDWS7B87aKhSfU",
	"sIlUc4uByOFAbyv5VK+BpWIL1Ck8qySgL4b4o+cauHW/0tXbTXfYj3Xue2t4dxwOsLA4z6pHScMRO6kw",
	"ciTVVUYOjAOoDtIQWCBJQI4jO7SQBvQuEnI5Y0rxOAZuX1It/HpIHG8a2MZOYBjnSQKKU5bQiGHn1fc7",
	"IIWmTE1YvFsn/1YGaWdWRuV1UahJbtlhYnZJle6TTCqj+2Qmkzxlul/IAbpPmImGuxWi+b7n2sGfz189",
	"+/fzJ5dPnqNdYiyBzmFvsJnf73+/fwT/4N7U6KFdyDnyjM2W89/nr14S29BqxCDFRMGGk4wqmjIDagHs",
	"kZkyrmDdPEYQBJJMOR9gmU2c9TEzlCcsJrGM8tSr1X2SIQuiowTUDpJSdR3LG+EIaoOsdLucJzxmWSLn",
	"0P/2cm7ZR0Xi9dgckbj8oHaEA6kU2SkaLobkuPoR1VpGHLSj8Hs8OlOqiZCFQYVrog1PEtgZzWOm4DAF",
	"M4Cug/mAxCmSeTgAmuYKIxDuJBwNeMJFzGc8zmlSjidIRDXTIHkrhkOhUY9rkmvAkIXlBmO7k58WWoBr",
	"CnArNQQp7l5qD0hki4lMqsq0nT2RkQdB0wfwCVLEPr5DYQ/NQVW9Q9qmbnW4avs73IWFDRiSMyfjWGto",
	"0F1lXo3aQVSaPhZscqCLu+ZuolGJx1UprbRhtI/g9cPWUVANdCvmOlxyJJViOpMiRjNAZWgx4eJd47BT",
	"KgRLWoa0L/uEjwkVuCcUQcuFYSK2R2fEiFE0unZwDSBQMNTaqHbWLL6QzQO7jfVm3eb1AtZSLvxiq3js",
	"Sf/PjdrkE26mTBFKHhcDPV2wk5aT9V014/XFApouTH1N+vmJlN5Zm6k21FCqaO1IrEMEv5HNy1yl4EaF",
	"xS/E/nJab9flNM+5vhNuA/1YgIPiAStv/EzfHd0sfBTV2T1fOfxazo1mttzg2+jsm5+BfRM23dqUNjMO",
	"WVRYfVgUcyrGZiclaIlABbEQtQ30KVbIglSeagzJa9z4yIo4wNaRWmBPLCbWFFs/RynTmk4a6GzBvN0X",
	"hL3LEmpF5pvp3OISr4wBctYNcg5JYkm40IbRuMoYL7AZzL3SdkjeaEaQaw6yJNdh4wYGgRqQF3lb7Fkh",
	"kwhaVAG4E2hRIEXuNrBxnNBKeusBuQItPoxyLqWXn4RKbkUbO4r4Z6SI2DEgZZK8GveOfvkAZ9T7RdvG",
	"OuqCKUjPiCVSTOxWnvOUJ1QBzUJrUoa2FUF+zkdMCWacl3gdpWIBZn5SdbC8XTziLxwokcZX/U/eVU2e",
	"vAMdQJMSEFbP9cvTkcy4mDSaKBa9IVsTIGhdCSaoerbqLKqBJnlj8xIDtjXOILqXvodKt+QxTiImUkTs",
	"b3XrvrYG/BkjjEbT0uPCRcwy0KWESeZDcjHP2BKXinekFNv/y3sP3NAEjc6JwimQKZkyM2W5Dv7ETd+U",
	"ThYeplt0KJza5gd14hkFFtk1+y6MuKgeWsPkJs1DM6nVMENxZ30huWgFnYTxBYvI8dMS/5SeyhthDTkW",
	"R2DjuJg0U8eKPe6NSpoYnbgGisDeueCVSpPGTqcyZVmjJAU0yL8lb86eN6rtJFMSA22a+uZRk84IXUlF",
	"kG68OTtt1BuhJY7nwcUFeXPaOIhzWquGmDD3BkbL8lHCNSjzTcPtwHZTMce4OUZT3J3dxuH0VCrzOByn",
	"Rg3ISHE2JlKwQcIFqPrF66bRm4fJs0wq077F7oOS0iJMw+1G+E2YQWFjypJseAf+Te/XdISriRjOKE8Q",
	"1f03zhx5wkXEhaCGk1TGLLGysxNxLb3MFE+pmhNgVn2ir3mmbVyBNtijMzS5NxiilbKYU1MOtkj2XBM0",
	"0Nteev3emGoD/K0ku87T4EjjUU9P6eE33x7Rhyz+/puIstH+4XjMvv0uiuPvx/F3jx7tf/vtd/uUff8w",
	"/vbhw2h08O2jw8N4f599R/9PdHj4/TffjB59Gz8KxH7dO+odDh89Gu73+j1cAEzpcPjo4XAf5lLYWODZ",
	"N8N9FBfC2a+e9Mz1Xxv0IQ5aGQG/24K2B9J2lZo3O4dLrhngzAqBq9lLjCxPjqsH1/E8EHQ9Lwk9c9LG",
	"Iar0hiqYTaz4DDlfyAWnLEl7fWCDccIMvkwzqfF7EBM39uTBTF+d92prelpOZOHNYz+vhectnl549ZOd",
	"9cLTfxSLqPXk17Q4NC6xugGB7rWe0NvOYGsSb4HQNRele2OFJi8YBSJvqLDVNYdlYsadMPnqsWsWQ98v",
	"j5+oic80Q7eUF/IwjsZIF5JdCfMYkp/ZXFuRL6UGREP7ORfotRkWB21IXolkTq7ZnMVBhARVjNCCNBfC",
	"qTfDVD2eH4MS+tgKS6YsgQNwhfA7WCQM1RDTlGa/tHj/39bMLHp99D1HlG/Qb0AEAt5VMjOno4uScfVL",
	"lyxwds/C8myiaMyQlQ2Ro1/z7IwKK2ltMi/bqD65c5bOmCIKXgMaFey28Ov7OcRcscgkcxvibOdvuS/g",
	"we8DbRQIPdYmgILEVJoxf7eoQ17l+/sP2Q8Hw/3hPsEf0cHwod1Jx9Fq0kBxTraa35rMH1jjAL2pzWJA",
	"D6fc6/cOhgeW267F9jxe1CnKbFMK2Ypi5yylwvCoQDAOOh4GgJEdNpwM++RgeDh82CeHsIaBig52F1yU",
	"hQNGxQyNTVTEBWwnimbT6jb647fAsWeFoaQg0hWqt4Y94Dh0Bi3YfMcySeSNPyaLwqBzYvvtuxJAr4SM",
	"rZ87wBVcD67QzxJJW0JH8CceUKld0+GVeBMcQ/tl7BTw0byUPXfsId/1MudOmieGZ/hEqitRnF2yo4NT",
	"txuEnLWwwDDW5kq42JlKEIxXYodXYokJZHv7a6vt9d7trhvbXDt765/N3rq9lc9Z+ODNqNHGF1KkYYGS",
	"SBIKccdqoYmMaJLMBykVdMLiFb6KezL+bGdLuTczyqeyoHxK48mSALfz4gbJFpiMbcOANlxvrhTSGfu2",
	"wl/tIhpDJ+3gTepW0B9b3M2yw7XI9SJ5OPHjrrQSBDNspAozdoIXU3+cn7MZU9zMN4Wpvdcqx3AEDBeR",
	"ISeXT4qgMqkmVPDf7ZaP5mTKJ1OmDdFutAaYKm54RJOmGNvchhmWI7lvccg1r7jCDNbp+yc+mW7SbyJv",
	"1un2ubzZpFcQwPN0nY5f4Jeb9C2kYGtBGfYTXUpCordfcqsw8DQDrXrn5PL8nOgIWO3+7pqDG2ma9vgC",
	"Hi8MTSMlta6h05oD5eJayBux2UJdI6BaucCVxRWUXTnuorEOV9svkdvhYbHBFn/cnpSTbjqzNlTu7o+t",
	"D3stbo83HOG+vdRtpftZeGN7qxP9Mk9HltX5wW9QuVikEv7KOUigvrcPOu7bDAzvPoQWbDNmIm8+kFBs",
	"M6rt64OoyDbDQk8fRj2CURexGo81NSRhFHQmwRbQt5iHuHNCsw0sXGefB62ppGY4z9OUqvkZRjhrtiHd",
	"8eSKaNuNiwxwNkB3ReDu1Oa00fGKdxGDC3+od/oIfRsPR45HIBr6LA9FOLG7kqCYsPcPXp1bY3KzSgFv",
	"HqN5uW0SPqXGR5pBszJ/5vVzeP03QpMbOtekfa9bdAB8t1FaD7/7rt+1tFs/ThN6Yqx404zXtxsun19/",
	"BXJX0dTGidgNb8rf4mkSD7ZeEznSTM1KfluEq2968KvDr2FNtNlSqnQQqQeI71GSIzFywS8OUTGNzXAp",
	"7D8KZbiXu+3N56J1oR9yLNox90PPhDOE1xa3jR28YtXGt7AD1BimoMt/7ez/7y8Hg+/fXl3FX+1eXQ2X",
	"/t75+9FgZ+fvR8Gz/4V/fqGD348H/2/w9pf9wff+b/wcelj7+92vdnf/jo2+3gnffG07qjzCb/+r8Y5w",
	"U76V0E3UBNfSSxRJoY2iXBgP0waXDsJ3d0jOMxqxgWYZVfb6G1Op7tu4NBRXpA9ZBpTHi/47rjvXb+T/",
	"YP5Bn/zQJ//pk3/tOn+ATz/U5IfstU2uusu/uM/sB//519uvAJhvv3ZQffv1TvHX7t93BiWkhwN8cnX1",
	"de0Z+Qid7n61wZZuYz9yhiM0gytmcuWuviKpimiSONdbLMUD47+QeMPJns879AhEMm5CxnwCZJrF5KeL",
	"i9d+CvBt6ZG28kWf7BM+xuuPus5uHh42iridb+BOfQMtNyyOayk36tbZ0kpp4YgEoi0EUTGqm83AKY2m",
	"XLDWoYoLHcUA9tYhzuGq95TyJFfsqlcIraduQhYFuHbJ1ww6H1HHq1xdKQImhuSYnOE0SZRQBWwJM+sg",
	"GrvFIhqPcjhfPr1a6e5rZsbFKW88yA6WJfDIK8GIHB+Rq955HkVM66sekSpc6UdHG52xaEBFPChv5mx+",
	"oc8t3JGJAgP6S2+jVMSRTZPXFGEcFWly5+Tyya7Xa4ckHIE7d/EkkSNrwcWccSrWJFMyzqMyf6H3M7F4",
	"0eYUUSGY+ht8NSfWo22IYYIKM7C594JA+Qt4Hs3tBSNgtt5N3XBdFF1W7B1QGSXzyZTcTHk0Lcf5LWeK",
	"2+uWC/Q8nnEt1fy0gVBeMhGDUOs+CSUwm9ypOA1NyLw6P2SrJW/kTvHJ5ZMheVrcxQ8Wae9sOYn34G/I",
	"LaqA4MbnHhI1e0aouRCVC2GDJJyi427d2/Ft16F5ZXADJ7g+DKoaofH3ZiqTrSwzW/PYGWvaRkDVReEZ",
	"ljY43D98NDg4fPio2S8XzbQ+j6RqMrpfnp+TEdXMmdHr6FAsc5xIasru7WbUQt9qFG8qlSlUK0f4Koep",
	"3YKx2oCyY+/UKfLm7PluyaqrWLaNiSTNvadh0Viybv9a503a0MswoUFxHvFjt6FnIERR0ycvLx/v2g0p",
	"THJr2lnuVjA6tofzcuWmJVxcN3uyXQZOQOAYk5BoktEJG5LXIFFhhk63bHLOohzV8UwqQxM8tf6dAxhn",
	"um/F2xuuMa7y5eXjZt+382rHx6Ypgs2B332FabUWAF5gPwhyA/igkd0HvpCF7Yb2ic1G6u0MGNEUBjOf",
	"lAbTn6zB9IU3mD5Hg+lLazB9UzOYBlPAPdzMKGabrHVPHwlSsNCVbBwT6W7MywFBvKPHEWAp8ICnKPzA",
	"adR9QrXTMCyLQfI/0JHM3J3fOpWvsm+Ml/LyvB6SJ6D5eiN44J6HsS0F4KJkxDjLG2qZObA5G+C1YVLl",
	"BYfjMtbpg+FxhV8W69ksr3OhKgaLBoCD0DMvl3/HaZ3vkIY2E8tnPh91XRWj707amfNPzk+zyKTdyaBJ",
	"UoBuPU6d0nevl1HE5zZDMm0kjKtG3ZJC/lOq0BXVMEqRd7zI6313hHMb2rciAXYL4m2p1sBJ8JTJGaZ9",
	"CqxQNukHhnOAHfeCkrMM+bunyIgxEyPePfictIiXTdI9nvlCsrcJgIqpr0EGv0DRd8yVNueMiaYT+s8i",
	"+btnQvj5gi+nGUpLD+gW8nC7XH3Gxnql8B44oAq67xjCGqS/5bpjSdXvSQDvZN4Gx4Sj5d5IiDSsusWf",
	"r/gbHoQK0S8xez2qv0Vg/2s64QJdMj6iv95tENq6UxF8m6wbux/9JkA55aVTLbY/cxEDW8pwn05+e85b",
	"KN7nE2pfmfSpQ9cNUfCssK0YSaggr84BsW6kuk4k9TVlRi7QHXStVkli3aoyFebO3tGFOIWQGWTURjaj",
	"ULBTJPgcJVQbomjMcyyKsm4o6DZGpuHHY55NhKhX7XyNXc82TwD/Ywi/SvQDUG4nkSO0bRLaspKNk9Tu",
	"0Lu4lvpZUJPqzrv4j09pj2ujkkwNGgoVKXmjl5ZtWptSVotLrU0kmwNPGjDqC5F9ttOnK2aHikuhuazU",
	"hyva64nxa85iqZj24dxpA+V9U0Deqx4fsNAGlX5Nrnr3Qh2pFH/6FLLa3Yppn+pqZ5Pg9qXJbIthoJsh",
	"mrUoVy3drvrfaL54SBkm7wew5glG4thk/XjVPryVBoiwu9VlqeKO1GKYeem2rc7gbu5R4fWpOx5y+RWr",
	"5/LmrgdcefvKXbq642FXXMyq1F+8tztZs8XYjdJC7JbPC8q17cJX39Wqrv1zvqbVZORoTu9doRQjGl0z",
	"rDBBTRkIgyB1UTQBwzYq14aP5za70nzNTEoXZat/YKvabD8okPsJ3nht8vd5G2wpVN+ZtrJwE25p7oOG",
	"O68fIpm3R4Ov59UI59GESO2Xf7fOmVp08SPVTUmk1slZ19qnzWDXlK1sjSsJRS8+Z4AuNBeMGxKMUJ2B",
	"0OFvVNevWXNNjl+fEr91w6VARAjUth2ekuLuNAhGOQbsBUlWyjywOFoYxWcz6+CFM9geNOHEcegzwsxS",
	"cDDrhwBU6QtFhbbA5G21DlDlRrOxC5FzczVFWxbbUBkAmguhRGMSqnCbqC7rxqn6jOAuS4QXHIu5hd4x",
	"v6uYlFBOFNN6SE6k0HkaVJMFWSijSjt5E3O9NEqSXmN7xoQL5myG2rCoDTwpvizrlpRQBF0QpDFQT2OS",
	"Z2vHmrXH2mLKhX495Na2KJN/+jk80G6Piw21iEV9vqYilDm0yVARkyw39RBiC24u/C6tCJjd6ui3lOos",
	"olEbcHvN2NRVQ64I8Q1QEANZxuRC5axPniIDI2/K25aetcL7Xr+HHyxTeZtzFVZn5/paeOq7XnhcjLRs",
	"1SsyOBZozMOA92B1x1mm5IwBB7p4/eKSYcB1jBWJixePmbDPnmK1qvqnGCDNbcLPyg9PeV/DyYVPz+ci",
	"wj/OGI1B7rikCcffQE5zcypeOxoAoM5iaixozzMW+U9fuIxRr24EU/Ddc8xIVXRt7diPWSTTlGvgsrYP",
	"NMU9ZomhrxXLqNs0//XC4ydCySRJmTA/SXmt19zustWZvYAQQLH2rgrEEyD8YyzLcM4nMOV6F63fFDvU",
	"+kWxda1fVKdzxjKpuZFq3rihAOzWF7VdD18W24S7Br9e0CzDaViMsBfi3F7jjybcsNsWYIh9EOKJfVLD",
	"Fvv4Y+CMfVzDnIbjW5gtGhN5Yeb2MsGSZ1SWO+m5MFNmeBRYiTBX5ZTOWMhXE66de2BGFZe5Lq6KuBtI",
	"5Lg04qR0jh1Ye4OjjO/LRPJ94id225j8xnCRN9ChF3SOJQ+ZIdzS31wzhb8pSXjKjS8cVoaS21JkPpzQ",
	"loMvC5YUHBq5vMJL0BiKiBAKbpGgQuXvnsiM/pazorL8COeBtbLQs+BFIX9tyJvLgxtGAHlrCUb5Ay2H",
	"RsI0FWczK3oJ9s5abuQ4SABagPvEgsnVi5NCc21AYMW+YFruklIm7anyIHMrrebYgnVHUyom1tGMIDBT",
	"inXk2A1JucgBXLinGdWaxRYkfsd92X9bS7gI3kRvik0ibTPqu611oLzhSQJTtGJGRBMPKQdpZ+tA07n3",
	"/vRJLtDKPJe5nY9iEeMFKI28ZsJVxxOEKQXLWSKZKJbaIjM2AWDeVOLlooJROh9p2FhhqnXuEPA2itTf",
	"GLHHJwjbwW8KR5a91cT8U4ssPqdZbAOJ0bSOUNUsYZGRSmPpvEU8L9bhJ1XkevCFJV03HugJGxuSC+3q",
	"FcqUG8NiEudoq9VMcZr46xCVieI+plnCDCM7zBZaG7GI5iAwGnsZy5Bomotr6EmWb/11EOPVDPxot1yP",
	"Yg50FgMX12QX4uX17VbirwFKrC2MOD47GB58Q2LpLy2GOgFieVENDxZRVPhZxBtY2VdMG54iE/nKnjb+",
	"O3M5v2QC+4eTOMHrhRVtRDGklG192zp82rpa7A/0pa9rjVop+AblTuoljsoKIHyRgdAkIRmcfrwd2shE",
	"7JngPuEmtHBUDOm3+zZSjJqmHB1CSJvabWn+5hUZm8uPrfo1L2ihSwxSr/oK83HahDY0zZrpQqEpO58F",
	"KHh2KfH6qnDMErbNWO4AYPNNxpss0WaPiaVuUUFdKh6bwNgQaLpFbUSNyW3RaDIkr2WWJ9SUl+FsweUh",
	"AeEM0/6ua6BH8Wpp+m76zqfv/vbhuvm7nV/qms29ZIP1hsPyyp6xu9Ary/Rdxnr4uWODVeCppc+74ZXs",
	"GlKJtUpM2u+hg2BZh980rUveiKawh+PQoUYNkTfC5Wf3z0G2I1doLtyDsa967QWByxKZl231JI+Fl4oc",
	"UG0BSW8/0IHo8cDlgA5SSyOFFMG610jYuEjAXlMTTZ3yAfMrXJsbJFqRLQevvKVsJFA7gFSo9tIYS8rb",
	"rMT4VypnePKqUT1BFCc106Ztw4rRGEXBFIGPmst6AqK2WP1RdHKWQal8quRhzXgis56bRpNdpJb8Ubs4",
	"DqxmbaE1YlQxdZzbldhfT/1h/u9/XvT6PbTsQEf2bbmWqTEY7CfVpCkgCFby5s3p4+JEhOkeQ4xmQWzf",
	"C5o5S2Tl+5JjDQHR0e0tsHwSU6Ah2jMJM/k3Knp+6Rn/mcHab/u2YrhPr2/jr4BFJ72jnmE0/b/jhE+m",
	"JjLJkMuyR1jEU3yDwrqSCblgNMX6TYmDgT7a26u0rtGqX6pdvN1parbrHO2Wn9nMsSxKKGDtDPQxQSfM",
	"V9N2oV5yjMm1y6tJRf1xHw6oh1fiSlx4w7c/rDuzA5pkU3qwWxrT8cFAGxta54UAKyEoBjIzciwjnZph",
	"71QlPGLOEeRgdpzRaMrIIeYKqYLp5uZmSPH1UKrJnmur956fnjx5ef5kcDjcH05NmiD6coOJSBbAf/z6",
	"tFJOxS8EMdHSkd5R7+Fwf3jgDgci+p5Lr1qQlAkzLUmzw5TDoSszzKRdUBPAfGx2nCRhQxzb14VHJ0wD",
	"sXUpXIoPAbY2mt7JzjpPTJDfwhLfUJN1Z6vsIShSYRa/euB1twdO+vYxm4rN0BxQVW1aDlmh2zvSQBtE",
	"t9t+k0hidR+rJMOXkSk1ElR/nMrpJUsrcXDlEsxj/TZM145ltmZMzc3UeT2bJoqtzt2o9zhbm3W+7xMd",
	"owLlkvQAiK8ZefDDgz558AP8Cyf2wV9+eFDkBOpds/nBD7hvB/1rNj/8i/1xeNXbbVspjrjdSgGVUvqO",
	"p3la0UQt5hWLDPXjUve9KG0RKMdaxasd0SrNCR9X0Zy949rYTheMDCmdW/1yxLzoymJCdYD3XADtLNV6",
	"hFArZvCUmwqcagluHEx6Rwf7+/tYK8X+3G9QzbAulF0UkpbD/X3PaVy52aCQ/d7/OB9QOfiaNXEwsA15",
	"2YJq9zPQvkd3OGjhq6mN9SONiRfQcNCDexj0jaC5maKwHttRH97DqE+lGvE4ZhhG8Ojw+3sY8kJK8oKK",
	"uQexhqG/uZfVnjux440o7JRWZqcTXSlMetvvvRt48QDYQchXb/sFo12PyVZDK+tc1fPcT8BOO27acdOO",
	"m/4huWnHSTtO+llw0kw2XUc7QdszoTUmWeeR9lNfsslah5g2P8p4fteHxq61ND8ZlbPb2lk9+DjDNgEo",
	"7tn7TThyBRA+m0MVVlHtk6pQEZSEh4k5sjyS8fyve978hHZW3M7HaLA/KYvIVweLK68XB3KUc/Uoz5hp",
	"HWJSvruD/stgqbZRzn2o1pZjBfLcqbfCVMdKFr/4kA06s1bTVvCp6vutl1Udpw2MqumrLce87ZjUx2ZS",
	"+/fBpE6kGCfcGus7trhCwawql3vv3V+3e5tadG1ciX+2VO1cy5K76PlrYtplWm0WT9iAZpn2wjS6b0p1",
	"sMLJS0a7mb71AcrwZ6em3r06+iFKWmdQ7DjMHXGYR/cw5EtpyFOZi7hjMVtpXnBKrDGklV2crNAqPj9+",
	"8fajqok2hWMDXpRLRaiWwS0yiBu7d/WybboNKmZF42tWMePaJ0s1GNyEIYaIlBu5he7WPJlJ9f1HnElV",
	"BWqejap/89Fm1ClIf0T2de862ReiGO3VfW+L6tHeezgZt5bhAYlqyvWF0eBV1rdKV3q8gt59AcpSy4wq",
	"PGrYPD7+tzHn/UhyfTuCdeL8H5Iefn7UqdEA8wxvdm1CVJ4tk1s6inJvFGWFhNyRlY6s3I+qTk00bUqV",
	"ZqLpRqo6tvjDkxa83wArvVMas669YIBDf70Zniy9B7KW27mjeh3V65TLD6SzuWlKcoVmm43o7NkqU08n",
	"xH3mBtnixtlnR3k/gQm4o/cdve+MiTVj4l7MskTOU5hZa/jFMxfDHBy1x2Uzl8k+o8rwKE+oKgi/YxrL",
	"DANBPx17ubf4kC/x7mEXlf/FhKSUh7oLTunMTp8hewyZXpVJbuxhWxLW/3hJ9PjG3A0ou51T58fqTn4n",
	"ineBcJs57ZbQqWdtV1C2IlITWwzgC/GLdSSqi5z9U0bOruWOW0I0QjfcXZCNztnVkbKOlHXS1hdBPJt8",
	"bJizfD3F8GzZpdWtqGeOg38ZrqzPjjze8333jiB3BLkjyPd+1di6u8r6N60qsy4Ky2ymPDemA9jKi9Xp",
	"zh1963TnL1N33ox6hFr0Z0g/OhW6o2gdRftzK7SbEbSz1RmSvgyS9uWrtR3J6pTMTsm8DyVzoXL68jRW",
	"MdeGi8i01VuvVdmwdYbHYxZhMS0sEhFU2K7nvbpcmE5XxOBPmsj4KYLWSKKlMgul2j2AcVtHrQGI0PLH",
	"eWXY2Gachpe+qnlZgCd4FM20Po+kgu3J8lHC9ZTFx8bWRD+NG6rx1FdwDhOXKmaqKJ/s5txePSZmqmW+",
	"0HdYLAh/4cN15tIFoH7eAaiVmv3PlMyz9ujT4ScRkIafRkIafgIRafgJxYehlR8O7kk+O02zBEs6sZjs",
	"VInsmFGTK+ZLcTIBAkZsq0ty7QjC7vCTyjvDisBTmX9d7FmUdBqkn71oxvTee6Txt3s8zVydrkaJ6Ayp",
	"JsmYGmAxLGSZ+BeWlh1hcVJFY577ayYnl0+CaviN9vgKITi1E1hDBa32THZgPHefpA8vB4f7h48GB4cP",
	"H+0OfUH5oIEm2gBlt4yAHO7vO8lNEJZmnuOCGu1FubI810640F1brVdIKzyBiIFVPjmAIBdxizpsmWp3",
	"pWSD9Z452c8h2sAhmpI3KPE5URsrO5IRG8Py6WSi2MSXsLVCIIvJNZvD/vyK3/5KdipN7QT6JEAo9+UP",
	"WId8L51b7P91d0heFdKkq9NKfv3h1z759Qf89y/wr61xaQbazKEnLn4le+RXIQ38dWOL91ragcf7I4uV",
	"lTPqQLeVNOnPhS23rkNBrfYGwfUSOu2kyE6K/GhSpGMenQjZiZCfvQh5t0Kcq0UaXIhqt2jVDFlIrl2N",
	"ai4miS9tGjDVona5rwRbk+Issd/QloXUNSwy68UM21t3K7czpnXGtE4M6sSgjcSgzo72iYWg+/U1doLX",
	"ZyN47ek8TamarzKgWSnCcgvi2jiDWVUCu+FmKnNDxsyZlqDlOE8SNH8BoVxTGJufu5l99hLZH1VC+Zjk",
	"v32/z9yQHT/o+EHHDz4+P0BL55Z6uLNVs9ixAutiGc3dH6t1cDRP35UKjp11GningXcaeKeBdxp4F87S",
	"iV2d2PVFiF13p4VbwWtLJbwmjX2wDn5fIlmngm9+Ylp3u9PAO1bQsYL7YwVrEv/wzsbghsc2oNDe0wBq",
	"5hnD6pDFkqrfj3DZ0ZUu3OXPdMZv+z3bj5WVcpX0jnp7NON7s4Me8HTX8eJBf+VPrYb5LN5SRRV+Ibt8",
	"XRQK+gDBsLp4xUDC0SjF1MmJpUO8MlB16bdvb/9/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
