Cypress.Commands.add('login', (url, auth, user, password) => {
    cy.visit(url)
    cy.wait(7000)
    cy.origin(auth, { args: { username: user, password: password } }, ({ username, password }) => {
        cy.contains('kube:admin').click()
        cy.get('#inputUsername').should('exist')
        cy.get('#inputUsername').should('be.visible')
        cy.get('#inputPassword').should('exist')
        cy.get('#inputPassword').should('be.visible')
        cy.get('#inputUsername').type(username)
        cy.get('#inputPassword').type(password)
        cy.get('#inputUsername').should('have.value', username)
        cy.get('#inputPassword').should('have.value', password)
        cy.contains('button', 'Log in').click()
      })
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button', { timeout: 60000 })
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').should('be.visible')
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').click()
    cy.url().should('include', `${Cypress.env('host')}`)
})
Cypress.Commands.add('deviceApproval', () => {
    cy.get('#nav-toggle').should('exist')
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Devices').click()
    cy.get('[data-label="Approve"]').should('exist')
    cy.get('[data-label="Approve"]').should('be.visible')
    cy.get('[data-label="Approve"]').click()
    cy.get('#rich-validation-field-deviceAlias').should('be.visible')
    cy.get('#rich-validation-field-deviceAlias').type('test-device')
    cy.get('#rich-validation-field-deviceAlias').should('have.value', 'test-device')
    cy.get('.pf-v5-c-form__actions > .pf-m-primary').should('be.visible')
    cy.get('.pf-v5-c-form__actions > .pf-m-primary').click()
})
Cypress.Commands.add('decommissionDevice', () => {
    cy.get('#nav-toggle').should('exist')
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Devices').click()
    cy.get('.pf-v5-c-table__tbody > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').should('be.visible')
    cy.get('.pf-v5-c-table__tbody > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').click()
    cy.get('#devices-toolbar > :nth-child(1) > .pf-v5-c-toolbar__content-section > :nth-child(3) > .pf-v5-c-button').should('be.visible')
    cy.get('#devices-toolbar > :nth-child(1) > .pf-v5-c-toolbar__content-section > :nth-child(3) > .pf-v5-c-button').click()
    cy.get('.pf-m-danger').should('be.visible')
    cy.get('.pf-m-danger').click()
})
Cypress.Commands.add('createFleet', () => {
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Fleets').click()
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').should('exist')
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').should('be.visible')
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').click()
    cy.get('#rich-validation-field-name').should('be.visible')
    cy.get('#rich-validation-field-name').type('test-fleet')
    cy.get('#rich-validation-field-name').should('have.value', 'test-fleet')
    cy.get('.pf-v5-l-stack__item > .pf-v5-c-label-group > .pf-v5-c-label-group__main > .pf-v5-c-label-group__list').click()
})