FROM registry.access.redhat.com/ubi9/go-toolset:1.24.6-1762373805

USER 0

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf install -y make packit golang openssl-devel go-rpm-macros selinux-policy selinux-policy-devel && \
    dnf clean all && \
    rm -rf /var/cache/dnf && \
    mkdir /work

WORKDIR /work
