# Container flavor configuration
# Format: FLAVOR_NAME=BUILD_IMAGE,RUNTIME_IMAGE,MINIMAL_IMAGE,PAM_BASE_URL,PAM_PACKAGE_VERSION

el9="registry.access.redhat.com/ubi9/go-toolset:1.24.6-1762373805,quay.io/flightctl/flightctl-base:el9-9.7-1762965531,registry.redhat.io/ubi9-micro:9.7-1762965531,https://mirror.stream.centos.org/9-stream,1.5.1-24.el9"

el10="registry.access.redhat.com/ubi10/go-toolset:10.1-1770279878,quay.io/flightctl/flightctl-base:el10-10.1-1769518576,registry.redhat.io/ubi10-micro:10.1-1769518576,https://mirror.stream.centos.org/10-stream,1.6.1-8.el10"