FROM quay.io/packit/packit:latest

USER 0

RUN dnf install -y \
      golang \
      openssl-devel \
      go-rpm-macros \
      selinux-policy \
      pam-devel \
      selinux-policy-devel

RUN dnf clean all

RUN install -d -m 0777 /root/go/pkg/mod && \
    install -d -m 0777 /root/.cache/go-build && \
    chmod -R 0777 /root/go /root/.cache/go-build && \
    rm -rf /var/cache/dnf && mkdir /work

RUN mkdir -p /root/.config

RUN git config --global --add safe.directory /work

WORKDIR /work
