#!/usr/bin/env bash
# get-flavor-vars.sh - Extract flavor variables for agent builds
# This script replaces the need for .conf files by using the centralized flavor system

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Build flavorctl if needed
FLAVORCTL="${ROOT_DIR}/bin/flavorctl"
if [ ! -x "${FLAVORCTL}" ]; then
    echo "Building flavorctl..." >&2
    mkdir -p "${ROOT_DIR}/bin"
    cd "${ROOT_DIR}"
    go build -o "${FLAVORCTL}" ./cmd/flavorctl
fi

# Default values
FLAVOR_NAME="${1:-}"
OVERRIDE_FILE="${2:-}"

if [ -z "${FLAVOR_NAME}" ]; then
    echo "Usage: $0 FLAVOR_NAME [OVERRIDE_FILE]" >&2
    echo "  FLAVOR_NAME: The flavor to extract variables for (e.g., community-el9)" >&2
    echo "  OVERRIDE_FILE: Optional override file path" >&2
    exit 1
fi

# Validate flavor exists
OVERRIDE_FLAG=""
if [ -n "${OVERRIDE_FILE}" ]; then
    OVERRIDE_FLAG="--override ${OVERRIDE_FILE}"
fi

if ! ${FLAVORCTL} ${OVERRIDE_FLAG} get "${FLAVOR_NAME}" -o name >/dev/null 2>&1; then
    echo "ERROR: Flavor '${FLAVOR_NAME}' not found" >&2
    echo "Available flavors:" >&2
    ${FLAVORCTL} ${OVERRIDE_FLAG} list >&2
    exit 1
fi

# Extract variables using flavorctl and output as shell variables
echo "# Flavor variables for ${FLAVOR_NAME}"
echo "# Generated by get-flavor-vars.sh"

# Get agent configuration
AGENT_CONFIG=$(${FLAVORCTL} ${OVERRIDE_FLAG} get "${FLAVOR_NAME}" -o yaml | yq eval '.agentImages' -)

# Extract required variables
OS_ID=$(echo "${AGENT_CONFIG}" | yq eval '.osId // ""' -)
DEVICE_BASE_IMAGE=$(echo "${AGENT_CONFIG}" | yq eval '.deviceBaseImage // ""' -)
ENABLE_CRB=$(echo "${AGENT_CONFIG}" | yq eval '.enableCrb // false' -)
EPEL_NEXT=$(echo "${AGENT_CONFIG}" | yq eval '.epelNext // false' -)

# Convert boolean values to 0/1 for shell scripts
if [ "${ENABLE_CRB}" = "true" ]; then
    ENABLE_CRB_NUM=1
else
    ENABLE_CRB_NUM=0
fi

if [ "${EPEL_NEXT}" = "true" ]; then
    EPEL_NEXT_NUM=1
else
    EPEL_NEXT_NUM=0
fi

# Validate required variables
if [ -z "${OS_ID}" ]; then
    echo "ERROR: osId not found in flavor ${FLAVOR_NAME}" >&2
    exit 1
fi

if [ -z "${DEVICE_BASE_IMAGE}" ]; then
    echo "ERROR: deviceBaseImage not found in flavor ${FLAVOR_NAME}" >&2
    exit 1
fi

# Output shell variables
cat <<EOF
OS_ID="${OS_ID}"
DEVICE_BASE_IMAGE="${DEVICE_BASE_IMAGE}"
ENABLE_CRB=${ENABLE_CRB_NUM}
EPEL_NEXT=${EPEL_NEXT_NUM}
EOF