# Updated base image
FROM scratch

# Copy the application configuration
COPY --from=common test-podman-compose-sleep-work-v2.yaml /podman-compose.yaml

# Labels updated for version v2
LABEL app="sleep" \
      appType="compose" \
      version="v2" \
      description="Sleep demo upgraded" \
      maintainer-name="John Doe" \
      maintainer-email="john@doe.com" \
      change-log="Version v2: Upgraded base image and added utilities."

