# Updated base image
FROM scratch

# Copy the application configuration
COPY --from=common test-podman-compose-sleep-work-v3.yaml /podman-compose.yaml

# Labels updated for version v3
LABEL app="sleep" \
      appType="compose" \
      version="v3" \
      description="Sleep demo upgraded with volumes" \
      maintainer-name="John Doe" \
      maintainer-email="john@doe.com" \
      change-log="Version v3: Add volume specification"

