# Build the installer binary
FROM registry.access.redhat.com/ubi8/ubi:latest as builder
WORKDIR /build
COPY ./podman/installer .
RUN dnf -y install go-toolset
RUN go build flightctl-installer.go

# Build the bootc image
FROM quay.io/centos-bootc/centos-bootc:stream9

# Copy the installer binary
COPY --from=builder /build/flightctl-installer /usr/bin/

# Copy quadlet files
COPY ./podman /etc/flightctl/
