# Build arguments for community-el10 flavor
# These args are used across all containerfiles for build and runtime base images

# Build-time base images
BUILD_BASE_IMAGE=registry.access.redhat.com/ubi10/go-toolset:10.1-1770279878
MINIMAL_BASE_IMAGE=registry.access.redhat.com/ubi10/ubi-minimal:10.1-1769677092

RUNTIME_BASE_IMAGE=quay.io/flightctl/flightctl-base:el10-10.1-1769518576