// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNrIw+irYOV+V7T2jke3sbu2qKrWfIjmJNralK8lJfSfydSASM4MVB5wFQMmT",
	"lKvuO9w3vE9yC90ACZIAyZElOXZ4TtXGGuK30Wj0f/82SfLVOhdMaDXZ+22ikiVbUfjn/qXKs0KzE6qX",
	"5u+UqUTytea5mOxNTtlaMmW6ESoItW3JnGeMrKlezibTyVrmayY1ZzDeOjjO+ZJVvU0TonNCcZxcEL1k",
	"RG2UZqsZeZ1rRvSSakLFhrD3XGkuFtj0hmcZuWQkv2byRnKtmTArYO/pap2xyd5k95rK3Sxf7NL1epbl",
	"i8l0ojdr80VpycVi8uFD+Ut++W+W6MmH6WR/vT6H30LLNq1JPoc10vU64wk1X2FeUawmez8jcBWbvG3O",
	"Np283zGNdq6pFHRlIPSzm+3AdcIFuHEPcqGZ0GYtNMuO55O9n3+b/C/J5pO9yX/tVse4a89w91ueMdfp",
	"w7S77SnLqObXeNimsWT/KbhkqVkXnNzbFnga63shrn+kEo+6dvCs+kDTlJu2NDupNWkcxbQB7Rfimstc",
	"rJjQ5JpKTi8zRq7YZueaZoVBGy7VlHBh1sVSkhZmGCILofmKzYg5rCu2IVSkBHswmizJqlDa4Mwl0zeM",
	"CfIMGjz/61ckWVJJE82kmk1a247giQPDicyvecrk2Zolw88qAEdzCnVA0gobe8aCZh+mE4NakTtXTUhM",
	"qxIaz/6//+f/rcOAZLlYTInSVGpyw/WSUJIxrZkkuSSiWF0yOQXYJbnQlAsicnKz5JqpNU3YbNBV+22S",
	"CzYAUEcrumAxcPdh+ZHIuIj3fvvhbffZnmmqCxWmCPjN0ANKFBeLrA5jS8tSds0RJI5EnEi2ppYmnBkQ",
	"4z9PCyHwXy+kzOVkOnkjrkR+IybTiSEQGdMsHU5X6jvw52x99BbR+latqvXJLbP1oVp365O3kTqgf8yz",
	"AjG3uj51cB+yORdMEQrYm5Jr6EEKxVJyuYE3qU6S61cpfDHeCP6fguF9sITdH9fgPhchet/Gb59+wmRv",
	"PxLnESQthA3BrUmC6lvHHan27l9ypQF/PbS1jc0euWYrNYD2NM6wuutUSrrppZ/YDfGj+5bdyZG/bp11",
	"4DzNcc6ZZCJhIU7IfjKcC97xdZZvWEqOD452DIwyToUm3JyioZjmes1posklTa7MQ9U5dwiX/PX0kCx1",
	"VqxWVG4Gkq4s84Go4mTre0YzvdxMppNDtpA0ZWmAVG1NnuqrreaINvEmj7YJUKZ6g3K5BnSFXh7kYs4X",
	"7ZuTsjktMu2uVzcy2caEFnrJhHYXam07B7Eslwsq+K+4xBfCsDlpe5aflkwv4fH1WhMqGWHYhcwNltXm",
	"9aa7zPOMUWHmc4vpIgYGI64pz4DnimxmC/pQ6KWD35GY5wPJQ6GXhxtBVzw59ja9rxRfAFfYXn9vF0Lh",
	"n8rQD6nM3a3D85IaupIL2HO5U5JklK9Um7rA7ydREedfZ8evS/HGoAe0R2nGck0KfvcXQXhqgD3nTJLH",
	"bLaYTcnFZCHzYq1mTy8mhpZcTJJC6Xw1y+XiYvKkF6sMhp5INufvPYSe7E0m08Ci19AQsKm1NHgjy0Xl",
	"crEzdPqzYj5segUNh0y/07F73Su/1QamJYL41C5FTGoTtCZ5hq9TDxveRtB5GzyOIHBqWaBlfmOReC5z",
	"g1NcNZDW0AbcGEtbmG72mXIz54oLqnOgayu6Xpv9mfXYvXfc6O67OZ2smXyjDMHsIArYJDqE0lR3L+IM",
	"WkQG+FDe181r4APwVAx6DmLBBkzQP0A3mIaM0A2lDzFk6+4WxLnOLiSRjGrgvpWRJKhuXE9zZ0HGNnjZ",
	"JpZDKJLpae71zhDSBI3VmiV8zpMuSlGOet/UavCK7p12ucs3jHZFUSjK9PhfiayrBcPsgnnx5nxRSPxZ",
	"Fet1DiInucz1khwfHR6AOuHYDP28jT50zX9kUsH0rdWcHNlvJX0E9hp/YynB64RcGlfVgq2YPjfrxq3P",
	"yBmTpiNRy7zIQL1xzaQmkiX5QvBfy9GUe9Uzcys04UIzKWiG2ibUjazohkhmxiWF8EaAJmpGXuWSES7m",
	"+R5Zar1We7u7C65nV39XM54berAqBNebXcMtSH5Z6Fyq3ZRds2xX8cUOlcmSa5boQrJduuY7sFiBFH6V",
	"/pdkKi9kwlQQ0a64CDCaP3CREg63HFpa5VkJMie7nL44OyduAgQrQtBDhwqYBhBczJnElvbNMsxrus65",
	"0JY94obOqOJyxbU5pf8UTGkD5xk5oELkoKsq1inVLJ2RI0EO6IplB1SxewelgZ7aMSALA3PFNE2ppn28",
	"8DHA6BXT1PRSVlgfyj2jBqBxhb2bYQ/VW46do++GA1sevOX23gYuZKGXb2QW7uURgDenL0sC2SkI4fEf",
	"BXDy0IpVFkGODmFAQzJ2kVzUhZK2YpmrdUYtE9Ac/PtiRcWOZDQFace2BYIdHIyrQ/coeO/DnGaKTSNC",
	"G+A8VzURMQAKT0jj6szyPtvOYe6t6VkR3sdw2/AYnxj5wTJ39oNBEyP3PImtRBWhFwAINn6EI37sjqQ6",
	"i/D71qmF84SfQTijknwdUmtZtMDPdm0NTHlSk18jz7ATUKcTnV8xEcT3c/OlomQVMEITDn3u7VPfoUhw",
	"T33O08Rc/L+ryXRC6XoyneSm2/PA4z8FXshQyeBO3tiPt96MGd2c74ERhdrjtwRi195Kxo+j1/pJv5LM",
	"7PkcJTEgTacv7b98dlZZNU8fPXzJle7mekBXAvctc1oTX/xSIwdz/xxMeXsjaqzWgWytrgpRgpFv+gR8",
	"kzlT5Jq2437wxPuuuzOadKlELFGN8XVAsGrjTZE0xzocHR407JhNbYVD3fOttBaBgXs6tJf+4W0dyLWV",
	"OI15p2okSDu7epSqWZplPZotcBax5lbL7Pgicb/qISxe+xbAmoh9s2SSeetyfidOu3Z/YrxVgA3VQLb2",
	"GcL7b6hOAgpr+BkImCAsY3AkXJBL+FkZkiLQGFQHbcZXXIf3uaLv+apYWWcBw3iumUzMm7WA/aN9CR4h",
	"pE3E2llhTjPVMIQ/KUcFVF9xYaad7D0rN28etoUh5gZ1FctYYq93J8Whlyw7c41NxyJJmFLnS8nUMs/S",
	"vgH8dX2IHcSZhWzkQNznGlfgGA6AEwLwkhH2niWFZqmBYvy8VHS+/fq4OCMvtcWDnk7ELUPWuTjCDs/a",
	"D6jSkmq22PSNdppnWV7oM9e8ifXlOCE0PzB7nhvGmZ3xheBicYrvYnvn0aY1zZZ7V9HQRqxiPan6Vq/z",
	"wf7I/Y36q1F/BT2it8txPap0+7jdMNj9rrRi0XnCImFn87p8GG06EotPLip2ns2gpy/+3owi5JcqQnaT",
	"trYPj6TrNVjm80KkhKK9EM2qKTk4O52SVZ6yDF1QropLJgXTTBGeAzDpms88fkPNrp/NOpfQJizs/Zqj",
	"Be6MJblIVci1DfqjS3VJM65pxlOuN6Va1luImWaeyxXVyGt/9XzSZr2nE/ZeS9rlED5cGdvwFDcDE6oR",
	"uZhyQpwBr/W2sTAG5szAeZ2viwx+utzAr/snR0TBjTGwh/YglpkbuVoVml5mLOAXjogU5CrPQZJR7G9/",
	"2WEiyVOWkpMXr6p//3Bw9l/PnprlzMgrx8kvGTEv06zkNTnLgKOnPj50MaxIFWpHcrnRLKg8NyysDAvE",
	"RyJFJIM1yRInsA8SfCBV/yloxuecpXGLScEDxO7N0eEDnJOvmqaLkKXgDfxOrNXeujfAm3DFNgR7efu3",
	"IioYPtLmJRiOwE7x3e1O+ACAaZBCh8015NiO9EWceCuEouu1zK9ptpsywWm2O6c8KySqcory8sIuvfgC",
	"FYE74fMqNCjko1c1Dd9RO2RbnptWgCO5kcFLmA+6XYa8ovgc4BrLb+h5ix5a3k2bkR9EfiNI4jWUjOwD",
	"6Fg6JYdMcPNfA6FvKc9wUcM4FTdm0A/TxwZvC0EcKAeKb7A6vpRpyjMFD0guGKHmyml33EkhJXAgGvyK",
	"LO9qkPrUI2kN3RNV+lxSoWCmcx5T7Jl2RPMVw5nKpemyL0uRLzLrsmioc0JFrpdobCtP2zBAO2asMCei",
	"DL2I2JhJaWO27QjHO2H4OgcdepkX2q64XF7YaekSrnv6HRMM3+nw7meOlZktypZIVOrQuKEKKB/6wBZr",
	"nNZ/1//2l+C7LhlVQUGFPL6UnM2fEGxRsQ5uzkdq0E4HCohuVCcQVjrYQd1Qyx5WrNoVTEMoVwKgOv/O",
	"y9If5VCD0RSQMp+Tc2kErW/BB4BY73VfV2y+T6YTaLC1O35jdXasxq9u6MbPvid9HZpRs3aFddyXJLzd",
	"OEo3mU7OT179yCTwGOjQ7z4gDYQ9GwLYbgr6Wn6ZseYfjqacUKmg6dlGJPCPHw2fa1qg7vFInMh8IZky",
	"h//GiD82aGvNEtf0VZFpvs7Y8Y1gUsG6rnnCDpmRfLgycoXpNOwgXgiZZ9mKCW3fU2+/rW/17UafZG+I",
	"aJsSltEWJZCjLerLOWXrXHGdy00Q9Abi0Q+t8/E/lmf1bcaYdqcAf4RODU/DOzv8wT9B/GXoOSKaz/mi",
	"aT0cZq74jutA9z4j3Q8l93/GEsn0LUIgbzHr91qvQ90ABuvCncqrXJiDbke/1t/rFTbrD66udBs5sZ36",
	"WVd/9GDcXXcodHsnuEuZixfv1waXwoyOzAVhZQOC7yU8dWbstMhAa8NXTM0uhNmkbcEV+eXPxP7/L3tk",
	"h7ziwkive+SXP/9CVlYifLrz13/MyA75Pi9k69Pzr8ynQ7oxQHuVC72st3i289Uz0yL46dlzr/NPjF01",
	"R//b7EKcoZsuS4k5SKpzs4gd03CvFFoN942aKuvfbIbhgizNksvx2DWTG/jtiZn3l51f9sgpFYuq19Od",
	"v/8CgHv2nOy/Mmf/d7L/CltPf9kjoKtzjZ9Nnz23rZUGLvjZc70kK4Ah9tn9ZY+cabaulrXr+uBimj3O",
	"0KRc38vfK5CYd/nvXpcL8QJTDRjIkac7f58++9vO86/skQZZmQMI3EHC4nwuY+qQJjcF2iJU+aYEI4CI",
	"8xjARYedH1suXuUgXCAygqAIjGc97q/FxODCQw6a5ve6uWy93Cie0Mwbb1Ryjxax0SK2WzEgw6Ub2+cW",
	"tq630XvcCs1vR7+KuMt0Jc76jjPdMfIgK6WbiP+N9ROZO50B+NosebIE3Qf0JINC8c00kLkiQEdfl7O4",
	"NsRJ0qWAGh7dE3mHnVk4icSHaTwav5IBbZMy0B3doOrrul1wflM8juh+yphzc14eQMvND8Kresx16FVT",
	"2MDhzxLCvxsZCQIh6XU05cHwhQaa+q8dqlsc5QMlhJ8B4U4UEt0B+W1nlh6oIh8eA+SBpz+rtAgIr2gI",
	"h2QiZZKl0Wf41DZwD2903D6tcn2ezk2qPItyGPazz2hYZQn8nORCsMTqFcrDDjlBAbN+dBgmRPazizMJ",
	"zxBGDOz5yns6Gvhe8nrlLI5QO9Jm1m3ND1/XUh0lVMBrqVBbDM5ZNOO/olqzTEzF5IoLmk3LNaN7mOk2",
	"JUwnseOi6bHINpM9LQvWQM3GrqYeAONH6cvNbUC4wSzfSR1KpXVpu9SHt85QU7lgetiz6S/lHPqFlX04",
	"5LAteeO0yXhpTMLLoswMra2tmF7maf1K+SqwN4KBwgcUXInO5eaUqdr6uhRJXSv2Ru5qVp+1hMKReQcl",
	"15uDJUuuYgQp3rZ5e+ski7seJDFdyJpJcyPQJn7LN2An+AZUEk9zTlzRR5D++OZvR/ujI/VokbcAZoV1",
	"LnPTG6Gc9O/rWEsV3zZ4GNpANVNXG38N8Xbl6uJNqnW3wRrVyVvmJIairbvbzB0Ds0BMm97cHmnAgWlb",
	"FqdCb2BvqkX3MDemdQmr9vvIV4YTXK3d3huDX0PPikcdZji71a2ymcvwiBxrrderj4HzrS9mezGDr2b0",
	"AfCU6SV+h6/nra5i41pEthS7WT13uH19q2v3kip9xpiIPRrue/OhAFRT5oP2sZBG718WnahtFrb8B1pB",
	"mXBuFUYy5A1/mg5UbuBPuYA4Br3kc5Zskox9n+dXDnEcBnzD5rn0bRf7c82k9zc2OGWXee63qH7YBjNq",
	"S2lNHWjTXE10GH+BsXG8NbeBcyuxJ3O970BgbKpHq8Hvilto7PV2jEJokBgh8lPZhiDW5gjQAGmpQd0q",
	"Vv9lS5LUWHWTqDQ+11YR+B5aWk+zOnkKOnpX3+pe3fj7GO776X24vZMYpBmzxozRPfv35p49nVil4LAT",
	"dFzX3fl1h/wBDpmGRNOH6KgVShRpPvQbt7EdaJZq4cZkXch1rhCBHe3tWkkwvwPYKrlYgDtEx2WZm++g",
	"uVfoDAYdG4zoUH/WBtw9SLQWNBTcp0zl2XUHuF3wLTQPQxz3WObAo4rkpjF5LIosI3xORI6/QHYJ86N5",
	"9p0GLGBIfaADdnsPHvBasmueF+rVNgdtz9j1zTbWpp3e8sDBHpBnRdzT6/v8xilO5xlPNDDW0m7MBwAa",
	"3WE3k+nkde7+Bfs6ZJGU150o11hbHOWOVThQw/9K8NOlfaJRR0iOz0rVcFQftQq6gp7XBsH8wGhAgzw6",
	"/cp0HLdzU7dhlo/PBm/hx7oxwG0j/GabL4d8EQ2RSOFbcyx0vyBqSZ//9W979OlsNnsyFDT1STsABZdt",
	"ydcHSyoWn4ayN9cQvPKC3XRQOcFuLF1DeldSN8lW+TVLhxE3Rxo6JnJNwrOJXLAhU8UvbvykSu+/rRC7",
	"ZCb71HTJuhjGadTX4VROKVdXH9N/xVb5UF4nNELTaX9dTMpB7eqGgrYbx1XNNw+BXUfqKnn3T1Ra4etA",
	"cs0Tmt06VXhooX4m8vbXavLQV29Boc9ukaFvvqtz+b1YMS+1QNiby6Zuo2JjPSPrWiI/08TbZiUWiAHz",
	"Pr+dhiP2jHgnYTllao0ynzVMQVzqCyPq7ebSRpe5X2dkX5OMUUONBasauyIhNv9KWqux81tj9XsTVtVt",
	"+Xot87QAc+lUcya/nksoTZN6yW7sHaxvMuQn4JaDu9TSMBV+NgwvnYiFAqrwuN2nmpE3ysXYmQfXOmJS",
	"RSrn2gZIVJWytYyiMHj5NU72bGp1P+slVexPX58wkXIRzezagNTd7hEGH7bHOjJ4e7xim2doc342vWKb",
	"53/CP56HN/Shi6jApVDrXCjWeyua2IzdUBSGbWKATCnde8iHUEitIDjZ++pD28eh3iLuD1QC17DKN0wy",
	"YjO+zIss21iApyGHoJa7Q23KOPHt4j4bvCftcKOs3EyG1fe4RUq0aO2dlmCQlHUUwgvB77dYQ9B9PTS9",
	"yrPQQZ9794gmml9XXh3WnWFb1ZFzVgkGKNd1kFu7KUCE18B1WDHGSmXA8gSoi1la7QG3DvP1xMzDYdBw",
	"mQ9BAYu4pREvG/zoLCyq4ezfCB0wUuEJ1ZpJobpyF6EaY21b1jbTorY2g5hdRyE4KkSmWO8ql/DfvNA2",
	"zfeUYOKfJcuyHaU3GSOLLL90k8H6YXa6oFwo7WIasw3JcpoynALWtKLvXzKx0MvJ3vO//m06sUNM9ib/",
	"989Pd/5Bd37d3/mfvYuLnXezC/i/ny8u3v7p4mLn4uLPFxf/fPvfj//3sHZP/vn44mL2MzYMff5f8dxl",
	"XcU5UNV4kmc8Gci5vvF6lGmMY3Sx06ek7UUSNtQor2yQJZ7E9l1RMIPzDN09E13QrAo9/VhaayVqn+RW",
	"NqIt6EvbPzdwx2jby3Dr0RtemsODl8szwKR54EfrPDYNHIORvTSkcLplwLL/3gwi2JULJfhUWGv1rTwP",
	"nLPE3ViYyePXx+cv9tAKUIZ1cEVErolkupCiFuz/ZKBJ2ohUi3zn3yoXO3whcmkFc7N4ZxC7lYFyyxeq",
	"7FN7o7aVeLc2DrQwG8m9i70ZMEDVvqR76TYkL434lnhXrLaq+pWehG+4D0Yfj8v7AGdTrbeCmn/sHZzp",
	"rd22PUxfUpneQBka4eLHDCePeyU1W9/du3PbNbho/rtw6A6A5nZW+q3Ks4V9g44hpDNcic33tjjJjSST",
	"Hs/nNeeh/RvKNUTuWo9mDOsGVf0JLdSWBvzahryltb55qw18rateap/aHiS1z7VtBr43XQpqH0PACDRr",
	"wqc6zhpJGRbOd7x2buB4G7zsRez9OlcVracLJvTsQrygyRJy0iS5lCAjp5ilomLg8VpYq35C1/SSZ1xv",
	"ZheiPzAQN1G7VUmeZVhct7RKRxkjs8iou4N5C/cXUMgXmwQvoW9ojozhtTC8B0amWji1wharkQ3qhJz9",
	"v8lzqCaxxVAYdznk+WiFepr30hFBhHZ4l8clpTxzlHLg8pr2bx+gJRTaq5jWjy9Ot1o8fI/n+xpagkFk",
	"RQVdVHoc66sABZyTrEjNl5slE+5358xyyUia3wgrP5l3xObLCTjb2nZnGHbdy9TgZsrW5eN+2/4fesCW",
	"3sosh2u6Uwc2/3m0iZfv8HmsbfZ2z2N7iC1c2CqAlf5r6/P8kEKSpuNCH8/tvz2/xdvYI2qL9KYIfPVn",
	"DXZuOFDWv7ZMDr6Y18OWOZWmCy0Ck10pTMCFmzP0I6hSqoPlvVP2rTA59tgNSBtUlrX5rfUW7ZNLyeiV",
	"udGdO7nckAt/XReTtjNmhVyqydP+DhZv19S9cJ1rmkXMcuaTFzkbmmlgGidL/X5P0LHSSxd0miFcAKpp",
	"AFmb59/YcJAacXXVm+Jk66wi099ZWpTgA55UJR3tAPB2c3WFKRHb5GEdLYObcgmGpk1Z+sdpnq2nhDdm",
	"917W4eKqb/GsZAGzflOkNjCwoTxstKin1GfXLLOlj/Mblppl2dZIJiVmFiIc8HRt0wu1wQCVer/ZxJWD",
	"aHy7Yhtg3m1AFoFuBsSlV1E1/yUst6Yt8/TFj3/e3/kfuvPr051/vP15p/z3u93Z2z8/+af3cYCmFxTT",
	"b0RZ+jlS1wELLHhUx52RVzTaXeq0AMyx4APdd0d9Bvi63zN9o6zEnBSiPW95jlvNH+ThCj+7nisH+lQF",
	"C4K6xZWpc906ytQCGJ6scwJF4plmMwKXpCyMWTK+LiUpeC5SAtm0+LWNHIICaXbsyw2hqGYsBNczUiXt",
	"KX+E9JF75BeF+W8UJv+dkl9W+AOmtDE/LPEHSN4D6O2h2j/3fn6284+3Fxfpn5/88+Ii/VmtlmG8eiGS",
	"3DD1Q+JjmW2LdA7Cm4EwUE0bju+1CqcZ5UasxRS7g7Or4VQntrP7+xs7yAc/yVqsIjwrW+xY3W0fZ1yN",
	"eWY7NClbYMzQi9TKANeGbatJRxELm4jVYCMuoNP0MYYzjNl6/oDZeloXarvEPe3ud1uvIpIwMiQwRJtW",
	"SXrDGoOSUHjWO1KRrHiSBuoyT3akg74pC5iW2Y/JkipyyZggboBwbVL0eeoSVnqUnvsu1zeOBOrU9Trb",
	"ONISTYXWOjy7z61OyJO1BokT8aNu8/E9k/aduGc7/9iz3484fgNvQrXN8OSf/g1VtYMfFkPuenyz6S/v",
	"ZtsOEJ+8Uaf+lgJSyHTLI7iFA0MA8OUBzYK4Fg5mDDarxzW2mowswSePcAyeySAXijbjOIY9fqlVacIM",
	"Sz8NAI9Tjq6mZUOkPq22j5QLYgK3nkBMhYpEkYRqoPjlHBSmlPbflcAjXvcSG544cToBbfppX+Kzc3iO",
	"OpOfYfF0zO00+7fKBXmcW6Nuh/v3nXIrLom/cyGCwqQeA8NV6XS0ZIKYO+Q9IFyF2KsIh2POcxiyRaxc",
	"kYbbvYKDHqWK/b0VM+U5wfWVDvFxuV0/ZLZ1VZB2DQz2ETT/zup8tNUXHadrm3QxmMv8xirADAmGWw8e",
	"t5R8m/HFUpMDQ5LzzEdWLw9L47xrFfK31sTsFxoKlnoKmILvuFcofOxvTl+603lzVN1CMKKTQqEr81q6",
	"V+z/OiUGRYD7yLi4wgzUMJ97OzscDm6rYoppmhrwqiaIwmAQSgAc+9HCNKtX9LFvfH1ZNaTBequ3QA0c",
	"ese7kjvhrIwH0NCra3BINa2W6V9z0EoC6adu6WZ8MucZRNuQ85dn4YuPi7lim85F/MA2W01+xTZ9czcv",
	"ewQq7SUOOvjhJGEAZXDpNc21yG956N6+DFLlkusoyKu2+65pHPo+l1KOTGoF+WIXOBRSi5yweYWBeKSp",
	"ZKr0/ujdOHnsmNplrrSRbffWudQDgqQ7AFQuNnjy18G67vBzXcds/QjYNTqGU03yBLzAy/Jp6PQWIObh",
	"yLim+A510cCMgbBAEiz5YgH8GsgRZnI0raC84oq2ryWb8/doNWEcNE9muD3yGMwe4EADZd6feDPYr7TQ",
	"+QqKrrmglTCnNwrGdy0Yp1VsfucraEZ0cfzg4H8NCSdQ6ztMN3zK5kxCifRRJL5rkThSHm0f712VprUh",
	"gDazxBo4rm0pszu0BsQLmallLvWUrGiy5IJV67THD/SnniekUfIMyZFnvnSuIQdY2NErcXRgSzeWiRfd",
	"hzelL3/9l1ZDlzWl8Ys/ZjvgMPJzo8fByZtW+PzByZtmwP3ByZvX5mmvGr2CfAStvvhzszv+2hjhkKur",
	"Vn/zY7O3+a3R14t1qvuYex9arunet2a6gUOuLKvip8YMOKk3fMabP5eZfrwPjVEPIGJetzwM7e9t38Ky",
	"Q9CrsDzPrQqNOdm4gQ2RvFTdGZ06KnCZX47Etf3tyD5S51RdlRP7P54wuaICIiy9OxCpOuZ+PhK0/sFS",
	"+7RqUl20doWxanl+wbHqFvu/nmkq27+WS60NYJ1Bmr9/Q3WyPORqjemaGl8t1Fjm4N7q6o/r11A7MBdc",
	"eyc2qCxbC3bVp2ClNvMjF4sWgapVcWv+WLZG7/RTpnQuI5lxsOcgruAMm3pVIeOOdh4DeYzFF5GeTIml",
	"NT4lL0mNo0Nv+21K3ZrdOtMSqC85LetS4qamlnGOsu1eaqMA975jPY0SV4V0ah62At75tMohYvn5zRqk",
	"rlqGIwzRXq9tqHsndejU03bn3OshLFuM3EwvF8sJ1RPWGMkg1XkRIyPGe3SM6lGGocNWXcLjbrXQnjU2",
	"6NOAAes9wqNaAjFgNGwZHsUR5wHD2KbVOIGXKVp5sdkyPEr7KRswYKtTNXbXsxZ1Vo528cetvSHdmBJs",
	"3B6rd121Zp5056KksYK9n0rsw3RgMc7o4IOimiPXf1jvblJ3mzGaRK2/LGgMObfpGcXCoTU3g+jR37kX",
	"W/uG6Lji23TdbtOd1HObzhFivvUQH7WIMLn+8HarHH/Ag0T8VNynhm/KNWhORoeUT+6QUh7EMC8UUCGP",
	"nidfrOeJJ2gFBaxyFagyg2sG2d6MRNlWljUsO65zv4Fgy3l6DCblvKE9f8szp3KJ7Rk+ogPDnIeqUSRd",
	"/SHQgWj2XpPHb86/3fk7GCYw7KGyTVWTQAydnSbkfmDaubiHfquyF8YRjI4x24+XuzNfywJ3kWCpSO5u",
	"nrFHCuOipl4ojDXZQESMS5ssihWTPCFHhzNyiBE6QHgvJjLP9cUkfEvylHVOvWbS6kCJaTsj/ycvgHjg",
	"YjAUf2Wu+pyueMapJHmiaeZ8GTJGIarlVyZzl2Lx6d/+8hc4PopuVglf2Q5YBC/U5y/Pnz4x1EsXPN1V",
	"TC/MfzRPrjbk0gb2kLLKzowczSFjUAmxKUbi1zcDV8DsU5HUA5hZXrjgaaGiSdYRWpAT+B4OKoZzx07/",
	"75fLSUo1nM197GXAGRYgVBva0+r5P5+WY9d+dmLMW7vC7UJFfTLSy4H5d66v8f4lJENnJxQcXX5rB1SW",
	"VCESWgkMX+Bu22By3/DL/CylI382xhCNMUSVzLRd3BB2udtYIRgzLGmVn+qSFlaXGG/yJ5e0qoMYJGkh",
	"zR4lrS9V0upX47TCli+hsEqQh4NPwIbWE8VUQfMPUwynw2oSsv7NraY8KA2W2QGwVTPLCGx5YGYUmwb8",
	"hMnEUKlYVRfbzPDatp0Tx24x2bzI+jZWtfyYzWm2Whua2RkK4cvW5/UOzv+ZK4tGhqJb12Zw4c+D+KP5",
	"iqXHhe7bJLSDgT5mj7dOoDN8lq6CRE0YT+1lDKHWtMxh42FCiese4AaRhbaC+IugC57dM0QYPglO3wYB",
	"+s6wn6rfO7y7SfAdQrqGWwbiLkEKpAP5SID3ATpsyHh4aDcs5sFXzzRHk2cfsBGkZYCKjQUzWM0gES9z",
	"6T2D8L270+2YGiqZiJRte8AVFLY/7LrF7uEP2Vr4H/Q+WS7o/m9Sw5L68NB1jh0h8ErXRFLNFoFEAXYM",
	"IwZBi9LdqfL2gtTG39z761N/cj76vWnufMAxBsM42222i+BscRANSwiGQH7Tx5NYhq2qsIFkBQtDNwDW",
	"md2r0syEt9oRFA1b6Q2EtlsdVirjtNYYgoeqalGdEmattJSHhJFLZr82ili280Y2MhXem4LMq4fUShcb",
	"1mY1Ez+6/UYRuxOjb43Kg0uKQOspYWAhoVm2IbySNryrsaTXDCw4EIOGbyQklhN0wWoRYFwQSm6WMYvi",
	"dmHG5Yl/fEWOtJWldpsaziWpGqTiqlOrLeOav2OCSZ6csnVeGmu66pStA8H6fV5KOLRzSitkRAx9vM7B",
	"rXoDVTs1ewJJv9GtaVhZWDO0bRPcK9eBAlqt13nB9anZTjgfgnW5wtjM77iul44iGDy4TWpQlxDUVQrm",
	"C0eBKq+uIGdaQaf/ea2GKlWXYW4X6Pgpu+ZdOSHwq1l04WrU9a63VR+uXHxr1mksyel0Igbx/I36av2r",
	"EchE25MPTfx9nl/tJ87YWtkzGxnJ552lgrDIuC0luWI6kBHzkhH2niWFxoQUgyiRWVsnNdJ8xfKYnul3",
	"na6TPFKP6tk6H60e1bN1UpGSR8tHH5+x80MoM/AwF9oKO04LMfnwFmzG9R8DKTSvf6TyY3KhvKiqjJJr",
	"KjmE412xzQ5aLtaUSygu8G8UM10a2EIYGAezbMtCRJ2WVgbQdQz1KxdQsSFULooVcA6FAglXU5FSmWK9",
	"OKI2QtP3Bnl4WWQUz12RlfXidTMpsuZrkI0XkBpvajCKw/XeYGFKtwhSGNGZUHJJ1ZLsJOgH9D6smrvJ",
	"5dUhj7hxmI+Y4tkla8btQjpWzIBcCOHsQHahA0hdIaIkpbq2e9vgWtnthOrl8brXAaLW58V7w+BhgcXe",
	"dXmN20ZOQVj52SNuzOAflFTIiZYFM0dXsiFhmmdzQLM0eGqhLbfuUx7xoiqjZB+rJ8TMDy4/VIMHGcts",
	"jX58hc0WFNVcWdcm+LVc+nDLY805J0CQ49wAta4qJVuA/nIEVAAlWpagBk45Qdf7jwRzKM/41EA1iCNa",
	"r6vcwFtUtj2ocUtmkd+fn59g8Q1DCQJsPJ0lMvB2Yb5i4rz/ZJ5rcrAfxJ81Veoml2mMAcOvxKY3QG1/",
	"YF2l/aMcLxSOd8XXaPz9kckyi3wg9cUVX1tG1zKN5NrrEE72qTM1CBjnL88wJYvzORy0dDP6FdsMH/2K",
	"bYYPnl/FSgTCp7uBfqGYjPOI7mvvXAMc8Kob0C1NLLVeDxQnBK5kmEBhqMJJkIyYX50IgXLoI4VExNbZ",
	"0rmXcNR5zTbLK8JSFDN4WfF3N5JrzcRHiyOyLY44aYLayt0bkZAOQQXL0YY2L0sP4DenL5FUJvnKkPy5",
	"til2L6mCrzNypElChWVjGPlPwaBEg6QrpsHlpkiWhKo9cjHZNRRxV+e7znXjn9D6a2gd89uMijzl8T28",
	"lOMwMkbXb6kLWNaehE5upGrphSLfiQ4BsBbOPScJzTLzbiZZLlBKDWISxLJjlZQITpnxEN+QFcxFhgW9",
	"XFfD/qLfg5Xjq6OGYvRSkRXkMjII7jATGWCQk+Dtsqt2/Oblxh2w9Zgi5iwMUw0rYcry0ZDTZ8myNdIy",
	"jcl+7I7K0pRar0uXo630KFP/XEMYc7SiCxarjT7Y9dcb4Mc8K1asUeO8JWivgi4opz49ddSNcsEkgR4V",
	"V+SXgqfJ1aDSKzhpMOtxGCwnRZZVSu+qcMbR/HWuT1DL2iqh4aoi1t3DH/l9Hs3IT0YcUUzDt/3shm7U",
	"I3Rzx41yRdYFGAIMCd+AWN3o9dp8qXUClpJmktF0Q9h7cLsTkeKbOOdk2twMjDrQ09zApxzH/NEYy/xk",
	"x3MgDWDHXhQ5OsM3q9FcWoSBx11bSSzS57CWCcc+cejWeXxwtAOaFE6FtpA3/IjUfE6TAAe8rqFR76Y8",
	"rIMduVRO3belf2GobJdswZU2hA3Iz4puDMmirZtmOoocs9pbc+bxwVE5GMjzWW4opyJWi5rLVUlBTVsc",
	"SPnVmIa8sm6/wZODuqwPT66wHGxHzX6fIFmWbLC46a2mCp/oznZqFzSQlkHjIcxu/z5R+javMwSWtOnL",
	"YAHbuZI3Zev7ZZ6igAtlRHhYB4BARoaQaZ5JmctXsTRkZnZoQWyiFZfTy6m95pRnhQwz5bnkCy5oVqZJ",
	"HBQIK5mWm4O8CAX/va45QSIx1VRdVdUxTG9eU2gMckesQaG58r7TjYb7P/xBt5Nm3MOZr90kv5fTv6HK",
	"HTy5ZPNcMuv8sKLyCjVh6wow1vHnI1HEW+gQfPnXTz+cnWLAbQDk/zo7fk1+YpfkB7YhZ0y33vwrtkGK",
	"Wpa7q8eeZIsAlc0WueR6GZZzQgzA2T5U2hbhGODp5IqHAiXYhhwdhtvrTbi9cyFq9RDhVa3ytMiKcMRB",
	"EQKomaRQbKDypvU2tlr8UFwyKZhm6owlkunud++u3pzpRMFsQ+3P1SoJdgz4qxiMvaWiqFaZBifwlEEw",
	"ckRjPwwg1ZqDA6g1TTpGgc+9Q4Wf8Wr4qQehXg8b27s6pNDNBz+kcIRZxQelXGkuEm3rGEzJzRKMWjRZ",
	"Eg5F6BVBjadGenZhSMLXYNm7mGA1e/aertYZw9p5pSnw67XM0yKxmc0Nu56Lrwu1w6jSO8/Ae57Jry9p",
	"csUEvBYliemtjFn3sArtDgp7OoctG0YHv6FmLb8GS52Nka2CwQjitioy+LCiOlm+xAIPGLSmk2VliULL",
	"8P7rQ5bOyIvVWm92RZFljdkVdiNGCLHp6ho3ozFq35P1qtkeaoWWK/2oohYrujYb/+2KbaZwxh/QfBsu",
	"StFGORdcFYydM1+81KzOg82auzZCL5nmSXUclWnJN/AazMXjuKaS54UqHcFgGWpG9itlrhELwTYFurIc",
	"Ewj+VvnETYlb2IdwKgguisDVf4XSpsEf7qXBNn9TkvEVLxUWVTQLoHep3kZ/AV5WXqvVD2ES+EpIaAAQ",
	"Kmuq+lm0IfMu/U/ByoBKp7PTOeFKwQeUfF19KivUekF/FH3YwLONKyQL4AdumJpr1BIK9l67u1JVdy3B",
	"fYBgwrrlSS4UV6DJh7HMsmzcoHWrYg5kdqd1M4PZt7MjQsFjCSnFjcQ/ZzfO2wLPdE2VMlfPXlo4cee3",
	"i1rNenl1dAaAfbqjbSQk5ynWPcgcpCykrScml1DCE5mpKSlExpQim7zA9UiWMF6C0lqToEKAqPO1EbvF",
	"inLBxeJIs1WEEW0GnV0qc7BCW+Sy6wTA44NpCJQBvzUs2KTv7qDdViBTRdnTIYvTpKSWoEGaCnCWcJQN",
	"dHZNPC/34RalSIF18wFPEZBmGAf0jM01KQRcHpGSfMW15yaimOQ047+i2qW2UC8uhTy2OS4uWUILxQiH",
	"z+C7uSwEuFPk1VcAgc32n1FlGz2p9iOZBR1iYHNPuJHSe+RWO3GRuXmWgjmICnL9bPbsryTNMWsI094c",
	"iOVGXhDmGM0mShtWE2/Mzv7MlOYrsAn8GW8b/9V6vyZ5Zs4PFoGFLsqQbjOvZEApY2OjaQCogSzdcKy6",
	"cEhgXuvNaDxnbaY2aAo+h5Oz5bt96mmffNBjgYYnLCOCV0SsvkHpqlEVoQQCAq9sI+XskeFuXuca/vvi",
	"vXmcJtPJYc7U61zD30FJGOPcI/uyvBm2gSLtLvRxKI/U4BcNCL1Nv22DXXUxicjAVD42w2Pfm4eLVcWP",
	"sOuzNmeH2cZ7C/3/ror2D8mr6O8EnPKO9wu9fN6U5hoWmFYbj3uiguD3Uo6rv6Th6ky5tPTnTcxyaQet",
	"Na4YhrD7sytXc5R2jmnTC0RkdvyKUu6QYTqENiYMh5LWjF1aFi0noJ/KcrdctaDJFbHjhH1ggMOSnSvF",
	"JparmHMmyeOypHrjW1lrCfmGSDGTXC6osIeyrxRfgKTVq5cv9PI43BMzt8KG+69Poy6Urz9w1DA3bZ7H",
	"4r3YQUb5qm6DhKxi7QL+oJjyXdJN911oTBIzimN2DOPNxTwvmRmXq+vCDn0xmUJSq4y5fzKard6hoXxm",
	"fw+DWyX5mnUkArHHjM2QbW6XheuVZuHA++4jcpO999BBo2+4EmqDRhR0FTq6NWiBJEvfle5OvcdYuj4N",
	"PcT2JHiKhjPJ8J+quAyfYNOV0Mf08gJP24TRO5M6SD1C1yBY0bsZ0swcHx0e9JD+RosG4T86PBhM9ntI",
	"sxnqowmzN8idk+XaXj+KKJuRLNl9c/rSoZhLVkOTxDC4arbI80XGZkm++lyJME+ThyTB//rp3NKnByS9",
	"5jA/kvA+CGkLAOcBSNrdkKkqdLRNoMpv5k7WVXk0y8iaSdADpWF1HmonrFZCQQ+rT8KCb9gWbfMBTlaI",
	"HDOUfYy2s2oM4qz1N/WKGbYAkthyUOd8xZSmq3VHNX0zls3HdUOV3coWJfRTWyZq27msKiLFulPD51sw",
	"4WXxbBc7/k8B5h6r56llI6OlbwypRqkqNENVZhuSTU7ydZFB2T4Hbyw/SE4ZTXdykW0G5hH66ArOr1DV",
	"bZOsXbGNUyqj0A3+ulT4OlV7dVDfmlDNFoZrYOQx0CH4FfUPT0rl6OTWXrU26V7wAboRLGj28LLBUU3y",
	"Gwj1w4TL8PvUEKULSG62i2TH2nYiCsmaSjUYd2MV0H7ttVLaUZ6W95HysgBWJbyr5ILD7KXNqoBBGNQs",
	"k36UaUOtNGbfu7vse8NwujybtPPYa5orTMQH4wffqDUTR4e1aJ7AYwWNiC3oVmeYu9Uk7+LVp/eDGpII",
	"B035Sr0rM0MHonDKuFNsux0js5BU6HdwRsMmgQ7AUm45E0/fATPzzjAOXCze0WzxDknmsJltP0Kdj8i2",
	"C4gw+B5zHzyCf99cqXeF5AEXmJ9+OOs+PieUbgPhUpC9BZCRrR0IT2h7C4VDB2af13QNs2gUVTnEO3Nn",
	"3q2YXubpwHU3xBjbd3v+3ZC8jq28UUwe+XqOoQ+NxyUHvJ7GjLtj7uw/Yu5s/1oEEwR1JtF923PRwr5K",
	"zRb1pNj+1zE39qfPjd06j0Fmwhq5HTNlf6mZslvko/Oyt/Xevu6qfddTrtYZ3YTTcX5frKggZbFwkErU",
	"Mr9x2YNkGFbsPV7PkPr8hf1Gjg5Lob2xwAGcxgnVydKWdq45Wm8R8tqbcsJs0uZc8BXFNMX6LOsMPVCx",
	"UgvkLIy4LYQTRuwTUIae5EDNQCkaC3EtImIiXl0jsqfg+GUXNWshX77uysvUJBxdecKrb84VyJIR1InU",
	"6YiXSBxbBTc4oBLiw4RmdNUcfXt3QfOg8LmhqqR026XG9GYNHeYpy6jm15H0Aqd+tRtpm6LbuEPAIanP",
	"9gN9nfuT002+zrXVqVFhA1IBT0x7p3DNr5n00hKUPtETJZNdLlL2fvZvNYwk1KLMQ/suvzrE9Ytly1r2",
	"M4cQC65tDHXw/E87zr+Ws82D+Xdc+7gAgZYY+O4LWyM/NkpOo+S0W12i7UoPef3utv5QNXBY7Kp/rwtd",
	"5Tc+Vhb7HchcsnEcg0Quj+KPAteXKnA1qE7HJW8KW42wjDpTMSxBYDOlb29yQD/nT1/jM7Ws2vZsPZJs",
	"utliu4zTdYh8ZMbn+mAfm/Z5u8zLzkV5P2NSnxYZC4ko3g7aDPTSyNY7pWzdSM4OaW7M2OEaNVGj3aHD",
	"Pcfj8hVy2V4sKL1m0ohkhbJSXH5po5lsNDZMbKQ18i2c5153Ltj+LK9dGV4vLtL/jiV1nU7WPSWr6qWq",
	"cEcY1yD5YmEIZQiS6I+BEbvXTHLdn9feP+8z26ksKlzL9u5G9I6pto+6S0UvctUma9uG7NcWzjgR5icq",
	"BabwOZAcorQm08mRmOcDs/xE11INHG3izRhtg0vxNv1D8BE9Ld9F82xA3LsyjAansO39kyN/0wcGf8E9",
	"nJ2h6dTpiqaTF0LmWbZiQle/YQr3iasUW5PsqpWdbUQymU7OW6Up9gu9dH6nEUGxFtBg9W6VNgIDWtdr",
	"W9D64ORNlICti1B0xHRyyNVVNEM9V1fhXhg5Eo1DicaVfCiJt9Uc1gI+Pgx97CK76XvGutbVk6s/Agnz",
	"GEbDV9oHGOYLzvxcR0gAsTm6e8Wdaqh7RELxROZ1gsczAzbdtJqRYxeYi7+uIYzWUgKuXBLwLdja5msW",
	"MrDT1TrjYgEJTK5D5ejKx+eS6RvGhNs/ga5m3Q/wnpTpwjsyhceOeuofRWDHXcQaqEOUbpmvdUVQzeUK",
	"Yqxt4C4mWbLpuiqlYY5ZNcFt19JCEAb5aMQblUaj0qhNzMyV21Zt5PW8a8VRNXR/TUSM5e/Nq4TNwEkU",
	"soY4/2CuSI3uIAbMgh7B5qC5/p6qgJbf/OoYSwz4hsYPVzYzCLV4jqxegEErBamwC0N9tgdYl2HGA+W0",
	"doS15fVhh1MsjtT8E6sHbeeNSLbmo4AXGBWEX66CsPHCdLJ9DSUhpvLI2GP1pGTqMN9Jp3aspwQV1l9r",
	"1ZrgopXR+si0LFtgAuGqQ3XtNeUCEwCF+E3MVy1ygzquNzd3+gVNljYNWX0oDGtxA5gF+0xv91192Oz0",
	"Q8pouQCdspxWG9L3VUUrwKV0498t9LR+/4/U1NLbkdLOklhOYXkAL24sz0nJsJClYWRKtwuzjkjmOzfw",
	"dx1xXeXgXthWYOxt660PVDh/IseY2uRBDkywm+NwiBXcUHZDIAKLPOZlvuTLjEG0pigyyI7lApvbWmBz",
	"zfJCdUzgmnzELPaZ+5azLO3gDCCzkI11g1pWtl9FAiraUqJ6GWUMOygD8azEgP+ZlbVS7d+BkqADU9fU",
	"+NL6voLI1a7dHbYulK/YMr+B1wvallVADTZ5lXG7dJxQIPfMBkjGiEC9UVvp6IocD9c4NkbsAIaf+j9Q",
	"YBk/OzOLK1K9xl+bJUmbVxQCpvEynVfV/ToVl0VVjyptH9OAkrzNw/0A5yML2Nc3Rbpg/YtotodSLhCX",
	"fr6UTC3zLO0bw/MtDLtx9RW4PkeXQyxuDUJwzhOsDWFrtCu3R3Mj6yfjE7U6KoSu2Jla3lGZrLOz77uq",
	"ZK0lv6aa/cA2J1Sp9VJSxeLlrvA7qkjV8qTs+/uoclVbUm81KrtzANDwglQhxPFt29s5Aiv/mHvM5/dU",
	"+cZsv+EZ6OrgdNW/6ar8Uu0qRORijKNlFjlqqHUhhZVGDbYlNMvsw5fm4pErO0UwXaYXvT3qLu5Xd2Hu",
	"TihOcLFgkD0C/Ent4Zi2tnIOd1lfp+Qp4XOXMLHJrX71PKgpHJUXd6q8iKTzH+IYUklqCEcXsBCRnakK",
	"e6CsaLLkgkWnulluGhOYg7Zc7sXkW6wmcDGx67FpRrmqMu2y1VpvbGZQSCxaFz2r/Lz75BSWSZKMSkyD",
	"4Nyi7WYBjS8LQ3kYpijNr5mUPGUkopFW3STOBZ+UwCPHkOh4j1xMzpCpuZiQXPo7vXe0MWz/DhXpjgVp",
	"L8kP6bDsxi2ZKDGgQrrQg9D0amg/U/UGdWOmn52COLFlfAlGm+Rok4QejcuznVmy2fluLZON0cN+7YFG",
	"def2RoORC/z0FqzQkQxSvTafgtGQ9aUaskJkqe/ut3zea2+/VcHEWQDQiYWFYPhEbpa5qgZw930Orrx5",
	"P0OE4w/ZbEl7h1UNtPqzcInArX3XtyyZ12kNsVi9rzuS3dWKAZXAvaEKTRleJOqQxHfbmC7eTnvw6Rbm",
	"qXIDFvdmcL58xf4ndwUMXU7Klzk6IDfWYGDyay6Yl2ZaWSdEmO1o//W+C2neP32xv/vy+GD//Oj4tav1",
	"Y36s88BYHcOcdC5JnjAq8A1xPV2+P7g0ayo1T4qMSqK4OQmul9zakahkdAoiu42HJfsrJnlCd1+zm3f/",
	"J5dXU/KiMPi3e0Ild+6ghaCrS74o8kKRr3aSJZU0gZrZbq9YeadMNEQeX0y+e3WOqTPfnB/EkopCYiMv",
	"1j6Ubt0m65SlR3Uom+67UD2yLbKcv1ORbLqDU5yH9Sb1nGSlvqSe0gx+hgxgwZGrZGLR5VXpw3wttGRz",
	"ydQSE4Q10yrDrJGUAlY3GqgLhl9gD65Zx8rrCwiVmTWfvTL/tQ4dA0OSrSg04Gtn7uxwXiow9Q/aWoNI",
	"eScUfB0Qy2Ml/xpobpu1eFxQG8RA6YoEuGLjV5Fa/OAsFu2ONXEMYsQ7v+uMPaoN5H2K5PJYc8nUOy6i",
	"Kc9MC2sGN6SGC+e5HfY47EE4uzrp411HNrXwlcOVNe/aN4zKYIRGyJ6A5rmzZMlSG97VtIVWgoqyrRzd",
	"yM3rlZA0vxFZTqEAl3kJ8JVVfl0uzVfua25LhwMUrQW1gV69FroDmYt64RClqdTfSZqwQy9obKipUXtv",
	"aqfI4Nq1WNMwL+YyzHVcuKPDA1ImooveOMj+HMgyY34mNE0NJMJ4bVq8Q3NWKOkejuCbu0hLJ+dZvSJ3",
	"9kX3ZQ2TuW+LLAOXpt5E6ipMI2sZdbZMDxjI4d1+YlybMnt3+GXJgxEtsEL4tmWCx+IyZPNAwbFi4wZm",
	"EPJ0EXWMuo4pKb7j2pd1wmmvI4+PG/TtB6wSWkiuN4a2rHDSS6BMhvJVf33rGPF//XQ+Mc+paW2wDqlY",
	"OSWkJzGIgVVEos9OPXck+O/RNudjKFGN9uL7qoxkkOU37WSvB5anahfKmRhhePf62a75tOu+o0YaJgi0",
	"cmxQlcne3vDJvns2sWog/gzlmYThK5vpapH7AHIx55BSpjGA/eBLG5MSZ5uN8eda2ZHQun1Mw9PAqlni",
	"KLXr6k2zWz+mSaN7YObZDcuyHSgVt4vA2Gmm6nVLqi0ESUmswsWbN+H8XLUk2Z6vEyGv6Brg1cg4VqW5",
	"nzlCYViJCZQUdTmK98xSjHhQ3fo1/4FtJh8MRM0JucqSFEHokEIzuvrf84wvljrR2Yzn1YhmF9/CF6i1",
	"KPOMnDO6mlgr/MRpemq9W/nOf64P8fZxqNsTq/RCamBdUZKMSsyQtKKCLtgKJMM5ajlAjmXpgpWuU7bK",
	"H5fkJpdXhmtQWCc24wmzL6Td2f6aJktGns+etjZzc3Mzo/B5lsvFru2rdl8eHbx4ffZi5/ns6WypVxm+",
	"7RruRQNI+ydHk2lFBSfXz2i2XtJnDpXpmk/2Jl/Nns6eWS9VuKbb4eTeb5MF678MKVdJfs3kppYcqTTZ",
	"GeQF6S2Uz7rKQAzre/70qcMhW3fEugeaxrv/tiZS5Gd69f+B6QBTt0igDaSCLiDGunHn4ZGI0M4o4DoL",
	"kLXEWSvlZvlNGKD7HrFeU0lXTDOpQEcW4da9xM2xO17LCD3xH0h0yKyA7xh2a8BE4hpi24doE0JLqRQS",
	"XcsYOp1k6AJP3pwexTePbSCddtekpf4NGw5dQylPhyZ3j+H2W0OlZYkC0QlMs84J3vbeR83e610gTrWL",
	"2Byodc1e5gsOmokV+f781Utw/YVHW+S155SlTwwN++rp85CWw56gecBqF2UNqSUkuaTJFfpjcVt96C93",
	"SFFKm15rd9/QtFSrddKM6WSdq1tRhqwCINhPlLLKgA66cJKDms+u7Js83XTA4v3Ozc3Njplgp5CZdf2r",
	"A6dDX9ip+wqos7x71nudGmnqW7TnbZdeK+hxEv7iy1J9QSF1IlmnVDUa4hVZKkESKIL/oUltPjSuYveN",
	"qCN+TG74HV6I5iOalD6ewRf0O9Zkvts14toXwrpY3iOz4c0S4jF+AMg/+/sDQN6sBItDW7iwdLsT+PfN",
	"lYrCH5Lh/sQuyQ9sQ86YJo//9dMPZ0/qpAol0mua8bTjUEzH+zwSM36puQoAqrmV7aAE5DgKJu+1q0Em",
	"SObjDB4MM5C5+yNyU58d2/MZcSQnMgflyhZ8B2z2i+E57oJP+N3wBWHG8jPgB0r7Uyff3Cgh7CRpj0sA",
	"zY21C4JaM4zC51azeWfo22mP8W32A476Ll/HuiU1cGLndSPqHWNK7/S3RhhXOSmuhKnZrGo4I5mWnF1z",
	"sUDZ1NM6h9HFDXOffEzLCheA1pvGavG4nj3sGkSpAEOO01lQgGfxbSc/v4WQzqEnahnJuFrtR9uAUNG8",
	"9qVhun12rlcff3W+ZMFRDVl1SytZjyWjKZh9nBbYp7sfyYPcB10+r1j1h30MSrJ3t4jat1Muqr1+OnFs",
	"OvnrgwD6yDlLo5cuAUP3VuTUFWGOS4TgyOzn1qxnCanfO9PYb6v6Lh/UYbUeF2VDc/OAxy+zkhSZ9nyO",
	"MQp2RqriK9ZGBiOYAaAE84pq62pZa/QIXQQL9giTCLhYqjJ3AXjTu7salbbsINvpc/eJyy5gUwhqyRP0",
	"rMzKlEe6kKIsM6pssWEuCWYrmJFDdKsEOx+7ZnKjl7aoS2ih0OvMy2nwQKvFBA1T5+lo3lzElVwaEF8x",
	"8ujrR1Py6Gvzv4Z7e/Snrx9Vhcav2ObZ13Buz6ZXbPP8T/jHc+sfGdopzHi7nRpMWtH3fFWsXJlozD4F",
	"cC43aTGljiCAhjYwGyqqKKY7Ea3WnfB5HcuhRAsO6vpb/F1RgC3UdXZerCmhyrs4kK9SFZdY81rjLYpi",
	"Bl9BZZWAnB6LP73XV8wnHBAAE9e0fbnPWJ3LMrN+9QCzfpvLS56mDBnL5/94kPc6J6+o2DgQK3w2H2K3",
	"Z9ZF4I0og19bj+a6zCQd1aAcQF18w5QGn8f264gdanmqh0qit79JwwTPZ/c4dwhq6XiN7/0aP32Ia3yQ",
	"i3nG0ZNpJBx1whHjtXd/My/wB6QoGdNBv2bz+xa0BTs0aEuv3Oun7AtOZBg/XGPJRUBKvJKJsCrO4QaH",
	"TyMHO77hD3P3//IAU77ONfk2L0Q6Xv4Q1xA3cA++1d8xfS9XeoGhWb/3+9zHS4y3erzVDy4LUJ0sQwF/",
	"OllucbOh/b3cbVjgnd7uoQLKDkz939sdTa2I9AMbyYbSl1FM+bKI2igZfXoyWgSYI4z23IKKnmKp9Xuh",
	"o1X5iQcnpPep6Xlo6jnqlkaiPRLtL0ydlVSlHRWWdnS5nrrtyNGSkH1G5WjH0cI8WphHC/NoYR5ECqNU",
	"ZDQ3j+bmT/bMRh/TAbbnAS9qzA7dVZ75PkSV+HwPbKHuWcgoUozm6pHwDGL2BxiyU2vI9gkVsdeOVAQn",
	"ZMzuIlBbqXj6aeRo5h7VEKNB7A64laDoLxlNUawuZYqk4263TOAPTAjuzDg+nRSC/6dgR5hdDfiaTyPf",
	"jLRipBW/P8mm05J+K8kG+j4wuRjt7fdLn0aha7TjjHLePZLhIsiygWG9wbUdDObarGH+gUnxZ2Gy/0g9",
	"2CelxqMabnwRxhdh1Pw5zd8uXa9lfk0hbVLwIdmHBpC8MWVi08XXt9l59AeLdth3k9/ZY6JzQusLHh+T",
	"kbUfCflIyD9vQo75zSnU41e7kqkCs5uFjcun8L1Min5JFUtJLtA9qPLYoSLdza0bTvlryEfXjIaF29Q9",
	"2ZZxdJzpExHA+hLiaZRG2je6lNw7Wajd98nb6eT9jrykCVbHsmOgsIyZzUCCBmst3FJHIT60aUiPgyfe",
	"gj5vzooYjK6bo+vm6Lr5hbhuBnDEFuci84wuDJ5gzTVGcpFtYDWrFZWbej1WNSM/mZ0AqHICkpWrc4Ng",
	"AUhCIRoucCi4+XYwP6sjFuUEgOc3gslHiE01vH9UwahZnPPGrOORHdgM9YhwBSuKJiOu2oawrCxWdq92",
	"YKSvo1PryIF8Yg5kiAdrg2WIuatis3uVHx7aEdWfdVR3j16nfzDK0JYttkiM1E82sGVJNrbSEDcGH91D",
	"RxXo6PK17bsfz3/Uf3m/Y/rObu5nkuwozg2M13a8tg/Irne7ZfZeXWh4Z5d39K68QwIyShKjvXUUXu6K",
	"TnZlMOonk9ZD8s4I5Wfh+7iNnuXhCOOo0xkp8UiJvzg10m7KknxlKxpGHRTNStIiY54BCtU9Xt+2aqn6",
	"eIcKpmrQz4KM+1AYed2Rwo4S+iemdxlVWjEmOqtrg5MBVZqYlkTzFVOartYRwtShmXtJlT5jTNyNhi66",
	"rnkuPx/tXQmTDl7zL+1zeZ2TA7uIkYyMZOQTkxHJRMokFrrtJCOuoWWbgrTi1La5S21+aHLn9GQreN4h",
	"1Qj6gwGluhL5jSgX8iOTNdat4RgEjU/rbSe/V1vDSKVGcXKkiw26qHDwPqqIzQwF28bOaVc+WjtHa+fI",
	"BP1erJ1bX2fP9nlnF3q0gI5aoZGSjZTsY+yRWxOymnXyzkjZaKMcSddIukYZ73ck4zEh8yxbMaGTXMz5",
	"olO8qxrXgsxCUt2LsukBjrsF9aQD011hGOwcQvEJV6qoJ1adkaM5sfVb0mkZHGsghAF0S5ZcEd6XE8XG",
	"2anwJBBPB7GLXJGEKlaG+HGnp7PxkU2IzMiRIDTLSK6XTEJfXKQHZX8iDJOElV8ywlZrHQ1eTJT8ZKq1",
	"1sGPJH3kRv8gBLa6ucEsJK3PPckEqqs0sEpUq8OYYmBMMTCmGBirQ235co9VocYA+t/jW9oXSy86nsxY",
	"XH2rxz2F2LfneeBo+8gCRiftMfB+5M6D3PkW4fjbUR7sFaI8W2mY41OOAfujzD6qYT8rziaeLWA72lLT",
	"vd4LYflMPGwG8TsjgRmVgp9GkOnMMrDdlYdO93zpRy+c+yE8o4w1slMjO3UP9LUrO8F25NX6At0zgf0s",
	"fINuqcT6JLR11J2NdH2k6388dd0tajIF3oP2M2B73cMz8NlVXWptoaxE9amfA7eQfpXiSKBHNcNILm8V",
	"1vfxCsnbedSPasmRXoz04tOpJT+KDISVlPdBCEZV5aiqHCngKNJ+CarKjyK5McXlfRDdUX05Mn8j8/el",
	"CIvXZp6oSHjKtOTsmilCy0AE7DK7EOHAFBywLxjlDxPvcJZLTXKZMgnhi7a4H8QfmA255H/1WJNHZoxH",
	"5LFgN4b6zrlUOro4GLy2qBSHgiqnKplMJ0wUK4MMFP6CH99ObxurgeeP52aOyAVb9MXx3E2dxS86iule",
	"tRHm2MY4jzHO49M9RQYD68/PPGOsLzbyW9OmLx7yWxxojIEcYyDHGMgvt8zykc24EKun7DYNdCW2Epra",
	"HK3qDAf5dOWLgWyNj/L4KH+yRxluypDixfVnOBZjCa3uKa4Sx37gWEpv0tEHbIyf/GMRhRanvvsb/PfD",
	"rmardUa1YQgVz0WchQf2w7UmZfMQD39uW/1YNepVW+c3Arkn8+q3pokoqecekbplZvRRkhgliVGSGLOp",
	"GDrboFsjOz+y85/Ryz0g9UFqUx+0HthIuoPGhfjod/z+nvGm5XvgzGNOhdG8PJqX6+qDIPcvGU2R9S3f",
	"/V4a8h3TIwF5SALShPZISUZK8rviXAbnZupVUmJDp6TcyimuPvSYdmm82OPFvgsWARIf9V7c75i+o1t7",
	"h8FDfwzz5Eg2RrLxaQ2TnQmUekkHtLsj4jEGHN0d7Rj1oGOQ0WimvSMS2ZUDqZdC2uihO6KRn0V80Ba+",
	"JA9GEke3lZEEjyT4y9Ja9eXcAAV5FfZZV5U7ghwWhW8X23mvAvEoi46y6B9YFm3Wnh0umd7VXR7l01E+",
	"HYnYSMRuIS1KFAK3ZEZ80fGuiNgoQI480Eg+PgNJBx27ByWPSLnSXCS6dMDGvmVOhIrOVJRgs2axLBMv",
	"ceYBpMaMYn2iSwIj7cLKRch8FbPGXXGRdtIbl1vBlrUfkldhn8x5ZuMFmmvJRbbBiIEy4pnoJfWjAhb8",
	"mglsXzq634sX/R2sEh3I+1Z55x7wFbrheh8kWcXtpF/2nq7WGfbA1b7AX+BSWwvw3sT+WPnfm5uTuWsA",
	"jvaY7uWay1ysmNBfr2WeFolGBzrJFjwXXxdqh1Gld56ZDXAmv76kyRUTKV7sYTQELt/o5T56uX+ytwjw",
	"vv4W5XJBBf8V1rFdPqNazxkhx4a2IbVQ9Y9I4gz5KBSTZEkVoUnClKEv4bQUx7VV3SNn6E80Xs3xaj74",
	"1axeKkjakjcQ391c//f6BZZsnSuuc8lZT0KYU9dy05cV5tQfc8wNM0Z0jhGdY0TnAPJXUZjxLR3f0k/G",
	"5pZP4mZIgpbAsxjL0lI1vadULd4ED5yvpTnz6P0yJm35A1KLCGO9TSzVIHqCrWv0ZCvrT2CSMbRqtMmM",
	"NpnbMAgd8VWDLvN3TN/5Tf5MvMu62YbxKo9X+YF5/e6Yp0HX2XpX3fGFHl3M7piojGLI6IQ/Sj53STs7",
	"g6EGkU7r1nbnxPOzcG3bVnnzsARzVBaNVHqk0l+UfsracDci6bX8YtOzjUj6bb9V29H4Oxp/R+PvaPwd",
	"yBRUhGM0/47m30/4YFYP4zADcOB1jJuAq8b3ZgT2pnhwM3Bz7pG3Hw3Bf0i6EWO1t7MFDyItzhpcIy1b",
	"6k0CE40W4VGsH81It+MZOm3Cgy41WIXv4UZ/Npbhbk5ivNTjpX5wQaDPOjzoYlvT6D1c7dFGfOfkZZRR",
	"RvvDKBbdLRXtsRMPIqKlpfgeyOhnYi3eVsvz0MRz1CuNNHuk2V+UKstWKooZi418q+zQXiGmllxb1Ze6",
	"NxI1oKjSaFl5aLRy+PMW+qLRFF/qQmaTvcnuxLyWtnUTuY4dFmH2IkMJmdB2CzOvjkftw6Rt7fUGygXZ",
	"L/TyRObXPGWy7tvgjbe2DXpHO2BS87mZm53xheBiYU8hOHRStVbYWpZPSvc8mPUoOCjWPOkewQAQ2xGa",
	"aFeyuTaA/b13JS+EzLNsxYTu2ikrWw3aoVmfzX3ExYKwa4OA/nDmh96l1VPc+f0xqdY2S7AJjWgic6VI",
	"yudzJpkIj45pUrYZ3U8jEhyylr+hb9+xRA12LM8hqH+kmONPOZb3UAzYccI4bDjwStgRHY348PbD/x8A",
	"AP//NLuiKP/RAgA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
