// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/service-tracing
// gowrap: http://github.com/hexdigest/gowrap

package fleet

import (
	"context"
	"errors"

	"github.com/flightctl/flightctl/internal/domain"
	"github.com/flightctl/flightctl/internal/instrumentation/tracing"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// TracedService wraps a Service implementation with OpenTelemetry tracing.
type TracedService struct {
	inner Service
}

// WrapWithTracing returns a Service that wraps inner with tracing spans, or nil if inner is nil.
func WrapWithTracing(inner Service) Service {
	if inner == nil {
		return nil
	}
	return &TracedService{inner: inner}
}

func startSpan(ctx context.Context, method string) (context.Context, trace.Span) {
	return tracing.StartSpan(ctx, "flightctl/service/fleet", method)
}

func endSpan(span trace.Span, st domain.Status) {
	span.SetAttributes(attribute.Int("status.code", int(st.Code)))

	if st.Status != "Success" {
		span.RecordError(errors.New(st.Message))
		span.SetStatus(codes.Error, st.Message)
	}

	span.End()
}

func (_d *TracedService) CreateFleet(ctx context.Context, orgId uuid.UUID, fleet domain.Fleet) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "CreateFleet")

	fp1, s1 = _d.inner.CreateFleet(ctx, orgId, fleet)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) DeleteFleet(ctx context.Context, orgId uuid.UUID, name string, enforceOwnership bool) (s1 domain.Status) {
	ctx, span := startSpan(ctx, "DeleteFleet")

	s1 = _d.inner.DeleteFleet(ctx, orgId, name, enforceOwnership)
	endSpan(span, s1)
	return s1
}

func (_d *TracedService) GetFleet(ctx context.Context, orgId uuid.UUID, name string, params domain.GetFleetParams) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "GetFleet")

	fp1, s1 = _d.inner.GetFleet(ctx, orgId, name, params)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) GetFleetRepositoryRefs(ctx context.Context, orgId uuid.UUID, name string) (rp1 *domain.RepositoryList, s1 domain.Status) {
	ctx, span := startSpan(ctx, "GetFleetRepositoryRefs")

	rp1, s1 = _d.inner.GetFleetRepositoryRefs(ctx, orgId, name)
	endSpan(span, s1)
	return rp1, s1
}

func (_d *TracedService) GetFleetStatus(ctx context.Context, orgId uuid.UUID, name string) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "GetFleetStatus")

	fp1, s1 = _d.inner.GetFleetStatus(ctx, orgId, name)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) ListDisruptionBudgetFleets(ctx context.Context, orgId uuid.UUID) (fp1 *domain.FleetList, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ListDisruptionBudgetFleets")

	fp1, s1 = _d.inner.ListDisruptionBudgetFleets(ctx, orgId)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) ListFleetRolloutDeviceSelection(ctx context.Context, orgId uuid.UUID) (fp1 *domain.FleetList, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ListFleetRolloutDeviceSelection")

	fp1, s1 = _d.inner.ListFleetRolloutDeviceSelection(ctx, orgId)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) ListFleets(ctx context.Context, orgId uuid.UUID, params domain.ListFleetsParams) (fp1 *domain.FleetList, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ListFleets")

	fp1, s1 = _d.inner.ListFleets(ctx, orgId, params)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) OverwriteFleetRepositoryRefs(ctx context.Context, orgId uuid.UUID, name string, repositoryNames ...string) (s1 domain.Status) {
	ctx, span := startSpan(ctx, "OverwriteFleetRepositoryRefs")

	s1 = _d.inner.OverwriteFleetRepositoryRefs(ctx, orgId, name, repositoryNames...)
	endSpan(span, s1)
	return s1
}

func (_d *TracedService) PatchFleet(ctx context.Context, orgId uuid.UUID, name string, patch domain.PatchRequest, enforceOwnership bool) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "PatchFleet")

	fp1, s1 = _d.inner.PatchFleet(ctx, orgId, name, patch, enforceOwnership)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) ReplaceFleet(ctx context.Context, orgId uuid.UUID, name string, fleet domain.Fleet, enforceOwnership bool) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ReplaceFleet")

	fp1, s1 = _d.inner.ReplaceFleet(ctx, orgId, name, fleet, enforceOwnership)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) ReplaceFleetStatus(ctx context.Context, orgId uuid.UUID, name string, fleet domain.Fleet) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ReplaceFleetStatus")

	fp1, s1 = _d.inner.ReplaceFleetStatus(ctx, orgId, name, fleet)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) StartFleetApplication(ctx context.Context, orgId uuid.UUID, name string, appName string) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "StartFleetApplication")

	fp1, s1 = _d.inner.StartFleetApplication(ctx, orgId, name, appName)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) StopFleetApplication(ctx context.Context, orgId uuid.UUID, name string, appName string) (fp1 *domain.Fleet, s1 domain.Status) {
	ctx, span := startSpan(ctx, "StopFleetApplication")

	fp1, s1 = _d.inner.StopFleetApplication(ctx, orgId, name, appName)
	endSpan(span, s1)
	return fp1, s1
}

func (_d *TracedService) UpdateFleetAnnotations(ctx context.Context, orgId uuid.UUID, name string, annotations map[string]string, deleteKeys []string) (s1 domain.Status) {
	ctx, span := startSpan(ctx, "UpdateFleetAnnotations")

	s1 = _d.inner.UpdateFleetAnnotations(ctx, orgId, name, annotations, deleteKeys)
	endSpan(span, s1)
	return s1
}

func (_d *TracedService) UpdateFleetConditions(ctx context.Context, orgId uuid.UUID, name string, conditions []domain.Condition) (s1 domain.Status) {
	ctx, span := startSpan(ctx, "UpdateFleetConditions")

	s1 = _d.inner.UpdateFleetConditions(ctx, orgId, name, conditions)
	endSpan(span, s1)
	return s1
}
