{{ if and .Values.remoteAccess.enabled (eq (include "flightctl.getServiceExposeMethod" .) "gateway") }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: flightctl-remote-access-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-remote-access
spec:
  parentRefs:
    - name: flightctl-gateway
      sectionName: api
  hostnames:
    - remote-access.{{ include "flightctl.getBaseDomain" . }}
  rules:
    - backendRefs:
      - name: flightctl-remote-access
        port: 3444
{{ end }}
