apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-remote-access
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-remote-access-agent
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "agent-api"
      port: 7444
      targetPort: 7444
  selector:
    flightctl.service: flightctl-remote-access
