{{ if eq (include "flightctl.getServiceExposeMethod" .) "gateway" }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: flightctl-remote-access-route-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-remote-access
spec:
  parentRefs:
    - name: flightctl-gateway
      sectionName: api
  hostnames:
    - agent-remote-access.{{ include "flightctl.getBaseDomain" . }}
  rules:
    - backendRefs:
      - name: flightctl-remote-access-agent
        port: 7444
{{ end }}
