{{- if .Values.remoteAccess.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-remote-access
  name: flightctl-remote-access
  namespace: {{ .Release.Namespace }}
{{- end }}
