apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-registry-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      upstream registry {
        server 127.0.0.1:5000;
      }

      server {
        listen 5002 ssl;
        ssl_certificate /certs/registry.crt;
        ssl_certificate_key /certs/registry.key;

        client_max_body_size 0;
        chunked_transfer_encoding on;

        # All requests require authentication
        location / {
          auth_basic "Private Registry";
          auth_basic_user_file /auth/htpasswd;
          proxy_pass https://registry;
          proxy_ssl_verify off;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
