apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: e2e-container-registry
  name: e2e-container-registry
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: "registry"
      port: 5000
      targetPort: 5000
      {{ if .Values.global.nodePorts.registry }}
      nodePort: {{ .Values.global.nodePorts.registry }}
      {{ end }}
    - name: "registry-auth"
      port: 5002
      targetPort: 5002
      {{ if .Values.global.nodePorts.privateRegistry }}
      nodePort: {{ .Values.global.nodePorts.privateRegistry }}
      {{ end }}
  selector:
    flightctl.service: e2e-container-registry
