// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H2Lctw2luiv4HK2yvaku/WyHUe3tmZlSbY1sWRFkp11It8xmkR3IyIBBgAltWddtf9w7xful9zCAUCC",
	"JNhv5zHl3aqJ3ACBA+Dg4LzPP6OYZzlnhCkZ7f8zkvGEZBj+jLkg/7jdGRKFd/7Bc8JwTv9xMJQ8LRQ5",
	"x2qiOyVExoLminIW7UcXJBdE6rEQZgjbvmhEU4JyrCaDqBflgudEKEpgkjw4ztWEVF/rLkhxhM04nCE1",
	"IUhOpSLZAJ1xRZCaYIUwmyJyT6WibGy63tE0RUOC+C0Rd4IqRZiGgNzjLE9JtB9t3WKxlfLxFs7zQcrH",
	"US9S01y3SCUoG0efP5e/8OEvJFbR517HxuT0HRES4G8u5+D8xLahhIwoIxKWcGt+Iwkyu474CKkJlUi4",
	"bcR6AP0zZsjMP0CXROgPkZzwIk1QzNktEQoJEvMxo5/K0aTeMz1NihWRClGmiGA4Rbc4LUgPYZagDE+R",
	"IHpcVDBvBOgiB+iUC4IoG/F9NFEql/tbW2OqBjfP5IDyrZhnWcGomm7FnClBh4XiQm4l5JakW5KO+1jE",
	"E6pIrApBtnBO+wAs04uSgyz5iyCSFyImEk6FFVm0/3NkNzbqRaOUjicqVqmerPo5+tA8pV5039ef92+x",
	"YDjTmPVzVB3Iu/LT6rcXbuwTHmo+znI11RPd98e838CJTgzIr6BjCJv1EOZ8CcJ5ntIYztZfOFxESaJe",
	"9GuBk5SoSE/EFKaMiKgXTUiaRb3oNlt4AwCew3JY+8MP5ehlj2oS+9MrM5f917ss+jBj1W4xehzClN4A",
	"nKZvRtH+z/+M/k2QUbQf/WWrojNbFkG3ggO+oClxI33urTDABUmxoreGROkRBPm1oIIkelOA3nxoXepF",
	"lndEpB7lUmEVOGTbilI6IvE0TgmSuiMacQG0MHzmomDMHKBUPM9JsvjZhsC6KIfr6HDpZllgvcfs9h0W",
	"hkrXaDapGnCSUN0Xp+e1Lq0bU9+sY3ZLBWcZYQrdYkHxMCXohkz7QHhQjqmQPUSZPhySoKTQwyBRMEUz",
	"MkD6Qt2QKZAw8wXB8QRlhVSa3A+JuiOEoR3osPtkD8UTLHCsiABK0zj7JUh8uTcnGR6TIzomUgXIPUNU",
	"tyNBRkQQFhMNSA/dTQhDN4zfsR6iSmrSrbEcJTAOogylPMYpkooLPCbtxzLpmPCwPpAlMwaG5qjoIRmM",
	"B0hO8O6Tp/t4GA8Gg0cD9CbTz2NiYIRXAz5yoElUMIB8EIXw09LIvryheZ/nBiP6OYc3J9pXoiCfexEA",
	"1Ib+pLlXElGlLwzBQmr4NTiCsITo++VdJCRzEg+Cb7Z/5c20H1Y45XMuArutf0UZznONk5TpG55hha6j",
	"CZdKN+6XVFv/6zoyW95D19Gz7Wfb+8+2r6NHdT7E/q4PHCv9TEf70f+5vk6+2df/82/tJS4Au+C3NCHi",
	"OZYkhDFZxhmq0MvQqTSt7a+eVLbREDPGDWuyDg04EEOqBBZTlBGFE6ww8gYeoLeSJCXTkk7RcAqIAKwG",
	"T1GeYkbcztY4hTsublKOE0DJRxajBWZSH5Q+s9YSEVYWwRAQmEgjEE7esHRqkDeAO7h67Zd+oRynYPak",
	"9qis8XB2PVWfP/SWeKuAAfV2qKfvY8YlcJiEqXSKJFHuNPSrtSUVFgol5JbGBB2cn8gBuiA46XOWTvdR",
	"DKeq6bL+LqGCxMocp55l+r+R7oYswzv3uqOEpPQWmix7i8eEqfaRfe5F+rXskC28UXWv8unY+Z///r/1",
	"BwOlnI17yKzxjqoJwigl+pIiLhArsiERhpm2tx4xju402ytzHJNB6O4KAsO9JIwIrIIiwyEvNOojymJB",
	"9DtJErfn9mtvw83zp1G3yV8ikCagP0n+CMdS7oa+2WMiWtTa3auV6LWleZc5ic17qbc0owwrLvQPlmob",
	"6dawxcvcMMtKezPWWPTlhrJf1QcDHn+ZcTSjXh/CCQ/LjGJFgvpAt8tB8q4Gx+fy0ZiewTUsD/ZzL+KM",
	"rErkAkewkpAQWPFK4wTPcaWRmie50iCNQ1iEzb+wQvhrmlGjA2rqdEw7SqGDfSRaUmydRYjzIkDTzt+a",
	"QTQ50WDJAXphmCdNowQFZn+I9cPPWeuZrrNM24Nvn4Roa0YyLqbtyU/hdzs/0HHHp6KCUbUGJLtPnmZr",
	"KY5aRzHrFGLOpBKYskWPIi3PdR2OooElKy1PsyOFDOtITBuoupCkbJzWnzGr9DNPni9AnwuSYyuHXOpn",
	"zvxZCcLHQnAR9aK3Rn6Jepr3zVOiSAKfGHnY/qU/WVoAN6D7gLQaPchabUGZ3TQ52FsN1WJaTf7qAnC4",
	"5YabYP0LnORbSURbLyAKdiDDDFchCeydk02N9hZ+bnGcTrM5JFriR4VmObTMT6XmZjTTAiPo0bBRpMIw",
	"+k5TBlrg8kmWAZUbekhH7t/DlDwaoCMywkWqSoWphQqripHRkEg93cMxMG1aIBGcq0eIjgAkzQTRESXJ",
	"TAE52o/e2p1YWG5e5aa942mRNeSJpghg9NAY+N8E3cIXeunAZ7Y1VvWjDrPWbxn9tSDIP2h/XHtCAYoV",
	"4JDjFNPsnKc0nq5Lu8xuXNSGbLKdsKAAz/nPdZgV0GyY2Wus6UpP+6mWCDY1GEDWOeKHhRiHwJctkmCO",
	"P0AUXlOjqPIvpu2sEYIqksnNnHtUXSAsBJ5Ga9yoiyZaJoZ0wAOtSU7U67hnE37nUZMJZkkKt8/ej1Lt",
	"xu9YU0UBIlzGbw1tcQ+fne/DCqohsxZD9me/xBuhCmctctBx5a0CMMT8ON2gpdAJyVM+JQl6c3jS15iR",
	"UqylVNAkcoH0azvCsUJDHN/o/Zw5d4gU+PCsIorKyyLLsJguyPPUFW+ym995RXCqJtOoFx2RscAJPOZt",
	"HueM+7Asz9PUwa8m7eziQdPZJ8DO1DsE2Zp6l+bCuo7iECuc8vGJItkFGc3QETTkltpnKxGg+syGoDYw",
	"rDHLwvgVGLpT/zrCqSQtnaunZgeLuoUEaXrbQzjlbGyEI2ufGNFxIbpkPPNtmOFzAwMvUPJSehpNz3Is",
	"NPUP0oF4ghkjadCsUolseYIVQbYvupvQeFKa+4FcKY5yc9Rl54JIQ2jxLaapZv6CAGggw4vyGRt/5/Ru",
	"kTS8nNtOpwB0i1OaOC8As0lxIYRRsoInQ2n+8GebT8Hcydi1VEAsjmn6mEf6ypBLOtZP0gX5tQgbn7q6",
	"Vm4M+qET9kewMyBJx4wkKK6+RSPBM1jr4UHA5FDzrliBKSg//9yLbihL2uv4nrJE4yZGZletZbFchHtG",
	"Lo4vr5DzXDDCi9lMb72Vl0aGp4iykRNzykUSlgCbb043pZorkMUQNCx2q7Q8MkCHpZ7WoHEyQCcMHeKM",
	"pIdYki/uowEGkr7eMjkI61uM8Walc3kDG3dKFNZDSUvQlie5XShoGeRIlrzOBsc2Y7b11yWqWUzz9siu",
	"cf1rWGq4ayj8o8B5TjT7wwuWIAySbD8WROMNOry86KGMJyQ1Wq2bYkgEI4pIRDngC87pwLuScnC7M5gJ",
	"QvuikvucmgfjksScJUFVFnxv7PqlhxMQQ6qmpVLLA0RPY6ysxnCwtxu17Qi9iNwrgWdZJEupooXFdQGh",
	"5a6gB0ZYmftDSq1CpShwewz0S+9zzvMixZ7V5uD8BEkgCnrvob9eOdZEJ8sK1XiOKsQQXYRXv0hDLMnT",
	"x33CYp6QBJ0fn1Z/f394+ZedbQ3OAJ1iFU+s2xlYzUtyTEma6FcG+/gwi6Ybwlc7kuFUkRBtACovzoJS",
	"wQlLDJJZw5LDCfONsagBNf61wCloVuD51fNmlL0mbKwm0f5OYNaCBqj725Oj3+DUPCAkHofk3rfwe6ku",
	"gueGgCR8Q6bIfOXthn3+qZRF/bmsCclz0dmp32YLZ7/BxjSIpcPtGqpsgDp2iLYVzuFcM4c43UoIozjd",
	"GmGaFsLYwYvyfsPSPdOu7DgMREeV92nAYcLrGr7Gdsg2V9SrdhNxzbWXB7HQBdQUmJaOGi2nIdtmRM/K",
	"dGtPZYC+19IYir2OgqAD2DqS9NARYVT/V+/QC0xTA9TqqpsSoqDKpsbgVutaHFvalsON+VvUnG1WUsgF",
	"/O7WHadDV7iuPrNLll7NfLqQmL6aipOllHVD++HzEpjj8HI9hCnHKdEkDzhMrTOwMbA3LosKu1O0vILK",
	"USpylxCFaWoMjZwRhPW7VToYWmHVOg8553X9MlyUXMLcPQ37p+lfK8KjJbICJBQ04mnK77Qs9n3Frugp",
	"fbEFvZXE+uro0wJVR6L5YfvsxsYdm7AiC9hLsVRXAjNpdpR2+RDpfpXPTQWrKr8liZH39M7Zh0VDwria",
	"EFGj31qw6+uxwhKWlEHHyVdFhhkSBCfwPth+iJpXTu+ROz885IWyEJfgBfkWPoRXPZnlm6RXP3AyzWBc",
	"9qz0PNVu3GFp/MXAll7kZlqfmX/6OMjMC4JlWG3ycCgoGT1CpkclL7g5H8iFVrqOTOim6pAB7dC9EC6V",
	"K6sOdnlCNF93X9uRHqAgH6ErUZAeegGqQfS28uh12mXdHvUi6ODpkxdTHzegs2M1fnVDN34uZ5q79I4Q",
	"CxteUSEe9ZUk3hId+xL1oqvz03dEgGxhVM6uwTA2sBGaq2l3jWMiJR2mpPkPR/jOsZDGrWDKYvjjnZZv",
	"dQ9NwAp1op+jsSBSo8nbPMHWPUA/Tq7raZEqmqfkzR0jQgJctzQmRyTmWUalpNw6DrxICVFHJFXY90Jw",
	"vRs/HzPB0zQjTL3i/GZR20D1leWxve1qtdV3q5NN94bo7FMeRWeP8ow6e9TBuSA5l1RxMQ2enD6wzobW",
	"8fqN5VHDcbhDhH+EDt0cj3f05gcfAcwvXwYNzM8tZJhx/0Z03DSerMFLvqQqMOZKnF7FCVySWBC1Kd5x",
	"U/C9UioPjTVrs9tOhf/awgp4FH2VeHzcaIoHORch/0w/HGVzvhMQ+hLQJAnfRXETDoVBX8LFOaK8cAOd",
	"cqapemkVLe9KfRcz021+pGZl4uHIfjRfoeWPHvQmWiGasb28GZRDcHZ8n+snJhxWIDhDpOzgYpc0D62h",
	"SIoUzFw0I3JwzfR22B5Uoo9/Rfb/P+6jPjqlrFBE7qOPf/2IMqtf3u4/+W6A+ugVL0SraXdPNx3hqd7e",
	"U87UpN5jp7+3o3sEm3Z2vY9/JOSmOfrTwTW7LHJ9S0iC9JFjxTUQfd1xv1SBYza1pj0bPKSHoQxNNMjl",
	"eOSWiCn89kjP+7H/cR9dYDauvtruP/sIG7eziw5ONZY8Qwenpnfv4z4CDyfXeae3s2t7SwUKs51dNUEZ",
	"7KH5ZuvjPrpUJK/A2nLfGGCaX1waN9n6Wp5VW6JFgGfeJ9fs2Pgs651D2/1nvZ2n/d09e6SDhYPMDgup",
	"eGb4hxM24rMsLk3ZDQxSJgY+QTEM5ILQ7KkE4Wjq0L1BKDMYCtpnEHPrjjOL0RFgjyqZt5KvlnCuOMdU",
	"oJgXTEn0MHZuuFuKK5w+snbvHDgwiMo0MWsDdE5EP9ef5hMsib5oWlhrAOT4Ro0KTKGcCCQVyXvge4r1",
	"v2PwKyNYqCHBaoAqbY4VMyWKsRDTynm2AaIFPaC9Lj2K29YDCH/SN/IXDqfhKQMgiNdmZhAE4VQQnEyR",
	"IiKjDKcLqgG0BP3WGL4D5JpWxgsQ+ZtLuhPUD2uzu7+46gVGmbXswni8tpYNdpuOGbsW29JxV47cBo4P",
	"i2NzTlhCWDzVMolhPS/IaCWsnjmW7+JRiw8bUTYmIheUVR4fQK2MT5FzzREPJCL3Ni9FUs4UwkGffT7r",
	"DOyreejUp7KBz7plTBXiAr26ujp3vexbr79/FCRB3orCU/tLthCU2+EivQ0IenqQ3RS6fHXQs7HY+iOA",
	"aMiTaQ99/0wiCeJMqU21fgVh+LyLcqAW0Vj68MYT/bQl6CEdkIHzsLSHUQJ/h6XzQXm06BVq222ax7gi",
	"Um8Al8MoLKcsngjO6Cdzn71tMnrwNr5SYt1lzavTQzHOVQFhkq244hBaX5BRiK8nom/a+yUK+2emmQg4",
	"Uevepmfoga61dCa2EaIGhDVlg9k0ZXUfa8NHLH2QdmGeg1k+mUoKOQsqp1kXo1V3IOtKLGP8wuzgUd21",
	"KcVDksLOjVIC0ZXO9bsMNI5GT3eT0fDx6EmyGyfD4Xd7e9/tPd0dPhntPBvtxmT36bPk2ydPH383TOJn",
	"29vbe6Ntsv1497td/C0ZPYv3YNO+ur19dXtb/Eo6heGa9gw70AoObR+Wu+atqLO2B/aG8iqQbEiSJMQ0",
	"/jghakJEKFLefeTcboacq9hEFXhIMOQ8JRiuFK3SwMi5iU1kO9KtkCCQgqMNFSY3TCMtjGznhXGZXRzP",
	"NarulzPJlpwHBOc/VHisGR4z4qOBl9aFL5r3Bf2oe5QzO3Yeu66CjHrub18CFWT0QNqGjWmn/PQ7ASWV",
	"fhZBgFrjNsD3espp9cSFXagaZlifBZ0f5oaTaQcnW8oYXjSj8XPX4pTZ/YWj6SADhJwlybg+yFmAu6KL",
	"A6baDcV9UolEAeFPNubzZISGKWY3vWBai4K5+E8QZ2FM+4OJsmrGam48NLMXSfopgBHH97lJXGWk0ITf",
	"sZTjBOnewSQrjoejDJ0cH0JAurTCwnW0+/jJYA+d0ufXUQ9dRzvopf7zkRbxs7zQ07htKDIXTOQIuL2w",
	"oF/Qs0v0UMujTKFvEDMuht+4uLtHPVRI4zWQKoxyPK2ArodNaFoyKtK0HN3rCc4Nd1Q/0QdDyB0C3zJu",
	"O5ebQWUFJeRImzahhvFmpZ5a79ULR6Z/7nUHLVbmdduljIxrHuiGYxhncNnByDVNVbxr36s8Esp3sbd8",
	"ppXWG14PzQrp+6Tp4K7/BALJGnGfgWi3OktArZJxJtn19YDG7cVxriAk1VI4fDHHkNkBgB1uIkvu/yHO",
	"8ZCmtGSYFheb/E81225U5daj1wqLZd6e+hlwecqT1biyN/BpuQNLrRXEzC70OvT8zyqvF7sOIzq3F+I4",
	"o85krReOdXKBWV3jznNtrs/zYemVS54G80x6zU3lRWx/jjljJLZ+MOW9aG+GNGagk6Pw622b0cmR72XV",
	"mCF8h8yXp56U1CANJdaWs5Rp4CxXo+G2jvH/XssLGWPmh/lRRhXFqX4slJ9p1SqaeyXMirvPeoiozsyB",
	"9XRVtQvbWFXP28Alz9f33gglq3EZ8cCi4TRLKKn7fJSe2q2DVViMiVqL/a1muoLBwr6lZp41Fu8N3n5v",
	"yygJcwFN1rrmJmRETXhSv6a+x9dbRsDLBfy5YsXF9ILIGtCzHJ9mQeyNPKtbfdZ5W9MQO5aj8BdEFmmp",
	"f/bS9lmmDnK7IawUyXJVsaJOhQggt7FphNN0iOObiw6fzEtf6ehPasct5yNpCiH5RmDFFiiT29vjJ4s0",
	"LblHyK9iO95h6cYyTKM5cN0kizgmJCHJAB2mBAtfpGXkvg2KW7pZs8nvF1b1zOHx7fzAq9bY9+/p855m",
	"23uaYe9pcK/o80d1thjYdsvmMq7QlCjUxewu+XY2XLu6HtGqG5rofn7a4k6OTDKcywlfjcDUAbt0Qy27",
	"vhMtgAqqpocTEt90La+7b0vxX+MiqPsCxfoTlBOh3yMTObkis9oPMquV0bo5p4Fo0zxq945skEntHH6O",
	"y/IS216Rd5c04i2Tzv/D990tfT+XIfihBVQzzerjw9Ddr4Suu0sF94J73ekVboWwLgxvvZyNrNNmloQw",
	"RdV0wzgHWtRl5bvqyoBsV61kjmSne5e7GvQmkApnec2loBr8Fr6s5PvFXAg2d1NtnjZzmE5XofJs4yey",
	"WQrQBnthGtDJ0nnu3OVFCtOBle584/71wu1dV3gOsWjTiTn3+7XL0rySHFzmeN6AXqXpX9VIIP2l3qrG",
	"BmzwmQqN3IWdfgWP0N623yPD6FgUaTrr+78siacNqJuY1miuQRFoD4E2p9t8nH0j2364qzlfvxGhhEot",
	"52jgwk/CBQbeuKxBE8rUPuSiqSVBsqKRyxnWyjL/QPoOXoLEXCTShdkRsHUPiZdSUo8qICX3RxBoPjr7",
	"HJUWcx7I0lJnrItOKEg4MYIAzbSgVko+NhvQ//z3//PxjzLng6LSKUqojDlY32PMEgriTn1pzqYAv0qU",
	"F8OUyonN7WbdMcEni98xdHjyCAkyxiJJiZRleCckjDAx31oslEaeq0Q4LbyZ3OEguTGjwZfd+QDmhaUe",
	"UzDXesGbbw5PmgU2QLzCs7JbNfIsGRWSIJKnt0aNhFl94EE0F8VXocdvLgOEOIy37+oKyDeXLVO0l7Rq",
	"VkGSKz19rTaIG6tRDWQbioF0sU6bN6kGK3XUF7MkRS8DspY6mzKqYR4vbPNar7gBdeDKEhBU3mx80CoN",
	"9gaHbXrz5UVUzmTXsdZxzQ7KkLWoDHOA9dJhVZ7CH7Gwj9mhoIrGOA2kSVzmza0D6mdhbLdWk4daPYBC",
	"zQ7IUNvcKFnPI6hDE3JpijXohiFkn+nCdN9At1j6VueluMEgpHq0VcvPw9hiuqFreADLtdOTtMMBQzBJ",
	"npIOf4jU7Vus6G1lTbFmhLVdNH3LUTCrVZ3V24x5ANIGrAOxZRab0WXNckHCxP6UFMDGWtXTVK65hY1o",
	"q9AmGheWZEnF/FXp/JJA3iQK/mC1yLJGnBpW8eTcVIMKmtYdKkFHZOtG1ZffssYbH3wHR8GoAnelni2I",
	"YJKoaxlPFqMRvbdclZyQNO1LNU0JGqd86CYD+GF2PMaUST99ZcpxQswUAFOG713Ort0nT2t1rn7e7n+H",
	"+58O+j/tX1/3/zG4hv/7+fr6w/+6vu5fX//1+vpvH755+B+L9Xv0t4fX14OfTcdQc7Ca1nznZWM/WCMh",
	"uRfvbYcpc8Mu82Ku6PheferrvcPCvfQyQNvnAdlvtayjBKapcbOKVQF+iTb/y7qviXNB8GsBeM/8upSx",
	"7X0auN647cKxmSkbzjL6lBueHKsSfH+YxZN+lWhg8o6D15/zx9FHGczw45/wF0n05T/qqz+AldMIvHq1",
	"ULoVRw7FB8LgfljEBiIrqqFJIzfD6jsSNgWC5t0qJTenn3bC4iUhbJEwJHvnTZ4gwsrCcuaNRA/P3lwd",
	"77tgOhsoao2lgqhCsFpOwkUDk6yH5y+Ssz4dMy5I6dJZKvU2p7HcBIdUDrReBH5QStZczdqkrkXeDJvh",
	"IoRXHbUapDbk5drRDs2h6qxd+IGqcU6beZoMHMlbRlX3o1RUEbBr8R1Jh+LFezJq51Z/DqPw6+ijpE9S",
	"SlIOyF8tokI2/7ItqThY3fPUIzoTLJI7CE5mLmMAZWPnpF6rTr55j1QLg0sM98V8UgP7tUELylJlLsLG",
	"vDeQbCdc0eKCDDm3+ZHO+R0RJHkzGtWsfQd3mCpI9mR9Ek12sVFKY3WOC7mkcaW2IA+0VpsHbaC1rsap",
	"NflrCjTXlhlob5p7ao2hzQh0a+7PnDOuEfLFUj2UNhd7mbzk2eQ+57J6tY3D8TU7xvEEkiDHXAgic84S",
	"adX4TsA3t8qG35bc83RwzeYnjTCLqF3KmKep8eEq46c65RcNZKfLsOZqDiDkxBoZgnfYDznsGMPr0eGf",
	"HRxZ41PIh/c55wqdHC07VNy5UGeR8Af8aKLk+n279o91DzcbQ2etWkwqnKaV854zysQ8y4xJiaZhK7Kx",
	"Tq3MTbSSljjB4DilY8j0NiNQsLTbgd0o5kwWGQFrkbGkDSCxolfEKaZ9Y3kbUqYfIZMJQm/KwGRfNH2p",
	"shvTqL+OGeJpQoSNYyqNgmbbbfQ+SZNwUCKPKYgry51iBXPXSVY91j/N8rE11zJ8Hd6UL/Kle5EXxONm",
	"CKt/88rr0oaiV7/nyz6FAeZ0CR1N/ZmUneQKtCLWWjXHS9MyqBvkksmmhIVq3LrY0GRKSk6xXMyap7J8",
	"0Iy37XYE2PdhQVPVpybnvU1l5B9XJ/NYp2Rdz+mKggQstCHbtfNKlLVkG0uDhdm1lD4GtfiR1tbLhZiD",
	"32815TG1b1RgPU3080Uh79xWx8Gm2LJM8a7xWJAxVqQp28ymFUby6aIO6x7OFxIrWmryObEhOfSEA88w",
	"w2MTxgoIbMRO2UOUxWmR6BZ4zuzvXrVZF5pKErjTtipCwCHW9rs0GfNWUxSZFZZDlEL+Rgf9vMquJyv5",
	"tRjoN+pk6IvJLkLlC4vJtR3YOD4nq7kZVltb+hjmV/wIQ82PN4V6M7J/e8mEV/FxqAHpTRFo9WcNftzI",
	"alxvnevGQOXN3LSem8mk2fuD5QcNEjlrCwPqZgYA+kbljakY1L51OVaTLj8wQSAcDek+HvAwfH3M2WuB",
	"OQJ1JTpPtZhVUCDD9zQrsqomGE5TfuenoTDPmeJllr8BggW5DypCXhbjRhgyQ3FNMm6tZzkRtoiE83sE",
	"U0TBqBqgKn9o+SMUvdlHH6VJxSlNVbMe+piZH0x2Tf3DxPwAeUThRCoT98O/7f+80//uw/V18tdHf7u+",
	"Tn6W2eTDvy2ccvOYxVy/XIuESRLb1yAqBMnCyWKFK5tfyf84ipKnpnqxKSi2cFJ4M9W5/dj9+7kdpHs5",
	"vj3qgigx9Usq1wMalUbV6nnHDJF6yJrFjPYlGOL4ho9GRyTF01AxKAgbRraXFuXxtMKmMvuGhFwbfo14",
	"82NYfWIG61rNczuXVAIrMp6Ws5B7Q8IoTgPT1Vo7EqTiBFSVbUXcLaRAQa6H2URIEaJ31sZDVtlGdraz",
	"AATwazgRFr4/sGME4pjtpWZemhl/1vo0T3qaCqDdbeswoj+N9ne3oeKb+cdOKP9Mhu/txnZDUJ5y63xD",
	"y90Nr3ZhdqojxDGQIcoV92Kc9W26x5jnwNrXBzm3V4CSNJG1DIOulll3jkEleHqeYkYO4g6/gLPa9Dah",
	"of2yD07w9pZ5udzspQxBsLo5LLxzBu6QZcwWblvDL+eFP0KQ5avP8WE9JLBLmXMCgAABUgcJQi29Q8f3",
	"WqAhEuFCTbaGBAsirvgNYSEuPCH3AeIg6JgynLrHFbq5/AvmfDtSPulrvIED9mm/Pl2aEV6ocGyeFgta",
	"13dvG+hzsASjSMOsht7ES/T24jUwEzhN5/M6Zv/MmCsgQGfx5FaXGUWTy0vGLVrUVH+r5bpsg1hPbWgz",
	"W+7sJU/3dpNnT/e+3YsxJgl++jjBj7ef7I6+e/LtCONvH++O4m+3n2xv7z799vGzYfztd9tPn8TPnu18",
	"l+wMt/00h7EU0X7U1//3/PjlyRk6PL64OnlxcnhwdYwujn94e3x5Ba3X7PTk5PnzXw6fix9Onh8cPX99",
	"+vbm7uLu/dG7H344Ot4+uD/d/WH39NPfb94cvf909unsl/c/vkh/enm8e/byYnJ2dLBzzU6z90/OrpLs",
	"/Y/He2dHf8/ef4rvzq4O7k5/eb93djSh7z/FT06P3u+8/zR+fHqV3pz+eHJ3+uLm7vju/avv+U8n1+zT",
	"L9uHBz+8P9H/+vTL9tHBD/HRD+OD41fPTw/3ts8u/n71972zH9+khH73/seb56dbp5/42dHL6enF98Wn",
	"4+2taxZ/fzP9z3d/J/evft2+P2G7u+8Pz872fjo6u7+/+/Hp6/SH8R795SW7vVQ/vBk+PTg4PeAvDw9/",
	"fXl5+vi75wenh9fsYHt8cHr89vDkh6NLcU+f3ojk8Pv49eEkOX2+d/ftya/ZUfrT5OL45fDV6eHx5Tv2",
	"VMrzg5PxT6+/+UH8Xd1ds2cX34jHOcXvb3+6UULe7E0PT4pPe5OTb1P+PvvP873k2b9fM9j247OjGUfy",
	"NUnp1ySlK9L7zdXkbo/5G9Ti7qiAFcoP39m1qqwY1niVNN5ztfR5gM58P9iV0ppR8/bOS3zqHpYJlmhI",
	"CENugLBJscp+3KXgn2N9fw0D6KcLqh3XcjmgEy0W5CmOie2mLyNYSR/aJMuPesiAALkvMyLGJLEFHseE",
	"KZcgO3G9vKvc2rvgdJDryZ8D5GbssmoZfQMaUZOvSiHwGdRUJzh/Rx1vb05zTiaBdJfZCZjv6tjaG8CF",
	"WwiUUgdwLALBKr/sHi67ZaBSD84EBTHACTOIfq1LbVF9/ZvrmWFWVyt204W2Pm8OJPPIg+eYvy6h6KoR",
	"AHovrGymWZ9UQPIlj0oslv7CffF8Or9gg+27gBrVG7XnL2mBKrfzjmCF6IjAxlcXcXGsDNu5gt0ML+R1",
	"NOC0+j7w81uFrDPAjIfO5fz4tA+aRJKg8+8PL/+ys12reC5NhUUf0QJPQD1gZc285L0IzAYX8xI4XvmV",
	"N8JJHIG22Xxyg1+kliddit+u8Oc1H8ADV+bf0ryyVK5zdL+jWqCD9GxQhr3yObKuQtJHMypDL3ZFBzeU",
	"rlOjixc9sNJ45/4IJj9d2/9YijXI+fzUZrWOy13x1iBdNNUwgpt7Prw4oerezb+s+mKSxL+rHZW9ZgQJ",
	"tet6k/A+/FFr/bd1eoFwaJMglGgGeIJvKRfW+c43KlQubM5Q8jzl8Y1xMVaUFWRBU0kNIjdG7cdqwM5V",
	"0ZQcmuIAYTxwlQMAcUc07dAGd34PRiCkyL1CD99eveg/e6R5TGMSKhHMm8Q4IqadGKb7OZvQipfDs3st",
	"rn7XG9Wdela3lslm2zs0FrzIu0o8pZAMRvfoeVZGYlOU6EfZMDQCsSIjgsbo5KhpXBCcq5B5YfGs85ml",
	"7Z0Q5hq1bVZdnpABes8LUHcYmKc2UacgaIQzmlIsEI+hYBrIAyglGEyIn4jgrrTg9tPHjwEfsOE9YprZ",
	"D0yK2tA3j3e3Hw3QJVEFTbYkUWP9H0XjmykaWtMqKvNggVTBuKo21uT9bywGlKF6nfqBrPZVgxfWVReS",
	"iJm7xe8YEV/0PFcpLrAUtm/APcKnLitVKq3dutVK+Q4lTwtFzrGawAgtd4OSrCzjeBAuNd2qPDOm6oKM",
	"uvjJWmKhl1DBzUs7AGwcEcs4Yjj3C69UnTW8VBXKO6p5uOb5IlU1VKkWDY5ppIQLcktn8dSmVQNdSFIp",
	"CGbC20qLXgLfmrXX5VLSVXllTsW/+dDYC2lPfmH24hVJs9+mNPe/SOlqYINyHHe5VBkZtewVKj2DEpKn",
	"fJrZ6gSluSvKpn2c5/1qigB6g7lghvhmUr23FHDe/TYjBGviOK8h/ZwNqRJY0HTqqqtIJQrQ38uGka7M",
	"+eVf54iNKbuHmzGO9qOdwe6OCdOG4q+6N2F4mGrkNSBPOFSe+vmf8Fe072YYxDyz98k0GzoUbdkfDU8c",
	"nQsyovf6yD5YDSWN8SEvNIO414usbOqKj0f7z7bLzT1MC6mIODkP82Vmv/STMCPfg9tUeMw1YQXx16oy",
	"vfNGMI6te5Ri8OWCpfl+upp6YpMkRiREoCEZcaOVFJXG0cxYO4qfLay6U1IY0/oUZ2nkFtHnt0QImhA5",
	"mGZg/i3Fnvl5RNrpzT6sXu38lVL5Ii/ZRKl8waeM+VVQ5z1m+qDOgw+a/tU9X2WKQ93dOacr7qkUnQjR",
	"DOAHUCS5JcJz5rsTVCnC1n4KRfspdC8Zrkp/ohmPpEmKE1q8KMUh8CqADIM80yg7UtbioqUo3TpAJyb9",
	"oHFHJ+jXgoAzpsCZFkklkkU8QVjuo+toS2P5luJbziT5N+j979C7y0Wp87ktj++3f2EdRi6M6jNfr4CX",
	"YB2nq0SOWl5xiT1BuFF4HEpxvbHsoe6FyLQobZN7XhLlULyWWNQpHKB4gZSjIrWjtdKNugSgZRkWo6Lp",
	"K963j6fN7zjHQb5aqJyzUjOXfcVgHRI20FW29p9mm0TSajJtZ02OwQ7EJbyXPTgVUzjL9nk0QBD1S5gS",
	"U0Qhwzj4sWLHEjTSfAK9tyvVf8KjD7rRximUX6ynpTJ1BvXQrygLlhrsSN25PELO8T/qeDpm3Z4K7iXj",
	"jOxmTqri3T4aOCzArFnwbPE7VdueqohH4xJRWZt4huAyK/FpvZymI2Q+fs0YuAP+q8YIPk0wmntXbAW8",
	"svn8A/ana6zKv7VLosCpZuVMCbnZBNT0MSJdhauZ/tw4mVbKEf0kzUhhu9ods2Xu4O0FzxXDg64wnBkJ",
	"Ft6ZX9aMvtxWBvNQ1wS/zT5JX4iwrKF9mg1KMNlyQP9c28TVTAeBfOB/yjzSgFfnRZr64QLWJyQ6GZ1x",
	"dW7sVFGv46WuqyIf+N88sBV7JVHQdpDe4al8YFSqZRnfvID4fc1yT433dv2rM91S+ygr9Ntrq/8CV9Jd",
	"msXMGfWai4FRFzSc6P0px9H/aIylf7LjzdznMBVkxiu/HqIFxOHzF6VwG3jeawMGzFsuxS9INkbcMT7l",
	"bw5P+uCfQ7HLP+8TjwE6vsexSqeIM/jkQXkbHuh+D+pX+IHBCD/q6je79b0or92e1U7Gu4FwLHaxC9He",
	"WRtpOGBBxlQqMR2gK80ZuGIBVVVn70PGjYOejTDUZMQN1tNCasrZWP/Xap+5yKRjoCqSI/2YwY0+AB3I",
	"CDmSZohq1QvZxSAuJYuUK5UVma5q8FKApq6f+zIyxheXLFg4oKvK/OuLYJbL3Vjq7coSNEenZaBcQ6ll",
	"8GcRtdb8HSk1ibEg4LvQfJlW35vSyhY4qi+rO+nc4o4N/b4YEsGIIvIS4olmb+qmYO9FJnppURNaBSUy",
	"H/5JLfEFUyuqRGteljb0q1J7WtkruNOLnVm1rcEBZthjKkPM/KH+vNb1wFXzjUjV0X6YlybGfl1dgIXv",
	"6ikUz5ib6+APlaJgM4kXOrn1hXUWZzgjiVMowmnVzRh6qQH+3vLaLf7+y6gcllQ1eEE3bZaobNOSW1kt",
	"G+RQnKYo14IpsEhVORvgzSf4lvQsrbFWBwlfGGAk2MhsX/NwBnwcGeOqyt++ohds1RkkzHqu56AjK8BD",
	"OSuLM85wWzd5zCHc6w5Lu5QlfNUTkpJV5qJpCumD9OfLzDeu5SRv+wv/WsBzaYPna8FunhbDsxWUTs6m",
	"ULbx+UbnPC9S7KXNM+/PAF0QnPQ5S6c1kClTTx8HHanmO0F7VR6e7s1NyXmKodSmDem7IVNjz7VWYV+/",
	"4kq9czHGjH4yPHqMFRlzof/5UMY8N79KkpJYPXK4HUSqxd5P079VvCK0LnjjQofoxSJipZ9CacQU93tP",
	"cwjXEJu2pee+jpA5iA5zp/mq0/X9gCGe418L4jYVpvWEHnfdoMpbmUrVc5LHzFv3qukPPBfyNhW7NBm6",
	"CPixG+/Ea0OUr6OyqJ4sq5RJ2z1BtxTbbKJcIJFnfS6VIE4vZdN56cFyHN80h2Pc9OsPscalOhRUInyL",
	"aeqK1Dn9ldMX2wEX1FiZ1TtVvvnXuRuha8vOsYonXph4KajMNNzUaTTvIFg2zaXx3LIVlf1l4iSJyvg0",
	"+Cvjt0Cx6gXYKkQMe7UdoL9fvjlD54bRKg0FYW+cMKgmrlcLCIkf3zZovas8n+Uu1q4pMS8wwaRlsOEJ",
	"Ac2PK6uPXREdck/iQhPVXJB+OCNNz8W7OQLcflbJPVWHQW/ec8FjIiXSPVAMfq/O366R9KZNqHmh8iK4",
	"jATHxisp4YXakiohQnjVKV1mCXjmuMKpKU6PY8GlYRlcFhAKOUhyYxx6/D19PkBG2iwrEaGH58enaJjy",
	"+Eb20HPITqE3a0TvieyZKvdI8RvCEGG3RuZ4ZH18LJjWhccxNqzLL6NDB3rueVjCniVkRBncJvT+4LR0",
	"1DCKuMTfAvRwxAWyPkJoi6h4q0yksAV18gfJlgHPnD1l462d7T4j6o6LG3AgejSf17aQ9yo8WJhTDIXV",
	"zMDbEJYaFF4MUXFX5phzIvp2zwTMBpb/cmjjjLWe6qX7oobKcxlfiu50zsAqt3dDljGrNiq2unjbC0Sl",
	"umkXPr8fCpykRP02bqTrDHbMbt9hIdceR4voaw8SkAv/rG6yqww9W9f++cPiWtcL60cZ1l1d1JPQWJdL",
	"UF6Fzf9dDEH7W6eTdULIGVeWO8bMGhQ14wr9nWTFb4nw3AAr318p4i1IzTP4Ra7BrzoFxUFKhLqwyVfz",
	"7uoG7XVOigyzfpnPtBGZCx7DeuywT1ZnXkSXMREyFDjJU2+GpzjEt0QA/yutSddU8qpeT5iYsvEAvQDJ",
	"Yn92PsQH8kE90eGD7EE90eGDyYPORIfX18k33bkNcyJiwlSnS03VrnfNrMgEygo6HhMhgztp5GOjgb4l",
	"K1ezqiHBpR0pnALWTeOdXW1xdUH3w0poWIOgnfLRtrawy/H0wQK4jdzVs4SYTliqgTu7eDN29jGgzNsJ",
	"V4ZTr5/q9WeUYftDhvPcxhUenr9djkLnRUgn2YuOoBTzMhHqHZlqe9GpLcC8xGDdyuBKWTk9Mxm5fC2t",
	"5vhXfwA7NmOl92nWClaJ/+/YXf3MdaqsF8SpmVnFwwl3cS2GqsEfu6djVula6ISE7jVAb5h1sTC/5kQg",
	"R1hAIWFI8mbK2VYPW4hj1q8pZeMTLbUH8xmV79CQqDtCWJkyGD7Vi/kNnpYygW7X+zLDjtHzzyew4oVJ",
	"dFeqAZtZgBp+SRXCRgyZggo4dRkfEs4euLgHZLw9PEXlF8yrFgeVDJfFeGy8KiD0wsIVuyhbEIhNMoQe",
	"2kbUhucaS6CvMN7bDeohviZz22gyNymDnNMi3Kefsl/vo9MIdqiZsQyzuRmOJ5SRzqnuJtPGBAh8cgCG",
	"a5fv4Dqy8Jg8Urq/QQEqEclyBVYKQUyZoXqKjlJLiw7QBYCJ4hQL69Fjg5mkS6aUEDQsvPpJLpALUTWn",
	"fMCs0jzV5qE34CG3j66jSyP/X0eIC3+lXxxtZE7iPmZJ327pArmT2knx7MItmSgxoEK6xQlkuG7LmiV3",
	"bBhCrX55oNhOm4amWKqrMiTminbZfeo1aduVZNzFcaVmJpiNlzH1dV7eRiEM28862pgwSIVpKv3sNAaG",
	"6rx989TT7c2WxQif56zKGL3Qpq+JP2Eh6LBZ5KamoJ+JJU5MegXfTb2Kk8sVzgiDW40abndzhVvnlseY",
	"VX6nTbTLqkH1EqgziwaFtyhQn3Pl3fIBD25XR6nNjh6BHQ3VzJyzpclBrJlX/Q3p9q6Z0PGkn2oCbeoA",
	"Y/1RVa2+hl/QZihqyiE/Cjj0lT+PME1hXW4Q6JCQ2j8zrHkqhpm1zo0EkRPTVKyw//4qDxwg7aYLD+J2",
	"60m1hnbjC7eqjgndwtrNR/WVtzuc1vYiBLW3O+3mRRHhGMLs5yCCicWvp8kCjHA5kRwWuKD9nvurLwpm",
	"n4qUshtoMn94LTilWMLxS9PD/OH10DPTWCMMlW4GykyFl6j0L4GfTVyoCZkY4sRDnV60HPZ4W3Ncrquz",
	"7aIEtt3ltVt6V9Osjw/s7rRbTt1+dTXNGvbSbWm76aja5HbjSbXt7caX3kEEEMw7mnbrcxz+qioDHNh7",
	"zUTPxfHXHCdzMFxTgAXwW6piqDGYWyLNuOqPeAGs5RAnfUmUvdDE0mmTftZH7pUoWbmESwNB8+fXvPZs",
	"VA1nXL2wADabnuPksoS32Vh/Z6rfT916Wg0NZCwbFqVEXmH4llECV4RtndrzzVev6agVfAS7RU4Xow4l",
	"lWrmmjc5YZeXr6wHEkowyYyU4TGw24+fBThYUiH3OittkvXPBmnXHrd+lcAKPSwHDV2rO8NA9GCTrLey",
	"c+irmIhy40TBmOMFKg+7x3X9GO5/2u5/1//wTdD2oicKQwNXGhzfbNa260jKSTKwbpm2vIZndPMa50qb",
	"MG0dn+qn6Z9Ar4bR3i4uLD5oYeMn7oJEXCzla26sEe2aIugTZ6RykBPSKiwBgU8Ozg6sOx46uDg+2Hr9",
	"5vDg6uTNWQ/dgYJC/1gv2BFDEkdIjygQjwlmPfBKdF+WbvBQlwwLReMixQJJqkiVXgErhAXBPeQ7oRyA",
	"hzzeOiN3/3jPxU0PHReaGmydY0GdPrlgOBvSccELifb68QQLHEMGErfWRs499PA6enl6dR3pU397ddhV",
	"S2WRapOBGMQR5NcEccP2MpJ8obiWOeKy5Cao11kSKtapaOZanS8/snViAjrT1Ty4DwVnx/f6HJ2+VCos",
	"1EuBY+KXrVveguE+tsVtHG4uPVCJ2C11joqC0C58Zd5lf3wflNJ3pOF1UAxTKifnXKgZWaYmXEKilDEk",
	"5oYK6tZ2WOVTeXdaCxMEV3iPElgicA1ZtvR0+zCY/stp/NotW7ngisc8vY7KckXPtp9t7z/bdh/Zf26p",
	"OLc3r7T1+JR9u//dh2/2zX8ebj1Ucf5fRZL/l4xV/ujR34LkvhW0147j+EM5zSzi2dLURr87RXdc3ACT",
	"6pyErYv7C3DWO1Sp8WwzHo3vTn0PQBuJm5CU3kKqcC8uyQvh3yrDeU3q03aAaRl7iV5w4dpdpJy0OUyN",
	"/6+NsTAehzYI7h0VCun/KXB6avTrxjsRXGCYCXLJwKMwHCExLySlXROvHStjFawmmGZR9x4zTu7FuVVB",
	"zeBCZ58ZGNzQ7nrqtQgcKyHn3ZYGZ5DsC75q3dHPEDNrig0DHDEsnWSYptF+pAjO/sMvhhW5OABgggzC",
	"IFt1A10RnNlyX/uRU9vXvm5FM/xcH+LDw9Bnj6zhy6ZKgsKcJE6xMF5Snk86H6FRSogC3TNJxi6I0MRI",
	"qAmhosR+ObhmoEGICZPEq9t1kON4QtDuYLu1mLu7uwGG5gEX4y37rdx6fXJ4fHZ53N8dbA8mKkvNy6Xg",
	"uBqbdHB+EvWi27LUmKsu9rkXWTyM9qO9wfZgp0pF+M9oy0tNbqsIODucSTQYSuRzaOJ5MTqsPr40H1eF",
	"0yr1bmmiOUnKjzu/jAx6Eame82TaSJLt3fOtX6xVzBCy1RiNTiA+19HcxpcKInOuz0XPtru987tCFzqS",
	"RJ/24+3tLwtYWd+pBcVznKASSA3Jzu8FyVuGCzWBeCS7KXu/FygvuBjSJCHMwPHd7wWHaTnkbJRS81g9",
	"3v3dgLniHJ1iNnXoAqUVnvx+h3Rp3oC3rDRqGz4Nj0HD1Uklow+62wwquvVPTf0/QwQ9CQYF4MTIZGVI",
	"dufFbxPTl0TNoqRVHstATqxmhN18Yo4UR2Pjb0L1CDYJuH3ebNx1nWr2vONqahILRn8tyInhsU0c+IcW",
	"kd3+AxHZN99/pWodVO3x7wVHqTv+Ss82SM8sd7sQ8cLIVIaawfPpfqbTskSpMbSmQILgZDMk6HegN3YX",
	"/hzE5fe81OgPequ9S2QuSfDGbLmSZ51X5yVRNhG2rY2WzLtEL4ly1dbWukvmEa9PLpue1pu6YL1O/y4T",
	"cirq9ePKaSGzdjVvsNbcn+pi75rb1MRz5KX2+nr323f/9xOX/riC0oIkqPIzzLGKwzmxXL4rr8Te3Mcc",
	"PqsVg1z/TQcIN/qoL6pC6sPU32zgDGtJIxZSIP3uvMZXRdFXkepPxX39EWQq1CVUlcS4FwUTfhgL/fIE",
	"98KkXdkwyTXG/d+F5m6Qrn0lsX9GEvuVtC3O1VWZURY3zLF2geC5FrnWF7+lJa49+R/BAtcB1VfL21fL",
	"27+IKPmH5qdalK+TIs7TU78kalmi+JKoEEVciuvqnm+jlrTfQdu1EGX8ai77Ktv9S9Oiz6YoqyMGxqVr",
	"C+d063bH1FwwX7fLaVhKIxFnTdkMnPIsIbCMYFuLXh+hm874g7WX8PnD5/8fAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
