// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3LcNrbgr2A5t8r2THdLspOso6pbuYr8iDaWpatHUve6tTGaPN2NiAQYAJTcSalq",
	"/2H/cL9kCy8SJMFu9sNxZkozVXGLeB0cHBwcnBf+iGKW5YwClSI6/CMS8RwyrH/GjMMvdwcTkPjgF5YD",
	"xTn55WgiWFpIOMdyriolIGJOckkYjQ6jC8g5CNUXwhRhWxdNSQoox3I+igZRzlkOXBLQg+TBfq7mULVW",
	"VZBkCJt+GEVyDkgshIRshN4zCUjOsUSYLhB8IkISOjNV70maogkgdgf8nhMpgSoI4BPO8hSiw2jvDvO9",
	"lM32cJ6PUjaLBpFc5KpESE7oLHp4KL+wya8Qy+hh0IGYPL/SFUNzUV0gNtWA4zxPSYxVqQaGFll0+MEs",
	"g4BoEP1W4CQFGamBqMSEAo8G0RzSLLppwjeIPg1VD8M7zCnOFE4/RBaU47JH++E/y47LGlX/9tMPepgl",
	"k3Swq7ZApZovTtOzaXT44Y/o3zhMo8Pob3sVUe1ZitoLdviGpOB6ehhs0MEFpFiSO0OPqgcOvxWEQ6IQ",
	"oYnrprWCfab3mt79hLkh0RrBQlWAk4Soujg9r1VpkNCgQRCv6R3hjGZAJbrDnOBJCugWFsM7nBaK3AkX",
	"A0SoAhYSlBSqG8QLKkkGI6To6RYWCNMEmRaA4znKCiEVrU9A3gNQdKArPP/6BYrnmONYAhejqIWLdejb",
	"4eaccdmmc/UVZTjPFbSEoinjGZZoHM2ZkKrwsCRn9dc4Qk9hNBsN0Dh6uf9y//Dl/jh6Vt+e9rtiGlhK",
	"4GqY/z0eJ/84VP/5t/Zu7QE7Z3ckAf49FoG9esyyjFFUrbiaBcJp6u9avZtFm5XhigOsTcaOezwMIrWN",
	"OziiB4OqVa75wf/7P/+3vtIoZXQ2QEJiLtE9kXOEUQoKh4hxRItsAnygKcQuCqIM3c+JBJHjGEZBRuhv",
	"LTfZm03ox67BZQ6xnilRM80IxZJx9cFSkTmEDBPrQKblcV7nNbbZ2cpWqLfTLLajieKL9dqOTXc0sMzW",
	"b/NQUszivV7kEosPg4hR2JSJBpCwES8NgrwRPAH0btRTE+u9WPcFCFbwGN6RjBihpimkmHKU6gp6iwcO",
	"5vrmjvMiwC7Or00nit8psMQIvTFsj4PaOJqBT7CARIktTR5SZ3b7o//5dYijZZAxvmgPfqq/2/H1Fme5",
	"OY1QQYncApLnX3+TbScJNZdi2SrEjArJMaF9lyIt13UTNttBJRtN71JiWYiw2GfKlNCHkSB0ltb5t5Vi",
	"E7gjht06OfCcQ46tbHep2Lf5eVFQan695pwpge2a3lJ2rziR2v8pSEj6y4f1Gfhjtgo9IFplFVStIgdm",
	"q6CCu1XkTaQH9q8F8LZ8xgt6JMLnZyFAI8FJ4uYKoT8jOSeitkBizoo0UacrLygqaAJcyV5EICIQZdL0",
	"oHrDQv/W3ah9SKi+ipSnkAhI/ugpmbq/Jyk8G6FXMMVFKoW66ZTd6XuNbjpT0iIvqFDDPZ0BBY7TdIE4",
	"Y/IZIlMNksghJlMCSfv8VoQwY0P78dpiwv88FLckHzoeMswZoVIhWPICNtodP7G0MKJMdUGoL8ormBIK",
	"AmEtziToTrdQU0/QZKGvkMsYQVhSuqbktwKQv9B+v3aFAlymxXk5xCkm2TlLSbzYlt8YbFzUumwKVXpC",
	"AYnqj22kg5MMz8CMXhO8NjqQT1lB5a4605B19njT67APtGyxBLP8AabwjgipObS3MW1lRRBEQiZ2s+5R",
	"tYEw53gRbbGjLppkmRjWoQ9VxXKiQcc+m7N7j5vMMU1Svfvs/rifg9kY7F5x9RpaiEAcMnZneIs7rOx4",
	"NxtcxMxcDN9ffnruhCu8b7GDji0/BQ40hpDAYosch04gT9kCEnR2fDJUlJESTCUiiqrVLUsdm1McSzTB",
	"8a3C59KxQ6zAh2eTi5a4LLIM80VPOaV+zRXdMsoPgFM5X0SD6BXMOE4gCcol75kPy/rCSR38atDOKh40",
	"nXUCckm9QlA+qVdpTqxrKY4VVU5VPbgkM7WnLuC3AkRAe9JZFXFPp4q4/ajVEkiQGYUExVVbNOUs06t2",
	"fBTSUJCfgAs9YhOAo/MTW4YSyy40vZpvkCDD8Mwe0tzAgmXl2anamIY0R+gSuGrohKiY0Tvgaioxm1Hy",
	"e9lbKe2kWKppaZFD3WC0YssoKDK8QBxUv6igXg+6ihihU8YBETplh2guZS4O9/ZmRI5uX4oRYYpjZ+o6",
	"tNhT8hgnk0IyLvYSuIN0T5DZEPN4TiTEsuCwh3My1MBSvbKjLPkbd1eYIL+4JTRp4/JHQhPFMTEyNa2e",
	"rkSZYwYXry+vkBvAoNVg0Fv0CpkKEYROnbBarjTQRAtr+o84JYq3i2Ki77aWXhSeR+gYUyUlTgAVeYIl",
	"JCN0QtExziA9xgI+Oyq13myoUBZGZgYSJ1jijY7cM424U5BYdSWsILC+7qJrH1oxJxLlibXDvk2fbR1b",
	"uV0tpXk4snPsfSwsn1iLhH/mOM9BHWKsoAnC+j4yjDkoukHHlxcDlLEEUqNPuC0mwClIEIgwTS84JyOP",
	"L4nR3cFoKQhtbgWfcsLN7RBiRpOgEkG3N1rykhHd4ZQkRC5KdYIHiBrGaKajw4hQ+eJ5RYmK+8yAKxTC",
	"J8nxMh1/KRu2qLgu5rWU/6pjhKXZP1DeDavrnsOxZuIKzznLi1R/miz016PzEyQ0U1C41/XVzBWzJFlW",
	"SHWjDKj6DXEFTx91O55gAd98NQQaswQSdP76tPr94/Hl3w72FTgjdIplPLengyLBUXkmEUgTpG6/Pj0s",
	"O9gM46styWQhIcQb9FHH3wdluxOaGCLTMPGSJkwbc4pobvxbgVN9P9a3wyAPKkiAn1+fvPoT1skDQuBZ",
	"6L5yrb+X13x9wIC+wdzCAplW3vztNZcIUdSlhNrlZiUBO7XJcqH6T0BMgz06aq4Rxw74YceVpKIynOec",
	"3eF0LwFKcLo3xSQtOCBRitLl1D0Li+hYDESmlek6YFbyqoY3ru2yLQwOKmwipi4u5UL02nKK5xIj4QYM",
	"Za7MXBnUcjN/+43Qj0qKRrFXkQM60qiDZIBeASXqX4WhN5ikBqjNr9wlRMGrtk833rz6U0vbxLKd4bvL",
	"JLmRIiVgt962nw4dz7Z6qC4r4Gb6I5oS2t3lzcMay+uIZ7tVLfsp1zIPeAZs07ExFzYoWoYtsTeDrl1b",
	"8aQEJCapsbwwCgirw0U6HhYXnOvrhFSMyl39FPu+KA/vlTgNm9rV14o7qItSoS8OaMrSlN2rK9KPlRSh",
	"hvRvE+hagLVrq9XS7kGJElPt2RgblxugRRYwIGEhrzimwmCUdNnbVT0kSQYGFyWssmwLibmGKcxZ7q8g",
	"oUzOgdeYrLpvDVVf4YuPUGd3G4ofigxTxAEnmonbeoiYo0jhyK0fnrBCWohL8ILCBZvoozd5q20IMqgM",
	"ULMfuavGaFbWrAwSFTbusdBSiDEuFrkZ1pexv/kqKGNzwCKoiUBPJ5zA9BkyNSox3o35RPSa6TZXNTdU",
	"x9XMdj0I0VI5s2ph12dEqxWjNYwMNAmyKbriBQzQG5wKGCCryvJVd6o8GkS6gqes66eba0Bn+2p8dV03",
	"PpcjrZx6hxuddaGrCI/4ugtvik7GiAbR1fnpT8C1yG/0ea7ASB8aEUr0aFeNYxCCTFJo/uEY3znmQle9",
	"XNBY//hJXTtVDcXACnmijqMZB6HI5DpPsDWiqsPJVT0tUknyFM7uKXCh4bojMbyCmGUZEerqrxr1W53X",
	"lLM0zYBKK8l6822V1afbKQx7XXTWKXHZWaNEcmeNOjgXkDNBJOOLIOoVxjsLWuvjF5Zr9SYFkG4V9B+h",
	"VTOr4a2d+eCvoPnSdx2X0P6UzJpWrC2ErbdEBvrcSMqqTuFLiDnIXcltu4LvBynzUF/LkN12T/rXlua1",
	"q8RnuhLUZStt/ephPDNWMnOyE1E5SwQP8pzxkCOX73G6O4Ot9m4NqEG478u0C8+jtlRhkBcU5HuKD3nh",
	"ej9lVHFQx0sq4q6vV2aqrXZdr8wUDNlGq1U0fu9Bv4YN/L3b01uy1Tmjrz/lip0H5VxVjqCs4HyWFVkq",
	"KJIi1aYakoEYjalCh61BBPr4d2T///EQDdEpoYUEcYg+/v0jyqyOdH/49bcjNEQ/sIK3ip6/UEWv8EKh",
	"95RROa/XOBi+OFA1gkUHz73GPwPcNnv/ZjSml0Wutg4kSC05lkwBMVQVD0s1LqYLa56y7tiqG0LRXIFc",
	"9gd3wBf62zM17sfhx0N0gemsarU/fPlRI+7gOTo6VVTyEh2dmtqDj4dI+1q4ygeDg+e2tpBaBXTwXM5R",
	"pnFo2ux9PESXEvIKrD3XxgDTbHFpnOzqc3lZoURxnZdekzF9bTweFebQ/vDl4OCb4fMXdklHvZ3Ljwsh",
	"WWYO/BM6ZcusBs2LjjaqGHNrgmLdkXM+t6sShKOpFfY6IdRQqNan6jth3YTfj4+Y2bQhNt/rJul8vhAk",
	"xqk3yKPV+dHq/Gh1XqOb6l6xpd7CdrSBPflmPd7Q8t1tu93tKB4GsgkkCQQI/uc5yDm0PMbVHnCNnA1s",
	"wpiMjdDpEcGEsRQw7Y66aejffJ/S1c6jOFmERSoTfmOVGc5H+H5O4rm2keiWqLePqo7xCZwu78tRXB3k",
	"VH9dfvYBHd2OvKkV6y60U6H1pD6ZokmK6e0gtHq8oM6rWntY6z7tB+O72PSA3rnD81a7MBwi8DDo9kSt",
	"1Hq2Sunu2ETljh1THatYYTMr3REVUXtUN6g0oeU+HawfHNbiKXV/u5DoJEwFR31z7R3YcOYNuDA2bqtW",
	"Xlu6632Ryqjb3UmqldC1WJrPppBe7tXZoZ5eE/9Gi9KF8mPPFlRpoA1mFSObklkbwRzUdoekUwC8sBWc",
	"yNfZ7ypfgPo4689csLRT4LXFvtxrte/6c8wohdjqpEtaaSNDmFvmyaswQ7XF6OSVb/FojBCmK9Py1JNk",
	"GtulvI+Uo7iD3x00Cm7rSfLvtUDkGFMtvAlj4yeUSIJT8ruxipWR7cAzQnE6KGGWzDUbIJBx1xri5Iym",
	"C8N1G0TcmNXAQ+Ca6+srYkORdBYV5sKEHfEldfVt6drQWliJ+QzkFgKbD9+V7ixs5zXjbDF5r/P2GVS6",
	"FZkNKNSwLSRkIOcsqW9T3/pyTUHbGrRtJZaMLy5A1IBeZsNYBrHX87Jq9VGXo+ZESTqcyMXxHOLbLs7X",
	"XbfJEeq8kbgWKFZNUA5c7TLjMrnhsTQMHkvVTb85poFo16dRN0Z2eBx1dr/CKLoG2iuidT7/11Q4pZlv",
	"HSyNU+uQcWgC1UjL6vgwdNcroeuuUsHdE9eddmcrbnVReIsf5A3Flx4lUfdyudgxzSk6WluSq7aMluKq",
	"mayQ4VTtEqvtc5xkSjTOcoeQRud3umUlyffzD9ndTrUhvWYx3a1E5tnOV2S3HKANdm8e0HlQefbmciOF",
	"+cBGe76x/wbh8q4tvIJZtPnEiv39jkwhXsQpbCTdp671Dm5QTaV01flnPasaCNjhMRXquYs6/TxQIdy2",
	"zyPjuGFJpO5NUP+yJp02oG5SWqO4BkWgPATaimqrafZMhENT/FJkiiZWaDUCMjq7LG9QnSJW2E59VevE",
	"GKmNkouj64t3qy+iXSbcVTPdZFueXfae10/127WbW3Cv6ZJXZNYZKZLosmZfxuaGxBw///qbQ7w/Go2e",
	"9cVXfdA1sVc6+KyFw9LCskp0sZlfNuQ7deDciZsQcbvzTqtEMTvstuk7nxdROZKdx1bLtdzxQNQ8D8wC",
	"GptYOxT5Z8wt7znmRJIYp4Gg5HVYZB1QP+a5XVoNHir1AAoVOyBDZSvdJj3TUQenbPBJvMRQ6wU190qW",
	"kFtnoB1639Tdi1peOEYh2A2dKd8VYEEftRBMgqXQYSdJHd5iSe4qlZ7VZW0JYF19GYw+rJ/Mu9FRaT/y",
	"bSC2Z3vTraqhtVSTqHEA609kV9mGfG6JwoZHUQiJxrSVdKhtTaEOaCPqPKk7SDXcrbCM5+cmmWHQrOGo",
	"RVdENu1hfYYtS4hxfHFwFJRILbMMbFYwk5VISd2imE7JpwEyyQPmkKZDIRcpoFnKJm4wDb8eHc8woUK6",
	"KJB0gVKGEzBDaJgy/Okd0JmcR4fPv/6mlqbxw/7wWzz8/Wj434fj8fCX0Vj/78N4fPM/xuPhePz38fi7",
	"m388/Y9+9Z5993Q8Hn0wFUPFwWSQqzOuGJeELTL8eC7CthtD2A/rHYrLVY9tZWP4RiW8rCmWySPbNsNa",
	"s0FSY0SNZYHTKqxn2zPBCqS1/FneYb0tf2s7GwQ2KW5byHYzZMMW2T8yslwvk1RHG9+dXVLhPBhh5S/F",
	"Z4mG9M/Qzc+bylColW9WL7E7FZVTtV0C0D7RWZYCTTASUBdpbJkyevr+7Or1oTGmlw52NpEbB1lwWotO",
	"ftZTN2e9CX4VjA7JjDIOpftAea/fndJiF6du2dF27szBm5c6KbfeeK3NZs4151m5aa9VJ8vOc8fPamfp",
	"bjiZgSC5pkR28zDrIbf1SZR0qGE9xlVDbJ17RmFm6tOMv+dLhqKps5pERQ3+bljztri5H4jHFeaYJ/eY",
	"g/bsNK7QhM6cx1LN13L3/iEWBhce+tk8RAL42qGWc61MYmGF+5kO+wknDbuACWM2yOqc3QOH5Gw6rWnk",
	"j+4xkTpizHpDmBjDaUpieY4LsaYCtDYhD7RWmQdtoLR+d68V+XMKFNemGShvqmRrhSFkBKo18bNijWuc",
	"tp8P+5nLOWw3k5fZBj7lTFTHqnbcG43paxzPdb6SmHEOImc0MVHT1a3O7CrrlB3jHE9ISuRiNKarveHN",
	"JGqbMmZpanLpl97LneKuArLTWUmJHUfa/9B6KwX3sO+Q3NGHV0NJiSZGw+Kp5atf9azoKeQ99D1jEp28",
	"WqcrE2yw8anaCnpQooljrGYJwlM/K7nvpeO+PWFuOjP7WC5R04ZiUF/TNdle62K3wmsm1zW19SHDFM9M",
	"iL4+AMyxqF92iNMiUSU64ab97iUcTtg9tTdtdWDZBCsBo7qtd2lClTaTNM0Myy5KIWSnnT5sgvVkI6OI",
	"gX6nhkr/GDfdf/ZjvIaBHR7j7X7XMFVWqC3tlPkVe4V1+qCzQp5N7W8vYnoTxXsNSG+IQKk/arBxI3S7",
	"XrpSt07E7cp4yt2EMA7+YoGZQSZnVTuau5kONH8j4tYkH1vneaeEcNCOeuX7Tk65q7qv97l8Luu+8vOq",
	"WJb2JMOfSFZkVUJBnKbs3o+ZMJ6+kqHYpqs3b/KUDSpGXuZjR1hHyjHFMu6sdwpwm+rGpjU2ugzzdEMV",
	"uFl+1PmzDtFHYWIghUmJOEAfM/PBhDWqD3PzQQdwjupv5zz97vDDwfDbm/E4+fuz78bj5IPI5jf9H9J5",
	"TWOmTq4+DqRg6xpC1e7DemWxxI0wPp+j5KlJYG2yEfbOfGGGOreN3d/f2066p9PIitGeU6vKkny8Ni2c",
	"Ig3jqbpUr/oYFPkYFPkYFLmkm9bW20F8ZLvPPyH1bkdiHpz2YDeuapWxLSyjlszHMyFYLqQfmuuMXcAu",
	"w8+ShJf3XqCl43hzLNAEgCLXQTiuMsUTSLd5Le/IpTg1PWlNQZ6niyoLf0doe/vBMjPP7ZetupdsIQV2",
	"E0Vb/FoBySra8MyC21LJUYdLmBZTsLRRrD6d3GNRI5F+Hs+uxfddIbT1SFxVl/d6tM71OvCn1CN14qol",
	"2MA2G0B8uUCj/lQZVksEq5mD0KtowGnVfSKcE6Q2SwZ84gQPr0soa7Sf61aYrF8+oQX2f90ivmUQ/CDS",
	"t7yLVZGIV5pol0Yj6nPeBkaNfhWMoqcufPhZR7DArrmfy7/oDJv6iVuPIRJRmkLnQJESPDwyIyLErjs4",
	"plrkzZlll/Kmo+J6G6jVSRfHMmfs7piz5wOwKi2zvxXauZlHa2dcbqdihTAe/qo5lP23foMYi02hWeIp",
	"CYUbxMva67sjkvBJoqfXV2+GL58hxpt57b1BdNgrSTvXQtVzV8kNyci7LvdXgipEdcfyqtIyereNoRln",
	"RR7Gj5rrE4F0jYGnnACipTvsHmKzT8QCJzE6eVV/mm4cccbkOFqacGFFZoWMJbAUwhy4dTTUj0yM0H+x",
	"Qt+5DMzGUJCpG9IUZyQlmCMWS5xWL91irXn4HThzqaD2v/nqK00P2JyBMclsAxPzG2rz1fP9Z+rSJwuS",
	"7AmQM/WPJPHtAk2sRgaVITg6p0XtFT6T26IxGa0qUPNUjLrCqwIvnIKjsM8cdmKL3etXDj7jen7WFwMV",
	"Pe9Aq7r1S+K1XbdZrkT/bfzgW+QlW1lHXxnO5dlKtzMj8kIBHJZrvPSLGL0lsu5Ca19jWEd/67S2Nk3B",
	"lMxcJoEqe2tHxhpXvFq0r7qqvRbSdvTU0uoF3JFlsp0pVUAXwnspaym8rTwTJfCtUQddmuhlb3r7s234",
	"rvd+JM6ufO+DuPmq8ufLfbpZbtB4jrmscoPOIc1W5kHSuuAcx8tjuspaoQxI9kE/JU3V30POFkOc58Nq",
	"iMD4RgXaLemb9BYtV1FvC5oegqmZnD1AnTgTIjnmJF0gal+5cZnzRQ1qD93+jovojNBPmnhn0WF0MHp+",
	"YDw4Tc7jwz8ioHiSKvoyIM+ZkEJThvoVHboRRjHLLMmbYsMqoj370ZgIonMOU/LJvebJQU/qmBVKhnsx",
	"iOw1RrMaxmV0+HK/RO5xWggJ/OQ8LDoZfCmuvcQx2SFVn7el6igpjOGqWm+k+7Hpt1KsrTR6ar4FXr9t",
	"ZGISeAIcTWCqZBCdxNFu2lIX7i/FBwurqpQUJo3LAmdp5CYxZHfAOUlAjBZZqjZy39d5dp1AtiOZcuuw",
	"mUuZ9zxtKPrh6uq853mjFuo8eOaor+6EMTfcJ2ZdneeRZJ72yUn5Td9eDYqAO+Ceme6eEymBbn1a8fZp",
	"5Q4bl81sQWO05BwzARqhyfPyxnJ98c6+s8QyRbJTaTWz6qKjg1TRidRZe4yjCaDfCtBmVo4zkNoWVMRz",
	"hMUhGkd7isr3JNtzpovvdO1/17VDYuHSE7Fcvj//EHQU2ZvUl75HsyRjct9T7Oz4JPAWbOjcyXF828vS",
	"vfX2Xvricjto2Dy8qwWlajaZag4Jwt5NR/PKJcHI2zxafam3izZKmWNjg+5MT3rinRHIpvf1UHlepGno",
	"HeaT6Xsmz40+q/Uas3OZrF/EnvhtnozQz3OgWvmnyo7Se7wQTwZe6nQiUF6kqbru6XTIkmTQaPVeldQa",
	"ZYWQCKcmw6R+cKw7J44ZMxo0J6N77WmYV/gp+1F/NPpSn2x/S/EcplbKpBFvfL8WvYgPn5UStwv5b3cY",
	"iPrykxrYk8SY9Ve8NR24wdVIdLPpe2S+xhvZq6E1j0VymBEh+WKErpS4n+GFOpRxlRzVa2heVip9nxRX",
	"cp0N1CGbMjpT/9oLLuOZaPNj4Xsz9Tnh1n6De/nLZMsOF+OIviQw1D84rJSzs+DrSn+yQsw0UG5zEHU9",
	"AXK4PkZK4d48PNnmaJvjptRNBWJ1Pq8404niDoQufaWlhdRdwa4ucGq0voon70U30/CfVH9dULnhLaVm",
	"Izc48G4iVrbq1HCsXrMKreuqSCrdyOqu/nl10oGt5ut1qqW9WWUeta2rDdB7r57q9CmPD7X4KOl7J3mP",
	"M0hskmyzXeqaBTXVgFxoZbSWXPh5rhRrXiU8f7l2fFVZpiT+MmmvVgDgNEU5cEG0HrBKaKSl/Dm+g4Hl",
	"NVYRIHQLA4xOMM5tXXNwBmzolDJZxf5v6MNQVTbvRNYis8NvktgXoctsikucjkxovfbUvMfCPT7d39Mo",
	"gRQ2GYukqY7VUc3XGW+25NnNIyTgt0Ifl/aNgJqfqve6qfckZ+miYvL1Go8ddN58c9ucPyN0ATgZMpou",
	"er7SubULyynWyTCt++0tLIxO1WpmjSarnmKa8Rmm5HcTrhtjCTPG1Z9PRcxy81VACrF85og5SEX9Dkzr",
	"Jx18KVUdYqFV8vyEsVRnnXCO2Ob7QIkAY+03uqfGGkf23aiuJxx0q25/cIpYjn8rwCFRD0t0MtXS3d5o",
	"VJ8Iz3G78mGq/MGDJ0E/NnWOZTz3HOVLsTpMGFP9BmmDo7CO7WWj9ox1zibs9ZUROEkiYz4w5zSHjN3p",
	"/VVPGOe9GReUz47Q/7o8e4/OjVhQqq3C5pwwqMaB3D44zPQWVUCNWqcAy5eZBNtJOQIo/88CJynIx4cK",
	"H98u76SRC2uvCl9ILurRKta0pW8kYZ1t175pt3UXbXeyvGfSckRMrXZRMStd3x2X7A64Z26pbKyCx3uE",
	"JvBp9KvYgkc5qfMoBS4vbPhq3h2/3p7nvJ5lveEsq1X3qu+w52pnZJmLOVNCnHTihEKGdxvEd8DxDEzY",
	"GyLecz3W0KgHJnQ2Qm/0aXK4PKLsiXhSDxV7kj2ph4o9mT/pDBUbj5N/dEeH5cBjoLIzh2pVrrBmZmR8",
	"VzmZzZTgGcKkEXqMWuEONk4oVCOCS9tTOIjWDeOtXW1ydWHmZiMyrEHQDpqzpS3qckdfMK+ljrnvp4Pv",
	"hKXquLOKN2JnHQPKKky47Hpq/kTNPyMU2w/2CVf18/j8umupO942HUSvdDLVcKOuCN5BdGqzpYbbdV/R",
	"qyvk4r0WMGt3ZyU1bn7MdExxowNm2Qw28anvQKQ6pzoVCT2JYmlihXDMMa75gzVurY73L0spqSshrmqN",
	"0BlNF/oBffM1B44cZ9Au84an7ibNZHUyhRJNquOQ0NmJkk6DAWLlQTIBeQ9Ay6hp3VRN5k84G8oY4q4D",
	"Yol2aeCvT2DGvXls50sVJk6AGIFHFty6VunZxDh1URQJo0+cgwgyZiXvNvkYrft5o3XjoA/4ZTGbGa82",
	"7ahjFyd2btMafyYOZID2EbH+1kZJ7esyXjwP6jIeQ4R3GiIsRFD+6yND+6lbFB7d9b/rKU0RFtYzHM8J",
	"hc6h7ueLxgBqoa19Zqzf/Sg4jCP39AQ6sQAZEtAPieZSK9A4mHyR9eikO0xSNfAIHaELDSaKU8yNWsa5",
	"vgkXpZkAmhSK84DJPOnc/hCRK9LILMu0ViEPnVElbx+icXRZxDEIMY4Q4/5MPzvZiBziIabJsPM1jx6h",
	"1uWjkppNlBRQEV3/U8KkXTzSybcV3qDbgjIns/kwVTM1iR91xu4qm23NO8Zk89agpUxHjmijbfl56h52",
	"cZ3oCgnU/sywYk4UU6vTmnIQc1NUrJU3pz3LIwdIu+jCg7hdelLNoV1YPlfTMaCbWLv4VX3m7QqnNVyE",
	"oPaw0y5emcvHNnmtvZtXEIJxga6H2mmKcNFijgqcr/TA/RryglrNf0rorS4yP7wSnBIs9PILU8P88Gqo",
	"kUlsHlhwIxBqUuZEpQ1BfzaZqIw71QQnHukMovWox0PN63JenWUXJbDtKu/c1LuKljU+sthpl5w6fHUV",
	"Lev20qG0XfSqQnK78KRCe7vwrbcQAQLzlqZd+j0Ot6ryPgZwr06jlTT+juFkBYUrDtCDvoUsJoqCmU2A",
	"SZkcTlmhefQEJ0MB0m5osHkwM+Azj6Y35WTlFC4NBM3P7xxEzYL3TL6xADaLvsfJZQlvs9Dl8Wx+P3Xz",
	"aRU0iLEs6MuJvEzA7afTK8a2TbLh5qnXtM0FD8Fu2c35LuscVTXt7VkO9PLyB2uEQgmGzBzX3vsA+1+9",
	"DIg4UBH3NjNtsvUHQ7Rb91vfStpDf1J2GtpW90aAGGgkWY8UZ7SthIgScbyg1MkCJaq++ap+28bD3/eH",
	"3w5v/hFUxaqBOl5ody9BuHjWcSTEPBlZ0/s4etbQwXuFK8U2PWydnuqr6a/AoEbRHhZ7y3FXJIP/Zs4R",
	"0PlZv2NGOdl+hBH9zihUNlIurPpDE/DJ0fsja5FFRxevj/benR0fXZ2cvR+gey3pq4/1RF9KGiZUB45z",
	"xGLA1FyyXcvS1UknesNckrhIMUeCSNBRxvrSgSXCHPBAbyWLeHSkvaDw3nu4/+W/GL8doNeF4gZ755gT",
	"p50qKM4mZFawQqAXw3iOOY514IebayMaGT0dR29Pr8aRWvXrq2O72P3SvF23MoA2/ZMrPYewtUwKtEIy",
	"dTWKyxymWllHk1D2U0kyV+r8tfR0WBFK57CZl84xZ/T1J7WO7tka/XD9W45j8PMArq8PdY0fBpH0aHPt",
	"jkrCbt2LZBSEtveW8T2U2m9et12nzApa36q+hkHTT+65PVZu2zoa31Kk7twscz04LtoDGe/pqER15ZyO",
	"kkPONs35+OC9BKvhiPXUIcMkjQ4jCTj7j2lKZnMZy3REWOS8RDS/fKNL0LG6+LIUXQHOlPzCVVN3Va61",
	"bvm6fKh3cfM01OyZVTbZDC46KSLEKebGvqrzBkNmc1RMUwCpr/qQzJxPqfGgkXMgHN0zfqs2mjDZsVMS",
	"AxVQOflGRzmO54Cej/Zbk7m/vx9hXTxifLZn24q9dyfHr99fvh4+H+2P5jJLDZFLvVwNJB2dn0SD6M4p",
	"RyNLhDYftKLD6DB6MdofHVTBon9Ee14mFJsSyOm+TChoKBXjsXHvxui4anxpGle5GSujQKkWOUnKxp0t",
	"I0NeIOT3LFk0Mo14Lvd7v1pNlNnTm/GkTiAe6mRu3Y1NknRhduHz/YMvCl1oSRK12l/t739ewMpMfS0o",
	"vscJKoFUkBx8KUiuKS7kXHurWaS8+FKgvGF8QpIEqIHj2y8FR/0hAg3M8y8GzBVj6BTThSMXncnp6y+3",
	"SJfmDLimpSLZ+Lrgmb4Md3LJ6EZVW8JF9/5Q3P9BB1SADLkF4cSIb6WHfufGbzPTtyCXcdIq0libwZf7",
	"X65m5kgyNDM2HqJ6sJlU7PFm3fDrXHPgLVdT6VBQ8lsBJ8aQa8ICblpMdv8vxGTPfnzkah1c7asvBUep",
	"ZnrkZzvkZ1a6tcxrz2Vj7ORib0HaxAs2baNNfdgtBr4F6RJBmiyR67Ir08qypPrgoumwshuO9dDOB1s+",
	"f6c1jSUEP1WP0uhhdSaHatxgGsxl4/7pbNEuSScPfG42fHMrIi9u9S/FJr8ke0IVf/pywt9fV+zzuJJh",
	"GmEWVFngcyzjcMCnC+b08pO+WsWHdLNantrN+JAvI2kId8Vzbta5EA/10P/YwRrWYkx6XYe/MEt6vPY+",
	"CoirOfCjhNiQEFGXiFgy40GUFwGR79q+v7Uuw70wUVo7ZrnVi1h/Os/dIV97ZLH/jCz2kbX1l+qqFPj9",
	"zQwUhd5+Wm5faD8o9Sdu6fbgfwV7QgdUj3aERzvCv8hV8i8tT7U4XydHXGUyeAtyXab4FmSII64ldXWP",
	"t1O7wBfQdvXijI/K/8e73b80L3owScAdMzAOKns4J3t3ByahoGndfnjechqBGG3ezbSLkWUEVhBsa9Hr",
	"PXTzGb+z9hQebh7+fwAAAP//a5F2S0ThAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
