// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H2Jctu4luiv4HGmKsltLV6StONXt+4otpOoO7IdL+lJt/xuIBKS0CYBBgBtKz2pmn947wvnS15hI0ES",
	"1J5ebmWm6nYsgMABcHBw9vNbENIkpQQRwYPD3wIeTlEC1T9DytA/73ZHSMDdf9IUEZjif/ZGnMaZQOdQ",
	"TGWnCPGQ4VRgSoLD4AKlDHE5FoAEQNMXjHGMQArFtBO0gpTRFDGBkZok9Y5zNUXF17ILEBRAPQ4lQEwR",
	"4DMuUNIBp1QgIKZQAEhmAD1gLjCZ6K73OI7BCAF6h9g9w0IgIiFADzBJYxQcBt07yLoxnXRhmnZiOgla",
	"gZilsoULhskk+PIl/4WOfkWhCL60GjYmxe8R4wr+6nJ6533TBiI0xgRxtYQ7/RuKgN51QMdATDEHzG4j",
	"lAPInyEBev4OuERMfgj4lGZxBEJK7hATgKGQTgj+nI/G5Z7JaWIoEBcAE4EYgTG4g3GGWgCSCCRwBhiS",
	"44KMOCOoLrwDBpQhgMmYHoKpECk/7HYnWHRuD3gH025IkyQjWMy6ISWC4VEmKOPdCN2huMvxpA1ZOMUC",
	"hSJjqAtT3FbAErko3kmif2OI04yFiKtTIVkSHP4SmI0NWsE4xpOpCEUsJyt+Dm6qp9QKHtry8/YdZAQm",
	"ErN+CYoDeZ9/Wvz2yo7dp77mkyQVMznRQ3tC2xWcaMSA9Ep19GGzHEKfLwIwTWMcqrN1F64uIkdBK/iU",
	"wShGIpATEQExQSxoBVMUJ0EruEuW3gAFz1E+rPnhXT563qOYxPz0Rs9l/nqfBDdzVm0XI8dBRMgNgHF8",
	"Ng4Of/kt+HeGxsFh8G/dgs50DYJ2vQO+wjGyI31prTHABYqhwHeaRMkRGPqUYYYiuSmK3tzULvUyyztG",
	"XI5yKaDwHLJpBTEeo3AWxghw2RGMKVO00H/mLCNEHyAXNE1RtPzZ+sC6yIdr6HBpZ1livSfk7j1kmkqX",
	"aDYqGmAUYdkXxuelLrUbU96sE3KHGSUJIgLcQYbhKEbgFs3aivCAFGLGWwATeTgoAlEmhwEsIwInqAPk",
	"hbpFM0XC9BcIhlOQZFxIcj9C4h4hAnZVh71n+yCcQgZDgZiiNJWzX4HE53tzTpmo44D8FSQwTSW0mMiz",
	"T6AAw2BKuZCNh/l9ln8NA/AYdSadFhgGBzsHO4cHO8PgSfmFMr/LdxMKScCDw+D/DIfRd4fyf/69/mAt",
	"ATujdzhC7CXkHjw+oklCCShOXGNwHLsorMgZr7/mkBCqH61NsKPHRlgwyGYgQQJGUEDgDNwB1xxF+XMW",
	"z8BopsiqeoRoDNIYEmR3tvSG3FN2G1MYKYL+BNxPEQGCQcLlQckzqy0RQPmykggxoFAvaAUMweiMxLPg",
	"ULAMeXAHFu/AyrTLviF6T0rkZgOS2kTEvty0VqBiijVxdqgFIAcJ5Yr3QETEM8CRsKch6VmXC8gEiNAd",
	"DhHonfd5B1wgGLUpiWeHIFSnKm+s/C7CDIVCH6ecZfa/gewGDCsk75McV58GikpnxVMUggjF+E41GcYH",
	"ThAR9SP70gokHW3gOp1RZa+cqOz+z3//3zIpATElkxbQa7zHYgogiJG8pIAyQLJkhJhms8ytB4SCe8kQ",
	"8RSGqOO7uwyp4V4jghgUXmbyiGYS9QEmIUOSgqLI7rn52tlwTRgl6lY5D6D4TNUfRX+GY8l3Q97sCWKK",
	"MLtPt71XN+vQa0PzLlMUqi3FcksTTKCgTP5gqLaWezTDtMoNM0yWM2OJeVttKPNVeTDF/a0yjmThykNY",
	"tnKVUQyzWB7objVI3pfg+JI/GrNTdQ3zg/3SCihB6xI5zxGsxT56VrzWON5zXGuk6kmuNUjlEJZhAC+M",
	"ePYWJ1hrB6rSvm4HsepgHomafFNmEcI089C082s9iCQnEizeAa808yRpFMOKDRxB+fBTUnumyyzTTuf7",
	"Zz7amqCEsll98oH63cyv6DhNNdcCpHS7ASR7z54nG6kUakcx7xRCSrhgEJNljyLOz3UTjqKCJWstT7Ij",
	"GfdLz7pNKUEAx2QSl58xow7ST54rWp0zlEIjQV3KZ07/sxCRThijUuS9JreE3ku6JklIjASK1CdaUjL/",
	"kp+sLJpp0F1Aao0OZLU2rzSnmyzstYZiMbUmd3UeOOxy/U1q/Uuc5DVHrC4xsoz0uJ/hyjhSe2eVI1qv",
	"p36ucZxW5zVCUhYEmWQ5pDSIueRmJNOiRpCjQa1iU8PIO42J0g/mTzL3KGPAYzy2f49i9KQDjtEYZrHI",
	"VWkGKigKRkZCwuV0jyeKaZMCCaNUPAF4rECSTBAeYxTVGb6yeuna7IT7c5vf4rRt6VE7pUrsMXzsOjft",
	"PY2zpCJPVEUAraGEiv+NwJ36Qi5d8Zl1XUb5qP2s9TXBnzIE3IN2xzUn5KFYHg45jCFOzmmMw9mmtEvv",
	"xkVpyCrbqRbk4Tl/24RZ6SdwgvTsJdZ0rad9ICWCbQ2mIGsc8WYpxsHzZY0k6OP3EIW3mAtF7Z2LaTpL",
	"hMACJXw75x4UFwgyBmfBBjfqooqWkSYd6oGWJCdoNdyzKb13qMkUkihWt8/cD62kmCJA70lVRaFEuITe",
	"adpiHz4z380aqiG9Fk3257/EW6EKpzVy0HDlx4ghEiIf82OaLIWOUBrTGYrA2VG/LTEjxlBKqRKrpVgu",
	"X9sxDAUYwfBW7ufcuX2kwIVnHVGUX2ZJAtlsSZ6nrHjjzfzOGwRjMZ0FreAYTRiM1GNe53FOqQvL6jxN",
	"Gfxi0sYuDjSNfTzsTLmDl60pd6kurOkojqCAMZ30BUou0HiOjqAit5Q+W4sAlWfWBLWCYZVZlsYvz9CN",
	"+tcxjDmq6VwBc68SBAYSIOltC8CYkokWjqSkF1IyxpOMNcl4+ls/w2cHVrxAzkvJaSQ9SyGT1N9LB8Ip",
	"JATFHvsqcUS2NIICAdMX3E9xOM0NwYpcCQpSfdR55wxxTWjhHcSxZP68AEgg/YtyGRt35+Ruodi/nLtG",
	"czG4gzGOrH1Yb1KYMaaVrMrGza3izZ1tMQWzJ2PWUgCxPKbJYx7LK4Mu8UQ+SRfoU4a4xxzS2LUwcMuH",
	"jpkflZ0BcDwhKAJh8S0YM5qotR71PCaHkt19DaYg//xLK7jFJKqv40dMIombEOhdNTanfBH2Gbk4ubwC",
	"1qathRe9mc56C/t9AmcAk7EVc/JFIhIpNl+fbowlV8CzkdKwmK2S8kgHHOV6Wo3GUQf0CTiCCYqPIEdf",
	"3XqvDCRtuWW849e3aOPNWudypjZugASUQ3FD0FYnuU0oaBjkgOe8zhbH1mPW9dc5qhlMc/bIrHHza5hr",
	"uEso/BODaYok+0MzEgGoJNl2yJDEG3B0edECCY1QrLVat9kIMYIE4gBThS8wxR3nSvLO3W5nLgj1i4oe",
	"UqwfjEsUUhJ5VVnqe23xzX1fFDHEYpYrtRxA5DTayqoNB/t7Qd2O0ArQg2BwnkUylypqWFwWEGqGbDkw",
	"gELfH5RrFQpFgd1jRb/kPqc0zWLoWG16533AFVGQe6/6y5VDSXSSJBOV56hADNZEeOWLNIIcPX/aRiSk",
	"EYrA+cmg+PePR5f/trsjwemAARTh1DgkSRTs5OQYoziSrwx08WEeTdeEr3Qko5lAPtqgqDw79UoFfRJp",
	"JDOGJYsT+httUVPU+FMGY6VZUc+vnDfB5C0iEzENDnc9s2bYQ92v+8e/w6k5QHA48cm91+r3XF2knhuk",
	"JOFbNAP6K2c3zPOPOc/Kz2VJSF6Izlb9Nl84+x02pkIsLW6XUGUL1LFBtC1wDqaSOYRxN0IEw7g7hjjO",
	"mLaDZ/n9Vkt3TLu84TAAHhd+iR6HCaer/xqbIetcUavYTUAl154fxFIXUFJgnDtqVC3Mtk2LnoXp1pxK",
	"B/wopTEQOh0ZAj21dShqgWNEsPyv3KFXEMcaqPVVNzlEXpVNicEt1rU8ttQth1vztyg526ylkPN4ZG06",
	"ToOucFN9ZpMsvZ75dCkxfT0VJ4kxaYb25ssKmGPxcjOEycfJ0ST1OExtMrA2sFcui/C7U9S8gvJRCnIX",
	"IQFxrA2NlCAA5bslchFYC6vGeci6NcuX4SLnEhbuqd8/Tf5aEB4pkWVKQgFjGsf0XspiPxbsipzSFVvA",
	"NUfGV0eellJ1RJIfNs9uqB11EckSj70UcnHFIOF6R3GTD5HsV/jcFLCK/FsUaXlP7px5WCQkhIopYiX6",
	"LQW7thzLL2FxyRbUoXiTJZAAhmCk3gfTD2D9ysk9sucHRzQTBuIcPC/fQkfqVY/m+SbJ1XesTNOZ5D0L",
	"PU+xG/eQa38xZUvPUj2ty8w/f+pl5hmC3K82eTxiGI2fAN2jkBfsnI/4UivdRCa0UzXIgGbolg+X8pUV",
	"B7s6IVqsuy/tSEuhIB2DK5ahFnilVIPAaFtd7bJsD1qB6uDok5dTH1egM2NVfrVDV37OZ1q49Abne+N4",
	"XyAedpUkzhIt+xK0gqvzwXvElGyhVc62QTM2aiMkV1PvGoaIczyKUfUPS/jOIeParWBGQvWP91K+lT0k",
	"ActEXz5HE4a4RJPrNILGPUA+TrbrIIsFTmN0dk8Q4wquOxyiYxTSJMGcY2ocB17FCIljFAvoeiHY3qWf",
	"lzvKE8JoHCeICMNRO5tTayvvTSNT7gzR2Cff+MYe+Yk09iiDc4FSyrGgbOY9J3k8jQ21w3Qb84NVm2+P",
	"TP3hO2J9GM5B6x/c49a/fJVDn3OrxnhSNYlswCG+xsIz5lr8W/G+X6KQIbEtjnBb8L0RIvWNNW+z666C",
	"/9oiiPIT+ibHuLhRZfpTynxel26QyfY8IlRAi0c/xFzHw224CXo9BJfnc9LMDjSgRFLv3NaZ35XyLia6",
	"2+LIvMJwQ4H5aLGayh3d6yO0RvRafXlzKAej5OQhlU+JP1iAUQJQ3sFGJEnOWEIRZbEyXuEE8c6QyO0w",
	"PTAHH/8GzP9/PARtMMAkE4gfgo9/+wgSozXeaT970QFt8IZmrNa0ty+bjuFMbu+AEjEt99ht7+/KHt6m",
	"3T3n458Quq2O/rwzJJdZKm8JioA8ciioBKItOx7mim1IZsZgZ0KC5DCYgKkEOR8P3SE2U789kfN+bH88",
	"BBeQTIqvdtoHH9XG7e6B3kBiyQHoDXTv1sdDoPyWbOfd1u6e6c2FUoPt7okpSNQe6m+6Hw/BpUBpAVbX",
	"fqOBqX5xqZ1fy2s5KLZEMvYHzidDcqI9keXOgZ32QWv3eXtv3xxpZ+nQsaOMC5po9qFPxnSeHaUqkSkz",
	"k455jkCoBrKhZeZUvHBUNePOIJhoDFU6ZSW8lt1hlqMjig0qJNlCalrBZeIcYgZCmhHBwePQOtd2BRUw",
	"fmKs2anitJAKBlSRaB1wjlg7lZ+mU8iRvGhSBKsAZPlDiQpEgBQxwAVKW8qjFMq/Q+UthiATIwRFBxQ6",
	"GiM8chBCxmaFS2wFRAO6Ryed+wnXbQIqqEneyF+pOg1HxFdBmyYSnyEAY4ZgNAMCsQQTGC8p3Eu5+Fqb",
	"sz3kGhcmCSXIV5d0z7AbrGZ2f3mFihpl3rIz7cdaW7ayxjTM2LTYmua6cM/WcNwsj80pIhEi4UzKHpr1",
	"vEDjtbB67liu40Yp6muMyQSxlGFS+HEoaqU9hazDDXvEAXoweQiifCYfDrrs82ljuF7J76Y8lSaRqmWC",
	"BaAMvLm6Ore9zFsvv3/iJUHOivxTu0s2EOTbEer4dQOCnF7JaAJcvum1AJ/CvWfP5UcKohGNZi3w4wEH",
	"XIkzuY7UeAv44XMuSk8so4d04Q2n8mmLwGPcQR3rN2kOIwf+HnLrWfJk2StUt8ZUj3FNpN4CLvtRmM9I",
	"OGWU4M/6PjvbpLXbdXzFyDjB6lenBUKYikwFP9aihX1ofYHGPr4esbZub+co7J6ZZCLUiRqnNTlDS2lQ",
	"cxdhE/epQdhQNphPU9b3nNZ8xMoHaRbmuI2l0xnHoTqX3BXWRl6V3cKaEoloby8zeFB2WIrhCMVq58Yx",
	"UjGT1qE7Dx8Oxs/3ovHo6fhZtBdGo9GL/f0X+8/3Rs/GuwfjvRDtPT+Ivn/2/OmLURQe7Ozs7I930M7T",
	"vRd78Hs0Pgj31aZ9c2b75sy2/JW0isENrRRmoDXc1G5Wu+a1WLK6X/WWsiWgZISiyMc0/jRFYoqYL/7d",
	"fmSdaUaUilDHCjhIMKI0RpDYR1dx6htsu/pebsysoKV+D5yKFc/ldRZHScFo1sAy5cysEwyn3aQl3665",
	"9qWDsVQCAT6PZbZ9gDUgNgWneix9WwobxBywTEXPmJDB/hiMYkhuW96sCBmx4YNKblJjmh90kE411G/r",
	"kX0b3W5/XO2XVnPIVWEcNF3yuJ7qVm45AmsON+GNu5FI7WBdq7Cn5ve/tXqeiBqtKgeW+PQaXHew2DdV",
	"YTCVqDVPrE6Z9GGjTJl76119hzba2xdaMYOlAPSvZtaeH77UYORecf+PYApHOMb5w7A8e+h+KtkTrRI0",
	"/oiGKc6zjpTPgPIBjdZ7fc7Up/kOrLRWxU43odeR4z1T2OzNOrSIUF+IlT0bkxBeWOHUhpU0jbvIMbM8",
	"z83KK+c09uZPc5qrQlpofg4pISg0Vvz8XtQ3g2t1d//Y/3iYZtA/dn1EKjP475D+cuBwgxXSkGNtPkue",
	"xMo8qhJu49b791K+sxASN0gJEywwjPFnLb/nGQSNQq2Vwyyo/awFkAibzrCcbKd0YSurajkbuOL5utZo",
	"X6oNm89LaW6tBA2isg079zOtHayAbILERtxXMdOVGszvGafn2WDxzuD19zb38dYXUOfcqm5CgsSURuVr",
	"6vqrXBOkHC6UN0ooKJtdIF4Cep4jxzyInZHndSvPumhrKlzvahT+AvEszvVsTtIxEMmBdWYqAIVASSoK",
	"BbBVlSiQ69g0hnE8guHtRYNH2aWrXHEnNePm86E4VgHFWvCFBiidszaLYxN+nGZx3AG9kc6bNQaEmo73",
	"kNuxUAQMRdJNPAtDhCIpDx/FCEo8ySEi6KEOil26XrPOTuYXaTn+7MHNk4fUJF3U80vygwnonxypbDgc",
	"PP4Rv2yBgfyf1/J/KANX+OWTfGE5ePpTnZdjhgTIfcrWzYdjTVACTRgWs6MpCm+b3tDmvjUFYOmVxfYL",
	"EMpPQIqYpNc6LmpNZq7tZeYK41V1Tg3Rtnm45h3ZIhPXOPwCh8QVtr0gfzYk/Jpwawd2PfNyX69VCKJv",
	"AcVM8/q4MDT3y6Fr7lLAveReN/p8GiGlCcNrL0taseWqWSJEBBazLeOcCqdeVf4proySfYqVLJB8ZO98",
	"V71WRS5gkpZMi8Xgd+rLQv5dzpS4vZtqsjDpw7SyvEiTrZ/IdilAHeylaUAjy+O4b+YXyU8H1rrzlfvX",
	"8rc3XeEFxKJOJxbc77c2B+tacmKewXULeoeqn0UlPezXeqsqG7DFZ8o3chN2upnbfXtbf4+0H7RBkapz",
	"rvvLinhagbqKaZXmEhSedh9oC7otxtkzXvfHW88J84z50qXUnCQVl6o+qB/gmc0JMsVEHKpME6UUJ0Z0",
	"sBmBajmkH3HX0YOhkLKI2yAapGxeI+QkjJOjMpVw96Ni+D9aOxjmBnMe8Tw0SlsZLNMcUaQZZZxIQSaX",
	"DEyuj//57//n4h8m1hYt4hmIMA+pssKFkERYiQPlpXHjiKB+5SDNRjHmU5O5ybhlKd8Mek/AUf8JYGgC",
	"WRQjzvPgLRUOriM6pdjEtbxTiDhSuNGZgZVkQxTrn/HmaN9FQWcnWJltnNCss6O+kaTyg1TiB5yXu6aS",
	"RUWrWBjiNL7TahZIygN3goUovg49Prv0EGI/3r4vK+jOLmsmKScljWw5xpPGPACRaquOZRBCe6Icwp1O",
	"p9PsZrJ9i1eFiOt9KC9mRYqeB2CsdDa5d/MiXthkrV1zA8rA5QneMb/d+qBFktstDlv16kmzIJ/JrGOj",
	"45rvnM1L3tn6AMslY4osZD9BZh6zI4YFDmHsSYK2yptbBtTNsVZvLSb3tToA+ZotkL62hTFwjmdAgybk",
	"Uqdilw0jlVuiCdNdA9ZyyRmtt9IWgxHKURe1oARtq2iGruIJyDdOPlAPC/LBxGmMGszVsd23UOC7wtpg",
	"1Owbu2q5lhVvzpoyq7cd9bkKCt4EYsMsVqNMqsVAmI4ByCmAibkoJ6HbcAsrURe+TdQeBtGKiuur3Dch",
	"UllRsHxsyhEmlXgVKMLpua714jU9W1RSHYGpClNefs1arX1xLRwZwUJ5k7RMunOdIlnKeDwbj/GD4ar4",
	"FMVxm4tZjMAkpiM7mYJfzQ4nEBPuJqeLKYyQnkLBlMAHm5Fn79nzUhWbX3baL2D7c6/98+Fw2P5nZ6j+",
	"75fh8OZ/DYft4fBvw+E/br57/B/L9Xvyj8fDYecX3dHX7K2Vs9iJUevXN0g37MR3mmHyzI+rvJhrOsAW",
	"n7p6b79wz538ruZ5AOZbKesIBnGsvWBCkcG4yO6w6WtiTfRupm/nmd+UMta90DzXG9ZdHLYzZcWZRJ5y",
	"xdNhXYLvDrN8Sp8cDXRWYeWUZf1V5FF683e4J/xV0vi4j/r6D2DhVKFevVJIzZoj++KE1OCue/QWPKxd",
	"tbjRGG5PeWwluUuEyDKxAuZC6hQdiOQ1nfQDBh6fnl2dHNqIFxPNZSx9DImMkVI6sGWjB4x33K+ckjae",
	"EMpQ7g6Xa9y2p07cBvuSD7RZmKxXhJUsx8Z0qEZ7NA9gw/jWHbUYpMwY+cl7ie/YDmHXEETXBItmkp4V",
	"cWQbvdpRg9rCIbiljS0/JoH/bXFxxr3zOSFU2FksosAG9zasKHav79foUIUpZNG9CvEjNu4Wk4n1wC3V",
	"dN2+v6OBwSZN+moej5792qL9YaUU8H5T2JlKWeHP9n6BRpSabCLn9B4xFJ2NxyVbWe8eYqFSoxiPN515",
	"ZxzjUJzDjK9omigtyAGt1uZA62ktK0FKTe6aPM2lZXraq8aSUqNvMzzdqvuz4IxLlHa5gOncYmEuk5NY",
	"Fj2klBfPqnZnHZITGE5VgtCQMoZ4SknEjRLcisf6Vpkgtpz3nHWGZHHotV5E6VKGNI61h1Ae5dPI/Usg",
	"Gx1SJdvRU/70RkXvvcNu4E7DGE6PBu9f78gSn3weoi8pFaB/vOpQYeNCrT7fHfCjjjVpt83aP5b9p0wk",
	"irEJES5gHBeuYdakEdIk0QYZHPttsNq2s/ZzXwv9t2z1SYwnKi/SnHCb3OqlrC4hJTxLkLK1aDtURyUd",
	"cwqchLit7VYjTOQjpOOp5aZ0dGYy3RcLszEdcJZgIaxLHCSAxhFiJkgjN6npbTcxsCiO/KE9NMSK2V/t",
	"FAuYm06y6LH5aeaPrb6W/utwlr/Il/ZFXhKPq4Fg7s3Lr0sdilb5nq/4FNYUIwu8ZVPVU/k5JpDAiU5m",
	"qNBMs0qqcHQYZ5FsUUdgfneqh0X0nhhNldxxk+XW4wJl+l3qXCnrSR96hfkQOWO61UG/rLPr0VqWTA39",
	"Vt1KXNbO+ux+ZdautANbZO3q467gWFJsbe5Vkl7RY6hyOJ9l4mxs/u2ki1vHqlUC0pnC0+rO6v24kreu",
	"3LrQcIX57cKETtvJodT6k2WG8hI5o/1U1E0PoOgb5rc6A3z91qVQTJss/wwpB30g+zjAq+HLY85fi5rD",
	"kye48VSzeQliE/iAkywpajzAOKb3blyojvARNM/vokv+5x8UhDwvrgigyglAJcm4M76EiJmkwNbTRem3",
	"dE3XInNU/qNKYn4IPnKdhInrKhUt8DHRP+i8SvKHqf5BZZDqlEvzP/7H4S+77Rc3w2H0tyf/GA6jX3gy",
	"vVm+Tv8JCal8uZYJHEGmr0ZUFTakThYKWGh5c7dVS1HSWFej0wUilk77qac6Nx/bv1+aQZqXU0kJ6gk4",
	"qHaZUx3I5OaXqKEjVEqK6fXSP9RBLEf7m2QPu/vR8/296OD5/vf7IYQogs+fRvDpzrO98Ytn348h/P7p",
	"3jj8fufZzs7e8++fHozC71/sPH8WHhzsvoh2Rztu5H/IWXAYtOX/vTx53T8FRycXV/1X/aPe1Qm4OHl3",
	"fXJ5pVqHZNDvv3z569FL9q7/snf88u3g+vb+4v7D8ft3745PdnoPg713e4PPP9yeHX/4fPr59NcPP72K",
	"f359snf6+mJ6etzbHZJB8uHZ6VWUfPjpZP/0+Ifkw+fw/vSqdz/49cP+6fEUf/gcPhscf9j98HnydHAV",
	"3w5+6t8PXt3en9x/ePMj/bk/JJ9/3TnqvfvQl399/nXnuPcuPH436Z28eTk42t85vfjh6of905/OYoRf",
	"fPjp9uWgO/hMT49fzwYXP2afT3a6QxL+eDv7z/c/oIc3n3Ye+mRv78PR6en+z8enDw/3Pz1/G7+b7ONf",
	"X5O7S/HubPS81xv06Oujo0+vLwdPX7zsDY6GpLcz6Q1Oro/6744v2QN+fsuiox/Dt0fTaPBy//77/qfk",
	"OP55enHyevRmcHRy+Z485/y815/8/Pa7d+wHcT8kBxffsacphh/ufr4VjN/uz4762ef9af/7mH5I/vN8",
	"Pzr4+5CobT85PZ5zJN/ydnzL27HSMDUKs4UUHvUxf4eiUw3Jn30p0xq7FiUE/KJATuMdq6Mh9okqt9wU",
	"GgptFuk5xV3unVwg9mGZQg5GCBFgB2hK/WETAjWp8hao0t6qAeTTpcr6lMKaQF9ymWkMQ2S6ycuoVB6P",
	"Td6hJy2gQVBZOhLEJqZuslZ32JxRke3lXOXa3nmnU2HB7hyKoYA2AFszYmCMdWizAMpCpyrS+uZvKFjl",
	"zFkqkusP69fO2MWx1TeAMrsQVTPMFMhVCKRW+XX3cNUtU7oG70wqR6QyeXrRr3apDapvfnMdt5L15a1m",
	"ulAXdBZAsog8OD4qmxKKprR5SiCAwuTEcUmFitN1qMRykWD2i5ezxTkMTd8l5Etn1Ja7pCXKuSw6gjUc",
	"hTwbX1zE5bHSrwD0dtO8kNNRg1Pr+8gNhfaprRQz7jsXX8k8t7QX18UFXETzPAFl360NU3W1AqVPuViU",
	"6+PKTUbpz/ehaJtJPdD5lVMCHttkRE2RABs+gD1bz87QvLwmjHUrUVV6dSS/qjdWGBCM3p+7aIa578Uu",
	"6OCWMrtIdEEFVq013rk7gk5lUHcm4GwDct6kyG3ouNoVrw3SRFM1I7i958NxmVtUJ8+9rPVieZ2VS+DV",
	"C1gh/z78WYvavcIxOtKZXBvqcJs0r+qIxzj2pytt/l7pkYBADwI8vr561T54IrmxStlRZxJtf4sbz0L2",
	"s2qlNdHIUZ0tbxCRG9Wcz0e25hl86js0YTRLm/IDxyqCUPZoOYpKZOLa5POln34GSJYghkPQP+6AY82r",
	"KklhGDBKxTCYm2BuQSa5xFDBRghTxIxHv6oB3AEfaKYUAxrmmcl+whAYwwTHGDJAQ5VtW3HOIEZQaSE/",
	"I0ZtXvqd50+fKnyA+pUOcWI+0Hl/fN883dt50gGXSGQ46nIkJvI/Aoe3MzAy2lmQB08r/ptQUWyszuVX",
	"WYxSG8p1yqek2FcJnj/lYMYRm7tb9F4Vof2K57lOwsCVsH0LFhaXuqxV5qJ069arAzPiNM4EOodiqkao",
	"WSxysrKK7cJfp6iWtnSCxYUE2M95laJRX6v0306siimPu4otx1pwnDznJptYUcaqIUOnbV4sfBRDlYo5",
	"14MmFD99ge7wPO5Tt0qgM+7U8J8Lby3XXA58bdZWk1WqKZvqgnTxi6ExF9Kc/NIP8RsUJ79PXad/kbpH",
	"yuiUwrDJKqulubyXL50siFAa01liUj7mhqEgmbVhmraLKTzorRTrcwQdnT+vpqpy7rcewZvn1hoe5XM2",
	"woJBhuMZIKbCuS1myivmrDxQ3L3OAZlg8qBuxiQ4DHY7e7s6fEBXljv8LUAEjmKJvBrkKeWCK/yQ/woO",
	"7QydkCbmPulmTYeCrvlR2yKDc4bG+EHVxzW6PBzCI5pJBnG/FRgpzlauCg4PdvLNPYozLhDrn/v5Mr1f",
	"8kmYEyRkN1U95pKwKkHRKP2c8wZqHJPLOIbKHKyW5rr6qLr2OrKQRYiBERpTrb9jhW5Oz1g6il8MrLJT",
	"lOk8kTOYxIFdRJveIcZwhHhnlqgSHsvWYvfGxN+sXyqroQpd7SWbCpEu+ZQRt4TGosdMHtS590GTv9rn",
	"K8+LIbtbt1dBHeWbFSGqgSUKFI7uEHP8Ae4ZFgKRjZ9CVn8K7UsGi7oRYM4jqSMpfYtnuTh0ffHWpKWg",
	"iUTZsTC2CSlFydYO6OucFdqjDYFPGVL+HAwmSCDGAc/CKYD8EAyDrsTyrqBda7z7h+r9d9Xbx3POfW7z",
	"4/v9X1iLkUuj+tzXy5MIt4zTRfYPKa/YbDBKuBFwsnTWjtWHnb8ZTQRg3h4MJDX2VEWsO7OqPporKwBN",
	"5Oe6jEkh30ismrMJ67EaJv23uj7KTKufkTWG0yOphTfmFdGjr7aV3vxDJd7tL4FVGwiQ80HxJtnxqJBK",
	"m7iensyTB+ovmT9I4dV5FsdFNHluAA3641MqzrVSNmg1xIWUtQmP3G8edcBPU0SUjl229eJ7OOOPtFZE",
	"A4e5ytKEIlNgUNUoKn91KltKHyUZF3kxN5WOqjklp54zaFUXo0Zd0tNM7k8+jvyjMpb8yYw3d5/9VJBQ",
	"odlo11FTEYcvX5XCbYG2lwb0ZHmxqV0Uc6I5Fjo22NlWxmgMbd4xl3h0wMkDDEU8s6XgH+W34ZHs96h8",
	"hR9pjHB9L3+3W98K0tLtWe9knBuojsUsdinaO28jlUwBGJpgLtisA66mmOdJ4opiK86HhGpvFONnLMmI",
	"Hawl+cyYkon8r1EgUZZwqwQqSA53PYe3+gAEc2plz+G2mirxYh0WOCeliSvBG7Z/azmFCm3lArlLQ7mB",
	"4NVYTPxw9R3Jpd2QIWWJqpLe9fcm1wR7Iqe/Ln/fuMUNGzq33vuhT320DdhbgS7HuKyat4DS1HH8i1qL",
	"MiLWFNtLPjOmlmUhmhvhwrvTy51Zsa3eAeboDAtl4eKh/roWIM9VcxWdxdHWb57/6+ICLH1XByor4Lca",
	"7e6WLCuUn8IERaYEl74uZVWbXKqHgTXMZI2B/Toy9YqytONCXY92z9ukaJKXydElpOMYpFLyUorxIk+n",
	"Yj6n8A61DK0xmjGuvtDAqPJlzPTVD6fHY4UQKorEVGv6NBWdlQhVzpPjL0cu4cGU5Fnn5zgh6gRNynn/",
	"HnKzlBU8DyMUo3XmwnGsomSRqke9/HyTUrKluvfXp0w9l6YCYSl0wRHTnZzLucuarpCjPfjAOU2zGDoR",
	"zfr96YALBKM2JfFs6WLji1zanPR1z/cXZksYQFVDwARo3KKZtjkYy4WrQLA1niibQII/61wqIRRoQpn8",
	"8zEPaap/5ShGoXhicduLVMu9n7p/LSufb13qjfMdohNZAoV8Crl21LO/tySHMFSRBl059zAA+iCa6ke6",
	"la49ExJAU/gpQ3ZT1bRY1aTI4+C0BeIRL7JcOC6PkDjrXrfyjOMQWKdilzoQHSmvRO1BM9REeRjk2cJ5",
	"nn6Zm+4RuMPQJHqgDLA0aVMuGLKKFxO1LgdLYXhbHY5Q3a89ghKXylBgDuAdxLHNvm0VNFYhagZcUiWj",
	"V9833+q/zu0ITVt2DkU4dYL+ckFlbvrCSnG+BoJlMhBo7wJTKsZdJoyiII82UP9K6J2iWOXM0gUi+j0v",
	"euCHy7NTcK4ZrVwT7rcY+0HVUVpSQIjcaIVO7V2l6TyXhnqyvEVupj1lnDTOph7Vhq2nlVfqRw8ozCRR",
	"TRlqO362U0pvTUhuy0YvWAJcf1bRAxZHXo+zc0ZDxDmQPUCofLOsT4gzhd8ri2YizbzLiGCoLecRzUSX",
	"iwgx5qTdN4Oq8GFBBYx1VSoYMso1y6B7qAiYEKaptn48/RG/7AAtbeYpVsHj85MBGMU0vOUt8BJBJnFC",
	"GcURb+nyVkDQW0QAInda5nhi7NAGTGNmtowNabIdNij5zh0vILVnERqrKoGUgA+9QW5M1JqmyN0C8FjX",
	"sld2bNBFIuzmYbFdORbvRF0Nnj57TCbd3Z02QeKesltl5H6ymNc2kLcKPFiaU/Q5Sc/BWx+WahReDlHN",
	"ufvr8Js9Y2o2+a4UQ2uHgc1UL80X1Zd3OAtD48/hz7SjWOX6bvA8AsnEOBUXb2eJGCM77dLn9y6DUYzE",
	"7+PqtMlgJ+TuPWR843GkiL7xIB658K/qyrXO0POVyV9ulte6XhhfH7/u6qKcUsC4BSnlld++3cQQ1L+1",
	"OlkrhJxSYbhjSIzFTDKuqr+VrOgdYo6rSuGfxlnYxSRCD51f+Qb8qlVQ9GLExIXJMZQ2J56rr3NaLlxY",
	"ibNSXm1ybH/QU2P6D5sYRMWbWslTboajOIR3iCn+lxubZV433ryeamJMJh3wSkkWh/PTfjzij8r5PB4l",
	"j8r5PB5NHzXm8xgOo++aU3ikiIWICK/l/kp7o5t2uWt6RTrsieHJBDHu3UktH2sN9B1aOxNwCQkuzUj+",
	"TEd2GufsSosrC7o3a6FhCQJPqVXdWsMuy9N7K3uonHTLCTGNsBQDN3ZxZmzso0FZtBO2voBcP5brTzCB",
	"5ocEpqmJfTk6v16NQqeZTyfZCo5VjZlV4g0bEjK1goGpLLPCYM3K4EJZOTvV+VVcLa3k+Nd/ABs2Y633",
	"ad4K1onmbNhd+cw1qqyXxKm5yfP8eaVgyc+/wh/bp2NeTQ7VCTDZqwPOiPEh0L+miAFLWJRCQpPk7dTp",
	"KB42H8csX1NMJn0ptXuzU+Tv0AiJe4RInhlLfSoX8zs8LXmeqKb3ZY4do+Wej2fFS5PoxtqxOv4Ta35J",
	"ZMx4tavVhKoAnHrIIkoeWd9coN0ZHEXlV8ySE3qVDJfZZKJ96ZV7sIErtJFgSiDWoa0tsKMr1QnAtSXQ",
	"VRjv73n1EN9S82w1NQ/nXs5pGe7TzUwp99FqBBvUzP767j2QwHCKCWqc6n46q0wgD9oYwYeqCG3G0DCw",
	"dVBVVhDZX6MA5gAlqVBWCmaKoZcDrnMtLegBXYYehDFkWrltHe65TY0RITDKnNS2NtgAYLEgS+a85OLF",
	"5oEz5QJ2CIbBpZb/hwGgzF3pV0cbnqKwDUnUbiwtu0SKI7NwQyZyDCiQbnkCqSsN9FThLrlvqNlMPcWT",
	"aTuWK9W1DlS1r6KeTUkVryuBKdBiqoJhlWdM/vPYVhm2g6gOESr9mUBJnAgkRs09ZohPdVO2UlrQ+ip7",
	"FpB604UDcb21X6yh3pjXTm6Y0C6s3nxcXnm9w6C0Fz6ond2pNy9MVWo+OVExVQsQQQdelbMHKIywAfAW",
	"C2yEVsv+q80yYsyrMSa3qkn/w2mBMYZcHT/XPfQ/nB5yZhzq4ox2Bkx0RtAgN9Sqn3WiXe1cO4KRgzqt",
	"YDXscbbmJF9XY9tFDmy9y1u79KameR/3zO7UWwZ2v5qa5g17abe03nRcbHK9sV9se73xtXMQHgRzjqbe",
	"+hL6vypKHXj2Xr5GC3H8LYXRAgyXFGAJ/OYiG0kMpqbmA6GiPaaZotEjGLU5EuZCI1P6QWflcpF7LUqW",
	"L+FSQ1D9+a2FqNpwSsUrA2C16SWMLnN4q422dEX194FdT62hgox5w7KUyCl+U9PuwYKwbVJfp/rqVT0e",
	"vI9gM+9mA2JVCt6S3vMsReTy8o0x5YMIokQ/146jws7TAw+Lgwrk3mSlVbL+RSPtxuOWr5Iy54zyQX3X",
	"6l4zEC21Scbtz3rGFExEvnEsI8TyAoWrytOyoAnbn3faL9o333mVmHIiPzR5oUibomMYcD6NOsa/aRg8",
	"qWivncaFbJuatoxP5dN0T6BVwmhnF5fm465wgn6m1tvaRt28pVqtV1k7ThD4rGqYW08Txo3krxC43zvt",
	"Gb8W0Ls46XXfnh31rvpnpy1wrzh9+WM5j7HkhjFRuXAYoCGCRBdTt1/m/qQqjzVkAodZDBngWCBlv8Mm",
	"BAkyBFvAteb2lKsp7J6i+39+oOy2BU4ySQ2655Bhq5jJCExGeJLRjIP9djiFDIYq3NSutZJgBTweBq8H",
	"V8NAnvr11ZE57OWyWF/XChxUo1XGmFjvHdNLZ3jOBJWiUZiXaFB6KhL5ijsInNhW6xSrlkMzX4aq9Vwh",
	"jxglJw/yHK3igQvIxGsGQ+SmOV9dFWg//tIKhIObKw+UI3ZNLhKBF9qlr8z75M9vzM2NsBXzXTaKMZ+e",
	"UybmpBSYUi7agrYnKl+hqhJjlPBF8ob3gw5QRZYQEWymfUodSmCIwFClVJDTHarB5L+s6Fxv6aaMChrS",
	"eBiYQvzD4GDnYOfwYMd+ZP7sijA1Ny9XmlZK6N58d6j/87j7WITpf2VR+l88FOmTdUve/smsz8uYiKtq",
	"nfcDcE/ZrWJSrbed8RV9pbxejkRsSmgp16D3A9eVxsRsRSjGdyqDouPg7wR7dvPAL53nSoe1eIOYwCvK",
	"bHteldwkrNKOdMZZWbvumGiS95gJIP8ng/FAK6q0m4+yJRPtLZ4o1xy/q/Ei3+7axRjUnc41WTZe6cva",
	"yfU4qRMwUoS/KV8U88yowTXtLufZCJSHkkpw0pXgdKJDRtetU/FFZUXRxWkUHKFaOkogjoPDQCCY/Idb",
	"IyCwDrWKCdIIA0wyYnCFYCKFEiY/tfqv0tc1t+BfykPcPPZ99sRokE0uTFXIAYUxZNrdwHHupGMwjhES",
	"Sn+HoomNxtHOxmKKMMuxn+sqbzEOEeHIKWfQS2E4RWCvs1NbzP39fQeq5g5lk675lnff9o9OTi9P2nud",
	"nc5UJLF+uYQ6rsom9c77QSu4yysw2KILuoaVxMPgMNjv7HR2i7wzvwVdJ2OjSa5qFdo6q4yvfMSRDoyD",
	"4Kj4+FJ/XNSTKIxcua6zH+UfN34ZaPRCXLyk0aySEdG5591fjXpZE7L1GI1GIL6U0dwEaulif1zfwr2d",
	"3T8UOt+RRPK0n+7sfF3A8rT3NShewgjkQEpIdv8oSK4JzMRUOfabTdn/o0B5RdkIRxEiGo4XfxQc5YKa",
	"Cpi9PwyYK0rBAJKZRReVcfbZH3dIl/oNuCa5dUjzaXCiNFyNVDK4kd3mUNHub5L6f1GhqMjrXQsjLZPl",
	"sY2NF79OTF8jMY+SFkmLPNlTqqEqi4k5EBRMtOEWyxFMxkfzvJkAxjLVbDnHVdUkZgR/ylBf89g6oPKm",
	"RmR3/kRE9uzHb1Stgao9/aPgyHXH3+jZFumZ4W4N8eravPaNVOw1EiaHm0mAb5LIN7OBr5GwKfV1vv1V",
	"yZX+ypCk8uS86oC1HYr1pZ6f6coW0tSRKKxcJCCfViWFK+b1FhSYN+/vThbNkTTSwD194atXETgZP/5U",
	"ZPKPJE+goE9/HPP352X7HKqkiYafBBVuNSkUoT9Vhk2D4dRROF5Eh9RnpYof69Ehl0dSEG6L5tysIhC3",
	"1dTfbeEMS7GkS4nDfzBJ+ib2fmMQF1PgbxxihUMETSxiToxbgTcO+NrUDF+V4F7oaOwtk9yiivfvTnO3",
	"SNe+kdi/Ion9RtqW5+qKgOnlzQwE+OpVz7cv+CpM/25Xuj75n8Ge0ADVNzvCNzvCv4go+afmp2qUr5Ei",
	"LjIZvFZlbVciiq+R8FHElbiu5vm2ahf4A7RdS1HGb8r/b7LdvzQt+qLrCVlioB1UujDF3btdnYpZf11L",
	"xmYpDQeUVGUz5WJkCIFhBOta9PIIzXTGHay+hC83X/5/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
