// Package pam_issuer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package pam_issuer

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/auth/.well-known/openid-configuration)
	AuthOpenIDConfiguration(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/auth/authorize)
	AuthAuthorize(w http.ResponseWriter, r *http.Request, params AuthAuthorizeParams)

	// (GET /api/v1/auth/jwks)
	AuthJWKS(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/auth/login)
	AuthLogin(w http.ResponseWriter, r *http.Request, params AuthLoginParams)

	// (POST /api/v1/auth/login)
	AuthLoginPost(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/auth/token)
	AuthToken(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/auth/userinfo)
	AuthUserInfo(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/v1/auth/.well-known/openid-configuration)
func (_ Unimplemented) AuthOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/auth/authorize)
func (_ Unimplemented) AuthAuthorize(w http.ResponseWriter, r *http.Request, params AuthAuthorizeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/auth/jwks)
func (_ Unimplemented) AuthJWKS(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/auth/login)
func (_ Unimplemented) AuthLogin(w http.ResponseWriter, r *http.Request, params AuthLoginParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/auth/login)
func (_ Unimplemented) AuthLoginPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/auth/token)
func (_ Unimplemented) AuthToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/auth/userinfo)
func (_ Unimplemented) AuthUserInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthOpenIDConfiguration operation middleware
func (siw *ServerInterfaceWrapper) AuthOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthOpenIDConfiguration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthAuthorize operation middleware
func (siw *ServerInterfaceWrapper) AuthAuthorize(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthAuthorizeParams

	// ------------- Required query parameter "response_type" -------------

	if paramValue := r.URL.Query().Get("response_type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "response_type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "response_type", r.URL.Query(), &params.ResponseType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "response_type", Err: err})
		return
	}

	// ------------- Required query parameter "client_id" -------------

	if paramValue := r.URL.Query().Get("client_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Required query parameter "redirect_uri" -------------

	if paramValue := r.URL.Query().Get("redirect_uri"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirect_uri"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthAuthorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthJWKS operation middleware
func (siw *ServerInterfaceWrapper) AuthJWKS(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthJWKS(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthLogin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthLoginParams

	// ------------- Required query parameter "client_id" -------------

	if paramValue := r.URL.Query().Get("client_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Required query parameter "redirect_uri" -------------

	if paramValue := r.URL.Query().Get("redirect_uri"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirect_uri"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthLoginPost operation middleware
func (siw *ServerInterfaceWrapper) AuthLoginPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLoginPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthToken operation middleware
func (siw *ServerInterfaceWrapper) AuthToken(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthUserInfo operation middleware
func (siw *ServerInterfaceWrapper) AuthUserInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthUserInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/.well-known/openid-configuration", wrapper.AuthOpenIDConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/authorize", wrapper.AuthAuthorize)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/jwks", wrapper.AuthJWKS)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/login", wrapper.AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.AuthLoginPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/token", wrapper.AuthToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/userinfo", wrapper.AuthUserInfo)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RaX2/jOA7/KoL2gOsA+dPp3h4Oebpst4PN/NkpmszNw3YQKDbtaCpLXklOmh30ux8o",
	"2Y4dy2mymNnD3T21sSiSIn+kSNpfaKSyXEmQ1tDJF2qiNWTM/fv645v5HZhcSQP4OwYTaZ5briSd0Nfz",
	"97+Qj7Aib2BH5mDpgOZa5aAtB7f9AXbuL7eQuX/ay0ykXaZTkSrN7Tob0QG1uxzohBqruUzp04BGetPd",
	"ciME/h+RqNAbIJJlQC4SpcnNNUEVBgRG6WhA7unt8OqHv9/TF0HegRPezacEHr1tPEt8gjzDLB543GWC",
	"1pn9FKa3uzA9UgZ3yLCSmYoLUZhTdCxCrkSZhQmLfAxY/Jo8DiOldMwls21rh6Xugkx25zB5qp+o1WeI",
	"LN0/YFqzXZjifQ5y9tO1kglPC8287ENVPBG5VlJCZEnUoj5ENSvsWmn+u1tdgoxzxaUNILlJRyq6MKwF",
	"45lZmiLPlbYQANG8WiKeFtnUYdXh1zbLgKaaSbvEpycKcRscCs+UxOOlVQ8gl4ankst0yUS63DBRnCq5",
	"3EdYlQfOVcCYAnTAxbOfrolfDLrg8/bBLAvNA2nu45v5cffpMkWeY+Fqzx8xsonUyXI87Xn8vQf7kb3A",
	"9eMmabNYYswsM7BrFZ+oN+4AaXnkw6fce945CgOay0QdOcoHA3omE3XsNKG0MrfMFiZwAPeccEMY0WAL",
	"LYlDP8HkFjEhDLFrZkms5F9tRaHsGjTxzN0RDxJOzv8F2gQz1/R2Vq6RGBIuAfkD2fhnzv94mxOVELvm",
	"hmjINRiQ1ptVJYTJUvKIzEHjRmLWqhAxpsENaNQyUqnkv9fcDLHKiRHMgrGESwtaMuGPOiBMxiRjO6IB",
	"+ZJCNjj4XDAi75QGgs6ZkLW1uZmMxym3o4d/mBFX40hlWSG53Y0jJa3mq8IqbcYxbECMDU+HTEdrbiGy",
	"hYYxy/nQKSvxUGaUxd9pMKrQkUd+N9+qGELgS1MwCL6fF4vbyjlI67zn7GecfwfkkvCESGWJAQeZROmM",
	"WTqhXNrvr/Yy0TQpaF8cyFB1wGXs4eLVK+FS+wkfoanvbuYLUp3K6+Ldtic1ew+i9blMoNQ60SpzXCqU",
	"ux+R4FjXmGKVcYvQ+K0AY9G5I3LNJJ5uBaTIY2YhHpGZJNcsA3HNDHxz/7msOESThT2YgTEsDThxStZF",
	"xuRQA4vZSgBpLPsogNKJdUxgrLlw6EnuzAQjj2QsWnMJvaK2692BAHQ0l06He/qKcVFouKelPiMyKxXy",
	"EOCGQJZb5AHa/ZTKWRyRhszYhnGBgkdkSu6cmlgdaJ5wMBjXDsblYR2MVwVmHjAOuWoDWvMYCA+ncHM8",
	"xZW23BuPvJdAVDIh93ReRBEYc0+J0s2TfnPYmByiIZPxsDRpMJkj0LnG6+fXZm4tI7Q+eJkmagTsQfcp",
	"cCG4O/HOh1Cg+sBi8Iq4W7EKtE6e9/G4DPUQ5f4yYn03IQvhvE8nVhcQrCodPwORBvscT09FLpRbZsKl",
	"vLxYCeyrHIkvyo9LHdCt5hbeS7HzBL3Jtl0d10m2XVy7x64WPenA+zK397T7whY5giwyRIGGRINZ+9KV",
	"DmhXi4bP9/JyZsxW6YC/bssVb8Xqhxd+gcFXGIgxFbiyNBFq+0et21a92xz65RJ5qE1rwxnGdYVkr13d",
	"6kl8sCjDFj1ci7nm/asa7TDiGyA5Esd9M4+DQC7JOhWbS399Pil5eCLPKjyQ0Frp3u1u1QVO/+Zla+dR",
	"Ro2lML/HnGswSy57+wGk8OFseYZZHpOKat/gjXroGeSW2ukmgI+0GuGo95odhvuPwDToQEiHKv2qQziC",
	"CYRj3Uj0ggIyxkVgDIKPCYtjDSZc67iNyw24iz3u4+DXy3apc/2tlBLA5BFY3RzHUzhkXxVCuIFbcI/S",
	"KZNlFjXheCctmvPau1xDAlpDvOzPKbcVDalowkWeEtCnoVs7s0EvVqH2wtfrPMaCJeHBQUQXgcgOokJz",
	"u5tj9+X1XDkIY4jsf72qepDXHxd00JliLIjHfZm82g02lj2OO2LFh0etCRZqzp245QrludzbmYVdlxd9",
	"6+EHLeiEYq023rwc49K4Wve1lQvvAFV1F/sBRiOA6LRKnM6nxD8eUJUkgktY+rzaufvKxwOqcpBYYx1O",
	"/fwF56I24XibHAoqF5o1OK2hc0jsH1fpqfd8TYd78z55DWdxqdez08qOI1vbA5JHWxBi+CDVVo69MYaH",
	"E89KpZYiT6gsHt4Vq0pa5rWr/GKBZf9MBE/XNrJixBWt0gZdrIG8ciuottVKkAWwjA5o4fSreoHW7qdD",
	"DN9O3w1XDIsAl3IPRkQG9IZHvnpoyxrdy4Vr3kuKXKsNj8EQf8eMQ9wKg5232RkLGbmdviMXt6JIU9fn",
	"Tduk71RcCDAvRvdoOsEjKK+J8vDTnEVrIFejy855t9vtiLnlkdLpuNxrxm9n1ze/zG+GV6PL0dpmwgGJ",
	"W4fKAzuibjM31yTT2xkd0E01K6Kbl0zka/aywhTLOZ3Q70eXo5eIc2bXLq7OA8fkC03heVTG3ETYYe5a",
	"k7W6W5zFZQ8Qms/vJ6pOv6vLywpx4Gd4LM9Faf3x57I796Mp/O8vGhI6od+N9++1xuXgahwS53B9xgsB",
	"F7MsNa5/bAffJ1zrSXa9hivLweDrgm5TVPZKQm3DBp02smvONMvAgkZdewusxiDaXXO4+FsBereP39aE",
	"mzYLal9y741f1Vhl7+yzXKjSOqXFDamy75KPqXGqOA0x1+jiD3ez/sN7Gvd64JjQegjoCU/Voe6dQsKr",
	"W+n8o2ENCKSGQK8AJDsq4NOz8Wjh0Y5dnmoF4iGjTpi9VSl3XWlGfl68e0sueOJvT+z2GqEF8QvMYd9f",
	"XoU63NKDVh0ESs5SIEqTFYsecNUjBxn97StmlPJNQOB0P7K4nvU4oS//BKEfZJ1xYpT6w59y1Fn1BsC4",
	"AbTvKc9LlJ+3D6Y3Rx5+akAuXn98M3/RTpO+ztswweN6nNvNj7jxW94wrW8mAqbqfDVxlpUERkyvmRrx",
	"1LJM8Irpv0IcmxOvj//HfP1fl1j/QznvGLAHNFehSfmtVq6PEvsTuBdUxvRGtDvsrXIT9VL2jyreHTnt",
	"43C73Q6R+bDQAiQWK3H7+EdG80fnwIH3Rw00hgg8TkIrzbHG8aFmTdlQpjvdbO+qB8gNBJ55w9ZJZsvt",
	"mhhwTvofv2APmr+EcYE37TlJvJ54hkOgNWPuNAIN2UzG9STajTrC8bEoJymnxcZ5dmq99sKDnhlmZ/B+",
	"Frxf8xZvvwYIwGDRfgPwlTH/rPiT8+wh9qpvYvrb0dY0uwU/DVZz2HCZ+iq9MQgLI69i8y3rrc58PlQU",
	"H2j7tbPFSTq0CvPGVNfVVs157q+fsDLo96jb677zcFv9RGlMG5vCGSU456qd5kbcZelyIPPp09O/AwAA",
	"///jN8H5JSwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
