// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9f2/jNpZfhdAukE5XtpPMtGgDLPbSZKbNdWYSJJkuduvcDi0929xIpEpSzrhFgPsO",
	"9w3vkxz4S6IkypY9mXZxW/SPZsxfj4+P7zeffokSlheMApUiOvklEskScqz/PJ0JlpUSrrBcqn+nIBJO",
	"CkkYjU6iayg4CDUMYYqw7YvmJANUYLkcR3FUcFYAlwT0fEVwntsl1KNVFyQZwmYeRpFcAhJrISEfo7dM",
	"ApJLLBGmawQfiJCELkzXB5JlaAaIrYA/cCIlUAUBfMB5kUF0Ek1WmE8ytpjgohhnbBHFkVwXqkVITugi",
	"enysfmGzf0Iio8c4Oi2KW/1bCGzVG7G5hhEXRUYSrFr1urTMo5MfDXIFRHft1eLow0h1Gq0wpzhXGPrR",
	"rXbmBhkA3LxnjEqgUsGCs+xyHp38+Ev0Rw7z6CT6w6Q+xok9w8krkoEb9Bhv7nsNGZZkZQ5bdebwU0k4",
	"pAoufXJ3HfS04HtJVz9gbo66cfBQN+A0Jaovzq4aXVpHEbew/ZKuCGc0ByrRCnOCZxmge1iPVjgrFdkQ",
	"LmJEqIILUpSWahrESypJDmOkDuse1gjTFJkRgJMlykshFc3MQD4AUHSkOxx/8RwlS8xxIoGLcdTZdg+d",
	"ODRccbYiKfCbApLhZxXAozqFJiJxTY1b5tLdHuNIkVbPnasXRKpXhY2j//3v/2niAGWMLmIkJOYSPRC5",
	"RBhlICVwxDiiZT4DHmvcJYxKTCiiDD0siQRR4ATGg67aLxGjMABRFzleQB+6t1H5Bc0I7R9993i3+Wxv",
	"JJalCHME06b4AUaC0EXWxLHlZSmsiEGJYxFXHApsecKNQrH587qk1Pz1knPGozh6R+8pe6BRHCkGkYGE",
	"dDhfae7AX7PT6AHRaauh6jQ5MDsNNdydJm8jTUT/wLLSUG59fZroPoc5oSAQ1tSbopUegUoBKZqttUxq",
	"suTmVQpfjHeU/FSCuQ+WsfvzKtonNMTvn5i+zfZbxBk3eLLewN1jEG9tFtTcutmR6O7+NRFS069Htraz",
	"2iORkIsBvKd1hjUuMOd4vZV/mmGGPjbfsic58redsw6fZxf3m7chbso8x3w9kGVkmQ+86GcX3wHO5HId",
	"xdE5LDhOIQ2wiJ3ZQhPaeo3eLt7ivX0CHKHZoQL3UfE0alSDLpqqJidfBEpBYpIJNGccMQoIiwIS6c4x",
	"KTlXqoKQWNrDJQKdXl2gaxCs5AajTerIsJC3HFOhV7olfXJT9UNKrTArVaDJaiykaM5ZruES5oSVSkuZ",
	"XAJXC88Zz7GMTqIUSxipuboUF0c5CIEXASi+K3NMEQecajXI9kOEphrJdFFhB89YKS3EFXjj0GJsJoCv",
	"IP0WKHAcPga1+3EOEqdY4vGi6mlU8iY2HrBAAiSaYXU5y8IsW22cUPnlixoOQiUsgEf6mmERWvwUfTbj",
	"BObPkOmhT76x5oEYtFNRMZZNbKwiOcuHKp41cJjRv1psQ89QQRCHSK5CQH3+IT7TBm8DZ2ngKNZEyebo",
	"lpcQo1c4ExAjew19LqPaozjSHXbmKy3o7FytX93UrZ+DLKHHBLPmV011hKIznEN2hkWDZ54WBWcrx6zc",
	"n+dAif7jFSaZaUwSEILMMmj/w/GNK8yF7nqzpon+43IFPMNFQejiBjJIJOPqbH/AGVHN1yzLWCkvlKa5",
	"4CBU27sixVbBUhLadX1TZpIUGVw+UNBznGvmfw4Jy3MiBGFa9Rp2Bi8pZ1mmDKZr+KkEIb2NnymuN1fM",
	"Am7IQk26Q58Ka709KnReQ8EEkYyvg7hUKOxt6CDcb6yQ/yoDkD0noNscbvU/QmdhcOydiPnBPxfzy9DT",
	"MXQ7J4u2EjZM/fuWyMDwbXbN9+UMOAUJ4gYSDnIPo2iPVb+TsggN0zgoSndibxhVRNC1h5sCODfdtrtb",
	"uJ1XSVU7aLvK5s9+F9LONztHujsxu+SMvvxQKFoKay6cUQRVB2QEoJZdau60zJS4VhqAGE+p2qTtQQR6",
	"/zmy/70/QSP0htBSgjhB7z9/j3IskyUIdDj64usxGqHvWMk7TcfPVdM5XiukvWFULps9jkbPj1SPYNPR",
	"sTf4rwD37dm/HE/pTVkUjEtIkTpIrC6eAvW9gviN7Ynp2vpcPoPxYhzraQhFSwVyNR+sgK/1b8/Uuu9H",
	"70/QNaaLetTh6Kv3GnFHx+j0jTr7r9DpG9M7fn+CtPHiOh/FR8e2t5DaM3F0LJco1zg0YybvT9CNhKIG",
	"a+LGGGDaI26MTd/cy1c1SpSg/cobMqUvjfNRYQ4djr6Kj74cHT+3RxrUTc5KIVluGMsFnbNNHrO2elQK",
	"4KNUG8UpSvREyF4wewDBJVv2rz8JoYYYFeEaTbJpkXS0EgN4FzjzO+KexxgVy7UgCc68+dq+LvID8PC1",
	"Or26sG0otW4Abb6Z3yBF5uJWmn+1snXFzJWtaOAeoxul+HKBxJKVmXZhrYBLxCFhC0p+rmbTWrzUFoAE",
	"IZFSWjnFmUGu8X/leI04qHlRSb0ZdBcxRm8YB43XE7SUshAnk8mCyPH9V2JMmOI8eUmJXE+UncPJrFQ3",
	"apLCCrKJIIsR5smSSEhkyWGCCzLSwFJtWI3z9A+OM4rgUd8TmnZx+T2hqWI3GJmelsArlGkGtQR0/fLm",
	"1mO9Cq0Gg9651shUiCB0Dtz01PaQmgVoWjBCrbmQEW2llbOcSHVKWn1QeB6jM0wp0/7IUslmSMfowtfu",
	"PjUqFfbESKEsjExnB22zCC41jt6AxNr4sDJw04haARlurtgx1lZpiT7vJlki8MC/673HHWdd15MU9qi0",
	"7FPfmbbZa6aNn3Qdlv7GzWz1fYmJ0sLQw5IkS4Q56OUUyQ1cRvuyA3z0bbWK64OcaVxZnOHZPRt22JmF",
	"3cqPcb9/rjbqbJfK9aUvWQuu/dx1bXvXc9p1PGDuvDyEVpsfRFdNb1BIqgnTwdHPUjumWj7KgLOsSabE",
	"itKNZOpLO+M/cZxPexV8n+iTeBg2uwrb+N6KVaOH9yHyzHOI1W4Bgy91n+Zk0UUbB5oCh7RXDF/bDk7w",
	"9s67WTVvr7Nxk4JlvRqGbfYVDev90D8njFJIrKOgOuzuvoVR1i/Ow4zINqOLc98H1VohTBhm5BtPdLTo",
	"vdL1qlUco3asTcGt8HwP6z83gp8JplpaKo4gGSKUSIIz8rPxU1ahauA5oTiLK5glc8NiBDLpOy6cXtJs",
	"HZ1IXkKLNFu7ij0E9h+lbzd3EeEms3ondiSVNq1tpzJ0z1BivgA5TGz6oNzqcWHvnZly2Ja8ebpsvICE",
	"zIlVWlMQaoXO1nKQS5Y2r5Tv03pHQbt4tP8qkYyvr0E04NvkHtoEsTfzpm7NVSssXCg5yInsZeqW2bV4",
	"EXHDujv+SGZemy6akdcLPQkbD27abnE/Tr5hri1u3g04rILNWIimz7OOzr6jwtnzO1FRC+BqiWBrtW6w",
	"tQamp9mDsELYazKHZJ1ksJf0y9zoJyW19uR27Y8mtNZe96Ow0CR9pOXnOIUwVrMjd3LG82zPuOkcbf6y",
	"I5m1oG6TSqu5AUWgPQTalm4NorsUzp8Z0kRMKzJNM8vpjQBBlzeV3tDL4/Jg4O+2MYnuZK0rjt5dv96u",
	"aZl5+wnjUux1hS5vBm/hh6am6LYRvBe65ZwsQMgwLlLd1p7L+OaQWOLjL748wYfj8fjZUNQ0F+1HVBWM",
	"2AldlXtmm4xLinIYO2jC4QzIlIj7jxmfQ874ev8ZWqhVu6kmtdANRe3maIBohAMMso3zq5st8VfM7UU/",
	"40SSBGd7502EAPXTMrqt9eKhVg+gULMDMtTmh0s9x1EPW2oxJbzB+Vobp8PyhAobAdorU6gVdWq5HuLI",
	"WJL9gJj2PWAIBr1CyytTSfQkhDhsJJKsalvQGkHDYWmauAEwWhbC7saNTvQYCIeVb8ZZZrhWwF5VoDXu",
	"oA2z2RMpTYLIcBy0Am0hLJhk8LTHNjeNSABXmxCtEGEr4IhlsrzCUgKnQeeTO1ndERW2Z2MzHX+VCRI5",
	"OEpKpBbRscmbZVz/X2mJopzPyYdY/YSRWEKWjYRcZ4AWGZu5xTT8enW8wIQK6VKbsjXKGE7BLKFhyvGH",
	"10AXchmdHH/xZRzZKaKT6L9+xKOfT0d/Pxx9fTKdjv4xnk6n08/vPv9jSOpuz9UzDvkrlpFkoJB4540w",
	"ZPXYy//7RKrf6nt4wvq38NIELZNDdmyOtelHMuPMTWSJszpT7GN5olWJfNZYq/478IGu9z1wF3DXh7jz",
	"7C0frGF3xg0lNqTieWeg8Wi85M4fq/AYTMTz0TuUQ9u0wI1yYRBjrR2kSrt0puVeFr6aIcNC3gDQIXmC",
	"lixMWhxQ47MHx6eGJwVWttde5uKOAqAa0xABu+qEmmnvQpwdgjTc1AXEB0xQ96/YVboLp0p7ImnezWhA",
	"1byJUfhi+mj0ya8iY302Nbw11jxS8ymgX4feP6zi0eoS8/QBc9CBbZPfQejCijbUCDU/fbjFwuDSZ5/O",
	"U/cEoZadErvDbrhLnXIVzuG+hhljNhntij0Ah/RyPt/TSGnA6q3aafMACbQ2TZBGkw9uoLmxg0B7wIBp",
	"3PZh6S+XhQubGOrE0sT8QSD4ULAqSgoIL4DK8ZS+xMlSvwlLGOcgCkZTk6Zdq66GTG2SR4ILPCMZkevx",
	"lG5PpDGbaFB5wrLMPE+rsiF6VQ0FZG/YTUmX04V+Cme6BC+Fn+DQM4fXQ0lzk8ll8dRJ86lnVucdCo59",
	"w5hEF+e7TGXylIZw9k5qlBJljikZbId3eVlxrhvHuQaC106j8BFaYaELRdw8vn4+0tGKt0SKCt1TOw9z",
	"TPHCZPprPmlkhn4CmWRlqloelkDd7y63aQYoZQ/UWg6Kr2tBBWmXBF2/G5OmuFXfMJupeldyd9/xj1vQ",
	"lu7lqTQwPX1QqTH9U4qrxmb3E1fdKXbw9dcIqxz9xS07x1JdgctSXs7t314G9T5yqgGkt0Sg1V81OLiV",
	"yt1s9cUNEfdbc5R3TguO/8XymoMcxVqmmpWYCTQzIeIelcL644c+3k8J1zn36+r1vnMCqembc27ey4Zn",
	"5uel/yppjstMmUqHSl/uQpTjDyQvc5TaQQhnGXvwM7hMFohkKLEPUM0b8WpAzS+FZcEpwjptlamLvbKx",
	"VlB7tHPP1srmVfZeSYkcozo3uvpRIMzhBL0XJs1YgLInRIze5+YHkzmsfliaH3SOtD6L2pfz2V9Ofjwa",
	"fX03naafP/vLdJr+KPLlXdCV85ImTMmCIWkIYPsaatRZJPr4sMSt9FmfGRQZJkobmmEBX74Y/DTFLHVl",
	"B7t/f2MneYy7r1e64He6NPOLbWaI3gTWz1pwpg7cpDZsdPP8nnf8e97xv2HecedC7ZaC3B2+RzayhTSk",
	"zPQ8aMPZANbgutbvh8O6XMUoPE+l5Ri69Ehvuhl2D+c6sFyYV7kglEIul8BtJNhwpyUWaAZAkZvAO/MZ",
	"YxlgajyNM8g+pn7KqX6My+bIzKQN3aLI1o619D7q6Bye3edOJ1Sr6sP0qv6j7io0WxbdduJenOBjz/60",
	"J0tBi38sba66f/oPWDQOfpgL2I34pi9Rvplvr/oO0CO9WWN/SwF1LN7xCPYI1gQQXx3QOEhrYQM62M1I",
	"Ha+jWbnT90C4bBsdvgikaQgePoKrl29GWqGCFF19f3bzh6NDlNTPZZEw72V9mgpc4GY0bPjzj0/BL9wL",
	"fxuwMOW2PBZCRBXiWAJFSqx6R0hEiMH18BiF1UHspc8D0NNxNzrsTNJ38Y0A2oudeSG3mji2U5SiHkh9",
	"ggr71jaF8boFMiC85Y8N0vVHUEJn7FcsC+IhMY3mjOYklLWZbBqvDRYk4YNEn727fTX66hliHBnzpUKw",
	"t4hOubfLhDCs+jn7ZTsdeOZY0MGltt//OkC1Vu8BuvtecFYW4V2rHRwIpHvEnkkLRGsk2FVRsuW8gJME",
	"XZyP0bmxtLW+MI04Y3IahbVSlsLGpQvgNgkFqb5j9DdWamXdAGM8sblSrec4JxnBHLFE4qwuN4a1dfoz",
	"cOYe3x5++eKFPj5s+HlCcjvAvBkIjXlxfPhMWQuyJOlEgFyo/0mS3K/RzBroqMoxHqOLOVLWQIWx2Dhi",
	"m5vRNqbap+KBNcIUeOH3YaUAvhFb7IEC/wQH1Udzu7m9dikr2KDobZ0bBSeDNQirO9fjJgpXT+i8W1wQ",
	"ea3ACB0BhzlwoMYNh9G3RDaTmbQIhFA6ESuprGtlOh/VpOOiUn3ccx4jNA+EKWJZRa8ayqIroqGukRpa",
	"O6f0kg2ZWl/Jfoedc9PZl0tzsnDQ1AU7ep5Nuubtmmc9VWW8B+c0GtY1rEh/sIvbVgV0KaC26jfC23ll",
	"VgHfWTXucz1uKqDo77aVgDiwgljsCDG0cE9xjQ4tL6UsBhIzRd/d3l4NJGdFkOHKr1vpVzKPfp0w5SBL",
	"TuuwmwZFwAq4R9Be5daPoj7epT5HPFjYmrI0QRvo0qTnhTbPK8Xg3fVroxknLAeB8Fxa817pEzojH11I",
	"/TDPhOUA/VSC9pNznIOurCnKZImwOEHTaKJocCLZxPmq/qJ7/1n37mPnvRReHd+vT9SOIkMrb6zeuU+x",
	"1FClxE4IpucxwrV/Oxyt6pfl9iVB4MU3KnByPyia0ffYohctV2WW1VmVtQS5mL9l8sqYLh1h4jIfmjrA",
	"gT/mYIz+qowyZdKpttPsAa/FgdFlzEaJQEWZZUrT0LVPTNncxqi3qqUxSBeMxZl5ea+rMfdXLTRrRnF7",
	"M3rWgXEDhZ9qHvWP1lzqJzufQ+mQcpgVcQysynmjmcbwa2SrVBqO6MpUF6woM+xlIVg2Wb/ly3cgsri/",
	"ImUX8EBmrf9KyXJLE6u4PLsY6RAZwcqM18euFG5leeIkYBMXDRreilGP5PXG7H3cclW3A6bEE0YcFkRI",
	"vh6j2yUxsYEZmAyfxjVXA011xioWe3l2UU0WK5mRMbpQ/7fqION5FZdRfc1Ewo+uDmHYbr/Bk9tYq/jT",
	"8UqTJLYhHd7nhpZs93n0UZsQm10GFqCBjLSvltnJ7vs0Jp1kKOGg3SRt5jZox5V9Fchf/rRyuBdxcbSx",
	"XtzAMi+7gxlHQq821PaqoURm4Faja38zyyww0LYahpAa5uAEujZ6/yy6eetU4ZOvp489DN1t87za0fUh",
	"hUjnjX7H929Q28+LoHbzTas2pTpVNTrMtymyDBXABRFKvNdvPrW6tMQriC3ZWaNA6BEGWl3Rh9u+hu0E",
	"/M6UMlm/Q9nTxV93NoV6Ow8SOiev4bGFaoXEebEh3mWehOgw/QMWdis7BLlSyGCftax6pYfvst5iQ93j",
	"UyTgp1KzJVuEqpGkgCuxj7yayFUananuYSJI6Kqt9rlPm1wDTkeMZuuBZZI/OsLzBhcKRpt7cQ9rUX8d",
	"w8Z7WhVlGF9gSn427wESLGHBuPrnZyJhhflV6PKrzxwxB6loGO+0STLBUtUPNOQ+PfWTRLBE7IEKl4Vj",
	"fo+VNJjqnIOJWmsa2WqbfTXC9Kj+ZCCKWIF/KsEhUS9LUkUWVVqV8a4cCC9rp34BXycDDXPVXmGZLL2E",
	"qEr/CNPAXFd3bjEP1nOTbBazcbIVwBVmfAMOp6l+wVJkRqxwyNkq8F2bXs/jKfrPm8u36IppTFSfCOqM",
	"1hQYhtFkCCnVIE2V0m6hGXcEAis2ufTaWljj0zcbv3OEuO26+2eOTgNjn/T7RoInE0JT+DD+pxhGTk7y",
	"nWbA5bXN0S76X1l0t7Qsc0xHVYJ0K6SuPSdq7nB8u+zjty7XU4lW6Zi82renruEVcGVxlcK6L6oqfTOY",
	"M24XJnQxRq/0HT/ZnLp5IA6aOZkH+UEzJ/NgedCbkzmdpn/qT8MsgCdAZW9Jj7pdYc3syATcOVkslDoQ",
	"wqQRRUapXsGQh4yN876xg8I55W5G75ga+2hKk7ttxNVYrJuIals7NON4T7B0g34EMsxx1AtLPXFvF2/F",
	"3j4GFG/T7vm62ipRW80JxfaH3FQqV3+eXb3rjaiHy2ebpPXeNJCehHantPeN61fpHyvmtn6r5XZD11bC",
	"eFBR857dbFPNN8G1JSGmBxPtj+g0LIfuAW58lRPOoceNcFdLcXeMdlMpBd0JcdVrjC5ptjbfN9G/FsCR",
	"u5s6qcYwsJ3LK9QcP1RgQUkUQhcXSk4H8ysrBu0+nOYS/vVQBfevwHOrJPg+xrvBSIz9owjsOMTQtnxp",
	"gxj1QJacWj1FAZ7gzGVPpYweuCgYMs5GT03+PQf90+agJ8EElZtysQBtputopD2cxOV0aPyZpLAYHSJi",
	"k0GMI8Y30p4fB4203xPfnzTxvedzSEPUUP8xoMKjM3b6ilD3fIIox8mSUOhd6mG5bi2gDtr6IKe65mLJ",
	"ld1pS4KgCwuQIQEiEOSF1J4Brv9JWTNVcYVJphYeo1N0bb6DlGSYG3vTxfeFy3xOAc1KxXlAaMpVOjQn",
	"KSAitzxM3PSavUYeutQfEzpB0+im1B9ymUbKLvN2+snJRhSQjDBNR70FFge8P6i+yKTZxMBvMN2SHP7O",
	"XAjBBWtfM6MsttR8ZcL8rAR55R/gwgpDjdSL07en7tsfp9cvTyevL89Oby8u38boQROD+rH5wkkhjFCd",
	"p8gRSwBTw4fdyCp9TL9bw1ySpMwwR4JIqL9kqIxNDjg2H74w1iQ61ZllePIWHv7xN8bvY/SyVAJqcoU5",
	"cWpJSXE+I4uSlQI9H1VfCzXmmtprK5sOfTaNvn1zO41iNI3e3Z5No2dBKnzXeTcc/vCjvte2l3nmVUqm",
	"LkpSPXLWChlNQ8+jpdLJF7a2hS0eoCBnZSjTd2sl4daHYMxl4vJbjhPw3y5uVFpdP6WUecS1aUxFhB0y",
	"D6XIPeq6N+apsw6CJnpjkGOSRSeRBJz/xzwji6VMZDYmzAWWjZ36SregM3VRWYZuAedRHJVcDXVXuzG6",
	"43T8sTnF3WehYc+scLSZ5voVIiguZ7wn+uk75DY/d54BmKA5pAsX5zGuTLkEwtED4/eKFIQp25CRBKiA",
	"OqoVnRY4WQI6Hh92NvPw8DDGunnM+GJix4rJ64uzl29vXo6Ox4fjpcwzc2BSu2FaSDq9uojiaOWUuWh1",
	"hLNiiY9s+QKKCxKdRM/Hh+Mj67LSBKc43WR1NLH7mfyigH2cuErpOocRAinO34K0+U+2MnvqPr1S2yQV",
	"/75IzQhXxt1+vkWB4fKTAt9dbXtq7cddJEOL9uKibShpQ0VNYpM57RFUHxNw5GuKjBsaD/iyu6+AqoJL",
	"+nU3alWUr5bVCVX1urrzdav6/KZ1tfUoCqaoQLUfHx62Ms692Pjkn1aLqOfb/obD3NFWsOl7RS3Hhy8C",
	"n6tgLgKvurw4PHoycKrXe91vBFFcyqX2/adm1Re/wqpvmXzFSmpX/PpXWNF9oZjOM+I++40X2qFkblV0",
	"p37ruaq1LlVgmYTD0y707D07Od92X/Wwxnuf/e6rH2jVED7V3bQeFhDyG2a+5bLhnEZ66T/tdmSNMMhj",
	"U/Ap6B5/w1v64gnX6ifNb3CKKgT8dvf++a+w6ivGZyRNgf42rOaLX2WTN0bXeUcrAy/MbuKoKANS/50t",
	"O7MrL7k28bMn5iZ1yZhfnZ3sd49/5x7/BlrDFuldP1Z1TjEtulmo8siZSQfEFIVqkPRdNjOqW9jk09B3",
	"d51BpH70qQEIYTL9XXB+esH5W2jM/yLis3O3t119q8NvtLJ3vP3XgNPQ3d9J2PYvaM3vJxW6n0gGDmIM",
	"Thz+rtf+f9ZrgxdTJ7TomJa+EcYjNzHZ/mZct/irvWn6Q5AtjVRHBOw9sIK/6z5qztB/zfzJusA/3j3+",
	"XwAAAP//lmtRKE6PAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
