// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LcNrLwq+DjbpXt7FwkO0klqtrKKvIl+mJZKl2S2vXorDFkzwwiEqABcORJSlXn",
	"Hc4bnic5hRsJkuAMZywrqY2TH9YQt0aj0Wj0Db9FMctyRoFKER38Fol4ARnWfx5OBUsLCWdYLtTvBETM",
	"SS4Jo9FBdA45B6GaIUwRtnXRjKSAciwXo2gQ5ZzlwCUB3V8e7OdyAVVrVQVJhrDph1EkF4DESkjIRugN",
	"k4DkAkuE6QrBByIkoXNT9ZakKZoCYkvgt5xICVRBAB9wlqcQHUTjJebjlM3HOM9HKZtHg0iuclUiJCd0",
	"Ht3dlV/Y9BeIZXQ3iA7z/FJ/C4GtaiM20zDiPE9JjFWpHpcWWXTw1iBXQHTdHG0QfRiqSsMl5hRnCkNv",
	"3WhHrpEBwPV7xKgEKhUsOE1PZ9HB29+iv3KYRQfRX8bVMo7tGo5fkhRco7vB+rrnkGJJlmaxVWUO7wvC",
	"IVFw6ZW7bqGnAd8LuvwJc7PUtYWHqgAnCVF1cXpWq9JYikED2y/oknBGM6ASLTEneJoCuoHVcInTQpEN",
	"4WKACFVwQYKSQnWDeEElyWCE1GLdwAphmiDTAnC8QFkhpKKZKchbAIr2dYWnXz1D8QJzHEvgYhS1pt1B",
	"Jw4NZ5wtSQL8Ioe4/1oF8KhWoY5IXFHjhr50tbtBpEirY89VAyJVq8TG/v/+9//UcYBSRucDJCTmEt0S",
	"uUAYpSAlcMQ4okU2BT7QuIsZlZhQRBm6XRAJIscxjHpttd8iRqEHoo4zPIcudG+i8mOaEtrd+vruev3a",
	"XkgsCxHmCKZM8QOMBKHztI5jy8sSWBKDEscizjjk2PKEC4Vi8+d5Qan56wXnjEeD6IreUHZLo0GkGEQK",
	"EpL+fKU+A3/MVqEHRKusgqpV5MBsFVRwt4q8idQR/RNLC0O51fapo/s5zAgFgbCm3gQtdQtUCEjQdKXP",
	"pDpLrm+l8Ma4ouR9AWY/WMbu96ton9AQv2/Tt88/9WDXH0nzBiUtgg3hrcmC6lM3MxLt2b8mQmr69cjW",
	"VlZzJBIy0YP3NNaw2uuYc7zayD9NM0Mf63fZvSz5m9ZaB9ZTLecMONAYQpKQLVKSi9njecpWkKDTo+Oh",
	"wlFKMJWIqFVUHFNtrxmOJZri+EYdVGvHDtGSD88GliUuiizDfNWTdaWpj0TRzbZ+AJzKxSoaRM9hznEC",
	"SYBVbc2e6tBWY3RW8QbvrBPgTPUKJbh3g+hIEcxMVYMLMlfM7hzeFyBkG22dVRH3hGPE7ceZWnokyJxC",
	"guKqLZpxlmksHx22qRbn5CfgQo/YBODw7NiWocSyQ01K5hskyOxKQ95EVGDZI2mm9oyhmhG6AK4aIrFg",
	"RaqP8iVwNZWYzSn5texNODJPsVTTIlQCpzg1kpWRAzK8QhxUv6igXg+6ihihE8YBETpjB2ghZS4OxuM5",
	"kaObb8SIMMVWsoISuRoreYKTaSEZF+MElpCOBZkPMY+VdBHLgsMY52SogaV6YUdZ8hcOghU8BhHcyjeE",
	"Jm1c/khogohaL1PTCoolytw+PX9xcYncAAatBoPeolfIVIggdAbc1CxXGmiSM0Kl/hGnRAm2ophmRApH",
	"LwrPI3SEKWVaLivyBEtIRuiYoiOcQXqEBXxyVCrsiaFCWRiZGUicYIk3nQunGkcnILFqJezBtK5F5+6y",
	"kl4kyiNit25M8yZ/9fabJRVvkhbyEMtdD26L3H7mOM9BnQWsoAnC6hTjw5iDWmN0dHE+QBlLIIVEseCb",
	"YgqcggSBCNNri3My8niIGC33R2tBaHMW+JATboQxiBlNROho0+3NlapkGkuckoTIleZomoCrgdUwM8Yz",
	"LKODiFD57GlFNYpTzIErbMEHyfG6C2EpbLQori5MtG6KqmOEpaF1EO5oV+g1ugOHY81wFZ5zlhep/jRd",
	"6a+HZ8dI6A2scK/rq5krxkayrJDq9hm4Fxo6Cp4U6sI1xQK+/nIINGYJJOjsxUn1949HF3/Z31PgjNAJ",
	"lvHCcnJFbaPy/CCQJohQhH16WHcIGSZVW5LpSkJoH+tjib8JikjHNDFEpmHiJU2YNobja875vsApmRFI",
	"tAQd5BcFCfDeq+PnD7BOHhACz0MC8JX+rrGupqEPA9Ai8Q2skGnlzd9eBYgQRf1Er0nLGwlYTXmzbPoA",
	"iGlwQkfNNeLYjvV1CPEVQeE852yJ03EClOB0PMMkLTggUUqk5Sw9/YLowDsis0o1KNocz6sa3qO2y7aM",
	"NqgQh5gS9Uuc99pdir1qNhdAxlFZZiRvtbLM32kj9KOSTlHsVeSADjXqIBmg50CJ+ldh6CUmqQGq13Wt",
	"HDx4TfOpwZtCkAbKjronWC1fAhKTVOgDhFFAWG056ZY7LjjXApFUa+qEV0XU5x5Lqy9tioW85JgKPdIl",
	"6VJ7qXpIkgzMSCVosmwLiRHTFFyWDCVDmDK5AF5bbSWPDVVfYcFIKH7RhuKHIsMUccCJpiZbDxGzJ5SY",
	"6bCDp6yQFuISvCBDY1O93ZNXQMGc0+HZj5wkM5qXNQ1TqWPjFgvN+dSZlaAiN8P65/rXXwbPdQ5YBG8q",
	"6PGUE5g9QaZGJTq4MR+JXjPtKfS5Xp2Q53rq2cyoTxs7QPdQQjAIkVyJgGr9126WzVqOGo4GmijZDF1y",
	"ddN6iVMBA2Rvr/7lXJVHg0hX2Po63oDO9tX46rpufK7dpGvYbNOjtZ5UVEf8i403G8fpokF0eXbyE3At",
	"Y5gLvSswPFDPWTHAdtU4BiHINIXmD8dTzjAXuurFisb6j5+UnKtqsDRlhTymZ5zNOQi1+FfqNmaVtjnE",
	"rupJkUqSp3B6S4ELDdeSxPAc1EWMCHWtUI36LcQLylmaZkClPU+9+bbK6tPtPJK9LjrrlLjsrFEiubNG",
	"HZxzyJkgkvFVEPUK450FrfXxC8u1epkCSLcK+kdo1cxqeGtnPvgraL70XUdD5jMyb6pc+yl2XxEZaL7J",
	"ivFjKf1fQMxB7mAC2WHUH6TMQ800DvLCrcoJo2qh29av+nmdmWqbjauVqoUh22iz6Or3HtS7rzeFtmdi",
	"ZskZffEhV7QUFnQ4owjKCsicl/qoU30nRaqVSCQDMZpQNUlbgwj07gtk/393gIbohFB1ez1A7754hzJ7",
	"I9wbfvXtCA3RD6zgraKnz1TRc7xSSDthVC7qNfaHz/ZVjWDR/lOv8c8AN83evx5N6EWR54yra4ZaSCyZ",
	"AmKoKh6Ul1YlfRvF2WMYzUcD3Q2haKFALvuDJfCV/vZEjftu+O4AnWM6r1rtDb95pxG3/xQdnqi1/wYd",
	"npjag3cHSJsqXOX9wf5TW1tILQXvP5ULlGkcmjbjdwfoQkJegTV2bQwwzRYXxoJXn8s3FUrUufyN12RC",
	"XxhXA4U5tDf8ZrD/9fDpM7ukQVHmqBCSZYaxHNMZW6cOaUpTWltkdL4JinVHyG4wuwDBIZvXXa8TQg0x",
	"6ouiFjzrev+WEGMAbwNnvtdV4PliJUiMU6+/z1ruz1ruz1rucSWA9L/d2DY76K+vO/dxyzTfthuHdVSN",
	"66xvOl9vI9d3pWQVPv2NU4m9HkhMlBSGbhckXmjdh26Jepni1TDacyXAR9+Uo7g6yN2kywtquHfvyttv",
	"zcJOJHeDbmt8dQe0VUpDt95kDbh2M843r8cdup/S5qzWy0NoOfledFW3uYZONWEqOPpZaPNvwyMhYJKu",
	"kymxR+laMvVPO6NucZxPKyF8D4h7UUisN8g38b0Rq0YO70Lkkac/q7QIBl9qP83IvI02DjQBDknnMXxu",
	"K7iDt7PfTVrl+jhrJylY2ilh2GJf0LDKEv05ZpRCbPUK5WK35y2MsH78PMyIbDE6fu6rrBojhAnDtDzx",
	"jo4GvZeyXjmKY9SOtSm4rfnh7zVXxxhTfVoKoy0mlEiCU/KrUWuWjqnAM0JxOihhlsw1GyCQcddy4eSU",
	"pqvoQPICGqTZmNXAQ2D3Uvr35jYiXGdW7sSOpJL6bbvUh7fWUGI+B9nv2PRBudTtwso+02W/KXn9tNl4",
	"aUwym0WoEVpTy0AuWFLfUr4K7IqCVvhoBVcsGV+dg6jBt06RtA5ir+d11eqjllg4VucgJ3J1tID4posh",
	"dddt7t46yyKuBYpVE5QDVzvC2MR3PAOGwTOguvE0xzQQfQTr7578bry/s6cNWuQtkFlRnfPcvKLC3f59",
	"HWup4tuGDkMTqEZaV8eHobteCV13lQruNlo7dfJWOOki0dbezRs3eD1Kom4dcrU70ShC2FrEqchbizcV",
	"0BuEG1W7xFX7fCSZkgSz3M290flSt6xk1H6Gs512lfVcNkvkRGuZZx+D5503ZhuY3luz8wDwlOklfYe3",
	"505bsbEtOqbUtbM27OH29q223Wsyg3gVp7CTMJu61vdwDWgqvarO7+sMaMx1N/Yf6qSLvPwApRDG2nze",
	"mJXsGtdtHfUvWxJaA+omqTSKa1AEykOgbahWI7pTEXbK80uRKZpawc3Ig+j0orwGdMoeWdDsf1nrxPiC",
	"G2UJR1fnrzdfnEy/3YRxKnbaQqcXvafwU/3i56YR3Be65DmZd7rDJbqs2ZdRtSOxwE+/+voA741Goyd9",
	"UVMftBtRpf1wK3SV2tZNB32cF/3YQR0Od2glRNx8TPsMMsZXu/fQdPvJi6js1ELXF7XrjXuiZt0zyDa6",
	"7HaIwc+Y241+xIkkMU53DjYIAerHMrRLq8FDpR5AoWIHZKjMd5bw9MAdbKnBlPAaW0qla+oX5JNbg+5O",
	"YT4NI3LLvdEohroBMeU7wBC0YYeGFywNKVi1O5jDRizJslLtWJ1Gf1jqGqugl3L9yNpaV6HdvHrCYc83",
	"o/s2XCugflKg1fagtZrbFbEO3/1x0LCbh7BgIrmTDlWbKdSeq0Qx2rrFv+E/gGW8OMNSAqdBXbJbWV0R",
	"5bZmbTIt9bOx+To4CkqkPqIHJuiVcf2vkhJFMZuRDwNkInoWkKZDIVcpoHnKpm4wDb8eHc8xoUI6x8Z0",
	"hVKGEzBDaJgy/OE10LlcRAdPv/p6ENkuooPov97uDb/Fw18Ph/86mEyG/x5N9H9vJ5Pr/zeZDCeTLyaT",
	"767/9vgf/eo9+e7xZDJ6ayqGiv8aOs03B/AZu90ZS0nc8/C58loYcr3rPFfWK5baqqSwXC+82EHLPJFt",
	"m2F9FyapsfnEssBp5X/6sbzWilo+y62uFFvwl7aRLrDHcNvUsHXvDVNNfw/mcg00Ho0xzZltFB6D7r0+",
	"ej/Wa9k/b3ox7MqOohUr9sq6k/rBaUwuAGgf72NLFsbZFqjz3rf8Dz1+c3r54sBY+0rfDiIQZRJxkAWn",
	"NY//Jz1VLEoqmrPhL4LRIZlTxsHo+RXw7v600312yxOqbFM7o7YVWvWpsg2VtyjbsHvngNOjg6p+yfeS",
	"bVhe0qFg8rZYDar6lo7CO9xHo0/H5X7Qa1PBW2HNX/ZuyX53261H6QvMk1vMQXvPGCcyQuf2wEU1f5b7",
	"t+laGJxL/31YdQOo2U2ps1WMdlhBeKr9OsPh2OcwZcx6vJ6xW+CQnM5mNQ3i4S0mUrvvWrOm8e2epSSW",
	"Z7gQW+p7ahPyQGuVedAGSuu3p1qRP6dAcW2agfKmBqpWGEJGoFoTP9Vy1lhKP5++09zZgs1u8EIY4UPO",
	"RMXr8RyoHE3oCxwvdGBazDgHkTOamFCVSoA328J6rsU4x1OSErkaTehm70Azidquilmamgw7pYtXp2Ck",
	"gOz0JVBn4eFcZ/MxVYKb0Pfa6ujDq6FkD+OeavHU8l2selakE7L4f8+YRMfPt+nKOF/2OT5a/p7qvHRM",
	"0GA7PMvTklNeOE7ZE7ymb5iP0BILbSgG9eXr5lstGX6D+TvXNbUKNcMUz020k+bL5mDSWZzitEhUye0C",
	"qPvuHDangBJ2S+39SZ0jNmguYHGz9S6M7/VGocZMpqxdHu67tr/bgLZkJ32tgele7R3+8Wi6v8/jsTbZ",
	"3Y7HdhdbWDwqhJXmjvySPcc6UvO0kKcz+7cXFrKLSrEGpDdEoNQfNdi4EZ9SL/W1hkTcbAy82DrWYfAH",
	"C9YIchR7j9asxHSgmQkRNyZQe5v8gwnhoN1bygSEThWmuq/3uX4uazLlPS/8yMwZLlJ1T9tTQnkbogx/",
	"IFmRVWkXcJqyW98t1bi2SYZim0PLpLkrG1T80oWzJwhrX3ymNvbSWp1BzdH2PV2pG7q6nRaUyBGqAj7K",
	"jzr0+AC9EyZ2QpjEEQP0LjMfTDiE+rAwH3Tgh16LSqP1+LuDt/vDb68nk+SLJ99NJslbkS2ug4qnFzRm",
	"6izo41sFtq6hRu0ap5cPS9yICfCZQZ5ioqQhk56hd2SeGerMNna/v7ed3AUC9Nrgt6qsyRtk4+TVght/",
	"rbVKqc/BFJ+DKf6EwRStDbVdXEW7+f2mCOqI58VpD9bgqlY5FMKyXMkoPL2q5Rg6e2qnDy12gcFrsnXc",
	"LkAugPvJKdACCzQFoMh14K35lLEUMDV60SmkH5MC9tClYjE96YtunqerKuleR6Raa/HsPLdaoUpU7ydX",
	"dS91W6DZMOimFfesGh+79ocdvhr6+MfSBuD4q3+LRW3h+7n4uRbfd0X/1IOIVN0ecqTX68CfUkAcG2y5",
	"BDuYlgKILxdoFKS18AU6WM2cOl5FM3Kr7iPhfI60sSXgrCJ4eAlC6an8TDvCRPv7NBXYwHXbXf+YtkGk",
	"7zjnm2JSLjUpro1L0eendbsf/SIYRY+ZVbU96fB5vW9O5fKrOMOOzlXuMS8iSlPQAihSB7pHPESEWGsH",
	"d1Pr2YuxdekeOiputwNanXSxHHP07cRIPdPkpqxOPi23UzuNtk7Y1E5PBOEpP2wKJj/dexAPsSk0azQj",
	"Ia/ZeF17fVVCEj5I9Pjq8uXwmyeI8WZeO28QHcFE0k4Mq3ru5rSZDryLYFC1pqbfHWylSsvwqva855wV",
	"eXjWagaPBNI1Bt5lGoiWhbBLQW1zoQMnMTp+PkLPzR1fSyqTiDMmJ1FYHmYJrB06B26dgHROyBH6Jyv0",
	"NcEAY3TAmRLqZzgjKcEcsVjitMrVjvW9+FfgzOUy2Pv6yy/18mFzksQksw1MCFaozZdP956oe4osSDIW",
	"IOfqH0nimxWaWtUAKn28R+h4pk3VJcYGRgVcn4y+3ap5Kh5YIUyBFw63LQTwtdhitzop4b0vVBfNbadw",
	"2+ZNhhpFb6pce60j+IBDuec6FFThZDStMPA5kecKjPBZ7KXCxugVkXVnMpuVcBvdnNPI2cjLGZm74Mgq",
	"qVBH2Lcr3ixkVl3Vsma2/aC0MHUOS7JOHjGlCuhCeNmd18LbipItgW+NOujSMq577sGfbcPjsnfOcbvy",
	"oYE7kgO1iGchZd6Teij64fLyrCf9qL0ffqdGfXUUY6SsR8I8GWMNrZJ59xp3ejX9azQoApbAPcWq987M",
	"R1Efb1OfIx5swyJXNEZr6NL4I4Ymz8uT+Or8tc0fyjIQCM+kvcmrA1yHIKBjqQOLjQUO0PsCtEqc4wz0",
	"OyCiiBcIiwM0icaKBseSjZ1a6jtd+++6dhf/7KTwcvkenqgdRYZGXvvWyC5Pu4TecGhZWzqiL1rPDJSZ",
	"MWzoRCBjBcpxfNPLcNEVXdKJlrMiTSt3z8qgcTx7w+SZuSu0TBvOyaF+6D7y2zwaoZ/VLUjdoVTZYXqL",
	"V+KRER7MRIlAeZGm6mjXuZvMIz+1Vm9USa2Rft4GpyZziE4Q2x33asaMBs3J6F57mggUfsp+1I9GX+qT",
	"7c+htM/jHSVx9Hwv5EIzjS2CidptA163fmSUZVjGMrDhxYvAwV8jo42T8qhui0c5NgNm0mpzmBMh+WqE",
	"LtWlXInYUzD+NLWdphqafLCl5fP06LjsbKDYdsroXP1rRSDGs9IKouqajoRvy+zDM9c9+rH+caNPx66M",
	"d9caF3yfIdkDdpdAk0psXn9NtgD15GVd6RAPtp+nucZIZjN0t/lLrxmXd4qAb/OnPQo7ETeI1qac7Jkp",
	"answB5HQo/W9b1RQItMwEDfCCip3lBRrGnAzgCcN6p5rOrpqGv0QUsEc7EA/ptbdiy7e2FV45avuBx6G",
	"rjdpG23rapFCpHOiYwf/BOlBPXtl27uzLFPSS5nmxzxmmaYoBy6IflSgijPVEssCL2Fgyc7K5UK3MNDq",
	"pGDc1jVsJ6BrpZTJKkZlR7V2VdmkBq8FKwQzRLqHB8o8EWusSyZcRBvFb7Fwbxz0NyklkMIuY9lnQ3Xz",
	"bcabr8m0fogEvC80W7J57GouAbg89pGXhb20WpgEQcZeg86aTzu4t1DPASdDRtNVz8TsH23VOME6zYf1",
	"dLiBlaie07Q2jkZSKsbnmJJfjbd/jCXMGVc/H4uY5eargBRi+cQRc5CK+vFO65ISTI5/S0Mqw0PfJQNL",
	"xG71uxLa58V8H6jTYKIt/GM11iSyCXu70gzqVt2uNxSxHL8vwCFRD0t0RpjSickoOB4Jz0emMmtVrjf9",
	"1JNnWMYLz/2olD/CNDDT+eQbzIN17CTrM2z0XDaXkH+Hwkmig1Ly1BwrHDK21FupHp1fITCsAzxE///i",
	"9A06Yxoh5dPCrdaaEMOgGrccJSEkiZLdLVCj1rnA8nXKtaYwVnsyd+37yIjbqts/j3wYaHuv7yILHo8J",
	"TeDD6BfRj6rcAXiYApfn1jE67w5taE9pUU/E1bBjax2G6jtsVC662K5zsFQnrHS8Xs3bk9rwEri6eBXC",
	"KhLKfJ9TmDFuByZ0PkIv9VY/WO8v+Ug8qjtCPsoe1R0hHy0edTpCTibJ37p9H3PgMVDZmU2kKldYMzMy",
	"tmZO5nMlFYQwaU4kI1svoU+sY229L2yjsCO369Fbpto86ofK9Sbiqg3W9v60pS2acSwomDVCR170U+F0",
	"wlJ13FnFG7GzjgHFm7SLnFdTJWqqGaHYfshwnls76dHZVacxOZyI33iKd/pedHiRO9m9q123ZH9XMreV",
	"eVKsJnKrM7nX8wgds9kkoa+Da4MXSgcm7q7XXCDaC7g2FCbsuI5rhqeG/O4Y7bosDroS4qrWCJ3SdGUe",
	"VtJfc+DI7U3tT2IY2NaZHSqOH8rtoE4UQufH6pwOOjWWDNo9uO687HVTBfcD8NzS87yL8a65Kw78pQjM",
	"OMTQNjzxQ4x4IAtOrZyiAI9x6hyHEkYfOXsUMjpHT1r+7Pj9aR2/46BvxkUxn5snALVd0C5O7NwZNP6M",
	"P9QA7SFi/SCMPqbH45ifvc3v1du84x22PmKoH4Gn8OjuPF3p7DvePstwvCAUOoe6XawaA6iFtqrIiU74",
	"WHB1/bRZQ9CxBciQABEIslxqBQEHkyKi7qW3xCTVjz6iQ3RuHmCLU8ztI5fW0i6cu3ECaFoozgMm2YSS",
	"oTlJABG5IRpwXch6hTx0ql8xO0CT6KLQzz5NInUv82b6yclG5BAPMU2Gnbkdezj9l0/BaTbR8/G3S5LB",
	"v5izJDiz6WtmhMV2hlX0qzrISzUBF/Yw1Eg9Pnxz6F4ROjx/cTh+fXp0eHl8+maAbjUxqI/1sCKFMEK1",
	"ix5HLAZMDR92LWvPn+aYSxIXKeZIEAnaQYzYJwMxBzwwT+iY2yQ61E5VePwGbv/9T8ZvBuhFoQ6o8Rnm",
	"xIklBcXZlMwLVgj0bBgvMMexdkVwc204kqHHk+jVyeUkGqBJdHV5NInCfrtXrWDdptWyOvXsc0yGXeNC",
	"MrVR4jKyWAtkNAnFJEslk89tAgsbsa8gZ0XIyXVjTvLGk1JmM3H5iuMY/IDBtUKrq6eEMo+41rUpibBF",
	"5iHvsDsv57C2hcZ6YpBhkkYHkQSc/WOWkvlCxjIdERY5rZ2+p77UJehIbVSWokvAWTSICq6auq1da93S",
	"Pb6td3H9ONTsiT0crZO1Dv0DxeWM9kTHm0NmXVNnKYDUrAmSuTP3GI2mXADh6JbxG0UKwuRKSEkMVEBl",
	"3IoOcxwvAD0d7bUmc3t7O8K6eMT4fGzbivHr46MXby5eDJ+O9kYLmaVmwaRWwzSQdHh2HA2ipRPmouU+",
	"TvMF3rc5AyjOSXQQPRvtjfatykoTnOJ04+X+2H8Z3DjquzNb62pYKBrxyBgtcc8XpUt2fpyUjTtbRuXb",
	"2N8z8+SL52jsmYfHv9gT1NDpzm+7G5Kt6NrmNzJZMoTZnE/39h8KkBCiE7WUX+7t3RsMZbBaa8DvcYJK",
	"eNSg+w8w6BXFhVxojb+d6rMHGPUl41OSJEDNkN8+wJD1XDBq3K8eZKoXhtFd0VK6M4zTShQPsMDwITfZ",
	"YECn6dHKYjzXqrNOBhRdq2qb+dT4N8Vn77TDMciQeh0n5RP5xs+7cxO22dUrkOt4VeXyqFVU6y1Pm9ml",
	"ugTPze2PqB6sN7Y9SMrHlXxmNfCWp6mpLCh5X8CxUdxozmbUUzXetvf78LbTH/9kHObLBxjyDZMvWUGT",
	"z7xlG95iZTrLSMYuTLCTo7wCab2xbTxh4h6y7BJ6XoF0EYr2McwtWYd9KtOwh/rgoqksvh/ucdcOPy7z",
	"UuqQS9R4n6scVrt3V+MG4zPXjfspWZTFfic/emq2aXNXIc+j8PdiWQ/EP1DJQB5GKPLFoT8I2zDbeS2P",
	"qBRZOZZx2EXQuf954a7PNzEK3awW4bwbo/AFCg3hfTGF623uZ0M99N+2W7SaK0qv29nDsYfPt7D/CBkJ",
	"/T5CEvpjSkkluxtEeREQd65sor9tedm5cZ66Z25WJel7cHa2Gx/5zL3+HOLSH1h4qXKE9FfuUhRKOrde",
	"q9vOZPdptld7nAfW4nYA8Fl7+x+svf3d9LZ/ULGhxVQ28ZxNitpXILdlO69AhnjOVjJG93j3qo39tHqN",
	"Xgzps8r183Xid+IL2olc+5HpHWms4GMTaGvatV85sBtdIEabFwHthWP3oRV42urKeg/d29zvrA383fXd",
	"/wUAAP//tWq8vvqqAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
