// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+z9j3LcNrIojL8Kds6psr07GtlONjerqtReRbITbWxLV5KTuifyL4FIzAxWHJBLgJIn",
	"KVf93uF7w+9JvkI3QIIkQHKkkRw7PKdqYw3xt9Fo9P/+fRKlqywVTCg52ft9IqMlW1H45z7NTvL0mscs",
	"P8tYpH+KmYxynimeisleswHBr5dMEirIvpD8MmFkv1Dpiuoe5CShap7mK/J4f//kCclMXxKlYs4XRQ6t",
	"ZpPpJMvTjOWKM1gHzfjbPGlPf75khAvFckETsr9/QvZPjsjb01d6BLXO2GRvIlXOxWLyYTqhhVqmOf8N",
	"5ggOd7xfqOVzUmtMmIizlAsVHDtKOBPqKO4cExuRo8OOIc5YlDM1ZBgJLdtDTSc3OVfsWCTryZ7KC/Zh",
	"Oom5zBK6fkNXrD3098WKip2c0Zjq0zJtiaArRuZpTtSSlQflXTkTuqPZ+5wWicKJp42JfloytWR6QC7h",
	"tMrj55KYQZwJLtM0YVToGWzDc/jig43uQ9I5nBsTikd4cO66mShWk72fJ5Rmk3eebcgozRDd6sO/4lLp",
	"oQ34sRlRKcnZfwom4Qi4Yivo2hrV/EDznK7h7/SK9WIfNOrDug/TiV4BzzXof67DaGqvjAftnTU4iNtA",
	"wBIcFaTSy3+zSOk97F/KNCkUO6Fq2d7HKctyJjU10USAmrZkzhNGMqqW7eudecfR8Ch76yYa5hTHSQWg",
	"pVxLxVYz8iZVjKglVYSKNWHvuVRcLLDpDU8ScslIes1yfTMUAwLD3tNVluh97V7TfDdJF7s0y2ZJuvBC",
	"ug2DLOvHRr1GmmWJQUcXC4HmSn1S/ylonADIo1QoygXL2/g5nbzf0V13rmmub6bUY5g1HJRDmR/+Tzli",
	"2aIcGJduV6Q/MAH0hibJ8Xyy9/Pvk//O2XyyN/mv3epd2DWPwu5LnjDb6cO0u+0pS6ji14gmunENXfWP",
	"beRqrO+FuP6R5ogkNZRh1Qcax1y3pclJrUnrKtbP6YW45nkqVpqWXtOcA/G7Yuuda5oUGuF4LqeEC70u",
	"FpO40MOQvBCKr9iM6GO+YmtCRUywB6PRkqwKqTS2XTJ1w5ggz6DB879/QaIlzWmkWC6du2y3HcAwC4aT",
	"NPe8CfpXsqJZphfGhSbWK6rIxWSZSqU/7pUIpf+6mJDHbLaYTcnF5OunXz/d+/rpxeRJ/S6Y3/UNpUq/",
	"q5O9yf/v4iL+257+n//2UX93mQ1eYRhKeY5bI0uTAyivW89Y0OzDdCK8j915/UbiK2cP7dn/+///f+pH",
	"RZJULKZEKporcsPVklCSMA0ZkuZEFKtLlk/hiA2oiUjJzZIrJjMasX6qbfflIbO/T1LBBsDvaEUXLHQK",
	"fXf0SCRchHu/+/CuGzNPmUyLPGKv+Ior6XsM8DtJoEHJUDSoYv2wo6xoj3Rw8hYH0agepTmTM/ISMT5n",
	"GrpwTS+pZLF+HtxD1huo4/nT2f/6uw+ZV2yV5uv25K/hdzM/4EGaIc0hheDqDit5/vevVoNfnCbUuwAe",
	"pUKqnHIxFOpJeYQDb2vj7PsWfaaoKqT/0cRvwMARycUiqd9S89zH7JrjpbKv6EnOMmoeyDN9SfGfp4UQ",
	"+K8XeZ7mk+nkrbgS6Y2YTCf6tUyYYvHwR7a+A3fO1kdnEa1v1apan+wyWx+qdbc+ORupA/rHNCmQ9lUE",
	"uA7uQzbnQgtpQP9icg09SKEx9nINbFsXpvhJ61vB/1MwpKiG93HH1beGCx8adlNImOyu5BFBshFlfJ0W",
	"Qt2iH8wX7Pzug/ewmi9nHd4Ixg7RxL0rpnFNKhl4oQ3itKSWnouN3RApu6/2VvDsTQvBvFJpzuYsZyJi",
	"PhppPmmJAglLlqRrFpPjg6MdDaOEU6EI10epH3p9p+c0UuSSRlea2+qc24fA7np6nlR5VqxWNF8PpJdJ",
	"4gJRhmnl94wmarmeTCeHbJHTmMVe+vgmddeyOZGsL7+aNNjEWU2wjYc+1ht46WS9SXNjGuqFWh6A6ql9",
	"6WjGf2S5BHi31F4nR+YbiQ0pBYzA31hM8HIhlnJJcisSm+dsrlEfD39GzliuOxK5TIsEGMlrlmtWIkoX",
	"gv9WjiYttiZUMakqxReIH8iFruia5EyPSwrhjABN5Iy8TnNGuJine2SpVCb3dncXXM2uvpYznmrqsNLs",
	"zHpXc7M5vyxUmsvdmF2zZFfyxQ7NI83bRqrI2S7N+A4sVgBAZ6v4v3LLl3hvpFEOWVrXfbNN4y6FTmuC",
	"NF9QYTQd8oWrlfKpoWqtCc2Z1UEBu1Sft1st1UWZ9fW8pjwB8TKwmQ2IdaGWJfx8dLouW5QY7CU5hVoe",
	"rgVd8ejYAcW+lHwBYrEH7/u6EAr/lJrE54CwdShXTHGhlo76N6F8JT2CgP79JKgd+tfZ8ZtSM6SRBtqj",
	"IsjIY3gx3UUQHusjmHOWW3n454vJIk+LTF5MtHD89GLyTlP9ny8mUSFVusKf03xxMXn3ZDN1nzuzRu+T",
	"nM35+5qqdDKZevaWQcOSc6/tAFisUpZP88WOEeQ7b4Se/qyYD5teQsMh0+8AXPzTq14NWW1gWuKR+27F",
	"iHAenW0D3xVqPiuk6cH60zRhA7G93pSw9yqnkZIkTxMmyTxPV16MJoUWZgitMPXuOK6n3AV0NejeRuJ3",
	"8BesrfyD0WT1C40iJg2W288bIrTUwg9VaV5Hor0WFp3ZhoBEab7Y0zNaJdVjS98f7T16MiOnAEdzZy2D",
	"VU4FxFlmCcj+DZqyA3rqGE/CDqRljbRQjREWSXpJE3gnNce0Bn1yktRJ1C3xGPb2UPi7CbkO0GnLtizT",
	"G0OrAYmBW6ljsoYcbozFLYKu9xlzPeeKC4sVRiUJ6zF773jOup+g6SRj+VupuYWOFxGbBIeQmu/qXMQZ",
	"tAgM8KG8ssaChqeiyesgCXTABP0DdINpyAjdUPoQQrbubl6c6+xCopxpBpZQez0bz4smF6BL13jZppdD",
	"XlTdU79LO0OeVmgsMxbxOY+6Xrpy1Pt+bQev6N7fXnv5htGuIAoFOX73ayUloeHQzyvXXQWILLIsBY0b",
	"uUzVkhwfHR4AhUdLqteVYBTrtirWXXHhkbJ+4CImHG45tDRGshJk9pE/fXF2TuwECFaEoIMOFTA1ILiY",
	"WycC82axylSOUgA6SBSXYHIwZnoN5xk5oEKkYOwpspgqFs/IkSAHdMWSAyrZvYNSQ0/uaJD5gbliisZU",
	"0T5B8Bhg9JopCkyZURsOFR1RFxkWF82hOssxc/TdcC32dt9yEIwBLxIrIrvshhxv7P3f2JLbD+gsWgey",
	"Bd3ESCc+Cp3QZ4pUYrPbjifed91Lp8AOEYDSLIgxDffC6eTqaxlq/MPXstE41Yj6PEghgQFoduFxUA7Q",
	"rEOzecaEXPK5CvbJmDjTDRomoqbAUHPOGiw4tFbUx+Z79tzbJbCDnrveOLm+9s3D09JG0HnNauaH6Gca",
	"ihlXrEXdTFN87RR2tyfONtY+XAZtdNye7NkaeLDM2ewZogqdMq739Lp6lKpkmiQ9KgrwCzRuAwjnmmzT",
	"L0P65STXkl2TlW6WTGNVuS7rYmjx7P7kMYNFQ1VJrX12H92QC+drWR2VBb9kymrFpFWz9d68+hlBXz/A",
	"LOcISjewQcIcsIjabBu65t5Fy7fhyeDufMfxLVWRRxcMPwOjJAhLGICdC3IJP0vNugg093qcevybWtH3",
	"fFWsjBcbSXOSsTzSvPECNosWZAAt8kDEuG/AnHqqYSTopBwViM6KCz3tZO9ZuXnNQC800/gOFMwJiwzp",
	"7eRs6CVLzmxj3bEA7fb5MmdymSZx3wDuuj6EDuLMQDZwIPZzTfqw6AlwQgBeMsLes6hQLNZQDJ+XDM63",
	"Xx8XZ+SlFnYQi464pdlHLo6wwzOPil/lVLHFum+00zRJ0kKd2eZNVC/H8aH5gd7znEdUsTO+EFwsTpH/",
	"9nj+hZrWNEaWf0frLTEvflT1raSAg/1Ryhz1QqNeCHoEb5cVZWTp2HW7YbD7trRNwXn8qqfO5nU9VLDp",
	"SCw+ukqq82wGPX3h92ZUVX2uqqpu0tZ2DMtploHFOy1ETCja4dBcGZODs9MpWaUxS9CD6aq4ZLlgiknC",
	"UwAmzfjM4Tfk7PrZrHMJbcLC3mccLVtnLEpF7HXwh/4YklTSjGua8JirdWlDdBaip0G3C+S1v3g+abPe",
	"0wk4tXQFVA2XpBqRVnpgQhUiF5NWptbgNc5aBsbAnGk4Z2lWJPDT5Rp+3T85IhJujIY9tAcpWd/I1apQ",
	"9DJhnrgqRCQvV3kOkoxkX325w0SUxiwmJy9eV//+4eDsv5491cuZkdeWk18yol+mWclrcpYAR09dfOhi",
	"WJEq1I7kcq2Y7+IAC5v79RNHIkYkQ5+gEiewDxJ8IFX/KWjC55zFICh7L2jBPcTu7dHhA5yTswhJFz55",
	"/y38Tow13LgNwJtwxdYEezn7NyIql7Koc/+bqQL0lvu9zx8AMA1SaLG5hhybkb6Am36FUDTL8vSaJrsx",
	"E5wmu3PKkyJHzVpRXl7YpRP4JgNwJ3xeBeX6XDyrpoH4fhyyLc9NK8CRVMvgJcwH3S5NXlF89nCN5Tf0",
	"rUfVsXPTZuQHkd4IEjkNc0b2AXQsnpJDJrj+r4bQS8pNZPswTsWO2evg62zBiwPlQOENVscXM0V5grFi",
	"qWCE6iun7HFHRZ4DB6LAX8fwrhqpTx2S1tA9UanOcyokzHTOQ3pW3Y4ovmI4U7k0VfZlMfJFel0GDVVK",
	"qEjVElWH5WlrBmhHj+XnRKSmF4EUCKRMgWDaEY53QvN1Fjr0Mi2UWXG5PL8z0CVc9/g7Jhi+0/7dzywr",
	"M1uULZGo1KFxQyVQPnShLjKc1n3Xv/rS+67njEqvoEIeX+aczZ8QbFGxDnbOR3LQTgcKiHZUKxBWCtdB",
	"3dB05temmhVMfShXAqA6/87L0h/HVIPRFJAynZPzXAtaL2ki2ZSYcBRXQay/T6YTaOAE3AyLr2mszozV",
	"+NUO3fi5nMndZSB3gdFzV1jHXUnC2Y2ldJPp5Pzk9Y8sBx4Dw2/sB6SBsGdNANtNQV/LLxPW/MPSlBOa",
	"S2h6thYR/ONHzefqFqh7PBInebrImdSH/1aLPyYWNGORbfq6SBTPEnZ8I1guYV3XPGKHTEs+XGq5Qnca",
	"dhAvRJ4myYoJZd5TZ7+tb/XtBp9kZ4hgmxKWwRYlkIMt6ss5ZVkquUrztRf0GuLBD63zcT+WZ/UyYUzZ",
	"U4A/fKeGp+GcHf7gniD+MvQcEc3nfNH0UhhmrviOK0/3XgN3yf1jApVbBOHfYtbvlcp83QAGWWFP5XUq",
	"9EG30zLU3+sVNutPa1LpNlJiOvWzru7o3nDe7lQi7Z3gLvNUvHifaVzyMzp5KggrG9jwA/3U6bHjIgGt",
	"DV8xObsQepOmBZfk178S8/+/7pEd8poLLb3ukV//+itZGYnw6c7f/zEjO+T7tMhbn55/oT8d0rUG2utU",
	"qGW9xbOdL57pFt5Pz547nX9i7Ko5+lezC3GG7q8sJvogqUr1InZ0w71SaNXcN2qqjN+wHoYLstRLLsdj",
	"1yxfw29P9Ly/7vy6R06pWFS9nu58/SsA7tlzsv9an/3XZP81tp7+ukdAV2cbP5s+e25aSwVc8LPnaklW",
	"AEPss/vrHjlTLKuWtWv74GKaPc7Qwl/fy9cVSPS7/LXT5UK8wDQLGnLk6c7X02df7Tz/whypl5U5gHgv",
	"JCxHYp52qUOa3BRoi1DlGxMMHCPWdwMXHYiKrIu7ziBcIDKCoAiMZz2yt8XE4MLbi8Pf6+aybLmWPKKJ",
	"M96o5B4tYqNFbLdiQIZLN6bPLWxd74L3uJXxwxekvmlaJLa6ZHHcFRfdyNAByflMp9IDJE1VhOkR/JHR",
	"IpxpsBKzXf+q7pQgIMPF64CblvFfmZMy3ZUkN0seLUEnAz3JoMwjehpI9eSh72/KWWwbYiX8UHqdtig+",
	"DJf8OXM+TMN5QCrZ1DQpU2ygp1V9XbdLC9IU2wM6qTLbhT4vB6COkF6i4LQr/VX7EtTTOfieYIkNLFIt",
	"IflEI0GKJ0NG/U5x8+534q77NKNuyJJp0JjUcj5tQ3vSnR+k7XkDY4ahikJDCJAHjrKvUnkgvEz8lcdf",
	"j4mY5SwO8gynpoHlEoLj9qnA6/N0blKmSZAdMp9drshoduDnKBWCRUYJUh62z2MLJIujQz91Mp/J0aGr",
	"X2vM4EcM7Pnaeeca+F4ypuUs9lWx9A5y7aKt5JtaXsOICnjaJaq2wZOMJvw31MGW+StZvuKCJtNyzejL",
	"prtNCVNR6LhoXOWfbaBmY1dTB4Dho3SFfF92NrNrZJKpRam4rhpwE7bWz1DRfIFZd/vfeHcp59DPr5nE",
	"IYdtyRmnTdtLyxdeFqlnaG1txdQyjetXytXXvRUMtFOgjYtUmq9Pmaytr0vr1bViZ+SuZvVZSygc6ccx",
	"52p9sGTRVYgghds2b2+dZHHbg0S6C8lYrm8EGvBv+QbseN+ASjxrzokrugPpD2/+drQ/OFKPynsDYFZY",
	"Z7MyvRXSqipchXCpj9wED30bqGbqauOuIdyuXF24SbXuNliDBgTDnIRQtHV3s4a6AWaB5DVqfXukAW+r",
	"TVmcCr2BvakW3cPc6NYlrNrvI19p9nCV2b03Br+GnhXjOszKd6tbZbI34hFZfltlq7vA+dYXs72YwVcz",
	"+AA4mv8Sv/3X81ZXsXEtAlsK3ayeO9y+vtW1e0WlOmNMhB4N+735UACqSf1BuVhIg/cvCU7UtmEb/gNN",
	"tkxYHxAtLvKG808HKjfwp1xAGINe8TmL1lHCvk/TK4s4FgO+ZfM0dw0t+3PFcudvbHDKtHTvtKh+2AQz",
	"aktpTe1p01xNcBh3gaFxnDW3gXMrsSexvbcgMDZ1udXg2+IWGnu9HaPgGyREiNyM9z6ItTkCtJYaalA3",
	"4dV/2ZAkNVbdJCqNz7VVeL77ltbTrE6evF7p1be6Czr+PuZA+PgO585JDFKXGcvL6Ev+R/Mln06MUnDY",
	"CVqua3tO6D7nhUOmoKrEIXqVtfX6qFLst8RjO9As1eLWSVbkWSoRgS3t7VqJtyIOGFa5WIDvRsdlmevv",
	"NhB3SRVaZBuM6FDn2wbcHUi0FjQU3KdMpsl1B7ht4DY090Mc91hmEqCSpLoxeSyKJCF8TkSKv0A2Lv2j",
	"fvatBsxj9X2gA7Z79x5wlrNrnhby9SYHbc7Y9k3WxgAf3/LAwUiQJkXYLe379MYqTucJjxQw1rnZmAsA",
	"9BCA3UAma/sv2NchC6T970S5xtrCKHcs/VEl7lenPhqoWUE7Ro7PStVwUB+18vqtntcGwXTlaFXLhxWN",
	"wnE7N3UbZvn4bPAWfqwbA+w2/G+2/nLIF8F4jhi+NcdCXxEil/T537/ao09ns9mToaCpT9oBKLhsS54d",
	"LKlYfBzK3lyD98oLdtNB5QS7MXQN6V1J3XK2Sq9ZPIy4WdLQMZFt4p9NpIINmSp8ccMnVboqboTYJTPZ",
	"p6YztWv6OY36OqzKKeby6i79qwI2txuhGWGQFZNyULO6oaDtxnFZcyREYNeRuiod8BPNjfB1kHPFI5p4",
	"KhdsIiPWF+oWRmh/rSb3fXUW5PtsF+n75vpll9+LFXPyIPhdz+bgYz6hYm3cOOtaIjctxrtm2TUIWHM+",
	"v5v6wwuxvqFeTpkHpMzdDlMQm6dDi3q7aW5C4eyvM7KvSMKopsaCVY1tqS2T9yWuFUP6vbH6vQmrirR9",
	"k+VpXIC5dKo4y7+Z51CHLnZyJJk7WN+kz0/ALgd3CSWbaqk7nNwnBgqowuNmn3JG3kobEGgKZa6o5g9J",
	"5QncAIms8raWIR8aL7/ByZ5Nje4nW1LJ/vLNCRMxF8H0rg1IbXePMPiwPdaRwdnjFVs/Q5vzs+kVWz//",
	"C/7x3L+hD11EBS6FzFIhWe+taFXDgm4oCsM2MZqnlO4d5EMoxEYQnOx98aHt41BvEXYSKoGrWeUbljNi",
	"0tPMiyRZG4DHPi+hlrtDbcow8e3iPpu1eTt8Pp0KKYPKDd0iT2SwVF1LMIjK2iz+heD3W6zB62vvm172",
	"Z6GikeLXlVeHcWfYVHVknVW80dR1HeTGbgoQjjZwHUaMMVJZoMjcvl5a7QE33v317MzDYdDw7/cWHoBa",
	"r4EKy+ajtbDIRmRCI85BS4UnWN9SdiVaQjWGqYRZ30yL2prsc2YdheCoEJmaaoF5VZMAcn1PCWYpWrIk",
	"2ZFqnWB5AjsZrB9mpwvKhVQ2ADNZkySlMcMpYE0r+v4VEwu1nOw9//tXtcqdPz/d+Qfd+W1/53/2Li52",
	"fpldwP/9fHHx7i8XFzsXF3+9uPjnu789/t/D2j355+OLi9nP2ND3+b/Dee+6SomhqvEkTXg0kHN96/Qo",
	"cxmH6GKnT0nbi8RvqJFOFTNDPInpu6JgBucJ+oBGqqBJFSd7V1prJGqX5LrM8gYUpu1O7LlltO1nuPHo",
	"DT/N4bHW5SlgykVwr7U+mxqS3kBk6lM53TK+2n1xBpHsyokSvCqMvfpWvgfWXWI7Nmby+M3x+Ys9tAOU",
	"UShcEpEqkjNV5KKWm+DJQKO0FqoW6c6/ZSp2+EKkOSuLzJf2vluZKDd8o8o+tVdqU5l3Y/NAC7OR4NtQ",
	"oQEDVO273jR7+2vvycb3HieL3wquwjfeGHo2IbxxwMPFueY1yNTJysRPZdyjdO9SeScBP6r1Vifnol4H",
	"f3xr53Hnti1pHt9ASmFhQ+60PIF7JTWL4/adys0abAKEbbiVe0BzO1+BjWpW+j2UjiEK1l+e0vX5OEm1",
	"PBUfz+c1F6b9G8oVBDsbv2qMhAeDwQkt5IZuBLUNOUtrfXNW6/laVwDVPrX9WGqfa9v0fG86NtQ++oDh",
	"adaET3WcNbI2LALy2FbENrfBSfjE3meprN4bumBCzS7ECxotIY1PlOY5SOoxJvaoxAi8Fsa3IKIZveQJ",
	"V+vZheiPpcRN1G5VlCYJ1vMvbeNB9kwvMuh0od/jfd3C+ll4L6Fr7g6M4bTQ/A8G8xo4tSI9q5E16vhC",
	"Dr5NU0WODjcZCkNVhzxhrejYD5AiH4kgQtu/y+OSUp5ZSjlweU0rvAvQEgrtVUzrxxemWy1Josf/PoOW",
	"YJZZUUEXlTbJeEzIKeEiSopYf7lZMmF/ty41l4zE6Y0wUpwtRsdRGdSwFZl2Zxip3stY4WbK1uXjftv+",
	"H3rAFt/KOIhr2qobnfs8mlzVW3wea5u93fPYHmIDR7oKYKUXXXaeHlLIa3VcqOO5+bfjPXkbq0htkc4U",
	"nq/urN7ODTfO+teW4cMVNXvYMqtYtQFOYDgsBRq4cHOG3gxVUQCw/3dK4BUmhx67AZmWyipvv7feon1y",
	"mTN6pW90504u1+TCXdfFpO0SWiGXbPK0f4DFmzV1L1yliiYB46D+5AT1+mYamPnKUL8/EnSM9NIFnWYg",
	"GYBq6kHW5vk3NuylRlxe9WaF2TgRy/QPlknG+4BHVXVJMwC83VxeYRbJNnnIgkV5Y56DuWtdVua1+m/j",
	"r+GM2b2XzF/n9R2eVV7ArN8WsQlPbKgwGy3qVQjYNUtMCfL0hsV6WaY1kskckzERDniamYxMbTBAVeFv",
	"12ElBZoAr9gamHcTFkagmwZx6dtUzX8Jy63pMRyt9eOf93f+h+789nTnH+9+3in//cvu7N1fn/zT+ThA",
	"3wzq8beiLMEeKIWBNSkcqmPPyCnebi91XADmGPCBBr6jpAV83e+ZvlGJY04K0Z63PMeN5vfycIWbkNBW",
	"Jn0qvbVJ7eLKbMN2HWXWAwySVinR9CJhis0IXJKyRmfJ+NosruA/SQkkIOPXJn6J6dtjxr5cE4qqzkJw",
	"NSNVnqPyR8i4uUd+lZgySGK+5Cn5dYU/YBYg/cMSf4B8R4DeDqr9c+/nZzv/eHdxEf/1yT8vLuKf5Wrp",
	"x6sXIko1Uz8kSpeZtkjnIMgaCANVtOF+Xyu2mlCuxVrMSjw4IR1OdWI627+/NYN8cPPSHZTa7Uba6bLF",
	"jtEf93HG1ZhnpkOTsnnG9L1IraR5bdi2mnTU/TC5azU24gI6DTBjUMWY4OhPmOCodaE2y3XU7r7dEh+B",
	"HJs+gSHYtMpr7NcYlITCsSCSimSFU0VQm6yzI4P2jZNJyVKnJZXkkjFB7AD+xEnoedUlrPQoPfdtenQc",
	"CdSpWZasLWkJZo9rHZ7Z50Yn5Mhag8SJ8FG3+fieSftO3LHg3/Xs9wPu58CbUGWST7mnf0Nl7eCHRbLb",
	"Ht+u+wsUmrYDxCdn1Km7JY8UMt3wCG7hRuEBfHlAMy+u+UMqvc3q0ZWtJiNL8NHjLL1nMsi43WYcx+DL",
	"z7WQj59h6acB4PfK0eG1bIjUp9X2kbShVOBa5InskIFYFl/ZGLcChsQs3O674nnE675qw3NNTiegTT/t",
	"S792Ds9RZwo2QFmTYWr2b5kK8jg1Rt0OJ/Stciu27oF1Y4LSug4Dw2Xp+LRkgug75DwgXPrYqwCHo89z",
	"GLIFrFyBhpu9goMepYr9vRUz5Tji9VVbcXG5XXJltnEhlXbZEHYHmr+10iht9UXH6ZomXQzmMr0xCjBN",
	"guHWg98vJS8TvlgqcqBJcpq4yOpkg2mcd6GWmixHpZJuI03MfqGgxqujgCn4jn2F/Mf+9vSVPZ23R9Ut",
	"BCM6KSQ6VGe5fcX+zynRKALcR8LFFSbthvns29nhcHBbFVNI09SAVzVBEAaDUALg2I8Wulm9CJJ54+vL",
	"qiENlqi9BWrg0DvOldzx54Y8gIZOKYhDqmi1TPeag1YSSD+1S9fjkzlPIOaHnL868198XMwVW3cu4ge2",
	"3mjyK7bum7t52QNQaS9x0MEPJwkDKINN8qmvRXrLQ3f2pZEqzbkKgrxqu2+bhqHvcinlyKRWwzB0gX2B",
	"vcgJ61cYiEcc50yW3h+9GyePLVO7TKXSsu1eluZqQKh2B4DKxXpP/tpb5h5+ruuYjR8Bu0bndKpIGoEn",
	"epkSG53ePMTcH5/XFN+hlByYMRAWSIJzvlgAvwZyhJ4cTSsorwBvBLGUbM7fo9WEcdA86eH2yGMwe4AD",
	"DZTDf+LMYL7SQqUrqFNnQ2f8nN4oGG9bMI6rDAGdr6Ae0WYTgCCDa0h7gVrfYbrhUzZnOVSVH0XibYvE",
	"gYpy+3jvqmSxDQG0matWwzEz1d+2aA0I136TyzRXU7Ki0ZILVq3THD/Qn3q2kkaVOCRHjvnSuoYcYC1M",
	"pyrUgal2WaZ/tB/elr789V9aDW3ulsYv7pjtsMfAz40eBydvW0H8Bydvm2H/Bydv3+invWr0GrIitPri",
	"z83u+GtjhEMur1r99Y/N3vq3Rl8n3qruY+58aLmmO9+aSQ8OuTSsipug0+Ok3vAZb/5c5htyPjRGPYC4",
	"fdXyMDS/t30Lyw5er8LyPDeqzWZl4wY2BLJjdeeV6ihapn85EtfmtyPzSJ1TeVVO7P54wvIVFRDn6dyB",
	"QKE2+/ORoPUPhtrHVZPqorWLslXLc2u0VbfY/fVM0bz9a7nU2gDGGaT5+7dURctDLjNMGtX4aqDGEgv3",
	"Vld3XLfs3IG+4Mo5sUGV7Fqwqz55i9vpH7lYtAhUrfBd88eyNXqnnzKp0jyQnwd7DuIKzrCpU0gz7Gjn",
	"MJDHWK8S6cmUGFrjUvKS1Fg69K7fptSt2a0zLZ6SnNOylCduamoY5yDb7iRY8nDvO8bTKLKFW6f6YSvg",
	"nY+rTCaGn19nIHXV8ixhoHiWmYD7TurQqaftzvzXQ1g2GLmZ5C6UmaontDKQx6rzIgZGDPfoGNWhDEOH",
	"rbr4x91ooT1rbNCnAQPWe/hHNQRiwGjY0j+KJc4DhjFNq3E8L1OwWGWzpX+U9lM2YMBWp2rsrmct6Kwc",
	"7OKOW3tDujHF27g9Vu+6as0c6c5GamPRfzeh2YfpwPqlwcEHRVYHrv+w3t2k7jZjNIlafyXVEHJu0jOI",
	"hUPLlHrRo79zL7b2DdFxxTfputmmO6nnJp0DxHzjIe60CD+5/vBuo0yDwIME/FTsp4ZvyjVoTkaHlI/u",
	"kFIexDAvFFAhj54nn63niSNoeQWschWoMoNrBjnntETZVpY1LDu2c7+BYMN5egwm5by+Pb/kiVW5hPYM",
	"H9GBYc59NTGirv4Q6EAUe6/I47fnL3e+BsMEhj1UtqlqEoihM9P43A90Oxv30G9VdsI4vNExevvhonv6",
	"a1lmLxAsFcggzhP2SGJc1NQJhTEmG4iIscmbRbFiOY/I0eGMHGKEDhDei0mepupi4r8lacw6p85YbnSg",
	"RLedkf+bFkA8cDEYir/SV31OVzzhNCdppGhifRkSRiGq5TeWpzbR49OvvvwSjo+im1XEV6YDluLz9fny",
	"+dMnmnqpgse7kqmF/o/i0dWaXJrAHlLW+pmRozlkLSohNsVI/Ppm4ArofUoSOwDTy/PXYi1kMNU7Qgsy",
	"E9/DQYVw7tjq/92iPVGphjMZmJ0MOMMChGpDO1o99+fTcuzaz1aMeWdWuFmoqEtGejkw9871Nd6/hJTs",
	"7ISCo8vv7YDKkioEQiuB4fPcbRNM7hp+mZsrdeTPxhiiMYaokpk2ixvCLtuNFYIx/ZJW+akuaWGNi/Em",
	"f3RJqzqIQZIW0uxR0vpcJa1+NU4rbPkSyrt4eTj4BGxoPVFMFTT/MCV5OqwmPuvf3GjKvdJgmR0AWzWz",
	"jMCWB2ZGMcnIT1geaSoVqi1jmmle27Sz4tgtJpsXSd/GqpZ32Zxiq0zTzM5QCFe2Pq93sP7PXBo00hTd",
	"uDaDC3/qxR/FVyw+LlTfJqEdDHSXPd46gc7wWbrKIjVhPDWX0Yda0zKHjYMJJa47gBtEFtoK4s+CLjh2",
	"Tx9h+Cg4fRsE6DvDfqp+7/DuJsFbhHQNtzTEbYIUSAdyR4D3AdpvyHh4aDcs5t5XTzdHk2cfsBGkZYCK",
	"iQXTWM0gES+z6T298N3e6XZMDfVURMw2PeAKCpsfdt1i9/CHbCz8D3qfDBd0/zepYUl9eOhaxw4feHPb",
	"JKeKLTyJAswYWgyCFqW7U+XtBamNv73316f+5Nz5vWnufMAxesM42202i+BscRANSwiGQH7bx5MYhq2q",
	"84FkBctTNwDWmd2r0sz4t9oRFA1b6Q2ENlsdVrDjtNYYgoeqmlWdEmatwJWDhIFLZr42Smm280Y2MhXe",
	"m4LMqcrUShfr12Y1Ez/a/QYRuxOjb43KgwubQOspYWAhoUmyJrySNpyrsaTXDCw4EIOGbyQklhN0wWoR",
	"YFwQSm6WIYviZmHG5YnfvSpI3MpSu0kl6ZJUDVJx1anVhnHN3zHBch6dsiwtjTVd1dIyT7B+n5cSDm2d",
	"0oo8IIY+zlJwq15D7VDFnkDSb3RrGlacVg9t2nj3ypWnjFfrdV5wdaq348+HYFyuMDbzO67qBawIBg9u",
	"khrUJgS19Yr5wlKgyqvLy5lW0Ol/XquhStWln9sFOn7KrnlXTgj8qhdd2Ep5vettVakrF9+adRpKcjqd",
	"iEE8f6PKW/9qBDLR5uQDuPN9cXkkVJ5q6gVJdb0vZqBhZQZIr5gg3P1OCqkfbuxJ9k+OyOOT47NzsutW",
	"Pdn9HbXEv/D4wy4M8sQpt3i8X6jlcxevjVL5CDPG4x9nLMoZ5j38lkoeEQhF19/fnr4CRGwjbjhSoL6H",
	"JpO44GpZXHqZw5IC2ESiVm9NMz7DfrMoXXmTizpAuqQS8hDU7ej+sWDP2Ff/OSWXhSIRFeSSESxnAFaQ",
	"qhV5IRTLs5xLZnT5/VgUJDzfp+nVfmQt9ZUxvJHOft5Z6wrr5JtqqCtzjPV0qpeMsPcsKhRmMxn0jOm1",
	"dT5liq9YGlJS/qFzvZJH8lE91euj1aN6qleN+4+Wj+6e7vWDL630MP/rCjtOCzH58A4cDuo/evKvXv9I",
	"87sk0nlRFcol1zTnEMt5xdY7aPbKKM+hMsW/UUdhcwgXQsPYm6I9L0TQ422lAV3HULfsBRVrQvNFsQK2",
	"E8mhVFTENI+x5CGRa6Hoe408vKyTi+cuycq4gNuZJMl4BoqVBeRVnGqM4vA2rLG2ql0EKUTMckI1MVmS",
	"nQidyN779bo3aX51yAM+QPoj5ge3mb5xu5DLF9NnF0JYI6JZ6IB3shBBklJd271NcK3sdkLV8jjr9Z6p",
	"9XnxXksHWCO0d11O47aFXBBWfnaIG9P4B/U4UqLygumjK3lYP80zCcRZ7D0135Zb9ykNuOCVIdaP5ROi",
	"5wd/MarA/ZAl6Q16lgELp7cgqeLS+MXBr+XSh5uta55dHoIcZiWp8XMqeUp0tiSgPyrRsgQ1iFkRxm3c",
	"Ecy+JPVTDVUvjiiVVYmlNyjOfFBjtfUivz8/P8HKLZoSeGRAOotyz9uFya6JdR3N01SRg30v/mRUyps0",
	"j0PcO34lJjcGmoo86yqNZ+V4vljOK54ht/Ejy8sSBJ68KVc8M1KSkTjItdPBnylWJXIQMM5fnWE+H+uw",
	"OmjpevQrth4++hVbDx9c87sh46Xmp7cC/UKyPCxg2K+9cw3w3qxuQLcoqpnZgbKowJUMk0Y1VTjxkhH9",
	"q5U/UYnxSCIRMUXaVOpkq7Uu1836oLAUyTReVvzdTc6VYuLOsmzelmWtKEpN8fm1iEiHlIsVlX2bz0v3",
	"cS0RAamM0pUm+XNl8jNXYscRihDIxjDyn4JBfY+crpgCf60iWhIq98jFZFdTxF2V7lq/n39C62+gdcjp",
	"Nygvl8f38CKyxcgQXb+lImlZexI6uZGqpRPHvhUFFGAtnHtKIpok+t2MklSgisOLSZAIAUvsBHBKj4f4",
	"hqxgKhKsBme7avYXnWaMEqg6ahDwc0lWkAhLI7jFTGSAQU6Ct8us2vKbl2t7wMbdjuiz0Ew1rIRJw0dD",
	"QqglSzKkZQozRZkdlXVNlcpKf7WNlHBT91x9GHO0ogsWKu8/2G/cGeDHNClWrFGmvyVor7z+S6cuPQWl",
	"ysERgbYQrZArPqeRI3Y7BbYzGl35q/dMJyCieGhNmiti8gUM92l0YZXmXu/GwfWNnbFOyz7N00RYeTN9",
	"+0/zdVoI5TmGFgCwDWoPK0ivdHfNjjrhGwHNVHmMnVG6uhFOVWW/gEn6emIn2E4AKnagICxOiiSpjF6V",
	"vuto/iZVJ2hlaWm5bFXUulrrkdvn0Yz8pCVKyRR8209u6Fo+wjAXhCOXJCvAEKhf4TVoRhq93ugvtU4g",
	"FdAkZzReE/Ye3G5FoPguzjmZNjcDow6MNNHwKcfRfzTG0j+Z8SxI/ZglUjjOes0vOJoP28KagfeitsxQ",
	"GOBhLU2WYWHQ5/v44GgHNGWcCtWmPh7DQg3HejfloCTsyOZ566aG/QtDS1zOFlwq/XDB87Kia/0klbkk",
	"We50FCmWvDC+DpoE2MFAX5Ok+mWUxJhY0nwl24RZuqXahnBRdr/ek4OizQ//HGGtaE/KNRuB4D41huW+",
	"zYtRxVZ1p0I2CxpI9KHxEGGmf5+oXdHcF0SdtYnPYAWKjTNpPo73yxwHAedLl/Kw3kGedC0+0wzL8zR/",
	"HcpRqGeHFsRkYbIJ/6xac055UuR+PijN+YILmpQ5VAdFyedM5esD+17Xl/Om5iGNxFRReVWVztG9eU1h",
	"NchXuQaF5sr7TjeYC+ThD7qdUecezjyzk/xRTv+GSnvw5JLN05wZz6gVza9Q05lVgDFegXdEEWehQ/Dl",
	"XzdqgCnZ12qAHflfP527UhxIdv/66YczX974mPtf/xfvM7T72CYkSihfmTAxqyD610/nvmDrYoBVukbN",
	"e0tycikLX/B1uUxs4C7yDmvEwbxo/O+bK/k2pD/QQCaP/3V2/Ib8xC7JD2xNzph6UsV6geSe5lW96ay4",
	"THhUVkI1pwaLhmIKVBV5IFbutnb5f9+o/ux8Rnq3u/Wh8A9fy275rtHAyQ1LyQ/FJcsFU0zuHmdMnC35",
	"XJXPbV2H6Y27DB5BGfJYzQC+An73IcjglyV07Xcl/76RkBfbklIJDNQvzCNomOuOcU34U3nRsmv8VJZ/",
	"45L88LWsQMElMYP4dfppvqCC/waQ2pcaZVYD6KtG+WN/T5SXYPL+h6lRsMCFhUW3q6+l3wv5kkZvpH/4",
	"02/3DwDKMqMRgrrK3eC/DXmasM32f1rv0bJguUCYWpwLAry1Au+VKXESHXG62eVtsarTiYTZhvq0OTcH",
	"O3p8YPVDd0v7Qa3aHU7g2AiM+se7jWEAqdbsHQBQKjwKYlzfUH7uvxp+6kCo12vX9K4OyYc64Nvsj1qv",
	"xKeYS8VFpExtpCm5WYKvA42WRL+1mpqgIUwhG3QxuWLrb+C5vJjMLoS+t+/pKksY1uMtPUS+yfI0LiJT",
	"LUVL+an4ppA7jEq18wwi8lj+zSWNrpgAJnP401732vbtDoqFWydwE5oPv6HBJb0GBw6Td6MKMCeI27JI",
	"4MOKqmj5CotGYSC8ipaVgwI6DO2/OWTxjLxYZWq9K4okacwusZtmJpYmBW7jZjRG7aNEr5vtof54udI7",
	"Fcpa0Uxv/Pcrtp7CGX9Arx5/oas2ytmAbW88vv7iPOnWK954QayFWjLFo+o4Ko8D1+9HYy4exzXNeVrI",
	"0rkcliFnZL+y8a3oGl0WwISSYlLi3ys/+ymxC/vgTy/FReG5+q9RSaXxhzulNfTflCR8xUslaBUhC+hd",
	"Wj3RjYyX1VxrNclYDuIoJEkCCJV12t3KHJDNn/6nYGWSBmvKUSnyo6XCzNa8NLowJ5EARb948JbnEskC",
	"xJZpWegajUeCvVf2rlQV40twHyCYwCil3xbJJRh4YSy9LJOLwLhqMwsys9O69Vnv27qXaPlRg0AtqSCU",
	"zNmNdcLDM82olPrqmUsLJ25jgdDYVdqYwZkKRR3Ypz3aRpETHiNrklhI1cSCOc+hLDhkRGNTUoiESUnW",
	"aYHryVnEeAlK42QAVYdEXRwOmLNXlAsuFkeKrQLyazOQ/VLqgxXKIJdZJwAeH0xNoDT4jb3ZFJKxB223",
	"AsJO2dMii1XAxoagQeor8KGzlA3sAE08L/dhFyVJIaB6IOApAlIPY4GesLkihYDLI2KSrrhyvAclyzlN",
	"DPdUX6gT60oem7xZlyyihWSEw2eIB1kWArzs0uorgMBUEEqoNI2eVPvJmQEdYmBzT7iR0qnwVjux2T7S",
	"JAY2ngpy/Wz27O8kTlHwZMqZA7FciypCH6PeROna0MQbvbO/Mqn4CkzFf8Xbxn8zETVRmiQo6M0IFs8q",
	"08ToeXMGlDI0NlqMgRrkpXemsTIMCfZvvRmN56zN1Ho9hM7h5DRaXrG1Sz3Nkw/qb1B5+FVL4CwXqplU",
	"evBVha2BgMAr20hjf6S5mzepgv++eK8fp8l0cpgy+SZV8LdXlkGlSGBfhjczihOV4sSbqD8a/KIGobPp",
	"d22wyy4mERmYyvVyuO25ebiaVeHiCLs+a3N2WMHEmpZfp4Kr1GNKaYoW0Kxf9nRdf0ynfk7dHf2dz2N7",
	"SK5mdyfgqz3Y5P2GrlhMrtHwDSJCW9fhMWUaW+MHrxh2FzN22HyNWrGa9rG9HU+jWrYrn4qytd+uGgom",
	"hiSws1BIzhR0XIFOXs3rdJLPo//11VfPg0ePn9s92xnY1Wa518MDd3cMbb6vn3f/H8Io0I3QHuWpo+YT",
	"Rrk6XLOHpfjwVQ3q+MygtcY1HWtH7cmjuHNMk4jr6LBjCNTdDBkmpD+YTm5yrtixSNaoD/xjKiKbh9en",
	"i+RNatEZHu0hMB2Kfge4RtWP7P2cs5w8BkFpDsqB2reykCqSokClwj+8DjXVbZ6HkjncUe85ncgozVhH",
	"2j0Dd2yGAmW7CHOvngdOoO9O44vRe5e1gM7FPO0bzrYbNqK+TgcJ5avaNfl5koGCNGfxL6WD+LvmxQGj",
	"jxvJW3qLo0nKSHPlgqy0Bi6cggCUNKxhCMkWGAhlsh//fOFZw8XkHXzRXH1i/5DF5cXk3ZM7cJdNvXeT",
	"IjsHWT8Hh8I2KOXdlObHR4cHPY9Qo0XjCTo6PBj8APU8EnqoOz8RziCf+gNRA23v89BF2vVIhni/PX1l",
	"Eb+M5Y0izanK2SJNFwmbRenqUyXlPI4+HiHXUL4jGX8gQvmvn87NY/AHJ5AGq++N+lVZZNp0r/ym715d",
	"A0+ThGQsB/Vt7NfCo1LRKBMl9DBqYKz9jG3RE8/DqguRYrLiuxgpqsaghTLRQ05d8xZAIlMZ9pyvmFR0",
	"FYjbhEBwPZZJzXtDpdlKXFNuxVSxHd3Yn8cRK8ZuOpfRIMZYgnb4fAsmnIT+rfq7oB6OSvVsLTExLT1h",
	"STWK1SrGTGrsNdmZyEmaFQlU8Lbwxkrk5JTReCcVyXpgStHkrjaq12ihMvmWwQsGbUGoK4PoK8zRYE0h",
	"5i6hmSSiii00d8LIYyBr8CuqDZ+UNo3JrWOkTP5t70NzI5jXWukkhqaKpDeQuAFrr8DvU03hLiDP8S5S",
	"KWOSDdgRapYQbxS1sRu5ZZhL2Ug6xplH0kkIbiwrtTzjw0IXmwXCvTCoORS4CWca2uAxEff2EnEPw+ny",
	"bOLOY68pnDEnt33P2xhhPbh62HRfswavXvqCgQA36o36xYIoKaRi+YHGqTQ5SahgYQCU4DW9wCyYpwnJ",
	"dL9PyUnO4zV4J/njnlRL25UdMiak3rO/DPQnpsXpYqu9VMbhott2xbEWx1hV509ZVce9Ft7UoZ3lNfou",
	"mt/jsNmiXi7H/TpWzfn4VXNa5zHI2F8jt2MNnc+1hk6LfHRe9jbH7uq22ne9n3EkJeMIDKNcpjc2r2ju",
	"hxV7j9fTx5G/MN/I0WEpwzcWOEDCPaEqWp4i/kDcqr0vG+Qz6c0npjdpEmq5PB6NsXJjlqAfOdZwhGzm",
	"AecjfzawfQKK1pMUqFmZQMHvuuRfKl5dLcHH4L5pFjVrIV+adWVsbRKOrgpC1Tfr0GfICKpI6nTEKTGE",
	"rbwbPCkDR3xAckqCwoMDqjSTZbI8KklS0anGqFqGqbBnVKO8vpgsmLqY6H/oJxT/hbpK/DfSLPw3VHzB",
	"f6J6Ef/9V1QjoRK3nOHJZry93WAoSsRQ63LZJsc1rgByZ8v2asqn68mQ6HyzgKkLUh9SVafq51BKqJce",
	"zk4AEa4NSIwnnULVLjysO1g1hWPQGPzMOujZa3hwVuaDSamSi6s8zKYe68NGIHcsxG/6ul3uL9B03lBZ",
	"vumblYdwZvVDM6GKXweypJ26FV9z0xTDnPy5akJUut3XuutapfybVBllMhUmKQtQRN3eWhrSa5Y72dXK",
	"GJ6JzKNdLmL2fvZvOezxqyXL8u27/GpJtMWRRuqqeipokwrKe/6nHedfy1vuwPw7rlxcgHwimL/LTVQ1",
	"Sh6jjmDUEexWl2iz8rtOv+3W4K0G9j/f9e919UL5jY/Vtf8A2oW8cRyDuB6H4o+qhc9VtdCgOh2XvJUe",
	"oh5GWGcqhvnVN8va9OY4d1OX9jU+k8uqbc/WAwWXmi02q7pUh8gdqx7VB7tr6aPNqg/ZkJr9hOXqtEiY",
	"T0RxdtBmoJcN82O9QBnk6dRj++2aRcjb5tDinuVx+Qq5bCd3Ab1mOV1oec/oK9JLE31rkg7BxFwsZuQl",
	"nOded0mL/mIVXYUqLi7iv4VqU0wnWU/Z5nq5ZtwRxuHlfLHQhNIHSXREwgwT1yznqr+2m3veZ6YT5uVt",
	"VjyzIzrHVNtH3Tzci1y1ydr51M3XFs5YEeYnmgs0wR/kHKKKJ9PJkZinAzNdBtdSDRxs4swYbINLcTb9",
	"g/cRPS3fRf1sEPZeC+8xueYUtr1/cuRu+kDjL5i62Rlf6GVareh08kLkaZKsmFDVb1jGbGJqzU1qkl21",
	"srO1iCbTyXmrPON+oZbWNyQgKNYC8IyGORg9dnDyNkjAssIXzTedHHJ5FazSxuWVvxdGOgbjJoNxkO3o",
	"MTdAcXAQWWA3fc9Y17p66tUFIKEfw2C4ZfsA/XzBmZvSEwkgNkc/x7AaltpHxBf/av2HoRHJdasZObaJ",
	"JPDXDNI+GErApdXZbsDWNl8zD3cr6SpLuFhAnr5rX0n28vG5ZOqGMWH3T6CrXvcDvCdl1aOOgkeho566",
	"R+HZcRexBuoQpFv6a10RVPM1hJwgJtEE5hI1WWkrpWGKxQHA/8XQQtT8j+bqUWk0Ko3axExfuU3VRk7P",
	"bSuOqqHLovxB6wbmnulNH4rNJAaqx0VkHeO5JDW6gxgw87rC64Pm6nsqPVp+/atlLDFBCTT2iyT3Y5Dx",
	"QC2cCrYXYNBKQkWfQlOfzQHWZZhxQDmtHWFteX3YYRWLIzX/yOpB03ktoo35KOAFRgXh56sgbLwwnWxf",
	"Q0mIqacS9lg+KZk6zM/VqR3rKcOMNchbJfO4aBXmOdItyxZYRKPqUF17RbnAhHU+fhOTM4tUo47tzfWd",
	"fkGjpUmbWR8K47nsAHrBLtPbfVcftsjWkFLSNjKtLCndhvR9VZL2cCnd+HcLPa3b/46aWno7UtpZ2dcq",
	"LA/gxQ3l5SoZFrLUjEzpdqHXEcjUagf+riOgsRzciVf0jD0kDdktFM4fyTGmNrmXAxPs5tgfWwg3lN0Q",
	"CD0kj3lZFuQyYeBcJYoEHJFs+IwnGoVd87SQHRPYJneYxTxzLzlL4g7OADLhmSBPKMlr+lUkoKItJaqX",
	"oTCwgzIC1UgM+J+ZzRtn/1ZG0+iFd6f1osaX1vflRa5QMqc2YQm0HJDd//TlAdF9y/rId6kCX4862l7x",
	"d5tOq7P6eyvtt92Zb/ObRROZ/PVFIHf9aZokaaFQX425h/1moJLdWKY3wGZAW5PYGh0JcxyrL5XZt1RF",
	"yzMTwh2i1vVGbe2wVDlVbLEerhpujNgBDLdOWQ1V3c/WHmY2TTL81fAM4APq8QLHqD6keudVNflODXNR",
	"1T+O28fUKT34DxfjGPMC9vVtES9Y/yKa7aF0KNRqPF/mTC7TJB7g4GktVn5/O1ztmT1Z782w547aipSb",
	"pPgIGIOUhnuqn4x7J+uo4LuZZ3K5pbLMZ2ffd1VlznJ+TRX7ga1PqJTZMqeShcsr43fUZcvlSdn3j1FV",
	"ubak3urHZucAoOEFkH2I4zohbBabIN1j7vFzuKdKq3r7DRdOW3e1q95qV6XRalc+Ihfi8A1Xz9GUoIpc",
	"GLWBxraIJonhUOJUPLJljgnm4XbyS4xKpvtVMum74zm7YrFgkN8GHH/N4ei2JvCc23TyU/KU8LnNxNwU",
	"K7547lXpjlqmrWqZAuXFhnjwVCI1wtHGhgSUHFT6XYVWNFpywYJT3SzXjQn0QRtx5GLyEqubXUzMekz+",
	"ci6rFP5slam1STkOGcvrOoIq8f8+OYVlkiihOSZqsf7rZrOAxpeFpjwMc5+n1yzPecxIwHQgu0mcjYcr",
	"gUeOoYLCHrmYnCFTczEhae7u9N7RRrP3O1TEOwakvSTfp2w0GzdkosSACum8DwKEV8T7keLXTIOIhYX9",
	"JV8sdxK9KaJ3S6juZArsK2PhKAP4YEBYRZLSGF17uCh/xmpzk+nEDgINYlb7c0UhOTwVJgZwrplN/GTS",
	"7w90O2rvct8upP3p1Flx++tRtYf2x5d2V4EJ7cbanw/rO283eF2DhW/VDnTan99aeFVn/gKyhPScOaYS",
	"qXtKwuHPeVI7cJu+pExkspMXwmT4Sri4gk/4D+cLTTiVcNISW+A/nBZ6Zh6hVGln4AKVxJMyVxj8DJw2",
	"x5xylzR2sGQ62QxRHNC8KPcV/HZaLrbd5JXdeuhTV+d9A532l9cWXqFPXcOeWZC2Px1WQG5/PKrA3v74",
	"nXMQHgRzjqb99Vvq7/W2PD4P7PUb46Lzq5TGPcis7/UAVJaquNTImtIYtiNStTNPCyCylzTekUyZawqG",
	"WKCw+cJB39vSp3ILZ7iC5s+v7IqaH96k6qVZYPPTtzQ+K9fb/PjCrL/5+2u7n9aHBt6VHzz05a3gqpI3",
	"GrJBRZl6pS//C9VMoud9sMIslU3JpBGgHisIKZXOvreSb0zZCl9R+v4VEwu1nOw9f/rl18EMTptsqkmC",
	"PyDWbTJEHe1BM3NZ9vddgRt8wqew9R29iZ0yZ2L1jJfgyAsh7GtcAuCrL+tOcnTnt6c7/9h59zev17We",
	"yL8auH5gbiujqaVcxjOT+fJi8qQRx+l87BeLBcRburPWz8gF9rSGkg4UfUxT02e3vbd6g7qrnpt0kFil",
	"/Cg+jx53o8cd9Ghcns2c7pqdt+t31xjdH7XpaVQP3Ww0GFVnH98/y3ckgxwLmk/B6Kb1ubpp+chS391v",
	"RXTW3n5jtwqzAGBI9HNO8IncLFNZDWDv+xwC1dJ+LRKOP2SzJe2t6pV1WgzR6GhjaO4YmYlw2o6vj8Hq",
	"fdWRw7xWmrkE7g2V6Kjj5FkZks98E8ecVpkA7zls5nxVbsDg3gzOl6/Y/6SC1bLNTl6lGF7XWIOGyW+p",
	"YE5CWGlCbGC2o/03+zY11f7pi/3dV8cH++dHx29s5WX9Y50Hxlql+qTTnKQRowLfENvTpnGHS5PRXPGo",
	"SGhOJNcnwdWSGy8pmjM6BWnOSAlkf8VyHtHdN+zml/+b5ldT8qLQ+Ld7QnNug50KQVeXfFGkhSRf7ERL",
	"mtNIaapp94p1kGWRZWmuWEweX0y+e32OeZ3enh8YyaRFns7TKyacnGm+MmHGryMv4wV9tVd+4XGwv6Hf",
	"1Wn4UiS/30mRvMZswcQOe69yuqPoAglLmq8me85UH4LWpf1amujSqlTLHv0L/LzIKaab6XaNGri0NGbT",
	"dKUvfKbW5fp+QUO0z23r5IeDF7g+22abayknbiwKNv2L3z/IHBc0absGob72F0CGZoUhAKhfd9S/XGdJ",
	"SHxQa/dLkfPgGm0j8vb0iDy29KrzpAmf10rw1vOJG+x+sq0zcHfROII6JD3Oq/DZ1i6GDH5Oh+2ibW3o",
	"xjoh5XTwBODrtpYBg9Wmb7xCDo5MHTLgZQWQpGGdrl6aZpq1BBowrIWOyGakh0Y4lD/nJagrQ92xHLWG",
	"S7jzL506w9pAzqdAAs6M50z+wn36H8z8rVsYj179rnBhg1D9wVM8DgLo6PCAHB0aKD/+10/nT2bkBJ9T",
	"tw44tANf+jRjgscVVnnsw523pqQLzuXxu7frLwECiGBoUr5vGc29ke0+9x70ljuLliw2aTGaromVCCxN",
	"K0u2Us0XRSROb4Sx6AGPgfybdOvvK76yX9MM3YfgyIxDYwOXex3mDvJU1AsES0Vz9V1OI3boJNsY6vmn",
	"HG6tUxi17VpCj5/LfytZfiTmacft1ghlm4Wvd+Bivui+kf5KHS+LJAGdcG9lM4/8oJday3W7vUzPnqpe",
	"bR7EtinLefldFIpLnxsPivVdbJ33ijiaovqpXIdUSN9x5Uqi/lpTAfnFDvpOz+zUVG5N8rpd19lkHMXC",
	"z0ODknAcCEsyPii2iH+OpM4w6TA43l5ZtxrsMhXtigUX73f1cmbxXp72F2LwB8xAkpeoyLlaa6K0wpVf",
	"AknTJLP666WVDf/10/lEv/669WTPfK3mh3yQiNmh6ipv3/oTOdeKKzmhAoS8phmo7BqpqavyaDOLnPr5",
	"mvynYBA2hFitl6K5geoOZPwHZrgILXAaKV7RCM4dKstN9iaK0dX/nid8sVSRSmY8rUbUu3gJX4gp0ULO",
	"GV0Z33QEgtzb3a31btXJ+rk+xLvHvm5PjFYNEdo4CEcJzTHB6IoKumArED3nqEYBQZnFC1Y6tOuHQC0Z",
	"z8lNml/px0POLgQ4METMEEqzs/2MRktGns+etjZzc3Mzo/B5luaLXdNX7r46Onjx5uzFzvPZ09lSrRIk",
	"8QpwtQGk/ZOjybS6yJPrZ5dM0Wem3L+gGZ/sTb6YPZ09MzFegI67NOO71892NUu+G5U+rgufMuk7pppF",
	"V1pVhkpnKY2gIBEaF1NIlgxPAsz7/OlTixqmeKMJmtF9d/9t/NGQ4A4p7Wi9bj+0MOH4Bw2CL599vbX5",
	"SktBay4owSTSipaxGCZ//o8HmPw8TclrKtbEKBXQloHs/s+T+sFN3ulvtcNvpHEOYgCo9nuTRUNKqGpK",
	"88z5MeQ7pk6cye8RUxpJsD1A7EyDDWf59NkDnOVbYWVkg0F/SvSdTv6+xcMPT31kTVRoGyHo67LR7bF1",
	"nYNXp84elymXyUmevrdVB40mxBrQqlMI1brCpDwq5+was6i7Sl7/ZbNLuM9r1hIWfBjeWO14t8a7Fbhb",
	"1zThsXFT8t6tH00DKHtcvymlNqJ9E2wvYIdyumKK5RLsVW222jeqvnx2aSV7vGQ0Bpbd8nyuqtPy9tRT",
	"XAITwd3ThezCDL0T2AbewIeY9FsaW0x8uGt/bkJkq72O9/6Pfe9/t8+cvksfdkv1Y5b2WszYe0yD5Hto",
	"XZOa3OCtfXyy/9rUtHzSNncYe1eS3qCqAWxMRt/gpz/nxpzTSXzeOAlGOpiAQlYkCNQRJQFyYThx9RZo",
	"MuihRwCkb9N4vTWMqZk99ZG7Q73fubm52dE8wU6RJyYC9NZjf2hu98M9kti67SNIf0q96JaJbe/0NZq7",
	"wS20+BMWCkFkcjPR1nPq1BFfN3bbyr4LAOW6jZ69bKhRHhRRZQ6fIlGODxM6ZM9IVZTLXCEYQQ8AlfpX",
	"VBnXjVqjR+hyULBHmHLDKhPLTB8g/tqTDGnG7CCdj/7UV7Qec3GYhJsq51Fd6MaozbIatTQ16XlOMLfH",
	"jByimwYQN3bN8rVammJfvoVCrzMnA8gDrRbTmUwtkeRiYULt0lyD+IqRR988mpJH3+j/pSImj/7yzaPK",
	"+/uKrZ99A+f2bHrF1s//gn88N/4Wvp3CjLfbqcakFX3PV8WKiDKtn0W8cpMGU+oIAmhoYgSg/pA0apQQ",
	"otW6Ez6vYzkUNMJBbX+DvysKsIXy/9YrJiZUOhcHsrvK4lJCVgOFtyiIGXwFfvEVnHqDgO+VjXUJR0iB",
	"Y9R9ny8f2xJfn37xALO+TPNLHsdMfHTm9SF2e2YsAm9FqQdsPZpZmXf9wzTAkh5ASUItlXqfx/briB1q",
	"Wd3vhwurTTGIU3p2j3P7oBaP1/jer/HTh7jGB6mYJxztzyPhqBOOEK+9+zuIvEhREqa83iz69w1oC3Zo",
	"0JZexZeb4NI7kWb8cI0BAfR2gueDK8Is3/CnuftfPsCUb1JFMNp4vPweriFsZR98q79j6l6u9AKT/vzR",
	"73MfLzHe6vFWP7gsQFXkcU6DGvkb3Gxofy93Gxa41ds9VEDZgan/tqHThu7zkbS6Q+nLKKZ8XkRtlIw+",
	"PhktPMwR+vhvQEVPWZbQ6H7EnqpYy4MT0vvU9Dw09Rx1SyPRHon2Z6bOiqpCqBILoVqPi247crCAap9R",
	"OdhxtDCPFubRwjxamAeRwiAVGc3No7n5oz2zwcd0gO15wIsaskN3FTO/D1ElPN8DW6h7FjKKFKO5eiQ8",
	"g5j9AYbs2BiyXUJFzLUjFcHxGbO7CNRGKp5+GjmauUc1xGgQ2wK34hX9c0ZjFKtLmSLquNstE/gDE4Kt",
	"Gcch4fV/CnaEWUeAr/k48s1IK0Za8ceTbDot6beSbKDvA5OL0d5+v/RpFLpGO84o590jGS68LBsY1htc",
	"28Fgrs0Y5h+YFH8SJvs76sE+KjUe1XDjizC+CKPmz2r+dmmW5ek1harG3odkHxowAsn3xLqLr2+z8+gP",
	"Fuywbyff2mOiUkLrCx4fk5G1Hwn5SMg/bUKO6UxpBKlfd3MmC0xa7Dcun8L3MgfqJZUsJqlA96DKY4eK",
	"eDc1bjjlrz4fXT0aFoKR92RbxtFxpo9EAOtLCGdqGWnf6FJy72Shdt8n76aT9zv5JY1swVUYA4VlTBQJ",
	"EjRYa+GWWgrxoU1Dehw88Rb0eXNWxGB03RxdN0fXzc/EddODI5dpmjAqyDyhC40npk4QSUWyhtWsVjRf",
	"1+u7yRn5Se8EQJUSkKxsWnsEC0DSJP/HoeDmm8HcJLlY5AsAnt4Ilj9CbKrh/aMKRs1iX1BR5ZEZWA/1",
	"iHAJKwrBzWnrwzIDj3t2EEH6Ojq1jhzIR+ZAhniwNliGkLsqNrtX+eGhHVHdWUd19+h1+iejDG3ZYoPE",
	"SP1kA1uWZGMjDXFj8NE9dFSBji5fm7774fxH/Zf3O6a2dnM/kWRHYW5gvLbjtX1Adr3bLbP36kLDrV3e",
	"0btyiwRklCRGe+sovGyLTnZlMOonk8ZDcmuE8pPwfdxEz/JwhHHU6YyUeKTEn50aaTdmUboy1T2DDopl",
	"rfjKAIXqHqdvW7VUfdyigqka9JMg4y4URl53pLCjhP6R6V1CpZIMq+h1F3imUhHdkii+YlLRVRYgTB2a",
	"uVdUqjPWX+NumIYuuK45+hR+Gtq7EiYdvOaX7XN5k0Kdd72IkYyMZOQjk5GciZjlWJmxk4zYhoZt8tKK",
	"U9Nmm9p83+TW6clUz9wi1fD6gwGluhLpjSgX8iPLa6xbwzEIGp/W207+qLaGkUqN4uRIFxt0UeLgfVQR",
	"m2kKtomd06x8tHaO1s6RCfqjWDs3vs6O7XNrF3q0gI5aoZGSjZTsLvbIjQlZzTq5NVI22ihH0jWSrlHG",
	"+wPJeEzkaZKsmFBRKuZ80SneVY1rQWY+qe5F2fQAx92AetKB6a4wDHYOofiES1nUE6vOyNGcmPot8bQM",
	"jtUQwgC6JYuuCO/LiWLi7KR/Eoing9hFLklEJStD/LjV05n4yCZEZuRIEJokJFVLlkNfXKQDZXciDJOE",
	"lV8ywlaZCgYvRjL/aKq11sGPJH3kRv8kBLa6ud4sJK3PPckEqqs0sEpUq8OYYmBMMTCmGBirQ234co9V",
	"ocYA+j/iW9oXSy86nsxQXH2rxz2F2LfneeBo+8ACRiftMfB+5M693PkG4fibUR7s5aM8G2mYw1OOAfuj",
	"zD6qYT8pziacLWAz2lLTvd4LYflEPGwG8TsjgRmVgh9HkOnMMrDZlYdO93zpRy+c+yE8o4w1slMjO3UP",
	"9LUrO8Fm5NX4At0zgf0kfINuqcT6KLR11J2NdH2k638+dd0tajJ53oP2M2B63cMz8MlVXWptoaxE9bGf",
	"A7uQfpXiSKBHNcNILm8V1nd3heTtPOpHteRIL0Z68fHUknciA34l5X0QglFVOaoqRwo4irSfg6ryTiQ3",
	"pLi8D6I7qi9H5m9k/j4XYfFazxMUCU+Zyjm7ZpLQMhABu8wuhD8wBQfsC0b508Q7nKW5ImkesxzCF01x",
	"P4g/0Buyyf/qsSaP9BiPyGPBbjT1nfNcquDiYPDaomIcCqqcymgynTBRrDQyUPgLfnw3vW2sBp4/nps+",
	"Ihts0RfHs506i591FNO9aiP0sY1xHmOcx8d7ijQG1p+fecJYX2zkS92mLx7yJQ40xkCOMZBjDOTnW2b5",
	"yGRcCNVTtpsGuhJaCY1NjlZ5hoN8vPLFQLbGR3l8lD/aoww3ZUjx4vozHIqxhFb3FFeJYz9wLKUz6egD",
	"NsZP/rmIQotT3/0d/vthV7FVllClGULJUxFm4YH9sK1J2dzHw5+bVj9WjXrV1umNQO5Jv/qtaQJK6rlD",
	"pG6ZGX2UJEZJYpQkxmwqms426NbIzo/s/Cf0cg9IfRCb1AetBzaQ7qBxIe78jt/fM960fA+cecypMJqX",
	"R/NyXX3g5f5zRmNkfct3v5eGfMfUSEAekoA0oT1SkpGS/KE4l8G5mXqVlNjQKik3coqrDz2mXRov9nix",
	"t8EiQOKj3ov7HVNburVbDB76c5gnR7Ixko2Pa5jsTKDUSzqg3ZaIxxhwtD3aMepBxyCj0Uy7JRLZlQOp",
	"l0Ka6KEt0chPIj5oA1+SByOJo9vKSIJHEvx5aa36cm6AgrwK+6yryi1B9ovCt4vtvFeBeJRFR1n0TyyL",
	"NmvPDpdMt3WXR/l0lE9HIjYSsVtIizkKgRsyI67ouC0iNgqQIw80ko9PQNJBx+5BySNiLhUXkSodsLFv",
	"mROhojMVJVhnLJRl4hXOPIDU6FGMT3RJYHKzsHIReboKWeOuuIg76Y3NrWDK2g/Jq7BP5jwx8QLNtaQi",
	"WWPEQBnxTNSSulEBC37NBLYvHd3vxYt+C6tEB/K+VW7dA75CN1zvgySruJ30y97TVZZgD1ztC/wFLrWx",
	"AO9NzI+V/72+OYm9BuBoj+lernmeihUT6pssT+MiUuhAl7MFT8U3hdxhVKqdZ3oDnOXfXNLoiokYL/Yw",
	"GgKXb/RyH73cP9pbBHhff4vSfEEF/w3WsVk+o1rPGSHHmrYhtZD1j0jiNPkoJMvJkkpCo4hJTV/8aSmO",
	"a6v6syZFuk+1oAvhkSaNNOnBaVL1REO2mrRx4y3Jcn+vU66cZankKs0568mEc2pbrvvS4Zy6Y45JccZQ",
	"1jGUdQxlHUD+KgozvqXjW/rR+PvySVwPyUzjeRZD6WmqpveUo8aZ4IET1TRnHt1+xmw1f0JqEWCsNwki",
	"G0RPsHWNnmxk9vJMMsaUjcao0Rh1GwahI7Bs0GX+jqmt3+RPxK2um20Yr/J4lR+Y1+8O9hp0nY1b2ZYv",
	"9Ohbt2WiMoohY/TBKPlsk3Z2RoENIp3Gn2/rxPOT8OnbVHnzsARzVBaNVHqk0p+VfsrYcNci6rX8YtOz",
	"tYj6bb9V29H4Oxp/R+PvaPwdyBRUhGM0/47m34/4YFYP4zADsOd1DJuAq8b3ZgR2pnhwM3Bz7pG3Hw3B",
	"f0q6EWK1N7MFDyIt1hpcIy0b6k08E40W4VGsH81It+MZOm3Cgy41WIXv4UZ/Mpbhbk5ivNTjpX5wQaDP",
	"OjzoYhvT6D1c7dFGvHXyMsooo/1hFIu2S0V77MSDiGhpKb4HMvqJWIs31fI8NPEc9UojzR5p9melyjIl",
	"mkLGYi3fSjO0U4GqJddWhbXujUQNqCY1WlYeGq0s/ryDvmg0xZe6yJPJ3mR3ol9L07qJXMcWizBtk6aE",
	"TCizhZlTwKT2YdK29joDpYLsF2p5kqfXPGZ53bfBGS8zDXpHO2C54nM9NzvjC8HFwpyCd+ioai2xdV4+",
	"Kd3zYLon76BY7KV7BA1AbEdopGyt6toA5vfelbwQeZokKyZU105Z2WrQDvX6TNInLhaEXWsEdIfTP/Qu",
	"rZ7bz+2P2cQ2WYLJ5ESjPJWSxHw+ZzkT/tExP8wmo7tpRLxD1vI39O07lKjBjOU4BPWPFHL8KcdyHooB",
	"O44Yhw17XgkzoqURH959+P8CAAD//5mGiuXu8QIA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
