// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/service-tracing
// gowrap: http://github.com/hexdigest/gowrap

package resourcesync

import (
	"context"
	"errors"

	"github.com/flightctl/flightctl/internal/domain"
	"github.com/flightctl/flightctl/internal/instrumentation/tracing"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// TracedService wraps a Service implementation with OpenTelemetry tracing.
type TracedService struct {
	inner Service
}

// WrapWithTracing returns a Service that wraps inner with tracing spans, or nil if inner is nil.
func WrapWithTracing(inner Service) Service {
	if inner == nil {
		return nil
	}
	return &TracedService{inner: inner}
}

func startSpan(ctx context.Context, method string) (context.Context, trace.Span) {
	return tracing.StartSpan(ctx, "flightctl/service/resourcesync", method)
}

func endSpan(span trace.Span, st domain.Status) {
	span.SetAttributes(attribute.Int("status.code", int(st.Code)))

	if st.Status != "Success" {
		span.RecordError(errors.New(st.Message))
		span.SetStatus(codes.Error, st.Message)
	}

	span.End()
}

func (_d *TracedService) CreateResourceSync(ctx context.Context, orgId uuid.UUID, rs domain.ResourceSync) (rp1 *domain.ResourceSync, s1 domain.Status) {
	ctx, span := startSpan(ctx, "CreateResourceSync")

	rp1, s1 = _d.inner.CreateResourceSync(ctx, orgId, rs)
	endSpan(span, s1)
	return rp1, s1
}

func (_d *TracedService) DeleteResourceSync(ctx context.Context, orgId uuid.UUID, name string) (s1 domain.Status) {
	ctx, span := startSpan(ctx, "DeleteResourceSync")

	s1 = _d.inner.DeleteResourceSync(ctx, orgId, name)
	endSpan(span, s1)
	return s1
}

func (_d *TracedService) GetResourceSync(ctx context.Context, orgId uuid.UUID, name string) (rp1 *domain.ResourceSync, s1 domain.Status) {
	ctx, span := startSpan(ctx, "GetResourceSync")

	rp1, s1 = _d.inner.GetResourceSync(ctx, orgId, name)
	endSpan(span, s1)
	return rp1, s1
}

func (_d *TracedService) ListResourceSyncs(ctx context.Context, orgId uuid.UUID, params domain.ListResourceSyncsParams) (rp1 *domain.ResourceSyncList, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ListResourceSyncs")

	rp1, s1 = _d.inner.ListResourceSyncs(ctx, orgId, params)
	endSpan(span, s1)
	return rp1, s1
}

func (_d *TracedService) PatchResourceSync(ctx context.Context, orgId uuid.UUID, name string, patch domain.PatchRequest) (rp1 *domain.ResourceSync, s1 domain.Status) {
	ctx, span := startSpan(ctx, "PatchResourceSync")

	rp1, s1 = _d.inner.PatchResourceSync(ctx, orgId, name, patch)
	endSpan(span, s1)
	return rp1, s1
}

func (_d *TracedService) ReplaceResourceSync(ctx context.Context, orgId uuid.UUID, name string, rs domain.ResourceSync) (rp1 *domain.ResourceSync, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ReplaceResourceSync")

	rp1, s1 = _d.inner.ReplaceResourceSync(ctx, orgId, name, rs)
	endSpan(span, s1)
	return rp1, s1
}

func (_d *TracedService) ReplaceResourceSyncStatus(ctx context.Context, orgId uuid.UUID, name string, resourceSync domain.ResourceSync) (rp1 *domain.ResourceSync, s1 domain.Status) {
	ctx, span := startSpan(ctx, "ReplaceResourceSyncStatus")

	rp1, s1 = _d.inner.ReplaceResourceSyncStatus(ctx, orgId, name, resourceSync)
	endSpan(span, s1)
	return rp1, s1
}
