FROM registry.access.redhat.com/ubi9/ubi:latest

RUN dnf install -y \
      git \
      git-core \
      openssh-server \
    && dnf clean all

RUN ssh-keygen -A

RUN useradd -d /home/user -s /usr/bin/git-shell -g 0 user

RUN mkdir -p /home/user/repos /home/user/.ssh \
    && chown -R user:0 /home/user \
    && chmod -R g=u /home/user

RUN mkdir -p /home/user/git-shell-commands
COPY git-server-cmds/* /home/user/git-shell-commands/
RUN chown -R user:0 /home/user/git-shell-commands

COPY git-server-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# So sshd (running as non-root "user") can read host keys and config
RUN chgrp -R 0 /etc/ssh && chmod -R g=u /etc/ssh

USER user
RUN git config --global init.defaultBranch main

# SSH key pair for git access (baked in at build; test copies private key from container to host)
RUN ssh-keygen -t rsa -b 4096 -f /home/user/.ssh/id_rsa -N "" -C "e2e git server" \
    && cp /home/user/.ssh/id_rsa.pub /home/user/.ssh/authorized_keys

ENV HOME=/home/user
WORKDIR /home/user

EXPOSE 2222

CMD ["/usr/local/bin/entrypoint.sh"]
