# localhost:5000/flightctl-device:v7
#     $(IP):5000/flightctl-device:v7
#
# Image built on top of our E2E base image which also includes microshift

FROM localhost:5000/flightctl-device:base

ADD test/scripts/agent-images/etc etc

# Use BuildKit cache mounts for dnf package caching
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y microshift && \
   systemctl enable microshift.service

# Create the required directory structure in /var/crio instead of /opt/crio
RUN mkdir -p /var/crio

RUN rm -rf /opt && ln -s /var /opt
RUN ln -snf /run /var/run

RUN firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1 && \
    firewall-offline-cmd --zone=trusted --add-source=fd01::/48
    # Application-specific firewall configuration
RUN firewall-offline-cmd --zone=public --add-port=80/tcp && \
    firewall-offline-cmd --zone=public --add-port=443/tcp && \
    firewall-offline-cmd --zone=public --add-port=30000-32767/tcp && \
    firewall-offline-cmd --zone=public --add-port=30000-32767/udp
