# empty base image
FROM localhost:5000/flightctl-device:base


COPY ./test/scripts/agent-images/infinite.sh /usr/lib/flightctl/custom-info.d/infinite
RUN chmod 755 /usr/lib/flightctl/custom-info.d/infinite

# Example: drop-in configuration file
RUN mkdir -p /etc/flightctl/conf.d
COPY ./test/scripts/agent-images/10-system-info.yaml /etc/flightctl/conf.d/10-system-info.yaml

# set the working directory to /
WORKDIR /

