# localhost:5000/flightctl-device:base
#     ${IP}:5000/flightctl-device:base
#
# Base bootc image used for E2E testing and agent-vm with the following features:
#
# * User/pw: user/user
# * Trust on our E2E CA Certificate
# * flightctl-agent configured to talk to our e2e kind flightctl-server
# * greenboot and podman-compose installed with podman service enabled

FROM quay.io/centos-bootc/centos-bootc:stream9

ARG RPM_COPR=
ARG RPM_PACKAGE=flightctl-agent

COPY bin/e2e-certs/pki/CA/ca.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust

COPY bin/rpm/flightctl-agent-*.rpm /tmp/

RUN if [[ -z $RPM_COPR ]]; then \
        dnf install -y /tmp/flightctl-agent-*.rpm ; \
    else \
        dnf copr -y enable ${RPM_COPR} &&  \
        dnf install -y ${RPM_PACKAGE}; \
    fi && \
    systemctl enable flightctl-agent.service


RUN dnf install -y epel-release epel-next-release
RUN dnf install -y greenboot greenboot-default-health-checks podman-compose && \
    systemctl enable podman.service


RUN useradd -ms /bin/bash user && \
    echo "user:user" | chpasswd && \
    echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

## Add your flightctl configuration and certificates
ADD bin/agent/etc/flightctl/config.yaml /etc/flightctl/
ADD bin/agent/etc/flightctl/certs/* /etc/flightctl/certs/
