# localhost:5000/flightctl-device:v3
#     $(IP):5000/flightctl-device:v3
#
# Image built on top of our E2E base image which also includes on dummy servive
#
# * test-e2e-another-dummy which just runs a sleep 3600 for 1h

FROM localhost:5000/flightctl-device:base

COPY test/scripts/agent-images/test-e2e-another-dummy.service /etc/systemd/system/
RUN systemctl enable test-e2e-another-dummy.service

