# localhost:5000/flightctl-device:v7
#     $(IP):5000/flightctl-device:v7
#
# Image built on top of our E2E base image which also includes microshift

FROM localhost:5000/flightctl-device:base

ADD test/scripts/agent-images/etc etc

RUN dnf install -y microshift && \
   systemctl enable microshift.service

# Create the required directory structure in /var/crio instead of /opt/crio
RUN mkdir -p /var/crio

RUN rm -rf /opt && ln -s /var /opt
RUN ln -snf /run /var/run

RUN firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1
RUN sudo sed -i 's/^SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
