# localhost:5000/flightctl-device:v2
#     $(IP):5000/flightctl-device:v2
#
# Image built on top of our E2E base image which also includes two dummy systemd services:
#
# * test-e2e-dummy which just runs a sleep 3600 for 1h
# * test-e2e-crashing which runs /bin/false and attempts restart every few minutes

FROM localhost:5000/flightctl-device:base

COPY test/scripts/agent-images/test-e2e-dummy.service /etc/systemd/system/
COPY test/scripts/agent-images/test-e2e-crashing.service /etc/systemd/system/

RUN systemctl enable test-e2e-dummy.service
RUN systemctl enable test-e2e-crashing.service
