# quay.io/flightctl/flightctl-device:prebase
#
# Prebase bootc image with everything except flightctl RPMs.
# This can be built in parallel with RPM creation.
#
FROM quay.io/centos-bootc/centos-bootc:stream9

ARG SOURCE_GIT_TAG
ARG SOURCE_GIT_TREE_STATE
ARG SOURCE_GIT_COMMIT

LABEL org.opencontainers.image.source="https://github.com/flightctl/flightctl"
LABEL org.opencontainers.image.version="${SOURCE_GIT_TAG}"
LABEL org.opencontainers.image.revision="${SOURCE_GIT_COMMIT}"

# Enable EPEL repos
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y epel-release epel-next-release

# Utilities used by tests
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y python-dotenv

# Base services and tooling that don't depend on our RPMs
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y greenboot greenboot-default-health-checks podman-compose && \
    dnf install -y firewalld && \
    systemctl enable firewalld.service && \
    systemctl enable podman.service

# Create test user
RUN useradd -ms /bin/bash user && \
    echo "user:user" | chpasswd && \
    echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Create flightctl custom info directory
RUN mkdir -p /usr/lib/flightctl/custom-info.d && \
    chmod 755 /usr/lib/flightctl/custom-info.d

# Add custom system info collectors
RUN echo -e '#!/bin/bash\necho "my site"' > /usr/lib/flightctl/custom-info.d/siteName && \
    echo -e '#!/bin/bash\necho ""' > /usr/lib/flightctl/custom-info.d/emptyValue && \
    echo -e '#!/bin/bash\necho "no-show"' > /usr/lib/flightctl/custom-info.d/keyNotShown && \
    chmod 755 /usr/lib/flightctl/custom-info.d/*


