# quay.io/flightctl/flightctl-device:base
#
# Base bootc image used for E2E testing with the following features:
#
# * User/pw: user/user
# * flightctl-agent installed (without configuration/certificates)
# * greenboot and podman-compose installed with podman service enabled

FROM quay.io/centos-bootc/centos-bootc:stream9

ARG SOURCE_GIT_TAG
ARG SOURCE_GIT_TREE_STATE
ARG SOURCE_GIT_COMMIT

LABEL org.opencontainers.image.source="https://github.com/flightctl/flightctl"
LABEL org.opencontainers.image.version="${SOURCE_GIT_TAG}"
LABEL org.opencontainers.image.revision="${SOURCE_GIT_COMMIT}"

COPY rpms/*.rpm /tmp/rpms/

RUN echo "Installing flightctl-agent RPMs" && \
    dnf install -y /tmp/rpms/flightctl-agent-*.rpm /tmp/rpms/flightctl-selinux-*.rpm && \
    systemctl enable flightctl-agent.service && \
    echo "Cleaning up RPMs" && \
    rm -rf /tmp/rpms

RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y epel-release epel-next-release

RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y python-dotenv

RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y greenboot greenboot-default-health-checks podman-compose && \
    dnf install -y firewalld && \
    systemctl enable firewalld.service && \
    systemctl enable podman.service

RUN useradd -ms /bin/bash user && \
    echo "user:user" | chpasswd && \
    echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Create flightctl directories for runtime configuration
RUN mkdir -p /etc/flightctl/certs && \
    chmod 755 /etc/flightctl && \
    chmod 755 /etc/flightctl/certs

# Create flightctl custom info directory
RUN mkdir -p /usr/lib/flightctl/custom-info.d && \
    chmod 755 /usr/lib/flightctl/custom-info.d

# Add custom system info collectors
RUN echo -e '#!/bin/bash\necho "my site"' > /usr/lib/flightctl/custom-info.d/siteName && \
    echo -e '#!/bin/bash\necho ""' > /usr/lib/flightctl/custom-info.d/emptyValue && \
    echo -e '#!/bin/bash\necho "no-show"' > /usr/lib/flightctl/custom-info.d/keyNotShown && \
    chmod 755 /usr/lib/flightctl/custom-info.d/*

