{{- $namespaces := list .Release.Namespace }}
{{- if .Values.global.internalNamespace }}
{{- $namespaces = append $namespaces .Values.global.internalNamespace }}
{{- end }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "flightctl-db-app-secret") }}
{{- $userPassword := "" }}
{{- if $existingSecret }}
  {{- $userPassword = (index $existingSecret.data "userPassword") }}
{{- else }}
  {{- $userPasswordRaw := (randAlphaNum 20) }}
  {{- $userPassword = printf "%s-%s-%s-%s" (substr 0 5 $userPasswordRaw) (substr 5 10 $userPasswordRaw) (substr 10 15 $userPasswordRaw) (substr 15 20 $userPasswordRaw) | b64enc }}
{{- end }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-db-app-secret
  namespace: {{ $ns }}
  labels:
    flightctl.service: flightctl-db-app
    security.level: application
type: Opaque
data:
  # Application user credentials for data operations
  user: {{ $.Values.db.user | b64enc }}
  userPassword: {{ if $.Values.db.userPassword }}{{ $.Values.db.userPassword | b64enc }}{{ else }}{{ $userPassword }}{{ end }}
{{- end }} 