describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://console-openshift-console.apps.ocp-edge-cluster-0.qe.lab.redhat.com')
    cy.wait(9000)
    cy.origin('https://oauth-openshift.apps.ocp-edge-cluster-0.qe.lab.redhat.com', () => {

      cy.contains('kube:admin').click()
      cy.get('#inputUsername').should('exist')
      cy.get('#inputUsername').should('be.visible')
      cy.get('#inputPassword').should('exist')
      cy.get('#inputPassword').should('be.visible')
      cy.get('#inputUsername').type('kubeadmin')
      cy.get('#inputPassword').type('Dtfw2-z9s49-YPfam-etIFK')
      cy.contains('button', 'Log in').click()
    })
    cy.wait(20000)
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').should('be.visible')
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').click()
    cy.url().should('include', 'https://console-openshift-console.apps.ocp-edge-cluster-0.qe.lab.redhat.com')
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Devices').click()
    cy.get('[data-label="Approve"]').should('exist')
    cy.get('[data-label="Approve"]').should('be.visible')
    cy.wait(5000)
    cy.get('[data-label="Approve"]').click()
    cy.get('#rich-validation-field-deviceAlias').should('be.visible')
    cy.get('#rich-validation-field-deviceAlias').type('test-device')
    cy.get('#rich-validation-field-deviceAlias').should('have.value', 'test-device')
    cy.get('.pf-v5-c-label-group__list-item > .pf-v5-c-button').click()
    cy.get('.pf-v5-c-form__actions > .pf-m-primary').should('be.visible')
    cy.get('.pf-v5-c-form__actions > .pf-m-primary').click()
    cy.get('.pf-v5-c-table__tbody > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').should('be.visible')
    cy.get('.pf-v5-c-table__tbody > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').click()
    cy.get('#devices-toolbar > :nth-child(1) > .pf-v5-c-toolbar__content-section > :nth-child(3) > .pf-v5-c-button').should('be.visible')
    cy.get('#devices-toolbar > :nth-child(1) > .pf-v5-c-toolbar__content-section > :nth-child(3) > .pf-v5-c-button').click()
    cy.get('.pf-m-danger').should('be.visible')
    cy.get('.pf-m-danger').click()
  })
})