describe('Fleet Management', () => {
    it('passes', () => {
        cy.visit(`${Cypress.env('host')}`)
        cy.waitForPageLoad()
        cy.origin(`${Cypress.env('auth')}`, () => {

            cy.contains('kube:admin').click()
            cy.get('#inputUsername').should('exist')
            cy.get('#inputUsername').should('be.visible')
            cy.get('#inputPassword').should('exist')
            cy.get('#inputPassword').should('be.visible')
            cy.get('#inputUsername').type(`${Cypress.env('username')}`)
            cy.get('#inputPassword').type(`${Cypress.env('password')}`)
            cy.get('#inputUsername').should('have.value', `${Cypress.env('username')}`)
            cy.get('#inputPassword').should('have.value', `${Cypress.env('password')}`)
            cy.contains('button', 'Log in').click()
        })
        cy.waitForPageLoad()
        cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').should('be.visible')
        cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').click()
        cy.url().should('include', host)
        cy.get('#nav-toggle').click()
        cy.contains('Edge Management').click()
        cy.contains('Fleets').click()
        cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').should('exist')
        cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').should('be.visible')
        cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').click()
        cy.get('#rich-validation-field-name').should('be.visible')
        cy.get('#rich-validation-field-name').type('test-fleet')
        cy.get('#rich-validation-field-name').should('have.value', 'test-fleet')
        cy.get('.pf-v5-l-stack__item > .pf-v5-c-label-group > .pf-v5-c-label-group__main > .pf-v5-c-label-group__list').click()

    })
})