// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: enrollment.proto

package grpc_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentChallenge is a wrapper for all possible messages the agent can send.
type AgentChallenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentChallenge_ChallengeRequest
	//	*AgentChallenge_ChallengeResponse
	Payload       isAgentChallenge_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentChallenge) Reset() {
	*x = AgentChallenge{}
	mi := &file_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentChallenge) ProtoMessage() {}

func (x *AgentChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentChallenge.ProtoReflect.Descriptor instead.
func (*AgentChallenge) Descriptor() ([]byte, []int) {
	return file_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *AgentChallenge) GetPayload() isAgentChallenge_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentChallenge) GetChallengeRequest() *ChallengeRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentChallenge_ChallengeRequest); ok {
			return x.ChallengeRequest
		}
	}
	return nil
}

func (x *AgentChallenge) GetChallengeResponse() *ChallengeResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentChallenge_ChallengeResponse); ok {
			return x.ChallengeResponse
		}
	}
	return nil
}

type isAgentChallenge_Payload interface {
	isAgentChallenge_Payload()
}

type AgentChallenge_ChallengeRequest struct {
	// The first message sent by the agent to request a challenge.
	ChallengeRequest *ChallengeRequest `protobuf:"bytes,1,opt,name=challenge_request,json=challengeRequest,proto3,oneof"`
}

type AgentChallenge_ChallengeResponse struct {
	// The agent's response containing the decrypted secret.
	ChallengeResponse *ChallengeResponse `protobuf:"bytes,2,opt,name=challenge_response,json=challengeResponse,proto3,oneof"`
}

func (*AgentChallenge_ChallengeRequest) isAgentChallenge_Payload() {}

func (*AgentChallenge_ChallengeResponse) isAgentChallenge_Payload() {}

// ServerChallenge is a wrapper for all possible messages the service can send.
type ServerChallenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerChallenge_Challenge
	//	*ServerChallenge_Success
	//	*ServerChallenge_Error
	Payload       isServerChallenge_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerChallenge) Reset() {
	*x = ServerChallenge{}
	mi := &file_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerChallenge) ProtoMessage() {}

func (x *ServerChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerChallenge.ProtoReflect.Descriptor instead.
func (*ServerChallenge) Descriptor() ([]byte, []int) {
	return file_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *ServerChallenge) GetPayload() isServerChallenge_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerChallenge) GetChallenge() *Challenge {
	if x != nil {
		if x, ok := x.Payload.(*ServerChallenge_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *ServerChallenge) GetSuccess() *ChallengeComplete {
	if x != nil {
		if x, ok := x.Payload.(*ServerChallenge_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ServerChallenge) GetError() *ChallengeError {
	if x != nil {
		if x, ok := x.Payload.(*ServerChallenge_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerChallenge_Payload interface {
	isServerChallenge_Payload()
}

type ServerChallenge_Challenge struct {
	// The service's challenge containing the credential blob.
	Challenge *Challenge `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"`
}

type ServerChallenge_Success struct {
	// A message indicating the entire challenge was successful.
	Success *ChallengeComplete `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type ServerChallenge_Error struct {
	// A message indicating a failure at some point in the challenge.
	Error *ChallengeError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerChallenge_Challenge) isServerChallenge_Payload() {}

func (*ServerChallenge_Success) isServerChallenge_Payload() {}

func (*ServerChallenge_Error) isServerChallenge_Payload() {}

// ChallengeRequest is sent by the client to initiate the challenge for a specific EnrollmentRequest.
type ChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the EnrollmentRequest resource created via the REST API.
	EnrollmentRequestName string `protobuf:"bytes,1,opt,name=enrollment_request_name,json=enrollmentRequestName,proto3" json:"enrollment_request_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeRequest) GetEnrollmentRequestName() string {
	if x != nil {
		return x.EnrollmentRequestName
	}
	return ""
}

// Challenge is sent by the server and contains the credential blob the agent needs to solve.
type Challenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The encrypted data blob that the agent must
	// pass to the TPM's ActivateCredential command.
	CredentialBlob []byte `protobuf:"bytes,1,opt,name=credential_blob,json=credentialBlob,proto3" json:"credential_blob,omitempty"`
	// The encrypted secret that accompanies the credential blob.
	EncryptedSecret []byte `protobuf:"bytes,2,opt,name=encrypted_secret,json=encryptedSecret,proto3" json:"encrypted_secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *Challenge) GetCredentialBlob() []byte {
	if x != nil {
		return x.CredentialBlob
	}
	return nil
}

func (x *Challenge) GetEncryptedSecret() []byte {
	if x != nil {
		return x.EncryptedSecret
	}
	return nil
}

// ChallengeResponse contains the agent's decrypted secret.
type ChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw bytes of the secret decrypted by the TPM.
	Secret        []byte `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_enrollment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_enrollment_proto_rawDescGZIP(), []int{4}
}

func (x *ChallengeResponse) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

// ChallengeComplete signals a successful end to the challenge.
type ChallengeComplete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A human-readable success message.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeComplete) Reset() {
	*x = ChallengeComplete{}
	mi := &file_enrollment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeComplete) ProtoMessage() {}

func (x *ChallengeComplete) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeComplete.ProtoReflect.Descriptor instead.
func (*ChallengeComplete) Descriptor() ([]byte, []int) {
	return file_enrollment_proto_rawDescGZIP(), []int{5}
}

func (x *ChallengeComplete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChallengeError signals a failure and terminates the challenge.
type ChallengeError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A human-readable error message.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeError) Reset() {
	*x = ChallengeError{}
	mi := &file_enrollment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeError) ProtoMessage() {}

func (x *ChallengeError) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeError.ProtoReflect.Descriptor instead.
func (*ChallengeError) Descriptor() ([]byte, []int) {
	return file_enrollment_proto_rawDescGZIP(), []int{6}
}

func (x *ChallengeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_enrollment_proto protoreflect.FileDescriptor

const file_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x10enrollment.proto\x12\fflightctl.v1\"\xbc\x01\n" +
	"\x0eAgentChallenge\x12M\n" +
	"\x11challenge_request\x18\x01 \x01(\v2\x1e.flightctl.v1.ChallengeRequestH\x00R\x10challengeRequest\x12P\n" +
	"\x12challenge_response\x18\x02 \x01(\v2\x1f.flightctl.v1.ChallengeResponseH\x00R\x11challengeResponseB\t\n" +
	"\apayload\"\xc8\x01\n" +
	"\x0fServerChallenge\x127\n" +
	"\tchallenge\x18\x01 \x01(\v2\x17.flightctl.v1.ChallengeH\x00R\tchallenge\x12;\n" +
	"\asuccess\x18\x02 \x01(\v2\x1f.flightctl.v1.ChallengeCompleteH\x00R\asuccess\x124\n" +
	"\x05error\x18\x03 \x01(\v2\x1c.flightctl.v1.ChallengeErrorH\x00R\x05errorB\t\n" +
	"\apayload\"J\n" +
	"\x10ChallengeRequest\x126\n" +
	"\x17enrollment_request_name\x18\x01 \x01(\tR\x15enrollmentRequestName\"_\n" +
	"\tChallenge\x12'\n" +
	"\x0fcredential_blob\x18\x01 \x01(\fR\x0ecredentialBlob\x12)\n" +
	"\x10encrypted_secret\x18\x02 \x01(\fR\x0fencryptedSecret\"+\n" +
	"\x11ChallengeResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\"-\n" +
	"\x11ChallengeComplete\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x0eChallengeError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2]\n" +
	"\n" +
	"Enrollment\x12O\n" +
	"\fTPMChallenge\x12\x1c.flightctl.v1.AgentChallenge\x1a\x1d.flightctl.v1.ServerChallenge(\x010\x01B4Z2github.com/flightctl/flightctl/api/grpc/v1/grpc-v1b\x06proto3"

var (
	file_enrollment_proto_rawDescOnce sync.Once
	file_enrollment_proto_rawDescData []byte
)

func file_enrollment_proto_rawDescGZIP() []byte {
	file_enrollment_proto_rawDescOnce.Do(func() {
		file_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrollment_proto_rawDesc), len(file_enrollment_proto_rawDesc)))
	})
	return file_enrollment_proto_rawDescData
}

var file_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_enrollment_proto_goTypes = []any{
	(*AgentChallenge)(nil),    // 0: flightctl.v1.AgentChallenge
	(*ServerChallenge)(nil),   // 1: flightctl.v1.ServerChallenge
	(*ChallengeRequest)(nil),  // 2: flightctl.v1.ChallengeRequest
	(*Challenge)(nil),         // 3: flightctl.v1.Challenge
	(*ChallengeResponse)(nil), // 4: flightctl.v1.ChallengeResponse
	(*ChallengeComplete)(nil), // 5: flightctl.v1.ChallengeComplete
	(*ChallengeError)(nil),    // 6: flightctl.v1.ChallengeError
}
var file_enrollment_proto_depIdxs = []int32{
	2, // 0: flightctl.v1.AgentChallenge.challenge_request:type_name -> flightctl.v1.ChallengeRequest
	4, // 1: flightctl.v1.AgentChallenge.challenge_response:type_name -> flightctl.v1.ChallengeResponse
	3, // 2: flightctl.v1.ServerChallenge.challenge:type_name -> flightctl.v1.Challenge
	5, // 3: flightctl.v1.ServerChallenge.success:type_name -> flightctl.v1.ChallengeComplete
	6, // 4: flightctl.v1.ServerChallenge.error:type_name -> flightctl.v1.ChallengeError
	0, // 5: flightctl.v1.Enrollment.TPMChallenge:input_type -> flightctl.v1.AgentChallenge
	1, // 6: flightctl.v1.Enrollment.TPMChallenge:output_type -> flightctl.v1.ServerChallenge
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_enrollment_proto_init() }
func file_enrollment_proto_init() {
	if File_enrollment_proto != nil {
		return
	}
	file_enrollment_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentChallenge_ChallengeRequest)(nil),
		(*AgentChallenge_ChallengeResponse)(nil),
	}
	file_enrollment_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerChallenge_Challenge)(nil),
		(*ServerChallenge_Success)(nil),
		(*ServerChallenge_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrollment_proto_rawDesc), len(file_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enrollment_proto_goTypes,
		DependencyIndexes: file_enrollment_proto_depIdxs,
		MessageInfos:      file_enrollment_proto_msgTypes,
	}.Build()
	File_enrollment_proto = out.File
	file_enrollment_proto_goTypes = nil
	file_enrollment_proto_depIdxs = nil
}
