{{- if eq .Values.db.type "builtin" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    flightctl.service: flightctl-db
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-db
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: flightctl-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        flightctl.service: flightctl-db
        {{- include "flightctl.standardLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecretName }}
      {{- end }}
      {{- if .Values.db.builtin.fsGroup }}
      securityContext:
        fsGroup: {{ .Values.db.builtin.fsGroup }}
      {{- end }}
      containers:
        - env:
            - name: POSTGRESQL_DATABASE
              value: {{ required "Values.db.name is required" $.Values.db.name }}
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: {{ .Values.db.builtin.maxConnections | quote }}
          image: {{ .Values.db.builtin.image.image }}:{{ .Values.db.builtin.image.tag }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.db.builtin.image.pullPolicy }}
          name: flightctl-db
          command:
            - /bin/sh
            - -c
            - |
              set -eu
              POSTGRESQL_MASTER_USER="$(cat /run/secrets/db-admin/masterUser)" \
              POSTGRESQL_MASTER_PASSWORD="$(cat /run/secrets/db-admin/masterPassword)" \
              POSTGRESQL_USER="$(cat /run/secrets/db/user)" \
              POSTGRESQL_PASSWORD="$(cat /run/secrets/db/userPassword)" \
              exec run-postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            {{- include "flightctl.dbAdminSecretVolumeMount" . | nindent 12 }}
            {{- include "flightctl.dbAppSecretVolumeMount" . | nindent 12 }}
            - mountPath: /var/lib/pgsql/data
              name: flightctl-db
            - mountPath: /usr/share/container-scripts/postgresql/start/enable-superuser.sh
              subPath: enable-superuser.sh
              name: init-scripts
          resources:
            requests:
              cpu: {{ .Values.db.builtin.resources.requests.cpu}}
              memory: {{ .Values.db.builtin.resources.requests.memory}}
      restartPolicy: Always
      volumes:
        {{- include "flightctl.dbAdminSecretVolume" . | nindent 8 }}
        {{- include "flightctl.dbAppSecretVolume" . | nindent 8 }}
        - name: flightctl-db
          persistentVolumeClaim:
            claimName: flightctl-db
        - name: init-scripts
          configMap:
            name: flightctl-db
{{- end }}
