# Build arguments for community-el9 flavor
# These args are used across all containerfiles for build and runtime base images

# Build-time base images
BUILD_BASE_IMAGE=registry.access.redhat.com/ubi9/go-toolset:1.24.6
MINIMAL_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:9.7

RUNTIME_BASE_IMAGE=quay.io/flightctl/flightctl-base:9.7-1762965531