{{- if .Values.ui.enabled }}
{{- if and (eq (include "flightctl.enableMulticlusterExtensions" .) "false") (eq (include "flightctl.getServiceExposeMethod" .) "route") }}
{{- $useExtCert := eq (include "flightctl.useRouteExternalCertificate" (dict "root" . "routeName" "flightctl-ui")) "true" }}
{{- $tlsSecretName := "" }}
{{- if .Values.global.baseDomainTlsSecretName }}
  {{- $tlsSecretName = .Values.global.baseDomainTlsSecretName }}
{{- else if $useExtCert }}
  {{- $tlsSecretName = "flightctl-ui-server-tls" }}
{{- end }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: flightctl-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    {{- with .Values.global.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ui.additionalRouteLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    flightctl.service: flightctl-ui
spec:
  host:  ui.{{ include "flightctl.getBaseDomain" . }}
  to:
    kind: Service
    name: flightctl-ui
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- if $tlsSecretName }}
    externalCertificate:
      name: {{ $tlsSecretName }}
    {{- end }}
  wildcardPolicy: None

{{- if $tlsSecretName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-ui-route-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-ui
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ $tlsSecretName }}"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flightctl-ui-route-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
    flightctl.service: flightctl-ui
subjects:
  - kind: ServiceAccount
    name: router
    namespace: openshift-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flightctl-ui-route-cert
{{- end }}
{{- end }}
{{- end }}
