apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flightctl.standardLabels" . | nindent 4 }}
data:
  FLIGHTCTL_SERVER: {{ .Values.api.url | quote }}
  FLIGHTCTL_SERVER_EXTERNAL: {{ include "flightctl.getApiUrl" . }}
  {{- if .Values.cliArtifacts.enabled }}
  FLIGHTCTL_CLI_ARTIFACTS_SERVER: {{ include "flightctl.getInternalCliArtifactsUrl" . }}
  {{- end }}
  {{- if .Values.alerts.enabled }}
  FLIGHTCTL_ALERTMANAGER_PROXY: {{ include "flightctl.getAlertManagerProxyUrl" . }}
  {{- end }}
  FLIGHTCTL_SERVER_INSECURE_SKIP_VERIFY: {{ .Values.api.insecureSkipTlsVerify | quote }}
  IS_RHEM: {{ .Values.isRHEM | quote }}
  ORGANIZATIONS_ENABLED: {{ if and (default false ((.Values.global).organizations).enabled) (not (eq (.Values.global).target "acm")) }}"true"{{ else }}"false"{{ end }}
  AUTH_INSECURE_SKIP_VERIFY: {{ default ((.Values.global).auth).insecureSkipTlsVerify .Values.auth.insecureSkipTlsVerify | quote }}
  {{- if ne (.Values.global).target "acm" }}
  {{- if .Values.baseURL }}
  BASE_UI_URL: {{ .Values.baseURL | quote }}
  {{- else }}
  BASE_UI_URL: {{ include "flightctl.getUIUrl" . }}
  {{- end }}
  {{- end }}
