registry:
  image: docker.io/library/registry:2
  nodeport: ""
  namespace: flightctl-e2e
  route: true
  hostName: ""
gitserver:
  image: localhost/git-server:latest
  nodePort: ""
  namespace: flightctl-e2e
